// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "cat",
    "segs": "c.a.t",
    "unit": "BR",
    "pic": "a cat",
    "tags": [
      "review",
      "picture",
      "sort:c"
    ]
  },
  {
    "text": "cup",
    "segs": "c.u.p",
    "unit": "BR",
    "pic": "a small shallow porcelain teacup with a delicate curved handle, wide open rim, sitting on a matching saucer, empty inside",
    "tags": [
      "review",
      "picture",
      "sort:c"
    ]
  },
  {
    "text": "crab",
    "segs": "c.r.a.b",
    "unit": "BR",
    "pic": "a crab",
    "tags": [
      "review",
      "picture",
      "sort:c"
    ]
  },
  {
    "text": "crisp",
    "segs": "c.r.i.s.p",
    "unit": "BR",
    "pic": "one very thin golden potato crisp with a wavy curled edge and a few darker toasted patches, shown tilted so its thinness is obvious, no whole potato",
    "tags": [
      "review",
      "picture",
      "sort:c"
    ]
  },
  {
    "text": "cap",
    "segs": "c.a.p",
    "unit": "BR",
    "pic": "a baseball cap",
    "tags": [
      "review",
      "picture",
      "sort:c"
    ]
  },
  {
    "text": "cot",
    "segs": "c.o.t",
    "unit": "BR",
    "pic": "a baby's cot",
    "tags": [
      "review",
      "picture",
      "sort:c"
    ]
  },
  {
    "text": "crust",
    "segs": "c.r.u.s.t",
    "unit": "BR",
    "tags": [
      "review",
      "sort:c",
      "dictation-safe"
    ]
  },
  {
    "text": "cub",
    "segs": "c.u.b",
    "unit": "BR",
    "tags": [
      "review",
      "sort:c",
      "dictation-safe"
    ]
  },
  {
    "text": "scrub",
    "segs": "s.c.r.u.b",
    "unit": "BR",
    "tags": [
      "review",
      "sort:c",
      "dictation-safe"
    ]
  },
  {
    "text": "scrap",
    "segs": "s.c.r.a.p",
    "unit": "BR",
    "tags": [
      "review",
      "sort:c",
      "dictation-safe"
    ]
  },
  {
    "text": "milk",
    "segs": "m.i.l.k",
    "unit": "BR",
    "pic": "a glass of milk",
    "tags": [
      "review",
      "picture",
      "sort:k"
    ]
  },
  {
    "text": "kiss",
    "segs": "k.i.ss",
    "unit": "BR",
    "tags": [
      "review",
      "sort:k",
      "dictation-safe"
    ]
  },
  {
    "text": "king",
    "segs": "k.i.ng",
    "unit": "BR",
    "pic": "a friendly grown-up king wearing a golden crown and a long red royal robe, with his face, full body and hands visible, waving",
    "tags": [
      "review",
      "picture",
      "sort:k"
    ]
  },
  {
    "text": "desk",
    "segs": "d.e.s.k",
    "unit": "BR",
    "pic": "one wooden writing desk with a wide flat top, a single drawer and an empty chair pushed under it, no writing",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:k"
    ]
  },
  {
    "text": "whisk",
    "segs": "wh.i.s.k",
    "unit": "BR",
    "pic": "a whisk",
    "tags": [
      "review",
      "picture",
      "sort:k",
      "sort:wh"
    ]
  },
  {
    "text": "park",
    "segs": "p.a.r.k",
    "unit": "BR",
    "tags": [
      "review",
      "sort:k",
      "dictation-safe"
    ]
  },
  {
    "text": "shark",
    "segs": "sh.a.r.k",
    "unit": "BR",
    "pic": "one grey shark swimming alone, full body",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:k"
    ]
  },
  {
    "text": "wink",
    "segs": "w.i.n=ng.k",
    "unit": "BR",
    "pic": "one child winking one eye with a friendly smile, face shown close up",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:k",
      "sort:w"
    ]
  },
  {
    "text": "sink",
    "segs": "s.i.n=ng.k",
    "unit": "BR",
    "pic": "one plain white kitchen sink with a tap and drain, empty and clean",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:k"
    ]
  },
  {
    "text": "chunk",
    "segs": "ch.u.n=ng.k",
    "unit": "BR",
    "tags": [
      "review",
      "sort:k",
      "sort:ch",
      "dictation-safe"
    ]
  },
  {
    "text": "duck",
    "segs": "d.u.ck",
    "unit": "BR",
    "pic": "a white farm duck standing side-on with a friendly face: one big round shiny black eye clearly drawn on its head, an orange beak with a little smile, and orange feet",
    "tags": [
      "review",
      "picture",
      "sort:ck"
    ]
  },
  {
    "text": "rock",
    "segs": "r.o.ck",
    "unit": "BR",
    "pic": "a rock",
    "tags": [
      "review",
      "picture",
      "sort:ck"
    ]
  },
  {
    "text": "chick",
    "segs": "ch.i.ck",
    "unit": "BR",
    "pic": "a chick",
    "tags": [
      "review",
      "picture",
      "sort:ck",
      "sort:ch"
    ]
  },
  {
    "text": "lock",
    "segs": "l.o.ck",
    "unit": "BR",
    "pic": "a padlock",
    "tags": [
      "review",
      "picture",
      "sort:ck"
    ]
  },
  {
    "text": "sock",
    "segs": "s.o.ck",
    "unit": "BR",
    "pic": "a sock",
    "tags": [
      "review",
      "picture",
      "sort:ck"
    ]
  },
  {
    "text": "black",
    "segs": "b.l.a.ck",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ck"
    ]
  },
  {
    "text": "back",
    "segs": "b.a.ck",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ck"
    ]
  },
  {
    "text": "neck",
    "segs": "n.e.ck",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ck"
    ]
  },
  {
    "text": "snack",
    "segs": "s.n.a.ck",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ck"
    ]
  },
  {
    "text": "pick",
    "segs": "p.i.ck",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ck"
    ]
  },
  {
    "text": "bench",
    "segs": "b.e.n.ch",
    "unit": "BR",
    "pic": "a park bench",
    "tags": [
      "review",
      "picture",
      "sort:ch"
    ]
  },
  {
    "text": "chest",
    "segs": "ch.e.s.t",
    "unit": "BR",
    "pic": "a plain wooden storage chest with a curved lid and simple iron bands, closed, no treasure or coins or lock",
    "tags": [
      "review",
      "picture",
      "sort:ch"
    ]
  },
  {
    "text": "lunch",
    "segs": "l.u.n.ch",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ch"
    ]
  },
  {
    "text": "chin",
    "segs": "ch.i.n",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ch"
    ]
  },
  {
    "text": "chip",
    "segs": "ch.i.p",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ch"
    ]
  },
  {
    "text": "chop",
    "segs": "ch.o.p",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ch"
    ]
  },
  {
    "text": "chat",
    "segs": "ch.a.t",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ch"
    ]
  },
  {
    "text": "much",
    "segs": "m.u.ch",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ch"
    ]
  },
  {
    "text": "check",
    "segs": "ch.e.ck",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ck",
      "sort:ch"
    ]
  },
  {
    "text": "which",
    "segs": "wh.i.ch",
    "unit": "BR",
    "tags": [
      "review",
      "reading-only",
      "sort:ch",
      "sort:wh"
    ]
  },
  {
    "text": "hutch",
    "segs": "h.u.tch",
    "unit": "BR",
    "pic": "a rabbit hutch",
    "tags": [
      "review",
      "picture",
      "sort:tch"
    ]
  },
  {
    "text": "match",
    "segs": "m.a.tch",
    "unit": "BR",
    "pic": "a match stick",
    "tags": [
      "review",
      "picture",
      "sort:tch"
    ]
  },
  {
    "text": "watch",
    "segs": "w.a.tch",
    "unit": "BR",
    "pic": "one simple wristwatch with a round face and no numbers",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:tch",
      "sort:w"
    ]
  },
  {
    "text": "hatch",
    "segs": "h.a.tch",
    "unit": "BR",
    "tags": [
      "review",
      "sort:tch",
      "dictation-safe"
    ]
  },
  {
    "text": "pitch",
    "segs": "p.i.tch",
    "unit": "BR",
    "pic": "one grassy sports pitch with white boundary lines and no words",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:tch"
    ]
  },
  {
    "text": "catch",
    "segs": "c.a.tch",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:c",
      "sort:tch"
    ]
  },
  {
    "text": "itch",
    "segs": "i.tch",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:tch"
    ]
  },
  {
    "text": "fetch",
    "segs": "f.e.tch",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:tch"
    ]
  },
  {
    "text": "patch",
    "segs": "p.a.tch",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:tch"
    ]
  },
  {
    "text": "ditch",
    "segs": "d.i.tch",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:tch"
    ]
  },
  {
    "text": "swim",
    "segs": "s.w.i.m",
    "unit": "BR",
    "pic": "a child actively swimming across a little patch of bright blue water, side view with face above the water and one arm reaching forward in a swimming stroke, small splashes around them",
    "tags": [
      "review",
      "picture",
      "sort:w"
    ]
  },
  {
    "text": "swing",
    "segs": "s.w.i.ng",
    "unit": "BR",
    "pic": "a swing",
    "tags": [
      "review",
      "picture",
      "sort:w"
    ]
  },
  {
    "text": "wag",
    "segs": "w.a.g",
    "unit": "BR",
    "tags": [
      "review",
      "sort:w",
      "dictation-safe"
    ]
  },
  {
    "text": "wing",
    "segs": "w.i.ng",
    "unit": "BR",
    "pic": "a wing",
    "tags": [
      "review",
      "picture",
      "sort:w"
    ]
  },
  {
    "text": "win",
    "segs": "w.i.n",
    "unit": "BR",
    "tags": [
      "review",
      "sort:w",
      "dictation-safe"
    ]
  },
  {
    "text": "twist",
    "segs": "t.w.i.s.t",
    "unit": "BR",
    "tags": [
      "review",
      "sort:w",
      "dictation-safe"
    ]
  },
  {
    "text": "twig",
    "segs": "t.w.i.g",
    "unit": "BR",
    "tags": [
      "review",
      "sort:w",
      "dictation-safe"
    ]
  },
  {
    "text": "well",
    "segs": "w.e.ll",
    "unit": "BR",
    "pic": "a stone well",
    "tags": [
      "review",
      "picture",
      "sort:w"
    ]
  },
  {
    "text": "wig",
    "segs": "w.i.g",
    "unit": "BR",
    "pic": "a bright purple curly wig resting on a simple plain wooden wig stand, with the wig cap edge visible below the curls",
    "tags": [
      "review",
      "picture",
      "sort:w"
    ]
  },
  {
    "text": "web",
    "segs": "w.e.b",
    "unit": "BR",
    "pic": "a spider web",
    "tags": [
      "review",
      "picture",
      "sort:w"
    ]
  },
  {
    "text": "when",
    "segs": "wh.e.n",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:wh"
    ]
  },
  {
    "text": "whip",
    "segs": "wh.i.p",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:wh"
    ]
  },
  {
    "text": "whack",
    "segs": "wh.a.ck",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ck",
      "sort:wh"
    ]
  },
  {
    "text": "van",
    "segs": "v.a.n",
    "unit": "BR",
    "pic": "a tall boxy delivery van with a large windowless cargo box behind the cab, two front seats only, sliding side door and rear doors, in bright blue",
    "tags": [
      "review",
      "picture",
      "sort:v"
    ]
  },
  {
    "text": "vest",
    "segs": "v.e.s.t",
    "unit": "BR",
    "pic": "a vest",
    "tags": [
      "review",
      "picture",
      "sort:v"
    ]
  },
  {
    "text": "vet",
    "segs": "v.e.t",
    "unit": "BR",
    "pic": "a friendly woman vet in teal scrubs examining a small puppy on a low table, wearing a stethoscope around her neck, full person and puppy both clearly visible",
    "tags": [
      "review",
      "picture",
      "sort:v"
    ]
  },
  {
    "text": "give",
    "segs": "g.i.ve",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ve"
    ]
  },
  {
    "text": "have",
    "segs": "h.a.ve",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ve"
    ]
  },
  {
    "text": "twelve",
    "segs": "t.w.e.l.ve",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:w",
      "sort:ve"
    ]
  },
  {
    "text": "live",
    "segs": "l.i.ve",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ve"
    ]
  },
  {
    "text": "dove",
    "segs": "d.o.ve",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ve"
    ]
  },
  {
    "text": "drive",
    "segs": "d.r.i.ve",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ve"
    ]
  },
  {
    "text": "dive",
    "segs": "d.i.ve",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ve"
    ]
  },
  {
    "text": "paw",
    "segs": "p.a.w",
    "unit": "BR",
    "pic": "one animal paw with soft pads shown close up",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:w"
    ]
  },
  {
    "text": "wall",
    "segs": "w.a.ll",
    "unit": "BR",
    "pic": "one short brick wall",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:w"
    ]
  },
  {
    "text": "jaw",
    "segs": "j.a.w",
    "unit": "BR",
    "pic": "one animal jawbone with teeth, shown gently",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:w"
    ]
  },
  {
    "text": "lawn",
    "segs": "l.a.w.n",
    "unit": "BR",
    "tags": [
      "review",
      "sort:w",
      "dictation-safe"
    ]
  },
  {
    "text": "corn",
    "segs": "c.o.r.n",
    "unit": "BR",
    "tags": [
      "review",
      "sort:c",
      "dictation-safe"
    ]
  },
  {
    "text": "howl",
    "segs": "h.o.w.l",
    "unit": "BR",
    "tags": [
      "review",
      "sort:w",
      "dictation-safe"
    ]
  },
  {
    "text": "clump",
    "segs": "c.l.u.m.p",
    "unit": "BR",
    "tags": [
      "review",
      "sort:c",
      "dictation-safe"
    ]
  },
  {
    "text": "wet",
    "segs": "w.e.t",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:w"
    ]
  },
  {
    "text": "clap",
    "segs": "c.l.a.p",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:c"
    ]
  },
  {
    "text": "cut",
    "segs": "c.u.t",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:c"
    ]
  },
  {
    "text": "kid",
    "segs": "k.i.d",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:k"
    ]
  },
  {
    "text": "with",
    "segs": "w.i.th=dh",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:w"
    ]
  },
  {
    "text": "went",
    "segs": "w.e.n.t",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:w"
    ]
  },
  {
    "text": "can",
    "segs": "c.a.n",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:c"
    ]
  },
  {
    "text": "stuck",
    "segs": "s.t.u.ck",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ck"
    ]
  },
  {
    "text": "thick",
    "segs": "th.i.ck",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ck"
    ]
  },
  {
    "text": "cloth",
    "segs": "c.l.o.th",
    "unit": "BR",
    "tags": [
      "review",
      "dictation-safe",
      "sort:c"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The clown had a brown hat.",
    "maxUnit": "IC10",
    "special": [
      "the",
      "a"
    ]
  },
  {
    "text": "The girl had a red skirt.",
    "maxUnit": "IC10",
    "special": [
      "the",
      "a"
    ]
  },
  {
    "text": "The stump is in the sun.",
    "maxUnit": "IC10",
    "special": [
      "the"
    ]
  },
  {
    "text": "Dad had a crisp.",
    "maxUnit": "IC10",
    "special": [
      "a"
    ]
  },
  {
    "text": "Mum swept the dust.",
    "maxUnit": "IC10",
    "special": [
      "the"
    ]
  },
  {
    "text": "A plump hen sat on a log.",
    "maxUnit": "IC10",
    "special": [
      "a"
    ]
  }
] as const;

export const chains = [] as const;

export const nonsense = [] as const;

export const poly = [] as const;
