// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "steak",
    "segs": "s.t.ea=ae.k",
    "unit": "EC1",
    "pic": "one cooked beef steak on a plain plate",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ea"
    ]
  },
  {
    "text": "great",
    "segs": "g.r.ea=ae.t",
    "unit": "EC1",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "break",
    "segs": "b.r.ea=ae.k",
    "unit": "EC1",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "tray",
    "segs": "t.r.ay",
    "unit": "EC1",
    "pic": "a tray",
    "tags": [
      "new",
      "picture",
      "sort:ay"
    ]
  },
  {
    "text": "day",
    "segs": "d.ay",
    "unit": "EC1",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ay"
    ]
  },
  {
    "text": "play",
    "segs": "p.l.ay",
    "unit": "EC1",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ay"
    ]
  },
  {
    "text": "say",
    "segs": "s.ay",
    "unit": "EC1",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ay"
    ]
  },
  {
    "text": "stay",
    "segs": "s.t.ay",
    "unit": "EC1",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ay"
    ]
  },
  {
    "text": "spray",
    "segs": "s.p.r.ay",
    "unit": "EC1",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ay"
    ]
  },
  {
    "text": "way",
    "segs": "w.ay",
    "unit": "EC1",
    "tags": [
      "new",
      "reading-only",
      "sort:ay"
    ]
  },
  {
    "text": "may",
    "segs": "m.ay",
    "unit": "EC1",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ay"
    ]
  },
  {
    "text": "rain",
    "segs": "r.ai.n",
    "unit": "EC1",
    "pic": "heavy raindrops falling from one grey cloud",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ai"
    ]
  },
  {
    "text": "train",
    "segs": "t.r.ai.n",
    "unit": "EC1",
    "pic": "a steam train",
    "tags": [
      "new",
      "picture",
      "sort:ai"
    ]
  },
  {
    "text": "snail",
    "segs": "s.n.ai.l",
    "unit": "EC1",
    "pic": "a snail",
    "tags": [
      "new",
      "picture",
      "sort:ai"
    ]
  },
  {
    "text": "tail",
    "segs": "t.ai.l",
    "unit": "EC1",
    "pic": "a fox tail",
    "tags": [
      "new",
      "picture",
      "sort:ai"
    ]
  },
  {
    "text": "paint",
    "segs": "p.ai.n.t",
    "unit": "EC1",
    "pic": "a paint pot",
    "tags": [
      "new",
      "picture",
      "sort:ai"
    ]
  },
  {
    "text": "nail",
    "segs": "n.ai.l",
    "unit": "EC1",
    "pic": "a nail",
    "tags": [
      "new",
      "picture",
      "sort:ai"
    ]
  },
  {
    "text": "sail",
    "segs": "s.ai.l",
    "unit": "EC1",
    "pic": "one white sailing boat sail on a small mast",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ai"
    ]
  },
  {
    "text": "pain",
    "segs": "p.ai.n",
    "unit": "EC1",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ai"
    ]
  },
  {
    "text": "cake",
    "segs": "c.a=ae.ke=k",
    "unit": "EC1",
    "pic": "one round birthday cake with icing and candles",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:a"
    ]
  },
  {
    "text": "gate",
    "segs": "g.a=ae.te=t",
    "unit": "EC1",
    "pic": "one wooden garden gate with a latch",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:a"
    ]
  },
  {
    "text": "flame",
    "segs": "f.l.a=ae.me=m",
    "unit": "EC1",
    "tags": [
      "new",
      "sort:a",
      "dictation-safe"
    ]
  },
  {
    "text": "whale",
    "segs": "wh.a=ae.le=l",
    "unit": "EC1",
    "pic": "one large blue whale swimming alone",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:a"
    ]
  },
  {
    "text": "take",
    "segs": "t.a=ae.ke=k",
    "unit": "EC1",
    "tags": [
      "new",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "bake",
    "segs": "b.a=ae.ke=k",
    "unit": "EC1",
    "tags": [
      "new",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "make",
    "segs": "m.a=ae.ke=k",
    "unit": "EC1",
    "tags": [
      "new",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "game",
    "segs": "g.a=ae.me=m",
    "unit": "EC1",
    "tags": [
      "new",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "came",
    "segs": "c.a=ae.me=m",
    "unit": "EC1",
    "tags": [
      "new",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "same",
    "segs": "s.a=ae.me=m",
    "unit": "EC1",
    "tags": [
      "new",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "wait",
    "segs": "w.ai.t",
    "unit": "EC1",
    "tags": [
      "new",
      "reading-only",
      "sort:ai"
    ]
  },
  {
    "text": "shake",
    "segs": "sh.a=ae.ke=k",
    "unit": "EC1",
    "tags": [
      "new",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "cave",
    "segs": "c.a=ae.ve",
    "unit": "EC1",
    "tags": [
      "new",
      "dictation-safe",
      "sort:a"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The star is over the barn.",
    "maxUnit": "IC11",
    "special": [
      "the"
    ]
  },
  {
    "text": "The king had a red cap.",
    "maxUnit": "IC11",
    "special": [
      "the",
      "a"
    ]
  },
  {
    "text": "The ship is in the mist.",
    "maxUnit": "IC11",
    "special": [
      "the"
    ]
  },
  {
    "text": "A fish can swim.",
    "maxUnit": "IC11",
    "special": [
      "a"
    ]
  },
  {
    "text": "The chick is in the nest.",
    "maxUnit": "IC11",
    "special": [
      "the"
    ]
  },
  {
    "text": "A drum is in the shed.",
    "maxUnit": "IC11",
    "special": [
      "a",
      "the"
    ]
  },
  {
    "text": "The crab sat on a rock.",
    "maxUnit": "IC11",
    "special": [
      "the",
      "a"
    ]
  },
  {
    "text": "The frog sat on a rock.",
    "maxUnit": "IC11",
    "special": [
      "the",
      "a"
    ]
  }
] as const;

export const chains = [
  [
    "day",
    "may",
    "way",
    "say",
    "stay"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [] as const;
