// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "flute",
    "segs": "f.l.u=oo.te=t",
    "unit": "EC10",
    "pic": "one silver flute",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:u"
    ]
  },
  {
    "text": "rule",
    "segs": "r.u=oo.le=l",
    "unit": "EC10",
    "tags": [
      "new",
      "dictation-safe",
      "sort:u"
    ]
  },
  {
    "text": "to",
    "segs": "t.o=oo",
    "unit": "EC10",
    "tags": [
      "new",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "do",
    "segs": "d.o=oo",
    "unit": "EC10",
    "tags": [
      "new",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "glue",
    "segs": "g.l.ue=oo",
    "unit": "EC10",
    "pic": "one plain bottle of glue with its cap open, no writing",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ue"
    ]
  },
  {
    "text": "blue",
    "segs": "b.l.ue=oo",
    "unit": "EC10",
    "tags": [
      "new",
      "reading-only",
      "sort:ue"
    ]
  },
  {
    "text": "true",
    "segs": "t.r.ue=oo",
    "unit": "EC10",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ue"
    ]
  },
  {
    "text": "clue",
    "segs": "c.l.ue=oo",
    "unit": "EC10",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ue"
    ]
  },
  {
    "text": "chew",
    "segs": "ch.ew=oo",
    "unit": "EC10",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ew"
    ]
  },
  {
    "text": "flew",
    "segs": "f.l.ew=oo",
    "unit": "EC10",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ew"
    ]
  },
  {
    "text": "drew",
    "segs": "d.r.ew=oo",
    "unit": "EC10",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ew"
    ]
  },
  {
    "text": "grew",
    "segs": "g.r.ew=oo",
    "unit": "EC10",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ew"
    ]
  },
  {
    "text": "blew",
    "segs": "b.l.ew=oo",
    "unit": "EC10",
    "tags": [
      "new",
      "reading-only",
      "sort:ew"
    ]
  },
  {
    "text": "threw",
    "segs": "th.r.ew=oo",
    "unit": "EC10",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ew"
    ]
  },
  {
    "text": "crew",
    "segs": "c.r.ew=oo",
    "unit": "EC10",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ew"
    ]
  },
  {
    "text": "spoon",
    "segs": "s.p.oo.n",
    "unit": "EC10",
    "pic": "one silver spoon",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:oo"
    ]
  },
  {
    "text": "moon",
    "segs": "m.oo.n",
    "unit": "EC10",
    "pic": "one bright full moon",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:oo"
    ]
  },
  {
    "text": "boot",
    "segs": "b.oo.t",
    "unit": "EC10",
    "pic": "one green rubber boot",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:oo"
    ]
  },
  {
    "text": "zoo",
    "segs": "z.oo",
    "unit": "EC10",
    "pic": "one zoo entrance with an animal statue and no writing",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:oo"
    ]
  },
  {
    "text": "broom",
    "segs": "b.r.oo.m",
    "unit": "EC10",
    "pic": "one wooden broom with straw bristles",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:oo"
    ]
  },
  {
    "text": "roof",
    "segs": "r.oo.f",
    "unit": "EC10",
    "pic": "one red tiled house roof",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:oo"
    ]
  },
  {
    "text": "hoop",
    "segs": "h.oo.p",
    "unit": "EC10",
    "pic": "one colourful hula hoop",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:oo"
    ]
  },
  {
    "text": "pool",
    "segs": "p.oo.l",
    "unit": "EC10",
    "pic": "one small blue swimming pool, empty of people",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:oo"
    ]
  },
  {
    "text": "tool",
    "segs": "t.oo.l",
    "unit": "EC10",
    "pic": "one hammer as a simple hand tool",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:oo"
    ]
  },
  {
    "text": "food",
    "segs": "f.oo.d",
    "unit": "EC10",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oo"
    ]
  },
  {
    "text": "cool",
    "segs": "c.oo.l",
    "unit": "EC10",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oo"
    ]
  },
  {
    "text": "room",
    "segs": "r.oo.m",
    "unit": "EC10",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oo"
    ]
  },
  {
    "text": "soon",
    "segs": "s.oo.n",
    "unit": "EC10",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oo"
    ]
  },
  {
    "text": "stool",
    "segs": "s.t.oo.l",
    "unit": "EC10",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oo"
    ]
  },
  {
    "text": "noon",
    "segs": "n.oo.n",
    "unit": "EC10",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oo"
    ]
  },
  {
    "text": "fool",
    "segs": "f.oo.l",
    "unit": "EC10",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oo"
    ]
  },
  {
    "text": "bloom",
    "segs": "b.l.oo.m",
    "unit": "EC10",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oo"
    ]
  },
  {
    "text": "loop",
    "segs": "l.oo.p",
    "unit": "EC10",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oo"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC8"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC8"
  },
  {
    "text": "The spoon is in the soup.",
    "maxUnit": "EC8"
  },
  {
    "text": "The clown had a brown hat.",
    "maxUnit": "EC8"
  },
  {
    "text": "A mouse ran out of the house.",
    "maxUnit": "EC8"
  },
  {
    "text": "The cow is by the house.",
    "maxUnit": "EC8"
  },
  {
    "text": "The star is over the barn.",
    "maxUnit": "EC8"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC8"
  }
] as const;

export const chains = [
  [
    "to",
    "do",
    "dove",
    "dive",
    "did"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "lemon",
    "syllables": "le|mon",
    "schwa": [
      1
    ]
  },
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "bedbug",
    "syllables": "bed|bug"
  },
  {
    "text": "hotdog",
    "syllables": "hot|dog"
  },
  {
    "text": "kidnap",
    "syllables": "kid|nap"
  },
  {
    "text": "pigpen",
    "syllables": "pig|pen"
  },
  {
    "text": "dogleg",
    "syllables": "dog|leg"
  },
  {
    "text": "admit",
    "syllables": "ad|mit"
  },
  {
    "text": "upset",
    "syllables": "up|set"
  },
  {
    "text": "comic",
    "syllables": "co|mic"
  }
] as const;
