// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "pie",
    "segs": "p.ie",
    "unit": "EC11",
    "pic": "a pie",
    "tags": [
      "new",
      "picture",
      "sort:ie"
    ]
  },
  {
    "text": "tie",
    "segs": "t.ie",
    "unit": "EC11",
    "pic": "a tie",
    "tags": [
      "new",
      "picture",
      "sort:ie"
    ]
  },
  {
    "text": "lie",
    "segs": "l.ie",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ie"
    ]
  },
  {
    "text": "sky",
    "segs": "s.k.y=ie",
    "unit": "EC11",
    "pic": "blue sky with one small white cloud",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:y"
    ]
  },
  {
    "text": "my",
    "segs": "m.y=ie",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:y"
    ]
  },
  {
    "text": "cry",
    "segs": "c.r.y=ie",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:y"
    ]
  },
  {
    "text": "fly",
    "segs": "f.l.y=ie",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:y"
    ]
  },
  {
    "text": "dry",
    "segs": "d.r.y=ie",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:y"
    ]
  },
  {
    "text": "try",
    "segs": "t.r.y=ie",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:y"
    ]
  },
  {
    "text": "by",
    "segs": "b.y=ie",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:y"
    ]
  },
  {
    "text": "light",
    "segs": "l.igh.t",
    "unit": "EC11",
    "pic": "a glowing lamp light bulb shining",
    "tags": [
      "new",
      "picture",
      "sort:igh"
    ]
  },
  {
    "text": "high",
    "segs": "h.igh",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:igh"
    ]
  },
  {
    "text": "bright",
    "segs": "b.r.igh.t",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:igh"
    ]
  },
  {
    "text": "night",
    "segs": "n.igh.t",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:igh"
    ]
  },
  {
    "text": "tight",
    "segs": "t.igh.t",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:igh"
    ]
  },
  {
    "text": "right",
    "segs": "r.igh.t",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:igh"
    ]
  },
  {
    "text": "fright",
    "segs": "f.r.igh.t",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:igh"
    ]
  },
  {
    "text": "might",
    "segs": "m.igh.t",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:igh"
    ]
  },
  {
    "text": "bike",
    "segs": "b.i=ie.ke=k",
    "unit": "EC11",
    "pic": "one blue bicycle, side view",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:i"
    ]
  },
  {
    "text": "child",
    "segs": "ch.i=ie.l.d",
    "unit": "EC11",
    "pic": "one smiling child standing alone",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:i"
    ]
  },
  {
    "text": "five",
    "segs": "f.i=ie.ve",
    "unit": "EC11",
    "pic": "five identical red apples in one row",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:i"
    ]
  },
  {
    "text": "kite",
    "segs": "k.i=ie.te=t",
    "unit": "EC11",
    "pic": "one bright diamond-shaped kite with a tail",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:i"
    ]
  },
  {
    "text": "line",
    "segs": "l.i=ie.ne=n",
    "unit": "EC11",
    "pic": "one straight blue line on a plain white card",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:i"
    ]
  },
  {
    "text": "lime",
    "segs": "l.i=ie.me=m",
    "unit": "EC11",
    "pic": "one green lime fruit cut in half",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:i"
    ]
  },
  {
    "text": "nine",
    "segs": "n.i=ie.ne=n",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:i"
    ]
  },
  {
    "text": "bite",
    "segs": "b.i=ie.te=t",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:i"
    ]
  },
  {
    "text": "like",
    "segs": "l.i=ie.ke=k",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:i"
    ]
  },
  {
    "text": "smile",
    "segs": "s.m.i=ie.le=l",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:i"
    ]
  },
  {
    "text": "hide",
    "segs": "h.i=ie.de=d",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:i"
    ]
  },
  {
    "text": "time",
    "segs": "t.i=ie.me=m",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:i"
    ]
  },
  {
    "text": "find",
    "segs": "f.i=ie.n.d",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:i"
    ]
  },
  {
    "text": "mind",
    "segs": "m.i=ie.n.d",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:i"
    ]
  },
  {
    "text": "side",
    "segs": "s.i=ie.de=d",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:i"
    ]
  },
  {
    "text": "ride",
    "segs": "r.i=ie.de=d",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:i"
    ]
  },
  {
    "text": "kind",
    "segs": "k.i=ie.n.d",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:i"
    ]
  },
  {
    "text": "slide",
    "segs": "s.l.i=ie.de=d",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:i"
    ]
  },
  {
    "text": "drive",
    "segs": "d.r.i=ie.ve",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:i"
    ]
  },
  {
    "text": "wide",
    "segs": "w.i=ie.de=d",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:i"
    ]
  },
  {
    "text": "whine",
    "segs": "wh.i=ie.ne=n",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:i"
    ]
  },
  {
    "text": "dive",
    "segs": "d.i=ie.ve",
    "unit": "EC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:i"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC9"
  },
  {
    "text": "The spoon is in the soup.",
    "maxUnit": "EC9"
  },
  {
    "text": "A mouse ran out of the house.",
    "maxUnit": "EC9"
  },
  {
    "text": "The cow is by the house.",
    "maxUnit": "EC9"
  },
  {
    "text": "The star is over the barn.",
    "maxUnit": "EC9"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC9"
  },
  {
    "text": "The tall horse ate an apple.",
    "maxUnit": "EC9"
  },
  {
    "text": "The fork is on the table.",
    "maxUnit": "EC9"
  }
] as const;

export const chains = [
  [
    "pie",
    "lie",
    "tie",
    "tea",
    "team"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "seven",
    "syllables": "se|ven",
    "schwa": [
      1
    ]
  },
  {
    "text": "object",
    "syllables": "ob|ject"
  },
  {
    "text": "uplift",
    "syllables": "up|lift"
  },
  {
    "text": "dentist",
    "syllables": "den|tist"
  },
  {
    "text": "suspect",
    "syllables": "sus|pect"
  },
  {
    "text": "himself",
    "syllables": "him|self"
  },
  {
    "text": "contest",
    "syllables": "con|test"
  },
  {
    "text": "backhand",
    "syllables": "back|hand"
  },
  {
    "text": "eggshell",
    "syllables": "egg|shell"
  }
] as const;
