// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "cook",
    "segs": "c.oo=uu.k",
    "unit": "EC13",
    "pic": "one smiling cook in a white hat stirring a pot",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:oo"
    ]
  },
  {
    "text": "foot",
    "segs": "f.oo=uu.t",
    "unit": "EC13",
    "pic": "one bare foot, side view",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:oo"
    ]
  },
  {
    "text": "wood",
    "segs": "w.oo=uu.d",
    "unit": "EC13",
    "pic": "one small stack of cut firewood logs",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:oo"
    ]
  },
  {
    "text": "good",
    "segs": "g.oo=uu.d",
    "unit": "EC13",
    "tags": [
      "review",
      "dictation-safe",
      "sort:oo"
    ]
  },
  {
    "text": "took",
    "segs": "t.oo=uu.k",
    "unit": "EC13",
    "tags": [
      "review",
      "dictation-safe",
      "sort:oo"
    ]
  },
  {
    "text": "shook",
    "segs": "sh.oo=uu.k",
    "unit": "EC13",
    "tags": [
      "review",
      "dictation-safe",
      "sort:oo"
    ]
  },
  {
    "text": "spoon",
    "segs": "s.p.oo.n",
    "unit": "EC13",
    "pic": "one silver spoon",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:oo"
    ]
  },
  {
    "text": "moon",
    "segs": "m.oo.n",
    "unit": "EC13",
    "pic": "one bright full moon",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:oo"
    ]
  },
  {
    "text": "boot",
    "segs": "b.oo.t",
    "unit": "EC13",
    "pic": "one green rubber boot",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:oo"
    ]
  },
  {
    "text": "food",
    "segs": "f.oo.d",
    "unit": "EC13",
    "tags": [
      "review",
      "dictation-safe",
      "sort:oo"
    ]
  },
  {
    "text": "room",
    "segs": "r.oo.m",
    "unit": "EC13",
    "tags": [
      "review",
      "dictation-safe",
      "sort:oo"
    ]
  },
  {
    "text": "soon",
    "segs": "s.oo.n",
    "unit": "EC13",
    "tags": [
      "review",
      "dictation-safe",
      "sort:oo"
    ]
  },
  {
    "text": "noon",
    "segs": "n.oo.n",
    "unit": "EC13",
    "tags": [
      "review",
      "dictation-safe",
      "sort:oo"
    ]
  },
  {
    "text": "bloom",
    "segs": "b.l.oo.m",
    "unit": "EC13",
    "tags": [
      "review",
      "dictation-safe",
      "sort:oo"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC11"
  },
  {
    "text": "The jar is on the cart.",
    "maxUnit": "EC11"
  },
  {
    "text": "The star is over the barn.",
    "maxUnit": "EC11"
  },
  {
    "text": "The car is by the farm.",
    "maxUnit": "EC11"
  },
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC11"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC11"
  }
] as const;

export const chains = [] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "seven",
    "syllables": "se|ven",
    "schwa": [
      1
    ]
  },
  {
    "text": "backpack",
    "syllables": "back|pack"
  },
  {
    "text": "catfish",
    "syllables": "cat|fish"
  },
  {
    "text": "discuss",
    "syllables": "dis|cuss"
  },
  {
    "text": "dandruff",
    "syllables": "dan|druff"
  },
  {
    "text": "backdrop",
    "syllables": "back|drop"
  },
  {
    "text": "chopstick",
    "syllables": "chop|stick"
  },
  {
    "text": "dishcloth",
    "syllables": "dish|cloth"
  },
  {
    "text": "lipstick",
    "syllables": "lip|stick"
  }
] as const;
