// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "touch",
    "segs": "t.ou=u.ch",
    "unit": "EC14",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ou"
    ]
  },
  {
    "text": "young",
    "segs": "y.ou=u.ng",
    "unit": "EC14",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ou"
    ]
  },
  {
    "text": "trouble",
    "segs": "t.r.ou=u.b.le=l",
    "unit": "EC14",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ou"
    ]
  },
  {
    "text": "double",
    "segs": "d.ou=u.b.le=l",
    "unit": "EC14",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ou"
    ]
  },
  {
    "text": "son",
    "segs": "s.o=u.n",
    "unit": "EC14",
    "tags": [
      "new",
      "reading-only",
      "sort:o"
    ]
  },
  {
    "text": "come",
    "segs": "c.o=u.me=m",
    "unit": "EC14",
    "tags": [
      "new",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "love",
    "segs": "l.o=u.ve",
    "unit": "EC14",
    "tags": [
      "new",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "done",
    "segs": "d.o=u.ne=n",
    "unit": "EC14",
    "tags": [
      "new",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "some",
    "segs": "s.o=u.me=m",
    "unit": "EC14",
    "tags": [
      "new",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "won",
    "segs": "w.o=u.n",
    "unit": "EC14",
    "tags": [
      "new",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "front",
    "segs": "f.r.o=u.n.t",
    "unit": "EC14",
    "tags": [
      "new",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "ton",
    "segs": "t.o=u.n",
    "unit": "EC14",
    "tags": [
      "new",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "duck",
    "segs": "d.u.ck",
    "unit": "EC14",
    "pic": "a white farm duck standing side-on with a friendly face: one big round shiny black eye clearly drawn on its head, an orange beak with a little smile, and orange feet",
    "tags": [
      "review",
      "picture",
      "sort:u"
    ]
  },
  {
    "text": "jump",
    "segs": "j.u.m.p",
    "unit": "EC14",
    "tags": [
      "review",
      "sort:u",
      "dictation-safe"
    ]
  },
  {
    "text": "run",
    "segs": "r.u.n",
    "unit": "EC14",
    "pic": "a child running",
    "tags": [
      "review",
      "picture",
      "sort:u"
    ]
  },
  {
    "text": "hug",
    "segs": "h.u.g",
    "unit": "EC14",
    "pic": "two children facing each other in one clear hug, both full bodies visible",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:u"
    ]
  },
  {
    "text": "bug",
    "segs": "b.u.g",
    "unit": "EC14",
    "pic": "one small green six-legged garden bug, shown alone with its body and legs clearly visible",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:u"
    ]
  },
  {
    "text": "sun",
    "segs": "s.u.n",
    "unit": "EC14",
    "pic": "the sun",
    "tags": [
      "review",
      "picture",
      "sort:u"
    ]
  },
  {
    "text": "bus",
    "segs": "b.u.s",
    "unit": "EC14",
    "pic": "a red double-decker bus",
    "tags": [
      "review",
      "picture",
      "sort:u"
    ]
  },
  {
    "text": "drum",
    "segs": "d.r.u.m",
    "unit": "EC14",
    "pic": "a drum",
    "tags": [
      "review",
      "picture",
      "sort:u"
    ]
  },
  {
    "text": "rug",
    "segs": "r.u.g",
    "unit": "EC14",
    "pic": "a round colourful rug",
    "tags": [
      "review",
      "picture",
      "sort:u"
    ]
  },
  {
    "text": "cup",
    "segs": "c.u.p",
    "unit": "EC14",
    "pic": "a small shallow porcelain teacup with a delicate curved handle, wide open rim, sitting on a matching saucer, empty inside",
    "tags": [
      "review",
      "picture",
      "sort:u"
    ]
  },
  {
    "text": "bun",
    "segs": "b.u.n",
    "unit": "EC14",
    "pic": "a single soft round iced bun with a little swirl of white icing on top, no plate or bread slices",
    "tags": [
      "review",
      "picture",
      "sort:u"
    ]
  },
  {
    "text": "plum",
    "segs": "p.l.u.m",
    "unit": "EC14",
    "pic": "a plum",
    "tags": [
      "review",
      "picture",
      "sort:u"
    ]
  },
  {
    "text": "mug",
    "segs": "m.u.g",
    "unit": "EC14",
    "pic": "a mug",
    "tags": [
      "review",
      "picture",
      "sort:u"
    ]
  },
  {
    "text": "plug",
    "segs": "p.l.u.g",
    "unit": "EC14",
    "pic": "a plug",
    "tags": [
      "review",
      "picture",
      "sort:u"
    ]
  },
  {
    "text": "tub",
    "segs": "t.u.b",
    "unit": "EC14",
    "tags": [
      "review",
      "sort:u",
      "dictation-safe"
    ]
  },
  {
    "text": "pup",
    "segs": "p.u.p",
    "unit": "EC14",
    "tags": [
      "review",
      "sort:u",
      "dictation-safe"
    ]
  },
  {
    "text": "jug",
    "segs": "j.u.g",
    "unit": "EC14",
    "pic": "a jug",
    "tags": [
      "review",
      "picture",
      "sort:u"
    ]
  },
  {
    "text": "puff",
    "segs": "p.u.ff",
    "unit": "EC14",
    "tags": [
      "review",
      "sort:u",
      "dictation-safe"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The cube is in the tube.",
    "maxUnit": "EC12"
  },
  {
    "text": "The horse stood by the gate.",
    "maxUnit": "EC12"
  },
  {
    "text": "The wood is in the shed.",
    "maxUnit": "EC12"
  },
  {
    "text": "The bull stood by the bush.",
    "maxUnit": "EC12"
  },
  {
    "text": "The cook put a pot on the hob.",
    "maxUnit": "EC12"
  },
  {
    "text": "The broom is by the door.",
    "maxUnit": "EC12"
  },
  {
    "text": "The spoon is in the soup.",
    "maxUnit": "EC12"
  },
  {
    "text": "The blue moon is bright.",
    "maxUnit": "EC12"
  }
] as const;

export const chains = [
  [
    "son",
    "sun",
    "bun",
    "bus",
    "us"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "lemon",
    "syllables": "le|mon",
    "schwa": [
      1
    ]
  },
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "backrest",
    "syllables": "back|rest"
  },
  {
    "text": "sandpit",
    "syllables": "sand|pit"
  },
  {
    "text": "complex",
    "syllables": "com|plex"
  },
  {
    "text": "triplet",
    "syllables": "tri|plet"
  },
  {
    "text": "flagship",
    "syllables": "flag|ship"
  },
  {
    "text": "pinprick",
    "syllables": "pin|prick"
  },
  {
    "text": "splendid",
    "syllables": "splen|did"
  },
  {
    "text": "grandstand",
    "syllables": "grand|stand"
  }
] as const;
