// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "soup",
    "segs": "s.ou=oo.p",
    "unit": "EC15",
    "pic": "one bowl of vegetable soup with a spoon",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ou"
    ]
  },
  {
    "text": "group",
    "segs": "g.r.ou=oo.p",
    "unit": "EC15",
    "tags": [
      "new",
      "sort:ou",
      "dictation-safe"
    ]
  },
  {
    "text": "touch",
    "segs": "t.ou=u.ch",
    "unit": "EC15",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ou"
    ]
  },
  {
    "text": "young",
    "segs": "y.ou=u.ng",
    "unit": "EC15",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ou"
    ]
  },
  {
    "text": "trouble",
    "segs": "t.r.ou=u.b.le=l",
    "unit": "EC15",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ou"
    ]
  },
  {
    "text": "double",
    "segs": "d.ou=u.b.le=l",
    "unit": "EC15",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ou"
    ]
  },
  {
    "text": "house",
    "segs": "h.ou=ou.se=s",
    "unit": "EC15",
    "pic": "one small red-roofed house",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:ou"
    ]
  },
  {
    "text": "cloud",
    "segs": "c.l.ou=ou.d",
    "unit": "EC15",
    "pic": "one fluffy white cloud",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:ou"
    ]
  },
  {
    "text": "out",
    "segs": "ou=ou.t",
    "unit": "EC15",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ou"
    ]
  },
  {
    "text": "loud",
    "segs": "l.ou=ou.d",
    "unit": "EC15",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ou"
    ]
  },
  {
    "text": "shout",
    "segs": "sh.ou=ou.t",
    "unit": "EC15",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ou"
    ]
  },
  {
    "text": "count",
    "segs": "c.ou=ou.n.t",
    "unit": "EC15",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ou"
    ]
  },
  {
    "text": "found",
    "segs": "f.ou=ou.n.d",
    "unit": "EC15",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ou"
    ]
  },
  {
    "text": "mound",
    "segs": "m.ou=ou.n.d",
    "unit": "EC15",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ou"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The wood is in the shed.",
    "maxUnit": "EC13"
  },
  {
    "text": "The cook put a pot on the hob.",
    "maxUnit": "EC13"
  },
  {
    "text": "I can see a bright light.",
    "maxUnit": "EC13"
  },
  {
    "text": "The pie is on the table.",
    "maxUnit": "EC13"
  },
  {
    "text": "The blue moon is bright.",
    "maxUnit": "EC13"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC13"
  }
] as const;

export const chains = [] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "seven",
    "syllables": "se|ven",
    "schwa": [
      1
    ]
  },
  {
    "text": "fantastic",
    "syllables": "fan|tas|tic"
  },
  {
    "text": "compliment",
    "syllables": "com|pli|ment"
  },
  {
    "text": "lemon",
    "syllables": "le|mon",
    "schwa": [
      1
    ]
  },
  {
    "text": "salad",
    "syllables": "sa|lad",
    "schwa": [
      1
    ]
  },
  {
    "text": "raindrop",
    "syllables": "rain|drop"
  },
  {
    "text": "playpen",
    "syllables": "play|pen"
  },
  {
    "text": "fishbowl",
    "syllables": "fish|bowl"
  },
  {
    "text": "snowflake",
    "syllables": "snow|flake"
  }
] as const;
