// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "scent",
    "segs": "sc=s.e.n.t",
    "unit": "EC16",
    "tags": [
      "new",
      "dictation-safe",
      "sort:sc"
    ]
  },
  {
    "text": "fence",
    "segs": "f.e.n.ce=s",
    "unit": "EC16",
    "pic": "one short wooden garden fence",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ce"
    ]
  },
  {
    "text": "bounce",
    "segs": "b.ou=ou.n.ce=s",
    "unit": "EC16",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ce"
    ]
  },
  {
    "text": "peace",
    "segs": "p.ea.ce=s",
    "unit": "EC16",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ce"
    ]
  },
  {
    "text": "mince",
    "segs": "m.i.n.ce=s",
    "unit": "EC16",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ce"
    ]
  },
  {
    "text": "house",
    "segs": "h.ou=ou.se=s",
    "unit": "EC16",
    "pic": "one small red-roofed house",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:se"
    ]
  },
  {
    "text": "mouse",
    "segs": "m.ou=ou.se=s",
    "unit": "EC16",
    "pic": "one small grey mouse with a long tail",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:se"
    ]
  },
  {
    "text": "goose",
    "segs": "g.oo.se=s",
    "unit": "EC16",
    "tags": [
      "review",
      "dictation-safe",
      "sort:se"
    ]
  },
  {
    "text": "else",
    "segs": "e.l.se=s",
    "unit": "EC16",
    "tags": [
      "review",
      "dictation-safe",
      "sort:se"
    ]
  },
  {
    "text": "dress",
    "segs": "d.r.e.ss",
    "unit": "EC16",
    "pic": "one simple bright red child-sized dress on a plain hanger, clear fitted bodice and wide flared skirt, shown full length with no person",
    "tags": [
      "review",
      "picture",
      "sort:ss"
    ]
  },
  {
    "text": "kiss",
    "segs": "k.i.ss",
    "unit": "EC16",
    "tags": [
      "review",
      "sort:ss",
      "dictation-safe"
    ]
  },
  {
    "text": "mess",
    "segs": "m.e.ss",
    "unit": "EC16",
    "tags": [
      "review",
      "sort:ss",
      "dictation-safe"
    ]
  },
  {
    "text": "fuss",
    "segs": "f.u.ss",
    "unit": "EC16",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ss"
    ]
  },
  {
    "text": "hiss",
    "segs": "h.i.ss",
    "unit": "EC16",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ss"
    ]
  },
  {
    "text": "miss",
    "segs": "m.i.ss",
    "unit": "EC16",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ss"
    ]
  },
  {
    "text": "less",
    "segs": "l.e.ss",
    "unit": "EC16",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ss"
    ]
  },
  {
    "text": "boss",
    "segs": "b.o.ss",
    "unit": "EC16",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ss"
    ]
  },
  {
    "text": "sun",
    "segs": "s.u.n",
    "unit": "EC16",
    "pic": "the sun",
    "tags": [
      "review",
      "picture",
      "sort:s"
    ]
  },
  {
    "text": "bus",
    "segs": "b.u.s",
    "unit": "EC16",
    "pic": "a red double-decker bus",
    "tags": [
      "review",
      "picture",
      "sort:s"
    ]
  },
  {
    "text": "snow",
    "segs": "s.n.ow",
    "unit": "EC16",
    "pic": "snow",
    "tags": [
      "review",
      "picture",
      "sort:s"
    ]
  },
  {
    "text": "desk",
    "segs": "d.e.s.k",
    "unit": "EC16",
    "pic": "one wooden writing desk with a wide flat top, a single drawer and an empty chair pushed under it, no writing",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:s"
    ]
  },
  {
    "text": "swim",
    "segs": "s.w.i.m",
    "unit": "EC16",
    "pic": "a child actively swimming across a little patch of bright blue water, side view with face above the water and one arm reaching forward in a swimming stroke, small splashes around them",
    "tags": [
      "review",
      "picture",
      "sort:s"
    ]
  },
  {
    "text": "sock",
    "segs": "s.o.ck",
    "unit": "EC16",
    "pic": "a sock",
    "tags": [
      "review",
      "picture",
      "sort:s"
    ]
  },
  {
    "text": "sit",
    "segs": "s.i.t",
    "unit": "EC16",
    "pic": "one smiling little girl sitting down: curly brown hair, a friendly face with two eyes and a big smile, a yellow T-shirt and blue shorts, sitting on a small red chair that is mostly hidden under her, both feet on the floor, facing the viewer, the whole girl visible from head to toe",
    "tags": [
      "review",
      "picture",
      "sort:s"
    ]
  },
  {
    "text": "stand",
    "segs": "s.t.a.n.d",
    "unit": "EC16",
    "tags": [
      "review",
      "sort:s",
      "dictation-safe"
    ]
  },
  {
    "text": "swing",
    "segs": "s.w.i.ng",
    "unit": "EC16",
    "pic": "a swing",
    "tags": [
      "review",
      "picture",
      "sort:s"
    ]
  },
  {
    "text": "snail",
    "segs": "s.n.ai.l",
    "unit": "EC16",
    "pic": "a snail",
    "tags": [
      "review",
      "picture",
      "sort:s"
    ]
  },
  {
    "text": "crisp",
    "segs": "c.r.i.s.p",
    "unit": "EC16",
    "pic": "one very thin golden potato crisp with a wavy curled edge and a few darker toasted patches, shown tilted so its thinness is obvious, no whole potato",
    "tags": [
      "review",
      "picture",
      "sort:s"
    ]
  },
  {
    "text": "sand",
    "segs": "s.a.n.d",
    "unit": "EC16",
    "pic": "a small golden sandcastle with a little flag on top, sitting on a heap of sand",
    "tags": [
      "review",
      "picture",
      "sort:s"
    ]
  },
  {
    "text": "soap",
    "segs": "s.oa.p",
    "unit": "EC16",
    "pic": "a pink bar of soap covered in white foam with shiny soap bubbles floating around it",
    "tags": [
      "review",
      "picture",
      "sort:s"
    ]
  },
  {
    "text": "toast",
    "segs": "t.oa.s.t",
    "unit": "EC16",
    "pic": "toast",
    "tags": [
      "review",
      "picture",
      "sort:s"
    ]
  },
  {
    "text": "chest",
    "segs": "ch.e.s.t",
    "unit": "EC16",
    "pic": "a plain wooden storage chest with a curved lid and simple iron bands, closed, no treasure or coins or lock",
    "tags": [
      "review",
      "picture",
      "sort:s"
    ]
  },
  {
    "text": "strap",
    "segs": "s.t.r.a.p",
    "unit": "EC16",
    "tags": [
      "review",
      "sort:s",
      "dictation-safe"
    ]
  },
  {
    "text": "vest",
    "segs": "v.e.s.t",
    "unit": "EC16",
    "pic": "a vest",
    "tags": [
      "review",
      "picture",
      "sort:s"
    ]
  },
  {
    "text": "crust",
    "segs": "c.r.u.s.t",
    "unit": "EC16",
    "tags": [
      "review",
      "sort:s",
      "dictation-safe"
    ]
  },
  {
    "text": "stamp",
    "segs": "s.t.a.m.p",
    "unit": "EC16",
    "pic": "one postage stamp with a scalloped edge and a simple flower picture, no letters or numbers",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:s"
    ]
  },
  {
    "text": "twist",
    "segs": "t.w.i.s.t",
    "unit": "EC16",
    "tags": [
      "review",
      "sort:s",
      "dictation-safe"
    ]
  },
  {
    "text": "frost",
    "segs": "f.r.o.s.t",
    "unit": "EC16",
    "tags": [
      "review",
      "sort:s",
      "dictation-safe"
    ]
  },
  {
    "text": "scrub",
    "segs": "s.c.r.u.b",
    "unit": "EC16",
    "tags": [
      "review",
      "sort:s",
      "dictation-safe"
    ]
  },
  {
    "text": "whisk",
    "segs": "wh.i.s.k",
    "unit": "EC16",
    "pic": "a whisk",
    "tags": [
      "review",
      "picture",
      "sort:s"
    ]
  },
  {
    "text": "nest",
    "segs": "n.e.s.t",
    "unit": "EC16",
    "pic": "a bird nest",
    "tags": [
      "review",
      "picture",
      "sort:s"
    ]
  },
  {
    "text": "stump",
    "segs": "s.t.u.m.p",
    "unit": "EC16",
    "pic": "a tree stump",
    "tags": [
      "review",
      "picture",
      "sort:s"
    ]
  },
  {
    "text": "strip",
    "segs": "s.t.r.i.p",
    "unit": "EC16",
    "tags": [
      "review",
      "sort:s",
      "dictation-safe"
    ]
  },
  {
    "text": "split",
    "segs": "s.p.l.i.t",
    "unit": "EC16",
    "tags": [
      "review",
      "sort:s",
      "dictation-safe"
    ]
  },
  {
    "text": "squid",
    "segs": "s.q.u=w.i.d",
    "unit": "EC16",
    "pic": "one squid swimming alone, with a long pointed mantle and ten trailing arms",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:s"
    ]
  },
  {
    "text": "scrap",
    "segs": "s.c.r.a.p",
    "unit": "EC16",
    "tags": [
      "review",
      "sort:s",
      "dictation-safe"
    ]
  },
  {
    "text": "sink",
    "segs": "s.i.n=ng.k",
    "unit": "EC16",
    "pic": "one plain white kitchen sink with a tap and drain, empty and clean",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:s"
    ]
  },
  {
    "text": "yes",
    "segs": "y.e.s",
    "unit": "EC16",
    "tags": [
      "review",
      "dictation-safe",
      "sort:s"
    ]
  },
  {
    "text": "stop",
    "segs": "s.t.o.p",
    "unit": "EC16",
    "tags": [
      "review",
      "dictation-safe",
      "sort:s"
    ]
  },
  {
    "text": "say",
    "segs": "s.ay",
    "unit": "EC16",
    "tags": [
      "review",
      "dictation-safe",
      "sort:s"
    ]
  },
  {
    "text": "seat",
    "segs": "s.ea.t",
    "unit": "EC16",
    "tags": [
      "review",
      "dictation-safe",
      "sort:s"
    ]
  },
  {
    "text": "sing",
    "segs": "s.i.ng",
    "unit": "EC16",
    "tags": [
      "review",
      "dictation-safe",
      "sort:s"
    ]
  },
  {
    "text": "song",
    "segs": "s.o.ng",
    "unit": "EC16",
    "tags": [
      "review",
      "dictation-safe",
      "sort:s"
    ]
  },
  {
    "text": "sleep",
    "segs": "s.l.ee.p",
    "unit": "EC16",
    "tags": [
      "review",
      "dictation-safe",
      "sort:s"
    ]
  },
  {
    "text": "this",
    "segs": "th=dh.i.s",
    "unit": "EC16",
    "tags": [
      "review",
      "dictation-safe",
      "sort:s"
    ]
  },
  {
    "text": "us",
    "segs": "u.s",
    "unit": "EC16",
    "tags": [
      "review",
      "dictation-safe",
      "sort:s"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The star is over the barn.",
    "maxUnit": "EC14"
  },
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC14"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC14"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC14"
  },
  {
    "text": "The broom is by the door.",
    "maxUnit": "EC14"
  },
  {
    "text": "The spoon is in the soup.",
    "maxUnit": "EC14"
  },
  {
    "text": "A mouse ran out of the house.",
    "maxUnit": "EC14"
  },
  {
    "text": "The cow is by the house.",
    "maxUnit": "EC14"
  }
] as const;

export const chains = [
  [
    "scent",
    "dent",
    "den",
    "down",
    "town"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "lemon",
    "syllables": "le|mon",
    "schwa": [
      1
    ]
  },
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "sunburn",
    "syllables": "sun|burn"
  },
  {
    "text": "blackbird",
    "syllables": "black|bird"
  },
  {
    "text": "haircut",
    "syllables": "hair|cut"
  },
  {
    "text": "staircase",
    "syllables": "stair|case"
  },
  {
    "text": "sunset",
    "syllables": "sun|set"
  },
  {
    "text": "zigzag",
    "syllables": "zig|zag"
  },
  {
    "text": "sunlit",
    "syllables": "sun|lit"
  },
  {
    "text": "wigwam",
    "syllables": "wig|wam"
  }
] as const;
