// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "dogs",
    "segs": "d.o.g.s=z",
    "unit": "EC17",
    "tags": [
      "new",
      "dictation-safe",
      "sort:s"
    ]
  },
  {
    "text": "beds",
    "segs": "b.e.d.s=z",
    "unit": "EC17",
    "tags": [
      "new",
      "dictation-safe",
      "sort:s"
    ]
  },
  {
    "text": "pigs",
    "segs": "p.i.g.s=z",
    "unit": "EC17",
    "tags": [
      "new",
      "dictation-safe",
      "sort:s"
    ]
  },
  {
    "text": "bags",
    "segs": "b.a.g.s=z",
    "unit": "EC17",
    "tags": [
      "new",
      "dictation-safe",
      "sort:s"
    ]
  },
  {
    "text": "pens",
    "segs": "p.e.n.s=z",
    "unit": "EC17",
    "tags": [
      "new",
      "dictation-safe",
      "sort:s"
    ]
  },
  {
    "text": "trees",
    "segs": "t.r.ee.s=z",
    "unit": "EC17",
    "tags": [
      "new",
      "dictation-safe",
      "sort:s"
    ]
  },
  {
    "text": "hens",
    "segs": "h.e.n.s=z",
    "unit": "EC17",
    "tags": [
      "new",
      "dictation-safe",
      "sort:s"
    ]
  },
  {
    "text": "hills",
    "segs": "h.i.ll.s=z",
    "unit": "EC17",
    "tags": [
      "new",
      "dictation-safe",
      "sort:s"
    ]
  },
  {
    "text": "sun",
    "segs": "s.u.n",
    "unit": "EC17",
    "pic": "the sun",
    "tags": [
      "review",
      "picture",
      "sort:s"
    ]
  },
  {
    "text": "bus",
    "segs": "b.u.s",
    "unit": "EC17",
    "pic": "a red double-decker bus",
    "tags": [
      "review",
      "picture",
      "sort:s"
    ]
  },
  {
    "text": "snow",
    "segs": "s.n.ow",
    "unit": "EC17",
    "pic": "snow",
    "tags": [
      "review",
      "picture",
      "sort:s"
    ]
  },
  {
    "text": "desk",
    "segs": "d.e.s.k",
    "unit": "EC17",
    "pic": "one wooden writing desk with a wide flat top, a single drawer and an empty chair pushed under it, no writing",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:s"
    ]
  },
  {
    "text": "swim",
    "segs": "s.w.i.m",
    "unit": "EC17",
    "pic": "a child actively swimming across a little patch of bright blue water, side view with face above the water and one arm reaching forward in a swimming stroke, small splashes around them",
    "tags": [
      "review",
      "picture",
      "sort:s"
    ]
  },
  {
    "text": "sock",
    "segs": "s.o.ck",
    "unit": "EC17",
    "pic": "a sock",
    "tags": [
      "review",
      "picture",
      "sort:s"
    ]
  },
  {
    "text": "sit",
    "segs": "s.i.t",
    "unit": "EC17",
    "pic": "one smiling little girl sitting down: curly brown hair, a friendly face with two eyes and a big smile, a yellow T-shirt and blue shorts, sitting on a small red chair that is mostly hidden under her, both feet on the floor, facing the viewer, the whole girl visible from head to toe",
    "tags": [
      "review",
      "picture",
      "sort:s"
    ]
  },
  {
    "text": "stand",
    "segs": "s.t.a.n.d",
    "unit": "EC17",
    "tags": [
      "review",
      "sort:s",
      "dictation-safe"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The spoon is in the soup.",
    "maxUnit": "EC15"
  },
  {
    "text": "The wood is in the shed.",
    "maxUnit": "EC15"
  },
  {
    "text": "The cook put a pot on the hob.",
    "maxUnit": "EC15"
  },
  {
    "text": "I can see a bright light.",
    "maxUnit": "EC15"
  },
  {
    "text": "The pie is on the table.",
    "maxUnit": "EC15"
  },
  {
    "text": "The blue moon is bright.",
    "maxUnit": "EC15"
  }
] as const;

export const chains = [] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "seven",
    "syllables": "se|ven",
    "schwa": [
      1
    ]
  },
  {
    "text": "bedbug",
    "syllables": "bed|bug"
  },
  {
    "text": "hotdog",
    "syllables": "hot|dog"
  },
  {
    "text": "kidnap",
    "syllables": "kid|nap"
  },
  {
    "text": "pigpen",
    "syllables": "pig|pen"
  },
  {
    "text": "dogleg",
    "syllables": "dog|leg"
  },
  {
    "text": "admit",
    "syllables": "ad|mit"
  },
  {
    "text": "upset",
    "syllables": "up|set"
  },
  {
    "text": "comic",
    "syllables": "co|mic"
  }
] as const;
