// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "doll",
    "segs": "d.o.ll",
    "unit": "EC18",
    "pic": "a doll",
    "tags": [
      "review",
      "picture",
      "sort:ll"
    ]
  },
  {
    "text": "bell",
    "segs": "b.e.ll",
    "unit": "EC18",
    "pic": "a bell",
    "tags": [
      "review",
      "picture",
      "sort:ll"
    ]
  },
  {
    "text": "hill",
    "segs": "h.i.ll",
    "unit": "EC18",
    "pic": "one smooth green grassy hill rising above a flat plain, no food or buildings",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:ll"
    ]
  },
  {
    "text": "yell",
    "segs": "y.e.ll",
    "unit": "EC18",
    "pic": "one child calling out loudly with hands cupped round the mouth",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:ll"
    ]
  },
  {
    "text": "shell",
    "segs": "sh.e.ll",
    "unit": "EC18",
    "pic": "a sea shell",
    "tags": [
      "review",
      "picture",
      "sort:ll"
    ]
  },
  {
    "text": "well",
    "segs": "w.e.ll",
    "unit": "EC18",
    "pic": "a stone well",
    "tags": [
      "review",
      "picture",
      "sort:ll"
    ]
  },
  {
    "text": "tell",
    "segs": "t.e.ll",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ll"
    ]
  },
  {
    "text": "smell",
    "segs": "s.m.e.ll",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ll"
    ]
  },
  {
    "text": "hole",
    "segs": "h.o=oe.le=l",
    "unit": "EC18",
    "pic": "one round hole in a wooden plank",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:le"
    ]
  },
  {
    "text": "pole",
    "segs": "p.o=oe.le=l",
    "unit": "EC18",
    "pic": "one plain upright wooden pole",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:le"
    ]
  },
  {
    "text": "mole",
    "segs": "m.o=oe.le=l",
    "unit": "EC18",
    "pic": "one small brown mole animal with a pointed nose and digging paws",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:le"
    ]
  },
  {
    "text": "smile",
    "segs": "s.m.i=ie.le=l",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:le"
    ]
  },
  {
    "text": "tale",
    "segs": "t.a=ae.le=l",
    "unit": "EC18",
    "tags": [
      "review",
      "reading-only",
      "sort:le"
    ]
  },
  {
    "text": "pile",
    "segs": "p.i=ie.le=l",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:le"
    ]
  },
  {
    "text": "sale",
    "segs": "s.a=ae.le=l",
    "unit": "EC18",
    "tags": [
      "review",
      "reading-only",
      "sort:le"
    ]
  },
  {
    "text": "rule",
    "segs": "r.u=oo.le=l",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:le"
    ]
  },
  {
    "text": "leg",
    "segs": "l.e.g",
    "unit": "EC18",
    "pic": "one isolated bare human leg from the upper thigh to all five toes, bent slightly at the clearly visible knee, natural skin colour, no sock, shoe, trousers or rest of body",
    "tags": [
      "review",
      "picture",
      "sort:l"
    ]
  },
  {
    "text": "milk",
    "segs": "m.i.l.k",
    "unit": "EC18",
    "pic": "a glass of milk",
    "tags": [
      "review",
      "picture",
      "sort:l"
    ]
  },
  {
    "text": "clock",
    "segs": "c.l.o.ck",
    "unit": "EC18",
    "pic": "a clock",
    "tags": [
      "review",
      "picture",
      "sort:l"
    ]
  },
  {
    "text": "leaf",
    "segs": "l.ea.f",
    "unit": "EC18",
    "pic": "a leaf",
    "tags": [
      "review",
      "picture",
      "sort:l"
    ]
  },
  {
    "text": "lamp",
    "segs": "l.a.m.p",
    "unit": "EC18",
    "pic": "a lamp",
    "tags": [
      "review",
      "picture",
      "sort:l"
    ]
  },
  {
    "text": "light",
    "segs": "l.igh.t",
    "unit": "EC18",
    "pic": "a glowing lamp light bulb shining",
    "tags": [
      "review",
      "picture",
      "sort:l"
    ]
  },
  {
    "text": "lock",
    "segs": "l.o.ck",
    "unit": "EC18",
    "pic": "a padlock",
    "tags": [
      "review",
      "picture",
      "sort:l"
    ]
  },
  {
    "text": "snail",
    "segs": "s.n.ai.l",
    "unit": "EC18",
    "pic": "a snail",
    "tags": [
      "review",
      "picture",
      "sort:l"
    ]
  },
  {
    "text": "flag",
    "segs": "f.l.a.g",
    "unit": "EC18",
    "pic": "a flag",
    "tags": [
      "review",
      "picture",
      "sort:l"
    ]
  },
  {
    "text": "plum",
    "segs": "p.l.u.m",
    "unit": "EC18",
    "pic": "a plum",
    "tags": [
      "review",
      "picture",
      "sort:l"
    ]
  },
  {
    "text": "belt",
    "segs": "b.e.l.t",
    "unit": "EC18",
    "pic": "a belt",
    "tags": [
      "review",
      "picture",
      "sort:l"
    ]
  },
  {
    "text": "plug",
    "segs": "p.l.u.g",
    "unit": "EC18",
    "pic": "a plug",
    "tags": [
      "review",
      "picture",
      "sort:l"
    ]
  },
  {
    "text": "tail",
    "segs": "t.ai.l",
    "unit": "EC18",
    "pic": "a fox tail",
    "tags": [
      "review",
      "picture",
      "sort:l"
    ]
  },
  {
    "text": "elf",
    "segs": "e.l.f",
    "unit": "EC18",
    "pic": "an elf",
    "tags": [
      "review",
      "picture",
      "sort:l"
    ]
  },
  {
    "text": "log",
    "segs": "l.o.g",
    "unit": "EC18",
    "pic": "a log",
    "tags": [
      "review",
      "picture",
      "sort:l"
    ]
  },
  {
    "text": "lid",
    "segs": "l.i.d",
    "unit": "EC18",
    "pic": "a pot lid",
    "tags": [
      "review",
      "picture",
      "sort:l"
    ]
  },
  {
    "text": "quilt",
    "segs": "q.u=w.i.l.t",
    "unit": "EC18",
    "pic": "one stitched patchwork quilt folded on a plain bed, with a repeating square pattern",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:l"
    ]
  },
  {
    "text": "split",
    "segs": "s.p.l.i.t",
    "unit": "EC18",
    "pic": "one log split neatly into two matching halves",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:l"
    ]
  },
  {
    "text": "nail",
    "segs": "n.ai.l",
    "unit": "EC18",
    "pic": "a nail",
    "tags": [
      "review",
      "picture",
      "sort:l"
    ]
  },
  {
    "text": "play",
    "segs": "p.l.ay",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:l"
    ]
  },
  {
    "text": "black",
    "segs": "b.l.a.ck",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:l"
    ]
  },
  {
    "text": "lunch",
    "segs": "l.u.n.ch",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:l"
    ]
  },
  {
    "text": "clap",
    "segs": "c.l.a.p",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:l"
    ]
  },
  {
    "text": "help",
    "segs": "h.e.l.p",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:l"
    ]
  },
  {
    "text": "long",
    "segs": "l.o.ng",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:l"
    ]
  },
  {
    "text": "sleep",
    "segs": "s.l.ee.p",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:l"
    ]
  },
  {
    "text": "blow",
    "segs": "b.l.ow",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:l"
    ]
  },
  {
    "text": "lap",
    "segs": "l.a.p",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:l"
    ]
  },
  {
    "text": "lip",
    "segs": "l.i.p",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:l"
    ]
  },
  {
    "text": "slept",
    "segs": "s.l.e.p.t",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:l"
    ]
  },
  {
    "text": "slow",
    "segs": "s.l.ow",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:l"
    ]
  },
  {
    "text": "cloth",
    "segs": "c.l.o.th",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:l"
    ]
  },
  {
    "text": "let",
    "segs": "l.e.t",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:l"
    ]
  },
  {
    "text": "left",
    "segs": "l.e.f.t",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:l"
    ]
  },
  {
    "text": "lift",
    "segs": "l.i.f.t",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:l"
    ]
  },
  {
    "text": "flat",
    "segs": "f.l.a.t",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:l"
    ]
  },
  {
    "text": "glad",
    "segs": "g.l.a.d",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:l"
    ]
  },
  {
    "text": "lost",
    "segs": "l.o.s.t",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:l"
    ]
  },
  {
    "text": "lump",
    "segs": "l.u.m.p",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:l"
    ]
  },
  {
    "text": "bulb",
    "segs": "b.u.l.b",
    "unit": "EC18",
    "tags": [
      "review",
      "dictation-safe",
      "sort:l"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The jar is on the cart.",
    "maxUnit": "EC16"
  },
  {
    "text": "The car is by the farm.",
    "maxUnit": "EC16"
  },
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC16"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC16"
  },
  {
    "text": "The cube is in the tube.",
    "maxUnit": "EC16"
  },
  {
    "text": "A hawk sat on the fence.",
    "maxUnit": "EC16"
  },
  {
    "text": "The pencil fell off the table.",
    "maxUnit": "EC16"
  },
  {
    "text": "A little bird sat on the fence.",
    "maxUnit": "EC16"
  }
] as const;

export const chains = [
  [
    "doll",
    "do",
    "day",
    "may",
    "mow"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "lemon",
    "syllables": "le|mon",
    "schwa": [
      1
    ]
  },
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "object",
    "syllables": "ob|ject"
  },
  {
    "text": "uplift",
    "syllables": "up|lift"
  },
  {
    "text": "dentist",
    "syllables": "den|tist"
  },
  {
    "text": "suspect",
    "syllables": "sus|pect"
  },
  {
    "text": "himself",
    "syllables": "him|self"
  },
  {
    "text": "contest",
    "syllables": "con|test"
  },
  {
    "text": "backhand",
    "syllables": "back|hand"
  },
  {
    "text": "eggshell",
    "syllables": "egg|shell"
  }
] as const;
