// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "sauce",
    "segs": "s.au=or.ce=s",
    "unit": "EC19",
    "tags": [
      "new",
      "dictation-safe",
      "sort:au"
    ]
  },
  {
    "text": "door",
    "segs": "d.oor=or",
    "unit": "EC19",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oor"
    ]
  },
  {
    "text": "floor",
    "segs": "f.l.oor=or",
    "unit": "EC19",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oor"
    ]
  },
  {
    "text": "poor",
    "segs": "p.oor=or",
    "unit": "EC19",
    "tags": [
      "new",
      "reading-only",
      "sort:oor"
    ]
  },
  {
    "text": "wart",
    "segs": "w.ar=or.t",
    "unit": "EC19",
    "pic": "one small wart on a finger, shown gently",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ar"
    ]
  },
  {
    "text": "dwarf",
    "segs": "d.w.ar=or.f",
    "unit": "EC19",
    "pic": "one friendly storybook dwarf standing alone",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ar"
    ]
  },
  {
    "text": "warm",
    "segs": "w.ar=or.m",
    "unit": "EC19",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ar"
    ]
  },
  {
    "text": "warn",
    "segs": "w.ar=or.n",
    "unit": "EC19",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ar"
    ]
  },
  {
    "text": "wall",
    "segs": "w.al=or.l",
    "unit": "EC19",
    "pic": "one short brick wall",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:al"
    ]
  },
  {
    "text": "chalk",
    "segs": "ch.al=or.k",
    "unit": "EC19",
    "pic": "one short white stick of chalk",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:al"
    ]
  },
  {
    "text": "tall",
    "segs": "t.al=or.l",
    "unit": "EC19",
    "tags": [
      "new",
      "dictation-safe",
      "sort:al"
    ]
  },
  {
    "text": "small",
    "segs": "s.m.al=or.l",
    "unit": "EC19",
    "tags": [
      "new",
      "dictation-safe",
      "sort:al"
    ]
  },
  {
    "text": "talk",
    "segs": "t.al=or.k",
    "unit": "EC19",
    "tags": [
      "new",
      "dictation-safe",
      "sort:al"
    ]
  },
  {
    "text": "walk",
    "segs": "w.al=or.k",
    "unit": "EC19",
    "tags": [
      "new",
      "dictation-safe",
      "sort:al"
    ]
  },
  {
    "text": "all",
    "segs": "al=or.l",
    "unit": "EC19",
    "tags": [
      "new",
      "dictation-safe",
      "sort:al"
    ]
  },
  {
    "text": "call",
    "segs": "c.al=or.l",
    "unit": "EC19",
    "tags": [
      "new",
      "dictation-safe",
      "sort:al"
    ]
  },
  {
    "text": "paw",
    "segs": "p.aw=or",
    "unit": "EC19",
    "pic": "one animal paw with soft pads shown close up",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:aw"
    ]
  },
  {
    "text": "jaw",
    "segs": "j.aw=or",
    "unit": "EC19",
    "pic": "one animal jawbone with teeth, shown gently",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:aw"
    ]
  },
  {
    "text": "lawn",
    "segs": "l.aw=or.n",
    "unit": "EC19",
    "pic": "one small square of green lawn grass",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:aw"
    ]
  },
  {
    "text": "saw",
    "segs": "s.aw=or",
    "unit": "EC19",
    "pic": "one hand saw with a wooden handle",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:aw"
    ]
  },
  {
    "text": "straw",
    "segs": "s.t.r.aw=or",
    "unit": "EC19",
    "pic": "one drinking straw bent at the top",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:aw"
    ]
  },
  {
    "text": "claw",
    "segs": "c.l.aw=or",
    "unit": "EC19",
    "pic": "one crab claw, detached and clearly shaped",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:aw"
    ]
  },
  {
    "text": "hawk",
    "segs": "h.aw=or.k",
    "unit": "EC19",
    "pic": "one hawk perched alone, full body",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:aw"
    ]
  },
  {
    "text": "yawn",
    "segs": "y.aw=or.n",
    "unit": "EC19",
    "tags": [
      "new",
      "dictation-safe",
      "sort:aw"
    ]
  },
  {
    "text": "horse",
    "segs": "h.or=or.se=s",
    "unit": "EC19",
    "pic": "one brown horse standing alone",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:or"
    ]
  },
  {
    "text": "fork",
    "segs": "f.or=or.k",
    "unit": "EC19",
    "pic": "one silver dinner fork",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:or"
    ]
  },
  {
    "text": "horn",
    "segs": "h.or=or.n",
    "unit": "EC19",
    "pic": "one curved animal horn",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:or"
    ]
  },
  {
    "text": "corn",
    "segs": "c.or=or.n",
    "unit": "EC19",
    "pic": "one corn cob with yellow kernels and green husk",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:or"
    ]
  },
  {
    "text": "cork",
    "segs": "c.or=or.k",
    "unit": "EC19",
    "pic": "one bottle cork alone",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:or"
    ]
  },
  {
    "text": "pork",
    "segs": "p.or=or.k",
    "unit": "EC19",
    "tags": [
      "new",
      "dictation-safe",
      "sort:or"
    ]
  },
  {
    "text": "short",
    "segs": "sh.or=or.t",
    "unit": "EC19",
    "tags": [
      "new",
      "dictation-safe",
      "sort:or"
    ]
  },
  {
    "text": "storm",
    "segs": "s.t.or=or.m",
    "unit": "EC19",
    "tags": [
      "new",
      "dictation-safe",
      "sort:or"
    ]
  },
  {
    "text": "draw",
    "segs": "d.r.aw=or",
    "unit": "EC19",
    "tags": [
      "new",
      "dictation-safe",
      "sort:aw"
    ]
  },
  {
    "text": "fall",
    "segs": "f.al=or.l",
    "unit": "EC19",
    "tags": [
      "new",
      "dictation-safe",
      "sort:al"
    ]
  },
  {
    "text": "sport",
    "segs": "s.p.or=or.t",
    "unit": "EC19",
    "tags": [
      "new",
      "dictation-safe",
      "sort:or"
    ]
  },
  {
    "text": "born",
    "segs": "b.or=or.n",
    "unit": "EC19",
    "tags": [
      "new",
      "dictation-safe",
      "sort:or"
    ]
  },
  {
    "text": "sort",
    "segs": "s.or=or.t",
    "unit": "EC19",
    "tags": [
      "new",
      "dictation-safe",
      "sort:or"
    ]
  },
  {
    "text": "fort",
    "segs": "f.or=or.t",
    "unit": "EC19",
    "tags": [
      "new",
      "dictation-safe",
      "sort:or"
    ]
  },
  {
    "text": "crawl",
    "segs": "c.r.aw=or.l",
    "unit": "EC19",
    "tags": [
      "new",
      "dictation-safe",
      "sort:aw"
    ]
  },
  {
    "text": "law",
    "segs": "l.aw=or",
    "unit": "EC19",
    "tags": [
      "new",
      "dictation-safe",
      "sort:aw"
    ]
  },
  {
    "text": "force",
    "segs": "f.or=or.ce=s",
    "unit": "EC19",
    "tags": [
      "new",
      "dictation-safe",
      "sort:or"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC17"
  },
  {
    "text": "The jar is on the cart.",
    "maxUnit": "EC17"
  },
  {
    "text": "The star is over the barn.",
    "maxUnit": "EC17"
  },
  {
    "text": "The car is by the farm.",
    "maxUnit": "EC17"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC17"
  },
  {
    "text": "The cube is in the tube.",
    "maxUnit": "EC17"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC17"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC17"
  }
] as const;

export const chains = [
  [
    "door",
    "poor",
    "paw",
    "law",
    "claw"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "seven",
    "syllables": "se|ven",
    "schwa": [
      1
    ]
  },
  {
    "text": "jackpot",
    "syllables": "jack|pot"
  },
  {
    "text": "padlock",
    "syllables": "pad|lock"
  },
  {
    "text": "backpack",
    "syllables": "back|pack"
  },
  {
    "text": "catfish",
    "syllables": "cat|fish"
  },
  {
    "text": "discuss",
    "syllables": "dis|cuss"
  },
  {
    "text": "dandruff",
    "syllables": "dan|druff"
  },
  {
    "text": "backdrop",
    "syllables": "back|drop"
  },
  {
    "text": "chopstick",
    "syllables": "chop|stick"
  }
] as const;
