// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "he",
    "segs": "h.e=ee",
    "unit": "EC2",
    "tags": [
      "new",
      "dictation-safe",
      "sort:e"
    ]
  },
  {
    "text": "we",
    "segs": "w.e=ee",
    "unit": "EC2",
    "tags": [
      "new",
      "dictation-safe",
      "sort:e"
    ]
  },
  {
    "text": "she",
    "segs": "sh.e=ee",
    "unit": "EC2",
    "tags": [
      "new",
      "dictation-safe",
      "sort:e"
    ]
  },
  {
    "text": "be",
    "segs": "b.e=ee",
    "unit": "EC2",
    "tags": [
      "new",
      "reading-only",
      "sort:e"
    ]
  },
  {
    "text": "leaf",
    "segs": "l.ea.f",
    "unit": "EC2",
    "pic": "a leaf",
    "tags": [
      "new",
      "picture",
      "sort:ea"
    ]
  },
  {
    "text": "beach",
    "segs": "b.ea.ch",
    "unit": "EC2",
    "pic": "one sandy beach beside blue sea",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ea"
    ]
  },
  {
    "text": "tea",
    "segs": "t.ea",
    "unit": "EC2",
    "pic": "one cup of tea in a plain white cup",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ea"
    ]
  },
  {
    "text": "bean",
    "segs": "b.ea.n",
    "unit": "EC2",
    "tags": [
      "new",
      "sort:ea",
      "reading-only"
    ]
  },
  {
    "text": "meal",
    "segs": "m.ea.l",
    "unit": "EC2",
    "tags": [
      "new",
      "sort:ea",
      "dictation-safe"
    ]
  },
  {
    "text": "eat",
    "segs": "ea.t",
    "unit": "EC2",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "seat",
    "segs": "s.ea.t",
    "unit": "EC2",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "dream",
    "segs": "d.r.ea.m",
    "unit": "EC2",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "bee",
    "segs": "b.ee",
    "unit": "EC2",
    "pic": "a bee",
    "tags": [
      "new",
      "picture",
      "sort:ee"
    ]
  },
  {
    "text": "tree",
    "segs": "t.r.ee",
    "unit": "EC2",
    "pic": "a tree",
    "tags": [
      "new",
      "picture",
      "sort:ee"
    ]
  },
  {
    "text": "feet",
    "segs": "f.ee.t",
    "unit": "EC2",
    "pic": "a pair of bare cartoon feet side by side with wiggly toes",
    "tags": [
      "new",
      "picture",
      "sort:ee"
    ]
  },
  {
    "text": "sheep",
    "segs": "sh.ee.p",
    "unit": "EC2",
    "pic": "a sheep",
    "tags": [
      "new",
      "picture",
      "sort:ee"
    ]
  },
  {
    "text": "queen",
    "segs": "q.u=w.ee.n",
    "unit": "EC2",
    "pic": "a queen",
    "tags": [
      "new",
      "picture",
      "sort:ee"
    ]
  },
  {
    "text": "teeth",
    "segs": "t.ee.th",
    "unit": "EC2",
    "pic": "a smiling mouth showing clean white teeth",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ee"
    ]
  },
  {
    "text": "wheel",
    "segs": "wh.ee.l",
    "unit": "EC2",
    "pic": "one single bicycle wheel with spokes",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ee"
    ]
  },
  {
    "text": "seed",
    "segs": "s.ee.d",
    "unit": "EC2",
    "pic": "one large brown seed with a tiny shoot",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ee"
    ]
  },
  {
    "text": "green",
    "segs": "g.r.ee.n",
    "unit": "EC2",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ee"
    ]
  },
  {
    "text": "sleep",
    "segs": "s.l.ee.p",
    "unit": "EC2",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ee"
    ]
  },
  {
    "text": "sea",
    "segs": "s.ea",
    "unit": "EC2",
    "tags": [
      "new",
      "reading-only",
      "sort:ea"
    ]
  },
  {
    "text": "three",
    "segs": "th.r.ee",
    "unit": "EC2",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ee"
    ]
  },
  {
    "text": "need",
    "segs": "n.ee.d",
    "unit": "EC2",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ee"
    ]
  },
  {
    "text": "keep",
    "segs": "k.ee.p",
    "unit": "EC2",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ee"
    ]
  },
  {
    "text": "meet",
    "segs": "m.ee.t",
    "unit": "EC2",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ee"
    ]
  },
  {
    "text": "beep",
    "segs": "b.ee.p",
    "unit": "EC2",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ee"
    ]
  },
  {
    "text": "read",
    "segs": "r.ea.d",
    "unit": "EC2",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "seen",
    "segs": "s.ee.n",
    "unit": "EC2",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ee"
    ]
  },
  {
    "text": "peep",
    "segs": "p.ee.p",
    "unit": "EC2",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ee"
    ]
  },
  {
    "text": "been",
    "segs": "b.ee.n",
    "unit": "EC2",
    "tags": [
      "new",
      "reading-only",
      "sort:ee"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The tart is on a plate.",
    "maxUnit": "BR"
  },
  {
    "text": "The jar is on the cart.",
    "maxUnit": "BR"
  },
  {
    "text": "The star is over the barn.",
    "maxUnit": "BR"
  },
  {
    "text": "The car is by the farm.",
    "maxUnit": "BR"
  },
  {
    "text": "The boy found a toy car.",
    "maxUnit": "BR"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "BR"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "BR"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "BR"
  }
] as const;

export const chains = [
  [
    "he",
    "be",
    "bee",
    "been",
    "bean"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [] as const;
