// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "their",
    "segs": "th=dh.eir=air",
    "unit": "EC20",
    "tags": [
      "new",
      "reading-only",
      "sort:eir"
    ]
  },
  {
    "text": "there",
    "segs": "th=dh.ere=air",
    "unit": "EC20",
    "tags": [
      "new",
      "reading-only",
      "sort:ere"
    ]
  },
  {
    "text": "where",
    "segs": "wh.ere=air",
    "unit": "EC20",
    "tags": [
      "new",
      "reading-only",
      "sort:ere"
    ]
  },
  {
    "text": "bear",
    "segs": "b.ear=air",
    "unit": "EC20",
    "pic": "one brown bear standing alone",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ear"
    ]
  },
  {
    "text": "pear",
    "segs": "p.ear=air",
    "unit": "EC20",
    "pic": "one ripe green pear",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ear"
    ]
  },
  {
    "text": "tear",
    "segs": "t.ear=air",
    "unit": "EC20",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ear"
    ]
  },
  {
    "text": "wear",
    "segs": "w.ear=air",
    "unit": "EC20",
    "tags": [
      "new",
      "reading-only",
      "sort:ear"
    ]
  },
  {
    "text": "hair",
    "segs": "h.air=air",
    "unit": "EC20",
    "pic": "one child's head with long flowing hair",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:air"
    ]
  },
  {
    "text": "chair",
    "segs": "ch.air=air",
    "unit": "EC20",
    "pic": "one simple wooden chair",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:air"
    ]
  },
  {
    "text": "stair",
    "segs": "s.t.air=air",
    "unit": "EC20",
    "pic": "one staircase with several clear steps",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:air"
    ]
  },
  {
    "text": "air",
    "segs": "air=air",
    "unit": "EC20",
    "tags": [
      "new",
      "dictation-safe",
      "sort:air"
    ]
  },
  {
    "text": "fair",
    "segs": "f.air=air",
    "unit": "EC20",
    "tags": [
      "new",
      "dictation-safe",
      "sort:air"
    ]
  },
  {
    "text": "pair",
    "segs": "p.air=air",
    "unit": "EC20",
    "tags": [
      "new",
      "reading-only",
      "sort:air"
    ]
  },
  {
    "text": "hare",
    "segs": "h.are=air",
    "unit": "EC20",
    "tags": [
      "new",
      "sort:are",
      "reading-only"
    ]
  },
  {
    "text": "care",
    "segs": "c.are=air",
    "unit": "EC20",
    "tags": [
      "new",
      "dictation-safe",
      "sort:are"
    ]
  },
  {
    "text": "share",
    "segs": "sh.are=air",
    "unit": "EC20",
    "tags": [
      "new",
      "dictation-safe",
      "sort:are"
    ]
  },
  {
    "text": "stare",
    "segs": "s.t.are=air",
    "unit": "EC20",
    "tags": [
      "new",
      "reading-only",
      "sort:are"
    ]
  },
  {
    "text": "dare",
    "segs": "d.are=air",
    "unit": "EC20",
    "tags": [
      "new",
      "dictation-safe",
      "sort:are"
    ]
  },
  {
    "text": "mare",
    "segs": "m.are=air",
    "unit": "EC20",
    "tags": [
      "new",
      "dictation-safe",
      "sort:are"
    ]
  },
  {
    "text": "bare",
    "segs": "b.are=air",
    "unit": "EC20",
    "tags": [
      "new",
      "reading-only",
      "sort:are"
    ]
  },
  {
    "text": "spare",
    "segs": "s.p.are=air",
    "unit": "EC20",
    "tags": [
      "new",
      "dictation-safe",
      "sort:are"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC18"
  },
  {
    "text": "The tall horse ate an apple.",
    "maxUnit": "EC18"
  },
  {
    "text": "The pencil fell off the table.",
    "maxUnit": "EC18"
  },
  {
    "text": "The child had a big kite.",
    "maxUnit": "EC18"
  },
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC18"
  },
  {
    "text": "The jar is on the cart.",
    "maxUnit": "EC18"
  },
  {
    "text": "The star is over the barn.",
    "maxUnit": "EC18"
  },
  {
    "text": "The car is by the farm.",
    "maxUnit": "EC18"
  }
] as const;

export const chains = [
  [
    "bear",
    "bare",
    "care",
    "cow",
    "crow"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "lemon",
    "syllables": "le|mon",
    "schwa": [
      1
    ]
  },
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "lipgloss",
    "syllables": "lip|gloss"
  },
  {
    "text": "wingspan",
    "syllables": "wing|span"
  },
  {
    "text": "backrest",
    "syllables": "back|rest"
  },
  {
    "text": "sandpit",
    "syllables": "sand|pit"
  },
  {
    "text": "complex",
    "syllables": "com|plex"
  },
  {
    "text": "triplet",
    "syllables": "tri|plet"
  },
  {
    "text": "flagship",
    "syllables": "flag|ship"
  },
  {
    "text": "pinprick",
    "syllables": "pin|prick"
  }
] as const;
