// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "due",
    "segs": "d.ue=ue",
    "unit": "EC21",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ue"
    ]
  },
  {
    "text": "stew",
    "segs": "s.t.ew=ue",
    "unit": "EC21",
    "pic": "one bowl of chunky vegetable stew",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ew"
    ]
  },
  {
    "text": "new",
    "segs": "n.ew=ue",
    "unit": "EC21",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ew"
    ]
  },
  {
    "text": "news",
    "segs": "n.ew=ue.s=z",
    "unit": "EC21",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ew"
    ]
  },
  {
    "text": "few",
    "segs": "f.ew=ue",
    "unit": "EC21",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ew"
    ]
  },
  {
    "text": "tube",
    "segs": "t.u=ue.be=b",
    "unit": "EC21",
    "tags": [
      "new",
      "sort:u",
      "dictation-safe"
    ]
  },
  {
    "text": "cube",
    "segs": "c.u=ue.be=b",
    "unit": "EC21",
    "pic": "one solid blue toy cube",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:u"
    ]
  },
  {
    "text": "duke",
    "segs": "d.u=ue.ke=k",
    "unit": "EC21",
    "tags": [
      "new",
      "sort:u",
      "dictation-safe"
    ]
  },
  {
    "text": "cute",
    "segs": "c.u=ue.te=t",
    "unit": "EC21",
    "tags": [
      "new",
      "dictation-safe",
      "sort:u"
    ]
  },
  {
    "text": "use",
    "segs": "u=ue.se=s",
    "unit": "EC21",
    "tags": [
      "new",
      "dictation-safe",
      "sort:u"
    ]
  },
  {
    "text": "tune",
    "segs": "t.u=ue.ne=n",
    "unit": "EC21",
    "tags": [
      "new",
      "dictation-safe",
      "sort:u"
    ]
  },
  {
    "text": "mule",
    "segs": "m.u=ue.le=l",
    "unit": "EC21",
    "tags": [
      "new",
      "dictation-safe",
      "sort:u"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC19"
  },
  {
    "text": "The jar is on the cart.",
    "maxUnit": "EC19"
  },
  {
    "text": "The star is over the barn.",
    "maxUnit": "EC19"
  },
  {
    "text": "The car is by the farm.",
    "maxUnit": "EC19"
  },
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC19"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC19"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC19"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC19"
  }
] as const;

export const chains = [
  [
    "due",
    "dare",
    "bare",
    "bee",
    "been"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "seven",
    "syllables": "se|ven",
    "schwa": [
      1
    ]
  },
  {
    "text": "benefit",
    "syllables": "be|ne|fit"
  },
  {
    "text": "habitat",
    "syllables": "ha|bi|tat"
  },
  {
    "text": "fantastic",
    "syllables": "fan|tas|tic"
  },
  {
    "text": "compliment",
    "syllables": "com|pli|ment"
  },
  {
    "text": "lemon",
    "syllables": "le|mon",
    "schwa": [
      1
    ]
  },
  {
    "text": "salad",
    "syllables": "sa|lad",
    "schwa": [
      1
    ]
  },
  {
    "text": "raindrop",
    "syllables": "rain|drop"
  },
  {
    "text": "playpen",
    "syllables": "play|pen"
  }
] as const;
