// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "flew",
    "segs": "f.l.ew=oo",
    "unit": "EC22",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ew"
    ]
  },
  {
    "text": "grew",
    "segs": "g.r.ew=oo",
    "unit": "EC22",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ew"
    ]
  },
  {
    "text": "blew",
    "segs": "b.l.ew=oo",
    "unit": "EC22",
    "tags": [
      "review",
      "reading-only",
      "sort:ew"
    ]
  },
  {
    "text": "brew",
    "segs": "b.r.ew=oo",
    "unit": "EC22",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ew"
    ]
  },
  {
    "text": "stew",
    "segs": "s.t.ew=ue",
    "unit": "EC22",
    "pic": "one bowl of chunky vegetable stew",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:ew"
    ]
  },
  {
    "text": "new",
    "segs": "n.ew=ue",
    "unit": "EC22",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ew"
    ]
  },
  {
    "text": "news",
    "segs": "n.ew=ue.s=z",
    "unit": "EC22",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ew"
    ]
  },
  {
    "text": "few",
    "segs": "f.ew=ue",
    "unit": "EC22",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ew"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC20"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC20"
  },
  {
    "text": "The bear sat on the chair.",
    "maxUnit": "EC20"
  },
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC20"
  },
  {
    "text": "The jar is on the cart.",
    "maxUnit": "EC20"
  },
  {
    "text": "The star is over the barn.",
    "maxUnit": "EC20"
  }
] as const;

export const chains = [] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "lemon",
    "syllables": "le|mon",
    "schwa": [
      1
    ]
  },
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "fishbowl",
    "syllables": "fish|bowl"
  },
  {
    "text": "snowflake",
    "syllables": "snow|flake"
  },
  {
    "text": "sunburn",
    "syllables": "sun|burn"
  },
  {
    "text": "blackbird",
    "syllables": "black|bird"
  },
  {
    "text": "haircut",
    "syllables": "hair|cut"
  },
  {
    "text": "staircase",
    "syllables": "stair|case"
  },
  {
    "text": "sunset",
    "syllables": "sun|set"
  },
  {
    "text": "zigzag",
    "syllables": "zig|zag"
  }
] as const;
