// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "boy",
    "segs": "b.oy=oy",
    "unit": "EC23",
    "pic": "one smiling young boy standing alone",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:oy"
    ]
  },
  {
    "text": "toy",
    "segs": "t.oy=oy",
    "unit": "EC23",
    "tags": [
      "new",
      "sort:oy",
      "dictation-safe"
    ]
  },
  {
    "text": "joy",
    "segs": "j.oy=oy",
    "unit": "EC23",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oy"
    ]
  },
  {
    "text": "coin",
    "segs": "c.oi=oy.n",
    "unit": "EC23",
    "pic": "one plain gold coin with no writing or numbers",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:oi"
    ]
  },
  {
    "text": "oil",
    "segs": "oi=oy.l",
    "unit": "EC23",
    "tags": [
      "new",
      "sort:oi",
      "dictation-safe"
    ]
  },
  {
    "text": "soil",
    "segs": "s.oi=oy.l",
    "unit": "EC23",
    "tags": [
      "new",
      "sort:oi",
      "dictation-safe"
    ]
  },
  {
    "text": "boil",
    "segs": "b.oi=oy.l",
    "unit": "EC23",
    "tags": [
      "new",
      "sort:oi",
      "dictation-safe"
    ]
  },
  {
    "text": "oink",
    "segs": "oi=oy.n=ng.k",
    "unit": "EC23",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oi"
    ]
  },
  {
    "text": "voice",
    "segs": "v.oi=oy.ce=s",
    "unit": "EC23",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oi"
    ]
  },
  {
    "text": "join",
    "segs": "j.oi=oy.n",
    "unit": "EC23",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oi"
    ]
  },
  {
    "text": "point",
    "segs": "p.oi=oy.n.t",
    "unit": "EC23",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oi"
    ]
  },
  {
    "text": "choice",
    "segs": "ch.oi=oy.ce=s",
    "unit": "EC23",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oi"
    ]
  },
  {
    "text": "spoil",
    "segs": "s.p.oi=oy.l",
    "unit": "EC23",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oi"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC21"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC21"
  },
  {
    "text": "The cube is in the tube.",
    "maxUnit": "EC21"
  },
  {
    "text": "The bull stood by the bush.",
    "maxUnit": "EC21"
  },
  {
    "text": "The cook put a pot on the hob.",
    "maxUnit": "EC21"
  },
  {
    "text": "The blue moon is bright.",
    "maxUnit": "EC21"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC21"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC21"
  }
] as const;

export const chains = [
  [
    "boy",
    "joy",
    "toy",
    "tea",
    "team"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "seven",
    "syllables": "se|ven",
    "schwa": [
      1
    ]
  },
  {
    "text": "cobweb",
    "syllables": "cob|web"
  },
  {
    "text": "nutmeg",
    "syllables": "nut|meg"
  },
  {
    "text": "bedbug",
    "syllables": "bed|bug"
  },
  {
    "text": "hotdog",
    "syllables": "hot|dog"
  },
  {
    "text": "kidnap",
    "syllables": "kid|nap"
  },
  {
    "text": "pigpen",
    "syllables": "pig|pen"
  },
  {
    "text": "dogleg",
    "syllables": "dog|leg"
  },
  {
    "text": "admit",
    "syllables": "ad|mit"
  }
] as const;
