// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "aunt",
    "segs": "au=ar.n.t",
    "unit": "EC24",
    "tags": [
      "new",
      "dictation-safe",
      "sort:au"
    ]
  },
  {
    "text": "palm",
    "segs": "p.al=ar.m",
    "unit": "EC24",
    "pic": "one palm tree with coconuts",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:al"
    ]
  },
  {
    "text": "half",
    "segs": "h.al=ar.f",
    "unit": "EC24",
    "tags": [
      "new",
      "dictation-safe",
      "sort:al"
    ]
  },
  {
    "text": "calm",
    "segs": "c.al=ar.m",
    "unit": "EC24",
    "tags": [
      "new",
      "dictation-safe",
      "sort:al"
    ]
  },
  {
    "text": "car",
    "segs": "c.ar=ar",
    "unit": "EC24",
    "pic": "one small red car",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ar"
    ]
  },
  {
    "text": "arm",
    "segs": "ar=ar.m",
    "unit": "EC24",
    "pic": "one person's bent arm shown from shoulder to hand",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ar"
    ]
  },
  {
    "text": "farm",
    "segs": "f.ar=ar.m",
    "unit": "EC24",
    "pic": "one farm barn with a field and a tractor",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ar"
    ]
  },
  {
    "text": "star",
    "segs": "s.t.ar=ar",
    "unit": "EC24",
    "pic": "one bright yellow five-pointed star",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ar"
    ]
  },
  {
    "text": "park",
    "segs": "p.ar=ar.k",
    "unit": "EC24",
    "pic": "one small park with a bench and a tree",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ar"
    ]
  },
  {
    "text": "barn",
    "segs": "b.ar=ar.n",
    "unit": "EC24",
    "pic": "one red farm barn with a pitched roof",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ar"
    ]
  },
  {
    "text": "cart",
    "segs": "c.ar=ar.t",
    "unit": "EC24",
    "pic": "one small wooden hand cart with two wheels",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ar"
    ]
  },
  {
    "text": "shark",
    "segs": "sh.ar=ar.k",
    "unit": "EC24",
    "pic": "one grey shark swimming alone, full body",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ar"
    ]
  },
  {
    "text": "jar",
    "segs": "j.ar=ar",
    "unit": "EC24",
    "pic": "one clear glass jar with a lid",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ar"
    ]
  },
  {
    "text": "card",
    "segs": "c.ar=ar.d",
    "unit": "EC24",
    "pic": "one blank greeting card folded open",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ar"
    ]
  },
  {
    "text": "tart",
    "segs": "t.ar=ar.t",
    "unit": "EC24",
    "pic": "one small fruit tart with pastry",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ar"
    ]
  },
  {
    "text": "charm",
    "segs": "ch.ar=ar.m",
    "unit": "EC24",
    "pic": "one small silver charm hanging from a bracelet",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ar"
    ]
  },
  {
    "text": "bark",
    "segs": "b.ar=ar.k",
    "unit": "EC24",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ar"
    ]
  },
  {
    "text": "dark",
    "segs": "d.ar=ar.k",
    "unit": "EC24",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ar"
    ]
  },
  {
    "text": "far",
    "segs": "f.ar=ar",
    "unit": "EC24",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ar"
    ]
  },
  {
    "text": "smart",
    "segs": "s.m.ar=ar.t",
    "unit": "EC24",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ar"
    ]
  },
  {
    "text": "hard",
    "segs": "h.ar=ar.d",
    "unit": "EC24",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ar"
    ]
  },
  {
    "text": "start",
    "segs": "s.t.ar=ar.t",
    "unit": "EC24",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ar"
    ]
  },
  {
    "text": "yard",
    "segs": "y.ar=ar.d",
    "unit": "EC24",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ar"
    ]
  },
  {
    "text": "mark",
    "segs": "m.ar=ar.k",
    "unit": "EC24",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ar"
    ]
  },
  {
    "text": "sharp",
    "segs": "sh.ar=ar.p",
    "unit": "EC24",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ar"
    ]
  },
  {
    "text": "dart",
    "segs": "d.ar=ar.t",
    "unit": "EC24",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ar"
    ]
  },
  {
    "text": "darts",
    "segs": "d.ar=ar.t.s",
    "unit": "EC24",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ar"
    ]
  },
  {
    "text": "spark",
    "segs": "s.p.ar=ar.k",
    "unit": "EC24",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ar"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC22"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC22"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC22"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC22"
  },
  {
    "text": "The bear sat on the chair.",
    "maxUnit": "EC22"
  },
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC22"
  },
  {
    "text": "The jar is on the cart.",
    "maxUnit": "EC22"
  },
  {
    "text": "The star is over the barn.",
    "maxUnit": "EC22"
  }
] as const;

export const chains = [
  [
    "aunt",
    "ant",
    "an",
    "am",
    "arm"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "lemon",
    "syllables": "le|mon",
    "schwa": [
      1
    ]
  },
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "cabin",
    "syllables": "ca|bin"
  },
  {
    "text": "invent",
    "syllables": "in|vent"
  },
  {
    "text": "object",
    "syllables": "ob|ject"
  },
  {
    "text": "uplift",
    "syllables": "up|lift"
  },
  {
    "text": "dentist",
    "syllables": "den|tist"
  },
  {
    "text": "suspect",
    "syllables": "sus|pect"
  },
  {
    "text": "himself",
    "syllables": "him|self"
  },
  {
    "text": "contest",
    "syllables": "con|test"
  }
] as const;
