// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "watch",
    "segs": "w.a=o.tch",
    "unit": "EC25",
    "pic": "one simple wristwatch with a round face and no numbers",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:a"
    ]
  },
  {
    "text": "wasp",
    "segs": "w.a=o.s.p",
    "unit": "EC25",
    "pic": "one yellow and black wasp with a narrow waist",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:a"
    ]
  },
  {
    "text": "want",
    "segs": "w.a=o.n.t",
    "unit": "EC25",
    "tags": [
      "new",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "wash",
    "segs": "w.a=o.sh",
    "unit": "EC25",
    "tags": [
      "new",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "was",
    "segs": "w.a=o.s=z",
    "unit": "EC25",
    "tags": [
      "new",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "what",
    "segs": "wh.a=o.t",
    "unit": "EC25",
    "tags": [
      "new",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "swan",
    "segs": "s.w.a=o.n",
    "unit": "EC25",
    "tags": [
      "new",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "wand",
    "segs": "w.a=o.n.d",
    "unit": "EC25",
    "tags": [
      "new",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "dog",
    "segs": "d.o.g",
    "unit": "EC25",
    "pic": "a friendly brown-and-white puppy sitting and facing the viewer, floppy ears, big shiny eyes, a little pink tongue, a wagging tail",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  },
  {
    "text": "doll",
    "segs": "d.o.ll",
    "unit": "EC25",
    "pic": "a doll",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  },
  {
    "text": "rock",
    "segs": "r.o.ck",
    "unit": "EC25",
    "pic": "a rock",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  },
  {
    "text": "box",
    "segs": "b.o.x",
    "unit": "EC25",
    "pic": "a simple open cardboard box with four folded flaps, hollow inside and clearly made of brown cardboard",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  },
  {
    "text": "frog",
    "segs": "f.r.o.g",
    "unit": "EC25",
    "pic": "a green frog sitting and facing the viewer, big round eyes with shiny black pupils, a wide smile",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  },
  {
    "text": "shop",
    "segs": "sh.o.p",
    "unit": "EC25",
    "pic": "a shop",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  },
  {
    "text": "clock",
    "segs": "c.l.o.ck",
    "unit": "EC25",
    "pic": "a clock",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  },
  {
    "text": "lock",
    "segs": "l.o.ck",
    "unit": "EC25",
    "pic": "a padlock",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  },
  {
    "text": "sock",
    "segs": "s.o.ck",
    "unit": "EC25",
    "pic": "a sock",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  },
  {
    "text": "mop",
    "segs": "m.o.p",
    "unit": "EC25",
    "pic": "a floor mop",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  },
  {
    "text": "pot",
    "segs": "p.o.t",
    "unit": "EC25",
    "pic": "a clay cooking pot",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  },
  {
    "text": "top",
    "segs": "t.o.p",
    "unit": "EC25",
    "pic": "a spinning top toy",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  },
  {
    "text": "cot",
    "segs": "c.o.t",
    "unit": "EC25",
    "pic": "a baby's cot",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  },
  {
    "text": "log",
    "segs": "l.o.g",
    "unit": "EC25",
    "pic": "a log",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  },
  {
    "text": "fox",
    "segs": "f.o.x",
    "unit": "EC25",
    "pic": "an orange fox sitting and facing the viewer with a friendly face: two big shiny eyes, a little black nose and a smile, white cheeks and chest, black-tipped ears, a bushy white-tipped tail",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  },
  {
    "text": "dot",
    "segs": "d.o.t",
    "unit": "EC25",
    "tags": [
      "review",
      "sort:o",
      "dictation-safe"
    ]
  },
  {
    "text": "jog",
    "segs": "j.o.g",
    "unit": "EC25",
    "tags": [
      "review",
      "sort:o",
      "dictation-safe"
    ]
  },
  {
    "text": "frost",
    "segs": "f.r.o.s.t",
    "unit": "EC25",
    "tags": [
      "review",
      "sort:o",
      "dictation-safe"
    ]
  },
  {
    "text": "pond",
    "segs": "p.o.n.d",
    "unit": "EC25",
    "pic": "a pond",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  },
  {
    "text": "rod",
    "segs": "r.o.d",
    "unit": "EC25",
    "pic": "a fishing rod",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  },
  {
    "text": "fog",
    "segs": "f.o.g",
    "unit": "EC25",
    "tags": [
      "review",
      "sort:o",
      "dictation-safe"
    ]
  },
  {
    "text": "stop",
    "segs": "s.t.o.p",
    "unit": "EC25",
    "tags": [
      "review",
      "dictation-safe",
      "sort:o"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC23"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC23"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC23"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC23"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC23"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC23"
  },
  {
    "text": "The bear sat on the chair.",
    "maxUnit": "EC23"
  },
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC23"
  }
] as const;

export const chains = [
  [
    "watch",
    "was",
    "wash",
    "wad",
    "wand"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "seven",
    "syllables": "se|ven",
    "schwa": [
      1
    ]
  },
  {
    "text": "acting",
    "syllables": "ac|ting"
  },
  {
    "text": "bedrock",
    "syllables": "bed|rock"
  },
  {
    "text": "jackpot",
    "syllables": "jack|pot"
  },
  {
    "text": "padlock",
    "syllables": "pad|lock"
  },
  {
    "text": "backpack",
    "syllables": "back|pack"
  },
  {
    "text": "catfish",
    "syllables": "cat|fish"
  },
  {
    "text": "discuss",
    "syllables": "dis|cuss"
  },
  {
    "text": "dandruff",
    "syllables": "dan|druff"
  }
] as const;
