// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "watch",
    "segs": "w.a=o.tch",
    "unit": "EC26",
    "pic": "one simple wristwatch with a round face and no numbers",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:a"
    ]
  },
  {
    "text": "wasp",
    "segs": "w.a=o.s.p",
    "unit": "EC26",
    "pic": "one yellow and black wasp with a narrow waist",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:a"
    ]
  },
  {
    "text": "want",
    "segs": "w.a=o.n.t",
    "unit": "EC26",
    "tags": [
      "review",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "wash",
    "segs": "w.a=o.sh",
    "unit": "EC26",
    "tags": [
      "review",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "was",
    "segs": "w.a=o.s=z",
    "unit": "EC26",
    "tags": [
      "review",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "what",
    "segs": "wh.a=o.t",
    "unit": "EC26",
    "tags": [
      "review",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "wand",
    "segs": "w.a=o.n.d",
    "unit": "EC26",
    "tags": [
      "review",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "swat",
    "segs": "s.w.a=o.t",
    "unit": "EC26",
    "tags": [
      "review",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "cake",
    "segs": "c.a=ae.ke=k",
    "unit": "EC26",
    "pic": "one round birthday cake with icing and candles",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:a"
    ]
  },
  {
    "text": "gate",
    "segs": "g.a=ae.te=t",
    "unit": "EC26",
    "pic": "one wooden garden gate with a latch",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:a"
    ]
  },
  {
    "text": "flame",
    "segs": "f.l.a=ae.me=m",
    "unit": "EC26",
    "tags": [
      "review",
      "sort:a",
      "dictation-safe"
    ]
  },
  {
    "text": "whale",
    "segs": "wh.a=ae.le=l",
    "unit": "EC26",
    "pic": "one large blue whale swimming alone",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:a"
    ]
  },
  {
    "text": "take",
    "segs": "t.a=ae.ke=k",
    "unit": "EC26",
    "tags": [
      "review",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "bake",
    "segs": "b.a=ae.ke=k",
    "unit": "EC26",
    "tags": [
      "review",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "make",
    "segs": "m.a=ae.ke=k",
    "unit": "EC26",
    "tags": [
      "review",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "game",
    "segs": "g.a=ae.me=m",
    "unit": "EC26",
    "tags": [
      "review",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "hand",
    "segs": "h.a.n.d",
    "unit": "EC26",
    "pic": "one open cartoon hand waving hello, palm facing the viewer, five fingers spread",
    "tags": [
      "review",
      "picture",
      "sort:a"
    ]
  },
  {
    "text": "cat",
    "segs": "c.a.t",
    "unit": "EC26",
    "pic": "a cat",
    "tags": [
      "review",
      "picture",
      "sort:a"
    ]
  },
  {
    "text": "man",
    "segs": "m.a.n",
    "unit": "EC26",
    "pic": "a grown-up man with a friendly face (two eyes and a big smile), short brown hair, a green jumper and blue jeans, whole from head to toe, facing the viewer and waving",
    "tags": [
      "review",
      "picture",
      "sort:a"
    ]
  },
  {
    "text": "ant",
    "segs": "a.n.t",
    "unit": "EC26",
    "pic": "an ant",
    "tags": [
      "review",
      "picture",
      "sort:a"
    ]
  },
  {
    "text": "hat",
    "segs": "h.a.t",
    "unit": "EC26",
    "pic": "a red woolly bobble hat with a big white bobble on top",
    "tags": [
      "review",
      "picture",
      "sort:a"
    ]
  },
  {
    "text": "lamp",
    "segs": "l.a.m.p",
    "unit": "EC26",
    "pic": "a lamp",
    "tags": [
      "review",
      "picture",
      "sort:a"
    ]
  },
  {
    "text": "stand",
    "segs": "s.t.a.n.d",
    "unit": "EC26",
    "tags": [
      "review",
      "sort:a",
      "dictation-safe"
    ]
  },
  {
    "text": "bag",
    "segs": "b.a.g",
    "unit": "EC26",
    "pic": "a school bag",
    "tags": [
      "review",
      "picture",
      "sort:a"
    ]
  },
  {
    "text": "flag",
    "segs": "f.l.a.g",
    "unit": "EC26",
    "pic": "a flag",
    "tags": [
      "review",
      "picture",
      "sort:a"
    ]
  },
  {
    "text": "crab",
    "segs": "c.r.a.b",
    "unit": "EC26",
    "pic": "a crab",
    "tags": [
      "review",
      "picture",
      "sort:a"
    ]
  },
  {
    "text": "wag",
    "segs": "w.a.g",
    "unit": "EC26",
    "tags": [
      "review",
      "sort:a",
      "dictation-safe"
    ]
  },
  {
    "text": "pan",
    "segs": "p.a.n",
    "unit": "EC26",
    "pic": "a frying pan",
    "tags": [
      "review",
      "picture",
      "sort:a"
    ]
  },
  {
    "text": "rat",
    "segs": "r.a.t",
    "unit": "EC26",
    "pic": "one large brown rat side-on, with a long pointed snout, visible front teeth, very small ears, coarse fur and a long thick bare pink tail curling behind it, no mouse",
    "tags": [
      "review",
      "picture",
      "sort:a"
    ]
  },
  {
    "text": "sand",
    "segs": "s.a.n.d",
    "unit": "EC26",
    "pic": "a small golden sandcastle with a little flag on top, sitting on a heap of sand",
    "tags": [
      "review",
      "picture",
      "sort:a"
    ]
  },
  {
    "text": "cap",
    "segs": "c.a.p",
    "unit": "EC26",
    "pic": "a baseball cap",
    "tags": [
      "review",
      "picture",
      "sort:a"
    ]
  },
  {
    "text": "jam",
    "segs": "j.a.m",
    "unit": "EC26",
    "pic": "a jar of jam",
    "tags": [
      "review",
      "picture",
      "sort:a"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC24"
  },
  {
    "text": "The jar is on the cart.",
    "maxUnit": "EC24"
  },
  {
    "text": "The star is over the barn.",
    "maxUnit": "EC24"
  },
  {
    "text": "The car is by the farm.",
    "maxUnit": "EC24"
  },
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC24"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC24"
  }
] as const;

export const chains = [] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "lemon",
    "syllables": "le|mon",
    "schwa": [
      1
    ]
  },
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "dishcloth",
    "syllables": "dish|cloth"
  },
  {
    "text": "lipstick",
    "syllables": "lip|stick"
  },
  {
    "text": "lipgloss",
    "syllables": "lip|gloss"
  },
  {
    "text": "wingspan",
    "syllables": "wing|span"
  },
  {
    "text": "backrest",
    "syllables": "back|rest"
  },
  {
    "text": "sandpit",
    "syllables": "sand|pit"
  },
  {
    "text": "complex",
    "syllables": "com|plex"
  },
  {
    "text": "triplet",
    "syllables": "tri|plet"
  }
] as const;
