// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "grey",
    "segs": "g.r.ey=ae",
    "unit": "EC27",
    "tags": [
      "new",
      "sort:ey",
      "dictation-safe"
    ]
  },
  {
    "text": "whey",
    "segs": "wh.ey=ae",
    "unit": "EC27",
    "tags": [
      "new",
      "reading-only",
      "sort:ey"
    ]
  },
  {
    "text": "steak",
    "segs": "s.t.ea=ae.k",
    "unit": "EC27",
    "pic": "one cooked beef steak on a plain plate",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:ea"
    ]
  },
  {
    "text": "great",
    "segs": "g.r.ea=ae.t",
    "unit": "EC27",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "break",
    "segs": "b.r.ea=ae.k",
    "unit": "EC27",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "eight",
    "segs": "eigh=ae.t",
    "unit": "EC27",
    "tags": [
      "new",
      "sort:eigh",
      "dictation-safe"
    ]
  },
  {
    "text": "sleigh",
    "segs": "s.l.eigh=ae",
    "unit": "EC27",
    "pic": "one traditional wooden sleigh with curved runners, empty and alone",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:eigh"
    ]
  },
  {
    "text": "neigh",
    "segs": "n.eigh=ae",
    "unit": "EC27",
    "tags": [
      "new",
      "dictation-safe",
      "sort:eigh"
    ]
  },
  {
    "text": "weight",
    "segs": "w.eigh=ae.t",
    "unit": "EC27",
    "tags": [
      "new",
      "reading-only",
      "sort:eigh"
    ]
  },
  {
    "text": "weigh",
    "segs": "w.eigh=ae",
    "unit": "EC27",
    "tags": [
      "new",
      "reading-only",
      "sort:eigh"
    ]
  },
  {
    "text": "cake",
    "segs": "c.a=ae.ke=k",
    "unit": "EC27",
    "pic": "one round birthday cake with icing and candles",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:a"
    ]
  },
  {
    "text": "name",
    "segs": "n.a=ae.me=m",
    "unit": "EC27",
    "tags": [
      "review",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "taste",
    "segs": "t.a=ae.s.te=t",
    "unit": "EC27",
    "tags": [
      "review",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "bake",
    "segs": "b.a=ae.ke=k",
    "unit": "EC27",
    "tags": [
      "review",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "ape",
    "segs": "a=ae.pe=p",
    "unit": "EC27",
    "tags": [
      "review",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "made",
    "segs": "m.a=ae.de=d",
    "unit": "EC27",
    "tags": [
      "review",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "late",
    "segs": "l.a=ae.te=t",
    "unit": "EC27",
    "tags": [
      "review",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "pale",
    "segs": "p.a=ae.le=l",
    "unit": "EC27",
    "tags": [
      "review",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "tray",
    "segs": "t.r.ay",
    "unit": "EC27",
    "pic": "a tray",
    "tags": [
      "review",
      "picture",
      "sort:ay"
    ]
  },
  {
    "text": "clay",
    "segs": "c.l.ay",
    "unit": "EC27",
    "tags": [
      "review",
      "sort:ay",
      "dictation-safe"
    ]
  },
  {
    "text": "day",
    "segs": "d.ay",
    "unit": "EC27",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ay"
    ]
  },
  {
    "text": "play",
    "segs": "p.l.ay",
    "unit": "EC27",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ay"
    ]
  },
  {
    "text": "say",
    "segs": "s.ay",
    "unit": "EC27",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ay"
    ]
  },
  {
    "text": "stay",
    "segs": "s.t.ay",
    "unit": "EC27",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ay"
    ]
  },
  {
    "text": "spray",
    "segs": "s.p.r.ay",
    "unit": "EC27",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ay"
    ]
  },
  {
    "text": "way",
    "segs": "w.ay",
    "unit": "EC27",
    "tags": [
      "review",
      "reading-only",
      "sort:ay"
    ]
  },
  {
    "text": "rain",
    "segs": "r.ai.n",
    "unit": "EC27",
    "pic": "heavy raindrops falling from one grey cloud",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:ai"
    ]
  },
  {
    "text": "train",
    "segs": "t.r.ai.n",
    "unit": "EC27",
    "pic": "a steam train",
    "tags": [
      "review",
      "picture",
      "sort:ai"
    ]
  },
  {
    "text": "snail",
    "segs": "s.n.ai.l",
    "unit": "EC27",
    "pic": "a snail",
    "tags": [
      "review",
      "picture",
      "sort:ai"
    ]
  },
  {
    "text": "tail",
    "segs": "t.ai.l",
    "unit": "EC27",
    "pic": "a fox tail",
    "tags": [
      "review",
      "picture",
      "sort:ai"
    ]
  },
  {
    "text": "paint",
    "segs": "p.ai.n.t",
    "unit": "EC27",
    "pic": "a paint pot",
    "tags": [
      "review",
      "picture",
      "sort:ai"
    ]
  },
  {
    "text": "nail",
    "segs": "n.ai.l",
    "unit": "EC27",
    "pic": "a nail",
    "tags": [
      "review",
      "picture",
      "sort:ai"
    ]
  },
  {
    "text": "brain",
    "segs": "b.r.ai.n",
    "unit": "EC27",
    "pic": "one simple pink model of a human brain, alone",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:ai"
    ]
  },
  {
    "text": "chain",
    "segs": "ch.ai.n",
    "unit": "EC27",
    "pic": "one short silver metal chain lying alone",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:ai"
    ]
  },
  {
    "text": "may",
    "segs": "m.ay",
    "unit": "EC27",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ay"
    ]
  },
  {
    "text": "hay",
    "segs": "h.ay",
    "unit": "EC27",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ay"
    ]
  },
  {
    "text": "aid",
    "segs": "ai.d",
    "unit": "EC27",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ai"
    ]
  },
  {
    "text": "drain",
    "segs": "d.r.ai.n",
    "unit": "EC27",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ai"
    ]
  },
  {
    "text": "cane",
    "segs": "c.a=ae.ne=n",
    "unit": "EC27",
    "tags": [
      "review",
      "dictation-safe",
      "sort:a"
    ]
  },
  {
    "text": "fail",
    "segs": "f.ai.l",
    "unit": "EC27",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ai"
    ]
  },
  {
    "text": "grain",
    "segs": "g.r.ai.n",
    "unit": "EC27",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ai"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC25"
  },
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC25"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC25"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC25"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC25"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC25"
  },
  {
    "text": "A hawk sat on the fence.",
    "maxUnit": "EC25"
  },
  {
    "text": "The tall horse ate an apple.",
    "maxUnit": "EC25"
  }
] as const;

export const chains = [
  [
    "grey",
    "grew",
    "crew",
    "crow",
    "cow"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "author",
    "syllables": "au|thor",
    "schwa": [
      1
    ]
  },
  {
    "text": "water",
    "syllables": "wa|ter",
    "schwa": [
      1
    ]
  },
  {
    "text": "somewhere",
    "syllables": "some|where"
  },
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "seven",
    "syllables": "se|ven",
    "schwa": [
      1
    ]
  },
  {
    "text": "lipstick",
    "syllables": "lip|stick"
  },
  {
    "text": "lipgloss",
    "syllables": "lip|gloss"
  },
  {
    "text": "wingspan",
    "syllables": "wing|span"
  },
  {
    "text": "backrest",
    "syllables": "back|rest"
  },
  {
    "text": "sandpit",
    "syllables": "sand|pit"
  }
] as const;
