// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "played",
    "segs": "p.l.ay.ed=d",
    "unit": "EC28",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ed"
    ]
  },
  {
    "text": "add",
    "segs": "a.dd=d",
    "unit": "EC28",
    "tags": [
      "new",
      "dictation-safe",
      "sort:dd"
    ]
  },
  {
    "text": "odd",
    "segs": "o.dd=d",
    "unit": "EC28",
    "tags": [
      "new",
      "dictation-safe",
      "sort:dd"
    ]
  },
  {
    "text": "fiddle",
    "segs": "f.i.dd=d.le=l",
    "unit": "EC28",
    "tags": [
      "new",
      "dictation-safe",
      "sort:dd"
    ]
  },
  {
    "text": "dog",
    "segs": "d.o.g",
    "unit": "EC28",
    "pic": "a friendly brown-and-white puppy sitting and facing the viewer, floppy ears, big shiny eyes, a little pink tongue, a wagging tail",
    "tags": [
      "review",
      "picture",
      "sort:d"
    ]
  },
  {
    "text": "hand",
    "segs": "h.a.n.d",
    "unit": "EC28",
    "pic": "one open cartoon hand waving hello, palm facing the viewer, five fingers spread",
    "tags": [
      "review",
      "picture",
      "sort:d"
    ]
  },
  {
    "text": "doll",
    "segs": "d.o.ll",
    "unit": "EC28",
    "pic": "a doll",
    "tags": [
      "review",
      "picture",
      "sort:d"
    ]
  },
  {
    "text": "duck",
    "segs": "d.u.ck",
    "unit": "EC28",
    "pic": "a white farm duck standing side-on with a friendly face: one big round shiny black eye clearly drawn on its head, an orange beak with a little smile, and orange feet",
    "tags": [
      "review",
      "picture",
      "sort:d"
    ]
  },
  {
    "text": "bed",
    "segs": "b.e.d",
    "unit": "EC28",
    "pic": "a bed",
    "tags": [
      "review",
      "picture",
      "sort:d"
    ]
  },
  {
    "text": "road",
    "segs": "r.oa.d",
    "unit": "EC28",
    "pic": "a road",
    "tags": [
      "review",
      "picture",
      "sort:d"
    ]
  },
  {
    "text": "dress",
    "segs": "d.r.e.ss",
    "unit": "EC28",
    "pic": "one simple bright red child-sized dress on a plain hanger, clear fitted bodice and wide flared skirt, shown full length with no person",
    "tags": [
      "review",
      "picture",
      "sort:d"
    ]
  },
  {
    "text": "desk",
    "segs": "d.e.s.k",
    "unit": "EC28",
    "pic": "one wooden writing desk with a wide flat top, a single drawer and an empty chair pushed under it, no writing",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:d"
    ]
  },
  {
    "text": "drum",
    "segs": "d.r.u.m",
    "unit": "EC28",
    "pic": "a drum",
    "tags": [
      "review",
      "picture",
      "sort:d"
    ]
  },
  {
    "text": "stand",
    "segs": "s.t.a.n.d",
    "unit": "EC28",
    "tags": [
      "review",
      "sort:d",
      "dictation-safe"
    ]
  },
  {
    "text": "shed",
    "segs": "sh.e.d",
    "unit": "EC28",
    "pic": "a garden shed",
    "tags": [
      "review",
      "picture",
      "sort:d"
    ]
  },
  {
    "text": "sand",
    "segs": "s.a.n.d",
    "unit": "EC28",
    "pic": "a small golden sandcastle with a little flag on top, sitting on a heap of sand",
    "tags": [
      "review",
      "picture",
      "sort:d"
    ]
  },
  {
    "text": "dot",
    "segs": "d.o.t",
    "unit": "EC28",
    "tags": [
      "review",
      "sort:d",
      "dictation-safe"
    ]
  },
  {
    "text": "lid",
    "segs": "l.i.d",
    "unit": "EC28",
    "pic": "a pot lid",
    "tags": [
      "review",
      "picture",
      "sort:d"
    ]
  },
  {
    "text": "den",
    "segs": "d.e.n",
    "unit": "EC28",
    "pic": "a small cosy den made of blankets draped over chairs",
    "tags": [
      "review",
      "picture",
      "sort:d"
    ]
  },
  {
    "text": "pond",
    "segs": "p.o.n.d",
    "unit": "EC28",
    "pic": "a pond",
    "tags": [
      "review",
      "picture",
      "sort:d"
    ]
  },
  {
    "text": "rod",
    "segs": "r.o.d",
    "unit": "EC28",
    "pic": "a fishing rod",
    "tags": [
      "review",
      "picture",
      "sort:d"
    ]
  },
  {
    "text": "squid",
    "segs": "s.q.u=w.i.d",
    "unit": "EC28",
    "pic": "one squid swimming alone, with a long pointed mantle and ten trailing arms",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:d"
    ]
  },
  {
    "text": "red",
    "segs": "r.e.d",
    "unit": "EC28",
    "tags": [
      "review",
      "dictation-safe",
      "sort:d"
    ]
  },
  {
    "text": "and",
    "segs": "a.n.d",
    "unit": "EC28",
    "tags": [
      "review",
      "dictation-safe",
      "sort:d"
    ]
  },
  {
    "text": "day",
    "segs": "d.ay",
    "unit": "EC28",
    "tags": [
      "review",
      "dictation-safe",
      "sort:d"
    ]
  },
  {
    "text": "dad",
    "segs": "d.a.d",
    "unit": "EC28",
    "tags": [
      "review",
      "dictation-safe"
    ]
  },
  {
    "text": "dish",
    "segs": "d.i.sh",
    "unit": "EC28",
    "tags": [
      "review",
      "dictation-safe",
      "sort:d"
    ]
  },
  {
    "text": "end",
    "segs": "e.n.d",
    "unit": "EC28",
    "tags": [
      "review",
      "dictation-safe",
      "sort:d"
    ]
  },
  {
    "text": "kid",
    "segs": "k.i.d",
    "unit": "EC28",
    "tags": [
      "review",
      "dictation-safe",
      "sort:d"
    ]
  },
  {
    "text": "dust",
    "segs": "d.u.s.t",
    "unit": "EC28",
    "tags": [
      "review",
      "dictation-safe",
      "sort:d"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC26"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC26"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC26"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC26"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC26"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC26"
  },
  {
    "text": "The bear sat on the chair.",
    "maxUnit": "EC26"
  },
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC26"
  }
] as const;

export const chains = [
  [
    "played",
    "play",
    "clay",
    "claw",
    "clue"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "airline",
    "syllables": "air|line"
  },
  {
    "text": "toilet",
    "syllables": "toi|let",
    "schwa": [
      1
    ]
  },
  {
    "text": "author",
    "syllables": "au|thor",
    "schwa": [
      1
    ]
  },
  {
    "text": "water",
    "syllables": "wa|ter",
    "schwa": [
      1
    ]
  },
  {
    "text": "somewhere",
    "syllables": "some|where"
  },
  {
    "text": "lemon",
    "syllables": "le|mon",
    "schwa": [
      1
    ]
  },
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "sandpit",
    "syllables": "sand|pit"
  },
  {
    "text": "complex",
    "syllables": "com|plex"
  },
  {
    "text": "triplet",
    "syllables": "tri|plet"
  }
] as const;
