// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "key",
    "segs": "k.ey=ee",
    "unit": "EC29",
    "pic": "one plain silver door key, alone",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ey"
    ]
  },
  {
    "text": "ski",
    "segs": "s.k.i=ee",
    "unit": "EC29",
    "pic": "one pair of skis crossed together, alone",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:i"
    ]
  },
  {
    "text": "he",
    "segs": "h.e=ee",
    "unit": "EC29",
    "tags": [
      "review",
      "dictation-safe",
      "sort:e"
    ]
  },
  {
    "text": "we",
    "segs": "w.e=ee",
    "unit": "EC29",
    "tags": [
      "review",
      "dictation-safe",
      "sort:e"
    ]
  },
  {
    "text": "she",
    "segs": "sh.e=ee",
    "unit": "EC29",
    "tags": [
      "review",
      "dictation-safe",
      "sort:e"
    ]
  },
  {
    "text": "eve",
    "segs": "e=ee.ve",
    "unit": "EC29",
    "tags": [
      "review",
      "dictation-safe",
      "sort:e"
    ]
  },
  {
    "text": "field",
    "segs": "f.ie=ee.l.d",
    "unit": "EC29",
    "tags": [
      "new",
      "sort:ie",
      "dictation-safe"
    ]
  },
  {
    "text": "chief",
    "segs": "ch.ie=ee.f",
    "unit": "EC29",
    "tags": [
      "new",
      "sort:ie",
      "dictation-safe"
    ]
  },
  {
    "text": "shield",
    "segs": "sh.ie=ee.l.d",
    "unit": "EC29",
    "tags": [
      "new",
      "sort:ie",
      "dictation-safe"
    ]
  },
  {
    "text": "thief",
    "segs": "th.ie=ee.f",
    "unit": "EC29",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ie"
    ]
  },
  {
    "text": "shriek",
    "segs": "sh.r.ie=ee.k",
    "unit": "EC29",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ie"
    ]
  },
  {
    "text": "bee",
    "segs": "b.ee",
    "unit": "EC29",
    "pic": "a bee",
    "tags": [
      "review",
      "picture",
      "sort:ee"
    ]
  },
  {
    "text": "tree",
    "segs": "t.r.ee",
    "unit": "EC29",
    "pic": "a tree",
    "tags": [
      "review",
      "picture",
      "sort:ee"
    ]
  },
  {
    "text": "feet",
    "segs": "f.ee.t",
    "unit": "EC29",
    "pic": "a pair of bare cartoon feet side by side with wiggly toes",
    "tags": [
      "review",
      "picture",
      "sort:ee"
    ]
  },
  {
    "text": "sheep",
    "segs": "sh.ee.p",
    "unit": "EC29",
    "pic": "a sheep",
    "tags": [
      "review",
      "picture",
      "sort:ee"
    ]
  },
  {
    "text": "queen",
    "segs": "q.u=w.ee.n",
    "unit": "EC29",
    "pic": "a queen",
    "tags": [
      "review",
      "picture",
      "sort:ee"
    ]
  },
  {
    "text": "green",
    "segs": "g.r.ee.n",
    "unit": "EC29",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ee"
    ]
  },
  {
    "text": "sleep",
    "segs": "s.l.ee.p",
    "unit": "EC29",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ee"
    ]
  },
  {
    "text": "see",
    "segs": "s.ee",
    "unit": "EC29",
    "tags": [
      "review",
      "reading-only",
      "sort:ee"
    ]
  },
  {
    "text": "leaf",
    "segs": "l.ea.f",
    "unit": "EC29",
    "pic": "a leaf",
    "tags": [
      "review",
      "picture",
      "sort:ea"
    ]
  },
  {
    "text": "beach",
    "segs": "b.ea.ch",
    "unit": "EC29",
    "pic": "one sandy beach with a single beach bucket",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:ea"
    ]
  },
  {
    "text": "tea",
    "segs": "t.ea",
    "unit": "EC29",
    "pic": "one cup of tea in a plain white cup",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:ea"
    ]
  },
  {
    "text": "eat",
    "segs": "ea.t",
    "unit": "EC29",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "seat",
    "segs": "s.ea.t",
    "unit": "EC29",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "dream",
    "segs": "d.r.ea.m",
    "unit": "EC29",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "sea",
    "segs": "s.ea",
    "unit": "EC29",
    "tags": [
      "review",
      "reading-only",
      "sort:ea"
    ]
  },
  {
    "text": "pea",
    "segs": "p.ea",
    "unit": "EC29",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "sweet",
    "segs": "s.w.ee.t",
    "unit": "EC29",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ee"
    ]
  },
  {
    "text": "cream",
    "segs": "c.r.ea.m",
    "unit": "EC29",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "treat",
    "segs": "t.r.ea.t",
    "unit": "EC29",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "freeze",
    "segs": "f.r.ee.ze=z",
    "unit": "EC29",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ee"
    ]
  },
  {
    "text": "breathe",
    "segs": "b.r.ea.the=dh",
    "unit": "EC29",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "sheet",
    "segs": "sh.ee.t",
    "unit": "EC29",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ee"
    ]
  },
  {
    "text": "each",
    "segs": "ea.ch",
    "unit": "EC29",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "flee",
    "segs": "f.l.ee",
    "unit": "EC29",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ee"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC27"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC27"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC27"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC27"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC27"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC27"
  },
  {
    "text": "The bear sat on the chair.",
    "maxUnit": "EC27"
  },
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC27"
  }
] as const;

export const chains = [
  [
    "he",
    "she",
    "we",
    "weigh",
    "weight"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "partner",
    "syllables": "part|ner",
    "schwa": [
      1
    ]
  },
  {
    "text": "airline",
    "syllables": "air|line"
  },
  {
    "text": "toilet",
    "syllables": "toi|let",
    "schwa": [
      1
    ]
  },
  {
    "text": "author",
    "syllables": "au|thor",
    "schwa": [
      1
    ]
  },
  {
    "text": "water",
    "syllables": "wa|ter",
    "schwa": [
      1
    ]
  },
  {
    "text": "somewhere",
    "syllables": "some|where"
  },
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "seven",
    "syllables": "se|ven",
    "schwa": [
      1
    ]
  },
  {
    "text": "benefit",
    "syllables": "be|ne|fit"
  },
  {
    "text": "habitat",
    "syllables": "ha|bi|tat"
  }
] as const;
