// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "steak",
    "segs": "s.t.ea=ae.k",
    "unit": "EC3",
    "pic": "one cooked beef steak on a plain plate",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:ea"
    ]
  },
  {
    "text": "great",
    "segs": "g.r.ea=ae.t",
    "unit": "EC3",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "break",
    "segs": "b.r.ea=ae.k",
    "unit": "EC3",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "leaf",
    "segs": "l.ea.f",
    "unit": "EC3",
    "pic": "a leaf",
    "tags": [
      "review",
      "picture",
      "sort:ea"
    ]
  },
  {
    "text": "beach",
    "segs": "b.ea.ch",
    "unit": "EC3",
    "pic": "one sandy beach beside blue sea",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:ea"
    ]
  },
  {
    "text": "tea",
    "segs": "t.ea",
    "unit": "EC3",
    "pic": "one cup of tea in a plain white cup",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:ea"
    ]
  },
  {
    "text": "eat",
    "segs": "ea.t",
    "unit": "EC3",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "seat",
    "segs": "s.ea.t",
    "unit": "EC3",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "dream",
    "segs": "d.r.ea.m",
    "unit": "EC3",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "sea",
    "segs": "s.ea",
    "unit": "EC3",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "speak",
    "segs": "s.p.ea.k",
    "unit": "EC3",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "clean",
    "segs": "c.l.ea.n",
    "unit": "EC3",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "team",
    "segs": "t.ea.m",
    "unit": "EC3",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "sneak",
    "segs": "s.n.ea.k",
    "unit": "EC3",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "steam",
    "segs": "s.t.ea.m",
    "unit": "EC3",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ea"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC1"
  },
  {
    "text": "The jar is on the cart.",
    "maxUnit": "EC1"
  },
  {
    "text": "The star is over the barn.",
    "maxUnit": "EC1"
  },
  {
    "text": "The car is by the farm.",
    "maxUnit": "EC1"
  },
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC1"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC1"
  }
] as const;

export const chains = [] as const;

export const nonsense = [] as const;

export const poly = [] as const;
