// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "build",
    "segs": "b.ui=i.l.d",
    "unit": "EC30",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ui"
    ]
  },
  {
    "text": "built",
    "segs": "b.ui=i.l.t",
    "unit": "EC30",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ui"
    ]
  },
  {
    "text": "fish",
    "segs": "f.i.sh",
    "unit": "EC30",
    "pic": "an orange goldfish swimming side-on, one big round friendly eye, a small smile, flowing tail fins",
    "tags": [
      "review",
      "picture",
      "sort:i"
    ]
  },
  {
    "text": "milk",
    "segs": "m.i.l.k",
    "unit": "EC30",
    "pic": "a glass of milk",
    "tags": [
      "review",
      "picture",
      "sort:i"
    ]
  },
  {
    "text": "kiss",
    "segs": "k.i.ss",
    "unit": "EC30",
    "tags": [
      "review",
      "sort:i",
      "dictation-safe"
    ]
  },
  {
    "text": "pig",
    "segs": "p.i.g",
    "unit": "EC30",
    "pic": "a round pink pig standing side-on with its head turned to smile at the viewer, flat snout, curly tail",
    "tags": [
      "review",
      "picture",
      "sort:i"
    ]
  },
  {
    "text": "ring",
    "segs": "r.i.ng",
    "unit": "EC30",
    "pic": "a ring",
    "tags": [
      "review",
      "picture",
      "sort:i"
    ]
  },
  {
    "text": "king",
    "segs": "k.i.ng",
    "unit": "EC30",
    "pic": "a friendly grown-up king wearing a golden crown and a long red royal robe, with his face, full body and hands visible, waving",
    "tags": [
      "review",
      "picture",
      "sort:i"
    ]
  },
  {
    "text": "chick",
    "segs": "ch.i.ck",
    "unit": "EC30",
    "pic": "a chick",
    "tags": [
      "review",
      "picture",
      "sort:i"
    ]
  },
  {
    "text": "swim",
    "segs": "s.w.i.m",
    "unit": "EC30",
    "pic": "a child actively swimming across a little patch of bright blue water, side view with face above the water and one arm reaching forward in a swimming stroke, small splashes around them",
    "tags": [
      "review",
      "picture",
      "sort:i"
    ]
  },
  {
    "text": "hill",
    "segs": "h.i.ll",
    "unit": "EC30",
    "pic": "one smooth green grassy hill rising above a flat plain, no food or buildings",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:i"
    ]
  },
  {
    "text": "ship",
    "segs": "sh.i.p",
    "unit": "EC30",
    "tags": [
      "review",
      "sort:i",
      "dictation-safe"
    ]
  },
  {
    "text": "sit",
    "segs": "s.i.t",
    "unit": "EC30",
    "pic": "one smiling little girl sitting down: curly brown hair, a friendly face with two eyes and a big smile, a yellow T-shirt and blue shorts, sitting on a small red chair that is mostly hidden under her, both feet on the floor, facing the viewer, the whole girl visible from head to toe",
    "tags": [
      "review",
      "picture",
      "sort:i"
    ]
  },
  {
    "text": "swing",
    "segs": "s.w.i.ng",
    "unit": "EC30",
    "pic": "a swing",
    "tags": [
      "review",
      "picture",
      "sort:i"
    ]
  },
  {
    "text": "crisp",
    "segs": "c.r.i.s.p",
    "unit": "EC30",
    "pic": "one very thin golden potato crisp with a wavy curled edge and a few darker toasted patches, shown tilted so its thinness is obvious, no whole potato",
    "tags": [
      "review",
      "picture",
      "sort:i"
    ]
  },
  {
    "text": "bib",
    "segs": "b.i.b",
    "unit": "EC30",
    "pic": "a baby bib",
    "tags": [
      "review",
      "picture",
      "sort:i"
    ]
  },
  {
    "text": "wing",
    "segs": "w.i.ng",
    "unit": "EC30",
    "pic": "a wing",
    "tags": [
      "review",
      "picture",
      "sort:i"
    ]
  },
  {
    "text": "bin",
    "segs": "b.i.n",
    "unit": "EC30",
    "pic": "a rubbish bin",
    "tags": [
      "review",
      "picture",
      "sort:i"
    ]
  },
  {
    "text": "win",
    "segs": "w.i.n",
    "unit": "EC30",
    "tags": [
      "review",
      "sort:i",
      "dictation-safe"
    ]
  },
  {
    "text": "tin",
    "segs": "t.i.n",
    "unit": "EC30",
    "pic": "a tin can",
    "tags": [
      "review",
      "picture",
      "sort:i"
    ]
  },
  {
    "text": "lid",
    "segs": "l.i.d",
    "unit": "EC30",
    "pic": "a pot lid",
    "tags": [
      "review",
      "picture",
      "sort:i"
    ]
  },
  {
    "text": "quilt",
    "segs": "q.u=w.i.l.t",
    "unit": "EC30",
    "tags": [
      "review",
      "sort:i",
      "dictation-safe"
    ]
  },
  {
    "text": "fix",
    "segs": "f.i.x",
    "unit": "EC30",
    "tags": [
      "review",
      "sort:i",
      "dictation-safe"
    ]
  },
  {
    "text": "twist",
    "segs": "t.w.i.s.t",
    "unit": "EC30",
    "tags": [
      "review",
      "sort:i",
      "dictation-safe"
    ]
  },
  {
    "text": "twig",
    "segs": "t.w.i.g",
    "unit": "EC30",
    "tags": [
      "review",
      "sort:i",
      "dictation-safe"
    ]
  },
  {
    "text": "whisk",
    "segs": "wh.i.s.k",
    "unit": "EC30",
    "pic": "a whisk",
    "tags": [
      "review",
      "picture",
      "sort:i"
    ]
  },
  {
    "text": "strip",
    "segs": "s.t.r.i.p",
    "unit": "EC30",
    "tags": [
      "review",
      "sort:i",
      "dictation-safe"
    ]
  },
  {
    "text": "wig",
    "segs": "w.i.g",
    "unit": "EC30",
    "pic": "a bright purple curly wig resting on a simple plain wooden wig stand, with the wig cap edge visible below the curls",
    "tags": [
      "review",
      "picture",
      "sort:i"
    ]
  },
  {
    "text": "split",
    "segs": "s.p.l.i.t",
    "unit": "EC30",
    "tags": [
      "review",
      "sort:i",
      "dictation-safe"
    ]
  },
  {
    "text": "squid",
    "segs": "s.q.u=w.i.d",
    "unit": "EC30",
    "pic": "one squid swimming alone, with a long pointed mantle and ten trailing arms",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:i"
    ]
  },
  {
    "text": "zip",
    "segs": "z.i.p",
    "unit": "EC30",
    "pic": "a zip",
    "tags": [
      "review",
      "picture",
      "sort:i"
    ]
  },
  {
    "text": "pin",
    "segs": "p.i.n",
    "unit": "EC30",
    "pic": "a big red drawing pin (a push pin) standing on its point, seen from the side",
    "tags": [
      "review",
      "picture",
      "sort:i"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC28"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC28"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC28"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC28"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC28"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC28"
  },
  {
    "text": "The bear sat on the chair.",
    "maxUnit": "EC28"
  },
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC28"
  }
] as const;

export const chains = [
  [
    "built",
    "belt",
    "best",
    "nest",
    "net"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "oyster",
    "syllables": "oyst|er",
    "schwa": [
      1
    ]
  },
  {
    "text": "target",
    "syllables": "tar|get",
    "schwa": [
      1
    ]
  },
  {
    "text": "bottle",
    "syllables": "bot|tle",
    "schwa": [
      1
    ]
  },
  {
    "text": "partner",
    "syllables": "part|ner",
    "schwa": [
      1
    ]
  },
  {
    "text": "airline",
    "syllables": "air|line"
  },
  {
    "text": "toilet",
    "syllables": "toi|let",
    "schwa": [
      1
    ]
  },
  {
    "text": "author",
    "syllables": "au|thor",
    "schwa": [
      1
    ]
  },
  {
    "text": "water",
    "syllables": "wa|ter",
    "schwa": [
      1
    ]
  },
  {
    "text": "somewhere",
    "syllables": "some|where"
  },
  {
    "text": "lemon",
    "syllables": "le|mon",
    "schwa": [
      1
    ]
  }
] as const;
