// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "yell",
    "segs": "y.e.ll",
    "unit": "EC31",
    "tags": [
      "review",
      "sort:y",
      "dictation-safe"
    ]
  },
  {
    "text": "yes",
    "segs": "y.e.s",
    "unit": "EC31",
    "tags": [
      "review",
      "dictation-safe",
      "sort:y"
    ]
  },
  {
    "text": "yum",
    "segs": "y.u.m",
    "unit": "EC31",
    "tags": [
      "review",
      "dictation-safe",
      "sort:y"
    ]
  },
  {
    "text": "yet",
    "segs": "y.e.t",
    "unit": "EC31",
    "tags": [
      "review",
      "dictation-safe",
      "sort:y"
    ]
  },
  {
    "text": "yap",
    "segs": "y.a.p",
    "unit": "EC31",
    "tags": [
      "review",
      "dictation-safe",
      "sort:y"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC29"
  },
  {
    "text": "The jar is on the cart.",
    "maxUnit": "EC29"
  },
  {
    "text": "The star is over the barn.",
    "maxUnit": "EC29"
  },
  {
    "text": "The car is by the farm.",
    "maxUnit": "EC29"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC29"
  },
  {
    "text": "The cube is in the tube.",
    "maxUnit": "EC29"
  }
] as const;

export const chains = [] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "happy",
    "syllables": "ha|ppy"
  },
  {
    "text": "sunny",
    "syllables": "su|nny"
  },
  {
    "text": "tummy",
    "syllables": "tu|mmy"
  },
  {
    "text": "yellow",
    "syllables": "ye|llow"
  },
  {
    "text": "silly",
    "syllables": "si|lly"
  },
  {
    "text": "ready",
    "syllables": "rea|dy"
  },
  {
    "text": "runny",
    "syllables": "ru|nny"
  },
  {
    "text": "dolly",
    "syllables": "do|lly"
  },
  {
    "text": "bunny",
    "syllables": "bu|nny"
  },
  {
    "text": "oyster",
    "syllables": "oyst|er",
    "schwa": [
      1
    ]
  }
] as const;
