// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "dough",
    "segs": "d.ough=oe",
    "unit": "EC32",
    "pic": "one round ball of uncooked bread dough, alone",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ough"
    ]
  },
  {
    "text": "toe",
    "segs": "t.oe=oe",
    "unit": "EC32",
    "tags": [
      "review",
      "sort:oe",
      "dictation-safe"
    ]
  },
  {
    "text": "hoe",
    "segs": "h.oe=oe",
    "unit": "EC32",
    "tags": [
      "review",
      "dictation-safe",
      "sort:oe"
    ]
  },
  {
    "text": "snow",
    "segs": "s.n.ow",
    "unit": "EC32",
    "pic": "snow",
    "tags": [
      "review",
      "picture",
      "sort:ow"
    ]
  },
  {
    "text": "crow",
    "segs": "c.r.ow",
    "unit": "EC32",
    "pic": "one black crow standing alone",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:ow"
    ]
  },
  {
    "text": "bowl",
    "segs": "b.ow.l",
    "unit": "EC32",
    "pic": "one empty blue ceramic bowl",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:ow"
    ]
  },
  {
    "text": "blow",
    "segs": "b.l.ow",
    "unit": "EC32",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "grow",
    "segs": "g.r.ow",
    "unit": "EC32",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "slow",
    "segs": "s.l.ow",
    "unit": "EC32",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "show",
    "segs": "sh.ow",
    "unit": "EC32",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "throw",
    "segs": "th.r.ow",
    "unit": "EC32",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "hole",
    "segs": "h.o=oe.le=l",
    "unit": "EC32",
    "pic": "one round hole in a wooden plank",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:o"
    ]
  },
  {
    "text": "cone",
    "segs": "c.o=oe.ne=n",
    "unit": "EC32",
    "pic": "one brown pine cone",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:o"
    ]
  },
  {
    "text": "home",
    "segs": "h.o=oe.me=m",
    "unit": "EC32",
    "tags": [
      "review",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "stone",
    "segs": "s.t.o=oe.ne=n",
    "unit": "EC32",
    "tags": [
      "review",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "poke",
    "segs": "p.o=oe.ke=k",
    "unit": "EC32",
    "tags": [
      "review",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "most",
    "segs": "m.o=oe.s.t",
    "unit": "EC32",
    "tags": [
      "review",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "both",
    "segs": "b.o=oe.th",
    "unit": "EC32",
    "tags": [
      "review",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "note",
    "segs": "n.o=oe.te=t",
    "unit": "EC32",
    "tags": [
      "review",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "coat",
    "segs": "c.oa.t",
    "unit": "EC32",
    "pic": "a coat",
    "tags": [
      "review",
      "picture",
      "sort:oa"
    ]
  },
  {
    "text": "boat",
    "segs": "b.oa.t",
    "unit": "EC32",
    "pic": "a boat",
    "tags": [
      "review",
      "picture",
      "sort:oa"
    ]
  },
  {
    "text": "road",
    "segs": "r.oa.d",
    "unit": "EC32",
    "pic": "a road",
    "tags": [
      "review",
      "picture",
      "sort:oa"
    ]
  },
  {
    "text": "goat",
    "segs": "g.oa.t",
    "unit": "EC32",
    "pic": "a goat",
    "tags": [
      "review",
      "picture",
      "sort:oa"
    ]
  },
  {
    "text": "soap",
    "segs": "s.oa.p",
    "unit": "EC32",
    "pic": "a pink bar of soap covered in white foam with shiny soap bubbles floating around it",
    "tags": [
      "review",
      "picture",
      "sort:oa"
    ]
  },
  {
    "text": "toast",
    "segs": "t.oa.s.t",
    "unit": "EC32",
    "pic": "toast",
    "tags": [
      "review",
      "picture",
      "sort:oa"
    ]
  },
  {
    "text": "coal",
    "segs": "c.oa.l",
    "unit": "EC32",
    "tags": [
      "review",
      "sort:oa",
      "dictation-safe"
    ]
  },
  {
    "text": "loaf",
    "segs": "l.oa.f",
    "unit": "EC32",
    "tags": [
      "review",
      "dictation-safe",
      "sort:oa"
    ]
  },
  {
    "text": "own",
    "segs": "ow.n",
    "unit": "EC32",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "groan",
    "segs": "g.r.oa.n",
    "unit": "EC32",
    "tags": [
      "review",
      "dictation-safe",
      "sort:oa"
    ]
  },
  {
    "text": "host",
    "segs": "h.o=oe.s.t",
    "unit": "EC32",
    "tags": [
      "review",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "throat",
    "segs": "th.r.oa.t",
    "unit": "EC32",
    "tags": [
      "review",
      "dictation-safe",
      "sort:oa"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The car is by the farm.",
    "maxUnit": "EC30"
  },
  {
    "text": "A hawk sat on the fence.",
    "maxUnit": "EC30"
  },
  {
    "text": "The pencil fell off the table.",
    "maxUnit": "EC30"
  },
  {
    "text": "The horse stood by the gate.",
    "maxUnit": "EC30"
  },
  {
    "text": "A little bird sat on the fence.",
    "maxUnit": "EC30"
  },
  {
    "text": "The bull stood by the bush.",
    "maxUnit": "EC30"
  },
  {
    "text": "The broom is by the door.",
    "maxUnit": "EC30"
  },
  {
    "text": "The cow is by the house.",
    "maxUnit": "EC30"
  }
] as const;

export const chains = [
  [
    "dough",
    "dare",
    "bare",
    "bee",
    "been"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "rotten",
    "syllables": "rot|ten",
    "schwa": [
      1
    ]
  },
  {
    "text": "payment",
    "syllables": "pay|ment",
    "schwa": [
      1
    ]
  },
  {
    "text": "happy",
    "syllables": "ha|ppy"
  },
  {
    "text": "sunny",
    "syllables": "su|nny"
  },
  {
    "text": "tummy",
    "syllables": "tu|mmy"
  },
  {
    "text": "yellow",
    "syllables": "ye|llow"
  },
  {
    "text": "silly",
    "syllables": "si|lly"
  },
  {
    "text": "ready",
    "syllables": "rea|dy"
  },
  {
    "text": "runny",
    "syllables": "ru|nny"
  },
  {
    "text": "dolly",
    "syllables": "do|lly"
  }
] as const;
