// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "gone",
    "segs": "g.o.ne=n",
    "unit": "EC33",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ne"
    ]
  },
  {
    "text": "shone",
    "segs": "sh.o.ne=n",
    "unit": "EC33",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ne"
    ]
  },
  {
    "text": "knee",
    "segs": "kn=n.ee",
    "unit": "EC33",
    "pic": "one bent human knee seen close up, no other body part prominent",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:kn"
    ]
  },
  {
    "text": "knock",
    "segs": "kn=n.o.ck",
    "unit": "EC33",
    "tags": [
      "new",
      "dictation-safe",
      "sort:kn"
    ]
  },
  {
    "text": "knew",
    "segs": "kn=n.ew=ue",
    "unit": "EC33",
    "tags": [
      "new",
      "reading-only",
      "sort:kn"
    ]
  },
  {
    "text": "know",
    "segs": "kn=n.ow",
    "unit": "EC33",
    "tags": [
      "new",
      "reading-only",
      "sort:kn"
    ]
  },
  {
    "text": "kneel",
    "segs": "kn=n.ee.l",
    "unit": "EC33",
    "tags": [
      "new",
      "dictation-safe",
      "sort:kn"
    ]
  },
  {
    "text": "hand",
    "segs": "h.a.n.d",
    "unit": "EC33",
    "pic": "one open cartoon hand waving hello, palm facing the viewer, five fingers spread",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "rain",
    "segs": "r.ai.n",
    "unit": "EC33",
    "pic": "heavy raindrops falling from one grey cloud",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:n"
    ]
  },
  {
    "text": "run",
    "segs": "r.u.n",
    "unit": "EC33",
    "pic": "a child running",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "train",
    "segs": "t.r.ai.n",
    "unit": "EC33",
    "pic": "a steam train",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "man",
    "segs": "m.a.n",
    "unit": "EC33",
    "pic": "a grown-up man with a friendly face (two eyes and a big smile), short brown hair, a green jumper and blue jeans, whole from head to toe, facing the viewer and waving",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "ant",
    "segs": "a.n.t",
    "unit": "EC33",
    "pic": "an ant",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "sun",
    "segs": "s.u.n",
    "unit": "EC33",
    "pic": "the sun",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "snow",
    "segs": "s.n.ow",
    "unit": "EC33",
    "pic": "snow",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "queen",
    "segs": "q.u=w.ee.n",
    "unit": "EC33",
    "pic": "a queen",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "stand",
    "segs": "s.t.a.n.d",
    "unit": "EC33",
    "tags": [
      "review",
      "sort:n",
      "dictation-safe"
    ]
  },
  {
    "text": "bun",
    "segs": "b.u.n",
    "unit": "EC33",
    "pic": "a single soft round iced bun with a little swirl of white icing on top, no plate or bread slices",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "snail",
    "segs": "s.n.ai.l",
    "unit": "EC33",
    "pic": "a snail",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "pan",
    "segs": "p.a.n",
    "unit": "EC33",
    "pic": "a frying pan",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "sand",
    "segs": "s.a.n.d",
    "unit": "EC33",
    "pic": "a small golden sandcastle with a little flag on top, sitting on a heap of sand",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "bin",
    "segs": "b.i.n",
    "unit": "EC33",
    "pic": "a rubbish bin",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "hen",
    "segs": "h.e.n",
    "unit": "EC33",
    "tags": [
      "review",
      "sort:n",
      "dictation-safe"
    ]
  },
  {
    "text": "bench",
    "segs": "b.e.n.ch",
    "unit": "EC33",
    "pic": "a park bench",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "win",
    "segs": "w.i.n",
    "unit": "EC33",
    "tags": [
      "review",
      "sort:n",
      "dictation-safe"
    ]
  },
  {
    "text": "pen",
    "segs": "p.e.n",
    "unit": "EC33",
    "pic": "a pen",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "van",
    "segs": "v.a.n",
    "unit": "EC33",
    "pic": "a tall boxy delivery van with a large windowless cargo box behind the cab, two front seats only, sliding side door and rear doors, in bright blue",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "tin",
    "segs": "t.i.n",
    "unit": "EC33",
    "pic": "a tin can",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "fan",
    "segs": "f.a.n",
    "unit": "EC33",
    "pic": "an electric fan",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "nap",
    "segs": "n.a.p",
    "unit": "EC33",
    "tags": [
      "review",
      "sort:n",
      "dictation-safe"
    ]
  },
  {
    "text": "tent",
    "segs": "t.e.n.t",
    "unit": "EC33",
    "pic": "a tent",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "paint",
    "segs": "p.ai.n.t",
    "unit": "EC33",
    "pic": "a paint pot",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "nut",
    "segs": "n.u.t",
    "unit": "EC33",
    "pic": "a shelled walnut cracked open to show the wrinkled nut kernel inside, no acorn cap",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "nest",
    "segs": "n.e.s.t",
    "unit": "EC33",
    "pic": "a bird nest",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "den",
    "segs": "d.e.n",
    "unit": "EC33",
    "pic": "a small cosy den made of blankets draped over chairs",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "pond",
    "segs": "p.o.n.d",
    "unit": "EC33",
    "pic": "a pond",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "net",
    "segs": "n.e.t",
    "unit": "EC33",
    "pic": "a fishing net",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "pin",
    "segs": "p.i.n",
    "unit": "EC33",
    "pic": "a big red drawing pin (a push pin) standing on its point, seen from the side",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  },
  {
    "text": "fin",
    "segs": "f.i.n",
    "unit": "EC33",
    "tags": [
      "review",
      "sort:n",
      "dictation-safe"
    ]
  },
  {
    "text": "nail",
    "segs": "n.ai.l",
    "unit": "EC33",
    "pic": "a nail",
    "tags": [
      "review",
      "picture",
      "sort:n"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC31"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC31"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC31"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC31"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC31"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC31"
  },
  {
    "text": "The bear sat on the chair.",
    "maxUnit": "EC31"
  },
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC31"
  }
] as const;

export const chains = [
  [
    "gone",
    "shone",
    "bone",
    "done",
    "do"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "holiday",
    "syllables": "hol|i|day",
    "schwa": [
      1
    ]
  },
  {
    "text": "chimney",
    "syllables": "chim|ney",
    "schwa": [
      1
    ]
  },
  {
    "text": "rotten",
    "syllables": "rot|ten",
    "schwa": [
      1
    ]
  },
  {
    "text": "payment",
    "syllables": "pay|ment",
    "schwa": [
      1
    ]
  },
  {
    "text": "happy",
    "syllables": "ha|ppy"
  },
  {
    "text": "sunny",
    "syllables": "su|nny"
  },
  {
    "text": "tummy",
    "syllables": "tu|mmy"
  },
  {
    "text": "yellow",
    "syllables": "ye|llow"
  },
  {
    "text": "silly",
    "syllables": "si|lly"
  },
  {
    "text": "ready",
    "syllables": "rea|dy"
  }
] as const;
