// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "nurse",
    "segs": "n.ur=er.se=s",
    "unit": "EC34",
    "tags": [
      "review",
      "sort:ur",
      "dictation-safe"
    ]
  },
  {
    "text": "purse",
    "segs": "p.ur=er.se=s",
    "unit": "EC34",
    "pic": "one small zipped purse for coins",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:ur"
    ]
  },
  {
    "text": "burn",
    "segs": "b.ur=er.n",
    "unit": "EC34",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ur"
    ]
  },
  {
    "text": "skirt",
    "segs": "s.k.ir=er.t",
    "unit": "EC34",
    "pic": "one plain red skirt",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:ir"
    ]
  },
  {
    "text": "stir",
    "segs": "s.t.ir=er",
    "unit": "EC34",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ir"
    ]
  },
  {
    "text": "first",
    "segs": "f.ir=er.s.t",
    "unit": "EC34",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ir"
    ]
  },
  {
    "text": "third",
    "segs": "th.ir=er.d",
    "unit": "EC34",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ir"
    ]
  },
  {
    "text": "birth",
    "segs": "b.ir=er.th",
    "unit": "EC34",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ir"
    ]
  },
  {
    "text": "worm",
    "segs": "w.or=er.m",
    "unit": "EC34",
    "pic": "one pink earthworm curved on plain white",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:or"
    ]
  },
  {
    "text": "world",
    "segs": "w.or=er.l.d",
    "unit": "EC34",
    "tags": [
      "review",
      "dictation-safe",
      "sort:or"
    ]
  },
  {
    "text": "worst",
    "segs": "w.or=er.s.t",
    "unit": "EC34",
    "tags": [
      "review",
      "dictation-safe",
      "sort:or"
    ]
  },
  {
    "text": "work",
    "segs": "w.or=er.k",
    "unit": "EC34",
    "tags": [
      "review",
      "dictation-safe",
      "sort:or"
    ]
  },
  {
    "text": "word",
    "segs": "w.or=er.d",
    "unit": "EC34",
    "tags": [
      "review",
      "dictation-safe",
      "sort:or"
    ]
  },
  {
    "text": "earth",
    "segs": "ear=er.th",
    "unit": "EC34",
    "pic": "one globe of planet Earth, with no labels",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ear"
    ]
  },
  {
    "text": "pearl",
    "segs": "p.ear=er.l",
    "unit": "EC34",
    "tags": [
      "new",
      "sort:ear",
      "dictation-safe"
    ]
  },
  {
    "text": "learn",
    "segs": "l.ear=er.n",
    "unit": "EC34",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ear"
    ]
  },
  {
    "text": "heard",
    "segs": "h.ear=er.d",
    "unit": "EC34",
    "tags": [
      "new",
      "reading-only",
      "sort:ear"
    ]
  },
  {
    "text": "earn",
    "segs": "ear=er.n",
    "unit": "EC34",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ear"
    ]
  },
  {
    "text": "search",
    "segs": "s.ear=er.ch",
    "unit": "EC34",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ear"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC32"
  },
  {
    "text": "A mouse ran out of the house.",
    "maxUnit": "EC32"
  },
  {
    "text": "The cow is by the house.",
    "maxUnit": "EC32"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC32"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC32"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC32"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC32"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC32"
  }
] as const;

export const chains = [
  [
    "burn",
    "barn",
    "bark",
    "park",
    "spark"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "litre",
    "syllables": "li|tre",
    "schwa": [
      1
    ]
  },
  {
    "text": "solar",
    "syllables": "so|lar",
    "schwa": [
      1
    ]
  },
  {
    "text": "favour",
    "syllables": "fa|vour",
    "schwa": [
      1
    ]
  },
  {
    "text": "collar",
    "syllables": "co|llar",
    "schwa": [
      1
    ]
  },
  {
    "text": "holiday",
    "syllables": "hol|i|day",
    "schwa": [
      1
    ]
  },
  {
    "text": "chimney",
    "syllables": "chim|ney",
    "schwa": [
      1
    ]
  },
  {
    "text": "rotten",
    "syllables": "rot|ten",
    "schwa": [
      1
    ]
  },
  {
    "text": "payment",
    "syllables": "pay|ment",
    "schwa": [
      1
    ]
  },
  {
    "text": "happy",
    "syllables": "ha|ppy"
  },
  {
    "text": "sunny",
    "syllables": "su|nny"
  }
] as const;
