// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "van",
    "segs": "v.a.n",
    "unit": "EC35",
    "pic": "a tall boxy delivery van with a large windowless cargo box behind the cab, two front seats only, sliding side door and rear doors, in bright blue",
    "tags": [
      "review",
      "picture",
      "sort:v"
    ]
  },
  {
    "text": "vest",
    "segs": "v.e.s.t",
    "unit": "EC35",
    "pic": "a vest",
    "tags": [
      "review",
      "picture",
      "sort:v"
    ]
  },
  {
    "text": "vet",
    "segs": "v.e.t",
    "unit": "EC35",
    "pic": "a friendly woman vet in teal scrubs examining a small puppy on a low table, wearing a stethoscope around her neck, full person and puppy both clearly visible",
    "tags": [
      "review",
      "picture",
      "sort:v"
    ]
  },
  {
    "text": "sleeve",
    "segs": "s.l.ee.ve",
    "unit": "EC35",
    "tags": [
      "review",
      "sort:ve",
      "dictation-safe"
    ]
  },
  {
    "text": "give",
    "segs": "g.i.ve",
    "unit": "EC35",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ve"
    ]
  },
  {
    "text": "have",
    "segs": "h.a.ve",
    "unit": "EC35",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ve"
    ]
  },
  {
    "text": "live",
    "segs": "l.i.ve",
    "unit": "EC35",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ve"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC33"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC33"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC33"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC33"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC33"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC33"
  },
  {
    "text": "The bear sat on the chair.",
    "maxUnit": "EC33"
  },
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC33"
  }
] as const;

export const chains = [
  [
    "van",
    "an",
    "add",
    "all",
    "am"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "savvy",
    "syllables": "sa|vvy",
    "schwa": [
      1
    ]
  },
  {
    "text": "skivvy",
    "syllables": "ski|vvy",
    "schwa": [
      1
    ]
  },
  {
    "text": "evening",
    "syllables": "e|ve|ning",
    "schwa": [
      0
    ]
  },
  {
    "text": "litre",
    "syllables": "li|tre",
    "schwa": [
      1
    ]
  },
  {
    "text": "solar",
    "syllables": "so|lar",
    "schwa": [
      1
    ]
  },
  {
    "text": "favour",
    "syllables": "fa|vour",
    "schwa": [
      1
    ]
  },
  {
    "text": "collar",
    "syllables": "co|llar",
    "schwa": [
      1
    ]
  },
  {
    "text": "holiday",
    "syllables": "hol|i|day",
    "schwa": [
      1
    ]
  },
  {
    "text": "chimney",
    "syllables": "chim|ney",
    "schwa": [
      1
    ]
  },
  {
    "text": "rotten",
    "syllables": "rot|ten",
    "schwa": [
      1
    ]
  }
] as const;
