// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "brew",
    "segs": "b.r.ew=oo",
    "unit": "EC36",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ew"
    ]
  },
  {
    "text": "through",
    "segs": "th.r.ough=oo",
    "unit": "EC36",
    "tags": [
      "new",
      "reading-only",
      "sort:ough"
    ]
  },
  {
    "text": "goose",
    "segs": "g.oo.se=s",
    "unit": "EC36",
    "pic": "one white goose standing alone, full body",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:oo"
    ]
  },
  {
    "text": "soon",
    "segs": "s.oo.n",
    "unit": "EC36",
    "tags": [
      "review",
      "dictation-safe",
      "sort:oo"
    ]
  },
  {
    "text": "flu",
    "segs": "f.l.u=oo",
    "unit": "EC36",
    "tags": [
      "review",
      "reading-only",
      "sort:u"
    ]
  },
  {
    "text": "rule",
    "segs": "r.u=oo.le=l",
    "unit": "EC36",
    "tags": [
      "review",
      "dictation-safe",
      "sort:u"
    ]
  },
  {
    "text": "truth",
    "segs": "t.r.u=oo.th",
    "unit": "EC36",
    "tags": [
      "review",
      "dictation-safe",
      "sort:u"
    ]
  },
  {
    "text": "juice",
    "segs": "j.ui=oo.ce=s",
    "unit": "EC36",
    "pic": "one glass of orange juice, alone",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ui"
    ]
  },
  {
    "text": "fruit",
    "segs": "f.r.ui=oo.t",
    "unit": "EC36",
    "pic": "one apple, one pear and one banana grouped together",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ui"
    ]
  },
  {
    "text": "suit",
    "segs": "s.ui=oo.t",
    "unit": "EC36",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ui"
    ]
  },
  {
    "text": "soup",
    "segs": "s.ou=oo.p",
    "unit": "EC36",
    "pic": "one bowl of vegetable soup with a spoon",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:ou"
    ]
  },
  {
    "text": "group",
    "segs": "g.r.ou=oo.p",
    "unit": "EC36",
    "tags": [
      "review",
      "sort:ou",
      "dictation-safe"
    ]
  },
  {
    "text": "you",
    "segs": "y.ou=oo",
    "unit": "EC36",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ou"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC34"
  },
  {
    "text": "The jar is on the cart.",
    "maxUnit": "EC34"
  },
  {
    "text": "The star is over the barn.",
    "maxUnit": "EC34"
  },
  {
    "text": "The car is by the farm.",
    "maxUnit": "EC34"
  },
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC34"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC34"
  },
  {
    "text": "The bear sat on the chair.",
    "maxUnit": "EC34"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC34"
  }
] as const;

export const chains = [
  [
    "brew",
    "blew",
    "flew",
    "flu",
    "flute"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "season",
    "syllables": "sea|son",
    "schwa": [
      1
    ]
  },
  {
    "text": "piano",
    "syllables": "pi|a|no",
    "schwa": [
      1
    ]
  },
  {
    "text": "savvy",
    "syllables": "sa|vvy",
    "schwa": [
      1
    ]
  },
  {
    "text": "skivvy",
    "syllables": "ski|vvy",
    "schwa": [
      1
    ]
  },
  {
    "text": "evening",
    "syllables": "e|ve|ning",
    "schwa": [
      0
    ]
  },
  {
    "text": "litre",
    "syllables": "li|tre",
    "schwa": [
      1
    ]
  },
  {
    "text": "solar",
    "syllables": "so|lar",
    "schwa": [
      1
    ]
  },
  {
    "text": "favour",
    "syllables": "fa|vour",
    "schwa": [
      1
    ]
  },
  {
    "text": "collar",
    "syllables": "co|llar",
    "schwa": [
      1
    ]
  },
  {
    "text": "holiday",
    "syllables": "hol|i|day",
    "schwa": [
      1
    ]
  }
] as const;
