// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "huge",
    "segs": "h.u=ue.ge=j",
    "unit": "EC37",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ge"
    ]
  },
  {
    "text": "hinge",
    "segs": "h.i.n.ge=j",
    "unit": "EC37",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ge"
    ]
  },
  {
    "text": "gentle",
    "segs": "g=j.e.n.t.le=l",
    "unit": "EC37",
    "tags": [
      "new",
      "dictation-safe",
      "sort:g"
    ]
  },
  {
    "text": "gem",
    "segs": "g=j.e.m",
    "unit": "EC37",
    "tags": [
      "new",
      "dictation-safe",
      "sort:g"
    ]
  },
  {
    "text": "germ",
    "segs": "g=j.er=er.m",
    "unit": "EC37",
    "tags": [
      "new",
      "dictation-safe",
      "sort:g"
    ]
  },
  {
    "text": "jump",
    "segs": "j.u.m.p",
    "unit": "EC37",
    "tags": [
      "review",
      "sort:j",
      "dictation-safe"
    ]
  },
  {
    "text": "jam",
    "segs": "j.a.m",
    "unit": "EC37",
    "pic": "a jar of jam",
    "tags": [
      "review",
      "picture",
      "sort:j"
    ]
  },
  {
    "text": "jet",
    "segs": "j.e.t",
    "unit": "EC37",
    "tags": [
      "review",
      "sort:j",
      "dictation-safe"
    ]
  },
  {
    "text": "jug",
    "segs": "j.u.g",
    "unit": "EC37",
    "pic": "a jug",
    "tags": [
      "review",
      "picture",
      "sort:j"
    ]
  },
  {
    "text": "jog",
    "segs": "j.o.g",
    "unit": "EC37",
    "tags": [
      "review",
      "sort:j",
      "dictation-safe"
    ]
  },
  {
    "text": "just",
    "segs": "j.u.s.t",
    "unit": "EC37",
    "tags": [
      "review",
      "dictation-safe",
      "sort:j"
    ]
  },
  {
    "text": "jack",
    "segs": "j.a.ck",
    "unit": "EC37",
    "tags": [
      "review",
      "dictation-safe",
      "sort:j"
    ]
  },
  {
    "text": "fridge",
    "segs": "f.r.i.dge=j",
    "unit": "EC37",
    "pic": "one white refrigerator standing alone, closed",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:dge"
    ]
  },
  {
    "text": "badge",
    "segs": "b.a.dge=j",
    "unit": "EC37",
    "tags": [
      "new",
      "sort:dge",
      "dictation-safe"
    ]
  },
  {
    "text": "bridge",
    "segs": "b.r.i.dge=j",
    "unit": "EC37",
    "pic": "one stone bridge over a narrow stream",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:dge"
    ]
  },
  {
    "text": "hedge",
    "segs": "h.e.dge=j",
    "unit": "EC37",
    "pic": "one short neatly clipped garden hedge",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:dge"
    ]
  },
  {
    "text": "edge",
    "segs": "e.dge=j",
    "unit": "EC37",
    "tags": [
      "new",
      "dictation-safe",
      "sort:dge"
    ]
  },
  {
    "text": "nudge",
    "segs": "n.u.dge=j",
    "unit": "EC37",
    "tags": [
      "new",
      "dictation-safe",
      "sort:dge"
    ]
  },
  {
    "text": "smudge",
    "segs": "s.m.u.dge=j",
    "unit": "EC37",
    "tags": [
      "new",
      "dictation-safe",
      "sort:dge"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC35"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC35"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC35"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC35"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC35"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC35"
  },
  {
    "text": "The bear sat on the chair.",
    "maxUnit": "EC35"
  },
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC35"
  }
] as const;

export const chains = [
  [
    "gem",
    "them",
    "then",
    "den",
    "dent"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "notebook",
    "syllables": "note|book"
  },
  {
    "text": "season",
    "syllables": "sea|son",
    "schwa": [
      1
    ]
  },
  {
    "text": "piano",
    "syllables": "pi|a|no",
    "schwa": [
      1
    ]
  },
  {
    "text": "savvy",
    "syllables": "sa|vvy",
    "schwa": [
      1
    ]
  },
  {
    "text": "skivvy",
    "syllables": "ski|vvy",
    "schwa": [
      1
    ]
  },
  {
    "text": "evening",
    "syllables": "e|ve|ning",
    "schwa": [
      0
    ]
  },
  {
    "text": "litre",
    "syllables": "li|tre",
    "schwa": [
      1
    ]
  },
  {
    "text": "solar",
    "syllables": "so|lar",
    "schwa": [
      1
    ]
  },
  {
    "text": "favour",
    "syllables": "fa|vour",
    "schwa": [
      1
    ]
  },
  {
    "text": "collar",
    "syllables": "co|llar",
    "schwa": [
      1
    ]
  }
] as const;
