// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "dog",
    "segs": "d.o.g",
    "unit": "EC39",
    "pic": "a friendly brown-and-white puppy sitting and facing the viewer, floppy ears, big shiny eyes, a little pink tongue, a wagging tail",
    "tags": [
      "review",
      "picture",
      "sort:g"
    ]
  },
  {
    "text": "frog",
    "segs": "f.r.o.g",
    "unit": "EC39",
    "pic": "a green frog sitting and facing the viewer, big round eyes with shiny black pupils, a wide smile",
    "tags": [
      "review",
      "picture",
      "sort:g"
    ]
  },
  {
    "text": "hug",
    "segs": "h.u.g",
    "unit": "EC39",
    "pic": "two children facing each other in one clear hug, both full bodies visible",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:g"
    ]
  },
  {
    "text": "leg",
    "segs": "l.e.g",
    "unit": "EC39",
    "pic": "one isolated bare human leg from the upper thigh to all five toes, bent slightly at the clearly visible knee, natural skin colour, no sock, shoe, trousers or rest of body",
    "tags": [
      "review",
      "picture",
      "sort:g"
    ]
  },
  {
    "text": "pig",
    "segs": "p.i.g",
    "unit": "EC39",
    "pic": "a round pink pig standing side-on with its head turned to smile at the viewer, flat snout, curly tail",
    "tags": [
      "review",
      "picture",
      "sort:g"
    ]
  },
  {
    "text": "bug",
    "segs": "b.u.g",
    "unit": "EC39",
    "pic": "one small green six-legged garden bug, shown alone with its body and legs clearly visible",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:g"
    ]
  },
  {
    "text": "goat",
    "segs": "g.oa.t",
    "unit": "EC39",
    "pic": "a goat",
    "tags": [
      "review",
      "picture",
      "sort:g"
    ]
  },
  {
    "text": "rug",
    "segs": "r.u.g",
    "unit": "EC39",
    "pic": "a round colourful rug",
    "tags": [
      "review",
      "picture",
      "sort:g"
    ]
  },
  {
    "text": "bag",
    "segs": "b.a.g",
    "unit": "EC39",
    "pic": "a school bag",
    "tags": [
      "review",
      "picture",
      "sort:g"
    ]
  },
  {
    "text": "flag",
    "segs": "f.l.a.g",
    "unit": "EC39",
    "pic": "a flag",
    "tags": [
      "review",
      "picture",
      "sort:g"
    ]
  },
  {
    "text": "wag",
    "segs": "w.a.g",
    "unit": "EC39",
    "tags": [
      "review",
      "sort:g",
      "dictation-safe"
    ]
  },
  {
    "text": "mug",
    "segs": "m.u.g",
    "unit": "EC39",
    "pic": "a mug",
    "tags": [
      "review",
      "picture",
      "sort:g"
    ]
  },
  {
    "text": "plug",
    "segs": "p.l.u.g",
    "unit": "EC39",
    "pic": "a plug",
    "tags": [
      "review",
      "picture",
      "sort:g"
    ]
  },
  {
    "text": "jug",
    "segs": "j.u.g",
    "unit": "EC39",
    "pic": "a jug",
    "tags": [
      "review",
      "picture",
      "sort:g"
    ]
  },
  {
    "text": "log",
    "segs": "l.o.g",
    "unit": "EC39",
    "pic": "a log",
    "tags": [
      "review",
      "picture",
      "sort:g"
    ]
  },
  {
    "text": "jog",
    "segs": "j.o.g",
    "unit": "EC39",
    "tags": [
      "review",
      "sort:g",
      "dictation-safe"
    ]
  },
  {
    "text": "twig",
    "segs": "t.w.i.g",
    "unit": "EC39",
    "tags": [
      "review",
      "sort:g",
      "dictation-safe"
    ]
  },
  {
    "text": "peg",
    "segs": "p.e.g",
    "unit": "EC39",
    "pic": "a clothes peg",
    "tags": [
      "review",
      "picture",
      "sort:g"
    ]
  },
  {
    "text": "wig",
    "segs": "w.i.g",
    "unit": "EC39",
    "pic": "a bright purple curly wig resting on a simple plain wooden wig stand, with the wig cap edge visible below the curls",
    "tags": [
      "review",
      "picture",
      "sort:g"
    ]
  },
  {
    "text": "fog",
    "segs": "f.o.g",
    "unit": "EC39",
    "tags": [
      "review",
      "sort:g",
      "dictation-safe"
    ]
  },
  {
    "text": "gate",
    "segs": "g.a=ae.te=t",
    "unit": "EC39",
    "pic": "one wooden garden gate with a latch",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:g"
    ]
  },
  {
    "text": "big",
    "segs": "b.i.g",
    "unit": "EC39",
    "tags": [
      "review",
      "dictation-safe",
      "sort:g"
    ]
  },
  {
    "text": "give",
    "segs": "g.i.ve",
    "unit": "EC39",
    "tags": [
      "review",
      "dictation-safe",
      "sort:g"
    ]
  },
  {
    "text": "green",
    "segs": "g.r.ee.n",
    "unit": "EC39",
    "tags": [
      "review",
      "dictation-safe",
      "sort:g"
    ]
  },
  {
    "text": "gift",
    "segs": "g.i.f.t",
    "unit": "EC39",
    "tags": [
      "review",
      "dictation-safe",
      "sort:g"
    ]
  },
  {
    "text": "grow",
    "segs": "g.r.ow",
    "unit": "EC39",
    "tags": [
      "review",
      "dictation-safe",
      "sort:g"
    ]
  },
  {
    "text": "get",
    "segs": "g.e.t",
    "unit": "EC39",
    "tags": [
      "review",
      "dictation-safe",
      "sort:g"
    ]
  },
  {
    "text": "got",
    "segs": "g.o.t",
    "unit": "EC39",
    "tags": [
      "review",
      "dictation-safe",
      "sort:g"
    ]
  },
  {
    "text": "grin",
    "segs": "g.r.i.n",
    "unit": "EC39",
    "tags": [
      "review",
      "dictation-safe",
      "sort:g"
    ]
  },
  {
    "text": "dug",
    "segs": "d.u.g",
    "unit": "EC39",
    "tags": [
      "review",
      "dictation-safe",
      "sort:g"
    ]
  },
  {
    "text": "glad",
    "segs": "g.l.a.d",
    "unit": "EC39",
    "tags": [
      "review",
      "dictation-safe",
      "sort:g"
    ]
  },
  {
    "text": "gum",
    "segs": "g.u.m",
    "unit": "EC39",
    "tags": [
      "review",
      "dictation-safe",
      "sort:g"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC37"
  },
  {
    "text": "The horse stood by the gate.",
    "maxUnit": "EC37"
  },
  {
    "text": "The girl had a red skirt.",
    "maxUnit": "EC37"
  },
  {
    "text": "A snail sat on the gate.",
    "maxUnit": "EC37"
  },
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC37"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC37"
  }
] as const;

export const chains = [] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "kneecap",
    "syllables": "knee|cap"
  },
  {
    "text": "notebook",
    "syllables": "note|book"
  },
  {
    "text": "season",
    "syllables": "sea|son",
    "schwa": [
      1
    ]
  },
  {
    "text": "piano",
    "syllables": "pi|a|no",
    "schwa": [
      1
    ]
  },
  {
    "text": "savvy",
    "syllables": "sa|vvy",
    "schwa": [
      1
    ]
  },
  {
    "text": "skivvy",
    "syllables": "ski|vvy",
    "schwa": [
      1
    ]
  },
  {
    "text": "evening",
    "syllables": "e|ve|ning",
    "schwa": [
      0
    ]
  },
  {
    "text": "litre",
    "syllables": "li|tre",
    "schwa": [
      1
    ]
  },
  {
    "text": "solar",
    "syllables": "so|lar",
    "schwa": [
      1
    ]
  },
  {
    "text": "favour",
    "syllables": "fa|vour",
    "schwa": [
      1
    ]
  }
] as const;
