// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "toe",
    "segs": "t.oe=oe",
    "unit": "EC4",
    "pic": "one bare foot with its toes clearly visible",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:oe"
    ]
  },
  {
    "text": "snow",
    "segs": "s.n.ow",
    "unit": "EC4",
    "pic": "snow",
    "tags": [
      "new",
      "picture",
      "sort:ow"
    ]
  },
  {
    "text": "crow",
    "segs": "c.r.ow",
    "unit": "EC4",
    "pic": "one black crow standing alone",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ow"
    ]
  },
  {
    "text": "bowl",
    "segs": "b.ow.l",
    "unit": "EC4",
    "pic": "one empty blue ceramic bowl",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ow"
    ]
  },
  {
    "text": "blow",
    "segs": "b.l.ow",
    "unit": "EC4",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "grow",
    "segs": "g.r.ow",
    "unit": "EC4",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "slow",
    "segs": "s.l.ow",
    "unit": "EC4",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "bone",
    "segs": "b.o=oe.ne=n",
    "unit": "EC4",
    "pic": "one clean white dog bone",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:o"
    ]
  },
  {
    "text": "hole",
    "segs": "h.o=oe.le=l",
    "unit": "EC4",
    "pic": "one round hole in a wooden plank",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:o"
    ]
  },
  {
    "text": "gold",
    "segs": "g.o=oe.l.d",
    "unit": "EC4",
    "pic": "one small plain gold nugget",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:o"
    ]
  },
  {
    "text": "pole",
    "segs": "p.o=oe.le=l",
    "unit": "EC4",
    "pic": "one plain upright wooden pole",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:o"
    ]
  },
  {
    "text": "mole",
    "segs": "m.o=oe.le=l",
    "unit": "EC4",
    "pic": "one small brown mole animal with a pointed nose and digging paws",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:o"
    ]
  },
  {
    "text": "cone",
    "segs": "c.o=oe.ne=n",
    "unit": "EC4",
    "pic": "one brown pine cone",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:o"
    ]
  },
  {
    "text": "go",
    "segs": "g.o=oe",
    "unit": "EC4",
    "tags": [
      "new",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "no",
    "segs": "n.o=oe",
    "unit": "EC4",
    "tags": [
      "new",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "coat",
    "segs": "c.oa.t",
    "unit": "EC4",
    "pic": "a coat",
    "tags": [
      "new",
      "picture",
      "sort:oa"
    ]
  },
  {
    "text": "boat",
    "segs": "b.oa.t",
    "unit": "EC4",
    "pic": "a boat",
    "tags": [
      "new",
      "picture",
      "sort:oa"
    ]
  },
  {
    "text": "road",
    "segs": "r.oa.d",
    "unit": "EC4",
    "pic": "a road",
    "tags": [
      "new",
      "picture",
      "sort:oa"
    ]
  },
  {
    "text": "goat",
    "segs": "g.oa.t",
    "unit": "EC4",
    "pic": "a goat",
    "tags": [
      "new",
      "picture",
      "sort:oa"
    ]
  },
  {
    "text": "soap",
    "segs": "s.oa.p",
    "unit": "EC4",
    "pic": "a pink bar of soap covered in white foam with shiny soap bubbles floating around it",
    "tags": [
      "new",
      "picture",
      "sort:oa"
    ]
  },
  {
    "text": "toast",
    "segs": "t.oa.s.t",
    "unit": "EC4",
    "pic": "toast",
    "tags": [
      "new",
      "picture",
      "sort:oa"
    ]
  },
  {
    "text": "toad",
    "segs": "t.oa.d",
    "unit": "EC4",
    "pic": "one brown toad sitting alone",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:oa"
    ]
  },
  {
    "text": "coal",
    "segs": "c.oa.l",
    "unit": "EC4",
    "pic": "one lump of black coal",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:oa"
    ]
  },
  {
    "text": "oak",
    "segs": "oa.k",
    "unit": "EC4",
    "pic": "one broad oak tree with a thick trunk",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:oa"
    ]
  },
  {
    "text": "home",
    "segs": "h.o=oe.me=m",
    "unit": "EC4",
    "tags": [
      "new",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "so",
    "segs": "s.o=oe",
    "unit": "EC4",
    "tags": [
      "new",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "cold",
    "segs": "c.o=oe.l.d",
    "unit": "EC4",
    "tags": [
      "new",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "stone",
    "segs": "s.t.o=oe.ne=n",
    "unit": "EC4",
    "tags": [
      "new",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "old",
    "segs": "o=oe.l.d",
    "unit": "EC4",
    "tags": [
      "new",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "loaf",
    "segs": "l.oa.f",
    "unit": "EC4",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oa"
    ]
  },
  {
    "text": "joke",
    "segs": "j.o=oe.ke=k",
    "unit": "EC4",
    "tags": [
      "new",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "hold",
    "segs": "h.o=oe.l.d",
    "unit": "EC4",
    "tags": [
      "new",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "rope",
    "segs": "r.o=oe.pe=p",
    "unit": "EC4",
    "tags": [
      "new",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "oat",
    "segs": "oa.t",
    "unit": "EC4",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oa"
    ]
  },
  {
    "text": "post",
    "segs": "p.o=oe.s.t",
    "unit": "EC4",
    "tags": [
      "new",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "most",
    "segs": "m.o=oe.s.t",
    "unit": "EC4",
    "tags": [
      "new",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "moan",
    "segs": "m.oa.n",
    "unit": "EC4",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oa"
    ]
  },
  {
    "text": "foam",
    "segs": "f.oa.m",
    "unit": "EC4",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oa"
    ]
  },
  {
    "text": "goal",
    "segs": "g.oa.l",
    "unit": "EC4",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oa"
    ]
  },
  {
    "text": "groan",
    "segs": "g.r.oa.n",
    "unit": "EC4",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oa"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC2"
  },
  {
    "text": "The jar is on the cart.",
    "maxUnit": "EC2"
  },
  {
    "text": "The star is over the barn.",
    "maxUnit": "EC2"
  },
  {
    "text": "The car is by the farm.",
    "maxUnit": "EC2"
  },
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC2"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC2"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC2"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC2"
  }
] as const;

export const chains = [
  [
    "toe",
    "tea",
    "sea",
    "seat",
    "eat"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "sunset",
    "syllables": "sun|set"
  },
  {
    "text": "zigzag",
    "syllables": "zig|zag"
  },
  {
    "text": "sunlit",
    "syllables": "sun|lit"
  },
  {
    "text": "wigwam",
    "syllables": "wig|wam"
  },
  {
    "text": "cobweb",
    "syllables": "cob|web"
  },
  {
    "text": "nutmeg",
    "syllables": "nut|meg"
  },
  {
    "text": "bedbug",
    "syllables": "bed|bug"
  },
  {
    "text": "hotdog",
    "syllables": "hot|dog"
  },
  {
    "text": "kidnap",
    "syllables": "kid|nap"
  },
  {
    "text": "pigpen",
    "syllables": "pig|pen"
  }
] as const;
