// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "puff",
    "segs": "p.u.ff",
    "unit": "EC40",
    "tags": [
      "review",
      "sort:ff",
      "dictation-safe"
    ]
  },
  {
    "text": "off",
    "segs": "o.ff",
    "unit": "EC40",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ff"
    ]
  },
  {
    "text": "sniff",
    "segs": "s.n.i.ff",
    "unit": "EC40",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ff"
    ]
  },
  {
    "text": "stuff",
    "segs": "s.t.u.ff",
    "unit": "EC40",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ff"
    ]
  },
  {
    "text": "huff",
    "segs": "h.u.ff",
    "unit": "EC40",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ff"
    ]
  },
  {
    "text": "stiff",
    "segs": "s.t.i.ff",
    "unit": "EC40",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ff"
    ]
  },
  {
    "text": "fish",
    "segs": "f.i.sh",
    "unit": "EC40",
    "pic": "an orange goldfish swimming side-on, one big round friendly eye, a small smile, flowing tail fins",
    "tags": [
      "review",
      "picture",
      "sort:f"
    ]
  },
  {
    "text": "feet",
    "segs": "f.ee.t",
    "unit": "EC40",
    "pic": "a pair of bare cartoon feet side by side with wiggly toes",
    "tags": [
      "review",
      "picture",
      "sort:f"
    ]
  },
  {
    "text": "frog",
    "segs": "f.r.o.g",
    "unit": "EC40",
    "pic": "a green frog sitting and facing the viewer, big round eyes with shiny black pupils, a wide smile",
    "tags": [
      "review",
      "picture",
      "sort:f"
    ]
  },
  {
    "text": "leaf",
    "segs": "l.ea.f",
    "unit": "EC40",
    "pic": "a leaf",
    "tags": [
      "review",
      "picture",
      "sort:f"
    ]
  },
  {
    "text": "flag",
    "segs": "f.l.a.g",
    "unit": "EC40",
    "pic": "a flag",
    "tags": [
      "review",
      "picture",
      "sort:f"
    ]
  },
  {
    "text": "elf",
    "segs": "e.l.f",
    "unit": "EC40",
    "pic": "an elf",
    "tags": [
      "review",
      "picture",
      "sort:f"
    ]
  },
  {
    "text": "fox",
    "segs": "f.o.x",
    "unit": "EC40",
    "pic": "an orange fox sitting and facing the viewer with a friendly face: two big shiny eyes, a little black nose and a smile, white cheeks and chest, black-tipped ears, a bushy white-tipped tail",
    "tags": [
      "review",
      "picture",
      "sort:f"
    ]
  },
  {
    "text": "fan",
    "segs": "f.a.n",
    "unit": "EC40",
    "pic": "an electric fan",
    "tags": [
      "review",
      "picture",
      "sort:f"
    ]
  },
  {
    "text": "fix",
    "segs": "f.i.x",
    "unit": "EC40",
    "tags": [
      "review",
      "sort:f",
      "dictation-safe"
    ]
  },
  {
    "text": "frost",
    "segs": "f.r.o.s.t",
    "unit": "EC40",
    "tags": [
      "review",
      "sort:f",
      "dictation-safe"
    ]
  },
  {
    "text": "fog",
    "segs": "f.o.g",
    "unit": "EC40",
    "tags": [
      "review",
      "sort:f",
      "dictation-safe"
    ]
  },
  {
    "text": "fin",
    "segs": "f.i.n",
    "unit": "EC40",
    "tags": [
      "review",
      "sort:f",
      "dictation-safe"
    ]
  },
  {
    "text": "gift",
    "segs": "g.i.f.t",
    "unit": "EC40",
    "tags": [
      "review",
      "dictation-safe",
      "sort:f"
    ]
  },
  {
    "text": "fun",
    "segs": "f.u.n",
    "unit": "EC40",
    "tags": [
      "review",
      "dictation-safe",
      "sort:f"
    ]
  },
  {
    "text": "soft",
    "segs": "s.o.f.t",
    "unit": "EC40",
    "tags": [
      "review",
      "dictation-safe",
      "sort:f"
    ]
  },
  {
    "text": "fist",
    "segs": "f.i.s.t",
    "unit": "EC40",
    "tags": [
      "review",
      "dictation-safe",
      "sort:f"
    ]
  },
  {
    "text": "from",
    "segs": "f.r.o.m",
    "unit": "EC40",
    "tags": [
      "review",
      "dictation-safe",
      "sort:f"
    ]
  },
  {
    "text": "left",
    "segs": "l.e.f.t",
    "unit": "EC40",
    "tags": [
      "review",
      "dictation-safe",
      "sort:f"
    ]
  },
  {
    "text": "lift",
    "segs": "l.i.f.t",
    "unit": "EC40",
    "tags": [
      "review",
      "dictation-safe",
      "sort:f"
    ]
  },
  {
    "text": "fetch",
    "segs": "f.e.tch",
    "unit": "EC40",
    "tags": [
      "review",
      "dictation-safe",
      "sort:f"
    ]
  },
  {
    "text": "flat",
    "segs": "f.l.a.t",
    "unit": "EC40",
    "tags": [
      "review",
      "dictation-safe",
      "sort:f"
    ]
  },
  {
    "text": "fed",
    "segs": "f.e.d",
    "unit": "EC40",
    "tags": [
      "review",
      "dictation-safe",
      "sort:f"
    ]
  },
  {
    "text": "fuss",
    "segs": "f.u.ss",
    "unit": "EC40",
    "tags": [
      "review",
      "dictation-safe",
      "sort:f"
    ]
  },
  {
    "text": "flop",
    "segs": "f.l.o.p",
    "unit": "EC40",
    "tags": [
      "review",
      "dictation-safe",
      "sort:f"
    ]
  },
  {
    "text": "flip",
    "segs": "f.l.i.p",
    "unit": "EC40",
    "tags": [
      "review",
      "dictation-safe",
      "sort:f"
    ]
  },
  {
    "text": "fizz",
    "segs": "f.i.zz",
    "unit": "EC40",
    "tags": [
      "review",
      "dictation-safe",
      "sort:f"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC38"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC38"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC38"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC38"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC38"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC38"
  },
  {
    "text": "The bear sat on the chair.",
    "maxUnit": "EC38"
  },
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC38"
  }
] as const;

export const chains = [
  [
    "puff",
    "huff",
    "hug",
    "hut",
    "hunt"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "routine",
    "syllables": "rou|tine"
  },
  {
    "text": "kneecap",
    "syllables": "knee|cap"
  },
  {
    "text": "notebook",
    "syllables": "note|book"
  },
  {
    "text": "season",
    "syllables": "sea|son",
    "schwa": [
      1
    ]
  },
  {
    "text": "piano",
    "syllables": "pi|a|no",
    "schwa": [
      1
    ]
  },
  {
    "text": "savvy",
    "syllables": "sa|vvy",
    "schwa": [
      1
    ]
  },
  {
    "text": "skivvy",
    "syllables": "ski|vvy",
    "schwa": [
      1
    ]
  },
  {
    "text": "evening",
    "syllables": "e|ve|ning",
    "schwa": [
      0
    ]
  },
  {
    "text": "litre",
    "syllables": "li|tre",
    "schwa": [
      1
    ]
  },
  {
    "text": "solar",
    "syllables": "so|lar",
    "schwa": [
      1
    ]
  }
] as const;
