// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "jammed",
    "segs": "j.a.mm=m.ed=d",
    "unit": "EC42",
    "tags": [
      "new",
      "dictation-safe",
      "sort:mm"
    ]
  },
  {
    "text": "lamb",
    "segs": "l.a.mb=m",
    "unit": "EC42",
    "pic": "one young white lamb standing alone, full body",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:mb"
    ]
  },
  {
    "text": "thumb",
    "segs": "th.u.mb=m",
    "unit": "EC42",
    "pic": "one hand showing its thumb upright, close up",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:mb"
    ]
  },
  {
    "text": "crumb",
    "segs": "c.r.u.mb=m",
    "unit": "EC42",
    "tags": [
      "new",
      "dictation-safe",
      "sort:mb"
    ]
  },
  {
    "text": "limb",
    "segs": "l.i.mb=m",
    "unit": "EC42",
    "tags": [
      "new",
      "dictation-safe",
      "sort:mb"
    ]
  },
  {
    "text": "numb",
    "segs": "n.u.mb=m",
    "unit": "EC42",
    "tags": [
      "new",
      "dictation-safe",
      "sort:mb"
    ]
  },
  {
    "text": "jump",
    "segs": "j.u.m.p",
    "unit": "EC42",
    "tags": [
      "review",
      "sort:m",
      "dictation-safe"
    ]
  },
  {
    "text": "milk",
    "segs": "m.i.l.k",
    "unit": "EC42",
    "pic": "a glass of milk",
    "tags": [
      "review",
      "picture",
      "sort:m"
    ]
  },
  {
    "text": "man",
    "segs": "m.a.n",
    "unit": "EC42",
    "pic": "a grown-up man with a friendly face (two eyes and a big smile), short brown hair, a green jumper and blue jeans, whole from head to toe, facing the viewer and waving",
    "tags": [
      "review",
      "picture",
      "sort:m"
    ]
  },
  {
    "text": "drum",
    "segs": "d.r.u.m",
    "unit": "EC42",
    "pic": "a drum",
    "tags": [
      "review",
      "picture",
      "sort:m"
    ]
  },
  {
    "text": "lamp",
    "segs": "l.a.m.p",
    "unit": "EC42",
    "pic": "a lamp",
    "tags": [
      "review",
      "picture",
      "sort:m"
    ]
  },
  {
    "text": "swim",
    "segs": "s.w.i.m",
    "unit": "EC42",
    "pic": "a child actively swimming across a little patch of bright blue water, side view with face above the water and one arm reaching forward in a swimming stroke, small splashes around them",
    "tags": [
      "review",
      "picture",
      "sort:m"
    ]
  },
  {
    "text": "plum",
    "segs": "p.l.u.m",
    "unit": "EC42",
    "pic": "a plum",
    "tags": [
      "review",
      "picture",
      "sort:m"
    ]
  },
  {
    "text": "mess",
    "segs": "m.e.ss",
    "unit": "EC42",
    "tags": [
      "review",
      "sort:m",
      "dictation-safe"
    ]
  },
  {
    "text": "mop",
    "segs": "m.o.p",
    "unit": "EC42",
    "pic": "a floor mop",
    "tags": [
      "review",
      "picture",
      "sort:m"
    ]
  },
  {
    "text": "mug",
    "segs": "m.u.g",
    "unit": "EC42",
    "pic": "a mug",
    "tags": [
      "review",
      "picture",
      "sort:m"
    ]
  },
  {
    "text": "jam",
    "segs": "j.a.m",
    "unit": "EC42",
    "pic": "a jar of jam",
    "tags": [
      "review",
      "picture",
      "sort:m"
    ]
  },
  {
    "text": "pram",
    "segs": "p.r.a.m",
    "unit": "EC42",
    "pic": "a pram",
    "tags": [
      "review",
      "picture",
      "sort:m"
    ]
  },
  {
    "text": "mat",
    "segs": "m.a.t",
    "unit": "EC42",
    "pic": "a rectangular striped mat with a short fringe at both ends, lying flat, seen from slightly above",
    "tags": [
      "review",
      "picture",
      "sort:m"
    ]
  },
  {
    "text": "stamp",
    "segs": "s.t.a.m.p",
    "unit": "EC42",
    "pic": "one postage stamp with a scalloped edge and a simple flower picture, no letters or numbers",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:m"
    ]
  },
  {
    "text": "stump",
    "segs": "s.t.u.m.p",
    "unit": "EC42",
    "pic": "a tree stump",
    "tags": [
      "review",
      "picture",
      "sort:m"
    ]
  },
  {
    "text": "map",
    "segs": "m.a.p",
    "unit": "EC42",
    "pic": "a treasure map",
    "tags": [
      "review",
      "picture",
      "sort:m"
    ]
  },
  {
    "text": "match",
    "segs": "m.a.tch",
    "unit": "EC42",
    "pic": "a match stick",
    "tags": [
      "review",
      "picture",
      "sort:m"
    ]
  },
  {
    "text": "mum",
    "segs": "m.u.m",
    "unit": "EC42",
    "tags": [
      "review",
      "dictation-safe"
    ]
  },
  {
    "text": "them",
    "segs": "th=dh.e.m",
    "unit": "EC42",
    "tags": [
      "review",
      "dictation-safe",
      "sort:m"
    ]
  },
  {
    "text": "yum",
    "segs": "y.u.m",
    "unit": "EC42",
    "tags": [
      "review",
      "dictation-safe",
      "sort:m"
    ]
  },
  {
    "text": "smell",
    "segs": "s.m.e.ll",
    "unit": "EC42",
    "tags": [
      "review",
      "dictation-safe",
      "sort:m"
    ]
  },
  {
    "text": "much",
    "segs": "m.u.ch",
    "unit": "EC42",
    "tags": [
      "review",
      "dictation-safe",
      "sort:m"
    ]
  },
  {
    "text": "him",
    "segs": "h.i.m",
    "unit": "EC42",
    "tags": [
      "review",
      "dictation-safe",
      "sort:m"
    ]
  },
  {
    "text": "am",
    "segs": "a.m",
    "unit": "EC42",
    "tags": [
      "review",
      "dictation-safe",
      "sort:m"
    ]
  },
  {
    "text": "bump",
    "segs": "b.u.m.p",
    "unit": "EC42",
    "tags": [
      "review",
      "dictation-safe",
      "sort:m"
    ]
  },
  {
    "text": "from",
    "segs": "f.r.o.m",
    "unit": "EC42",
    "tags": [
      "review",
      "dictation-safe",
      "sort:m"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC40"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC40"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC40"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC40"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC40"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC40"
  },
  {
    "text": "The bear sat on the chair.",
    "maxUnit": "EC40"
  },
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC40"
  }
] as const;

export const chains = [
  [
    "lamb",
    "limb",
    "lid",
    "kid",
    "kind"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "olive",
    "syllables": "o|live",
    "schwa": [
      0
    ]
  },
  {
    "text": "routine",
    "syllables": "rou|tine"
  },
  {
    "text": "kneecap",
    "syllables": "knee|cap"
  },
  {
    "text": "notebook",
    "syllables": "note|book"
  },
  {
    "text": "season",
    "syllables": "sea|son",
    "schwa": [
      1
    ]
  },
  {
    "text": "piano",
    "syllables": "pi|a|no",
    "schwa": [
      1
    ]
  },
  {
    "text": "lemon",
    "syllables": "le|mon",
    "schwa": [
      1
    ]
  },
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "skivvy",
    "syllables": "ski|vvy",
    "schwa": [
      1
    ]
  },
  {
    "text": "evening",
    "syllables": "e|ve|ning",
    "schwa": [
      0
    ]
  }
] as const;
