// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "sauce",
    "segs": "s.au=or.ce=s",
    "unit": "EC43",
    "tags": [
      "review",
      "dictation-safe",
      "sort:au"
    ]
  },
  {
    "text": "door",
    "segs": "d.oor=or",
    "unit": "EC43",
    "tags": [
      "review",
      "dictation-safe",
      "sort:oor"
    ]
  },
  {
    "text": "caught",
    "segs": "c.augh=or.t",
    "unit": "EC43",
    "tags": [
      "new",
      "dictation-safe",
      "sort:augh"
    ]
  },
  {
    "text": "taught",
    "segs": "t.augh=or.t",
    "unit": "EC43",
    "tags": [
      "new",
      "dictation-safe",
      "sort:augh"
    ]
  },
  {
    "text": "lawn",
    "segs": "l.aw=or.n",
    "unit": "EC43",
    "tags": [
      "review",
      "sort:aw",
      "dictation-safe"
    ]
  },
  {
    "text": "dawn",
    "segs": "d.aw=or.n",
    "unit": "EC43",
    "tags": [
      "review",
      "dictation-safe",
      "sort:aw"
    ]
  },
  {
    "text": "crawl",
    "segs": "c.r.aw=or.l",
    "unit": "EC43",
    "tags": [
      "review",
      "dictation-safe",
      "sort:aw"
    ]
  },
  {
    "text": "four",
    "segs": "f.our=or",
    "unit": "EC43",
    "tags": [
      "new",
      "dictation-safe",
      "sort:our"
    ]
  },
  {
    "text": "pour",
    "segs": "p.our=or",
    "unit": "EC43",
    "tags": [
      "new",
      "reading-only",
      "sort:our"
    ]
  },
  {
    "text": "fourth",
    "segs": "f.our=or.th",
    "unit": "EC43",
    "tags": [
      "new",
      "dictation-safe",
      "sort:our"
    ]
  },
  {
    "text": "bought",
    "segs": "b.ough=or.t",
    "unit": "EC43",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ough"
    ]
  },
  {
    "text": "brought",
    "segs": "b.r.ough=or.t",
    "unit": "EC43",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ough"
    ]
  },
  {
    "text": "nought",
    "segs": "n.ough=or.t",
    "unit": "EC43",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ough"
    ]
  },
  {
    "text": "roar",
    "segs": "r.oar=or",
    "unit": "EC43",
    "tags": [
      "new",
      "sort:oar",
      "dictation-safe"
    ]
  },
  {
    "text": "board",
    "segs": "b.oar=or.d",
    "unit": "EC43",
    "pic": "one plain wooden board lying alone",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:oar"
    ]
  },
  {
    "text": "boar",
    "segs": "b.oar=or",
    "unit": "EC43",
    "pic": "one brown wild boar standing alone, full body",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:oar"
    ]
  },
  {
    "text": "oar",
    "segs": "oar=or",
    "unit": "EC43",
    "tags": [
      "new",
      "dictation-safe",
      "sort:oar"
    ]
  },
  {
    "text": "shore",
    "segs": "sh.ore=or",
    "unit": "EC43",
    "tags": [
      "new",
      "sort:ore",
      "dictation-safe"
    ]
  },
  {
    "text": "more",
    "segs": "m.ore=or",
    "unit": "EC43",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ore"
    ]
  },
  {
    "text": "sore",
    "segs": "s.ore=or",
    "unit": "EC43",
    "tags": [
      "new",
      "reading-only",
      "sort:ore"
    ]
  },
  {
    "text": "snore",
    "segs": "s.n.ore=or",
    "unit": "EC43",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ore"
    ]
  },
  {
    "text": "wore",
    "segs": "w.ore=or",
    "unit": "EC43",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ore"
    ]
  },
  {
    "text": "tore",
    "segs": "t.ore=or",
    "unit": "EC43",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ore"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC41"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC41"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC41"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC41"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC41"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC41"
  },
  {
    "text": "The bear sat on the chair.",
    "maxUnit": "EC41"
  },
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC41"
  }
] as const;

export const chains = [
  [
    "door",
    "dare",
    "bare",
    "boar",
    "board"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "shampoo",
    "syllables": "sham|poo"
  },
  {
    "text": "together",
    "syllables": "to|geth|er",
    "schwa": [
      0,
      2
    ]
  },
  {
    "text": "olive",
    "syllables": "o|live",
    "schwa": [
      0
    ]
  },
  {
    "text": "routine",
    "syllables": "rou|tine"
  },
  {
    "text": "kneecap",
    "syllables": "knee|cap"
  },
  {
    "text": "notebook",
    "syllables": "note|book"
  },
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "seven",
    "syllables": "se|ven",
    "schwa": [
      1
    ]
  },
  {
    "text": "sunset",
    "syllables": "sun|set"
  },
  {
    "text": "zigzag",
    "syllables": "zig|zag"
  }
] as const;
