// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "hand",
    "segs": "h.a.n.d",
    "unit": "EC44",
    "pic": "one open cartoon hand waving hello, palm facing the viewer, five fingers spread",
    "tags": [
      "review",
      "picture",
      "sort:h"
    ]
  },
  {
    "text": "hug",
    "segs": "h.u.g",
    "unit": "EC44",
    "pic": "two children facing each other in one clear hug, both full bodies visible",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:h"
    ]
  },
  {
    "text": "hat",
    "segs": "h.a.t",
    "unit": "EC44",
    "pic": "a red woolly bobble hat with a big white bobble on top",
    "tags": [
      "review",
      "picture",
      "sort:h"
    ]
  },
  {
    "text": "hill",
    "segs": "h.i.ll",
    "unit": "EC44",
    "pic": "one smooth green grassy hill rising above a flat plain, no food or buildings",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:h"
    ]
  },
  {
    "text": "hen",
    "segs": "h.e.n",
    "unit": "EC44",
    "tags": [
      "review",
      "sort:h",
      "dictation-safe"
    ]
  },
  {
    "text": "hut",
    "segs": "h.u.t",
    "unit": "EC44",
    "pic": "a tiny rustic round thatched hut with a simple wooden door and no windows, made of straw and timber, clearly a one-room shelter",
    "tags": [
      "review",
      "picture",
      "sort:h"
    ]
  },
  {
    "text": "hutch",
    "segs": "h.u.tch",
    "unit": "EC44",
    "pic": "a rabbit hutch",
    "tags": [
      "review",
      "picture",
      "sort:h"
    ]
  },
  {
    "text": "have",
    "segs": "h.a.ve",
    "unit": "EC44",
    "tags": [
      "review",
      "dictation-safe",
      "sort:h"
    ]
  },
  {
    "text": "help",
    "segs": "h.e.l.p",
    "unit": "EC44",
    "tags": [
      "review",
      "dictation-safe",
      "sort:h"
    ]
  },
  {
    "text": "high",
    "segs": "h.igh",
    "unit": "EC44",
    "tags": [
      "review",
      "dictation-safe",
      "sort:h"
    ]
  },
  {
    "text": "hang",
    "segs": "h.a.ng",
    "unit": "EC44",
    "tags": [
      "review",
      "dictation-safe",
      "sort:h"
    ]
  },
  {
    "text": "hot",
    "segs": "h.o.t",
    "unit": "EC44",
    "tags": [
      "review",
      "dictation-safe",
      "sort:h"
    ]
  },
  {
    "text": "hunt",
    "segs": "h.u.n.t",
    "unit": "EC44",
    "tags": [
      "review",
      "dictation-safe",
      "sort:h"
    ]
  },
  {
    "text": "him",
    "segs": "h.i.m",
    "unit": "EC44",
    "tags": [
      "review",
      "dictation-safe",
      "sort:h"
    ]
  },
  {
    "text": "hop",
    "segs": "h.o.p",
    "unit": "EC44",
    "tags": [
      "review",
      "dictation-safe",
      "sort:h"
    ]
  },
  {
    "text": "hiss",
    "segs": "h.i.ss",
    "unit": "EC44",
    "tags": [
      "review",
      "dictation-safe",
      "sort:h"
    ]
  },
  {
    "text": "huff",
    "segs": "h.u.ff",
    "unit": "EC44",
    "tags": [
      "review",
      "dictation-safe",
      "sort:h"
    ]
  },
  {
    "text": "hip",
    "segs": "h.i.p",
    "unit": "EC44",
    "tags": [
      "review",
      "dictation-safe",
      "sort:h"
    ]
  },
  {
    "text": "her",
    "segs": "h.er=er",
    "unit": "EC44",
    "tags": [
      "review",
      "dictation-safe",
      "sort:h"
    ]
  },
  {
    "text": "his",
    "segs": "h.i.s=z",
    "unit": "EC44",
    "tags": [
      "review",
      "dictation-safe",
      "sort:h"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC42"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC42"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC42"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC42"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC42"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC42"
  },
  {
    "text": "The bear sat on the chair.",
    "maxUnit": "EC42"
  },
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC42"
  }
] as const;

export const chains = [
  [
    "hand",
    "and",
    "an",
    "add",
    "all"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "shampoo",
    "syllables": "sham|poo"
  },
  {
    "text": "together",
    "syllables": "to|geth|er",
    "schwa": [
      0,
      2
    ]
  },
  {
    "text": "olive",
    "syllables": "o|live",
    "schwa": [
      0
    ]
  },
  {
    "text": "routine",
    "syllables": "rou|tine"
  },
  {
    "text": "kneecap",
    "syllables": "knee|cap"
  },
  {
    "text": "lemon",
    "syllables": "le|mon",
    "schwa": [
      1
    ]
  },
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "cobweb",
    "syllables": "cob|web"
  },
  {
    "text": "nutmeg",
    "syllables": "nut|meg"
  },
  {
    "text": "bedbug",
    "syllables": "bed|bug"
  }
] as const;
