// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "school",
    "segs": "s.ch=k.oo.l",
    "unit": "EC45",
    "pic": "one small primary school building with playground, no writing",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ch"
    ]
  },
  {
    "text": "milk",
    "segs": "m.i.l.k",
    "unit": "EC45",
    "pic": "a glass of milk",
    "tags": [
      "review",
      "picture",
      "sort:k"
    ]
  },
  {
    "text": "kiss",
    "segs": "k.i.ss",
    "unit": "EC45",
    "tags": [
      "review",
      "sort:k",
      "dictation-safe"
    ]
  },
  {
    "text": "king",
    "segs": "k.i.ng",
    "unit": "EC45",
    "pic": "a friendly grown-up king wearing a golden crown and a long red royal robe, with his face, full body and hands visible, waving",
    "tags": [
      "review",
      "picture",
      "sort:k"
    ]
  },
  {
    "text": "desk",
    "segs": "d.e.s.k",
    "unit": "EC45",
    "pic": "one wooden writing desk with a wide flat top, a single drawer and an empty chair pushed under it, no writing",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:k"
    ]
  },
  {
    "text": "whisk",
    "segs": "wh.i.s.k",
    "unit": "EC45",
    "pic": "a whisk",
    "tags": [
      "review",
      "picture",
      "sort:k"
    ]
  },
  {
    "text": "kid",
    "segs": "k.i.d",
    "unit": "EC45",
    "tags": [
      "review",
      "dictation-safe",
      "sort:k"
    ]
  },
  {
    "text": "skip",
    "segs": "s.k.i.p",
    "unit": "EC45",
    "tags": [
      "review",
      "dictation-safe",
      "sort:k"
    ]
  },
  {
    "text": "kit",
    "segs": "k.i.t",
    "unit": "EC45",
    "tags": [
      "review",
      "dictation-safe",
      "sort:k"
    ]
  },
  {
    "text": "duck",
    "segs": "d.u.ck",
    "unit": "EC45",
    "pic": "a white farm duck standing side-on with a friendly face: one big round shiny black eye clearly drawn on its head, an orange beak with a little smile, and orange feet",
    "tags": [
      "review",
      "picture",
      "sort:ck"
    ]
  },
  {
    "text": "rock",
    "segs": "r.o.ck",
    "unit": "EC45",
    "pic": "a rock",
    "tags": [
      "review",
      "picture",
      "sort:ck"
    ]
  },
  {
    "text": "chick",
    "segs": "ch.i.ck",
    "unit": "EC45",
    "pic": "a chick",
    "tags": [
      "review",
      "picture",
      "sort:ck"
    ]
  },
  {
    "text": "lock",
    "segs": "l.o.ck",
    "unit": "EC45",
    "pic": "a padlock",
    "tags": [
      "review",
      "picture",
      "sort:ck"
    ]
  },
  {
    "text": "sock",
    "segs": "s.o.ck",
    "unit": "EC45",
    "pic": "a sock",
    "tags": [
      "review",
      "picture",
      "sort:ck"
    ]
  },
  {
    "text": "black",
    "segs": "b.l.a.ck",
    "unit": "EC45",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ck"
    ]
  },
  {
    "text": "back",
    "segs": "b.a.ck",
    "unit": "EC45",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ck"
    ]
  },
  {
    "text": "neck",
    "segs": "n.e.ck",
    "unit": "EC45",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ck"
    ]
  },
  {
    "text": "coat",
    "segs": "c.oa.t",
    "unit": "EC45",
    "pic": "a coat",
    "tags": [
      "review",
      "picture",
      "sort:c"
    ]
  },
  {
    "text": "cat",
    "segs": "c.a.t",
    "unit": "EC45",
    "pic": "a cat",
    "tags": [
      "review",
      "picture",
      "sort:c"
    ]
  },
  {
    "text": "cup",
    "segs": "c.u.p",
    "unit": "EC45",
    "pic": "a small shallow porcelain teacup with a delicate curved handle, wide open rim, sitting on a matching saucer, empty inside",
    "tags": [
      "review",
      "picture",
      "sort:c"
    ]
  },
  {
    "text": "crab",
    "segs": "c.r.a.b",
    "unit": "EC45",
    "pic": "a crab",
    "tags": [
      "review",
      "picture",
      "sort:c"
    ]
  },
  {
    "text": "crisp",
    "segs": "c.r.i.s.p",
    "unit": "EC45",
    "pic": "one very thin golden potato crisp with a wavy curled edge and a few darker toasted patches, shown tilted so its thinness is obvious, no whole potato",
    "tags": [
      "review",
      "picture",
      "sort:c"
    ]
  },
  {
    "text": "cap",
    "segs": "c.a.p",
    "unit": "EC45",
    "pic": "a baseball cap",
    "tags": [
      "review",
      "picture",
      "sort:c"
    ]
  },
  {
    "text": "crow",
    "segs": "c.r.ow",
    "unit": "EC45",
    "pic": "one black crow standing alone",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:c"
    ]
  },
  {
    "text": "cot",
    "segs": "c.o.t",
    "unit": "EC45",
    "pic": "a baby's cot",
    "tags": [
      "review",
      "picture",
      "sort:c"
    ]
  },
  {
    "text": "clock",
    "segs": "c.l.o.ck",
    "unit": "EC45",
    "pic": "a clock",
    "tags": [
      "review",
      "picture"
    ]
  },
  {
    "text": "crust",
    "segs": "c.r.u.s.t",
    "unit": "EC45",
    "tags": [
      "review",
      "sort:c",
      "dictation-safe"
    ]
  },
  {
    "text": "cub",
    "segs": "c.u.b",
    "unit": "EC45",
    "tags": [
      "review",
      "sort:c",
      "dictation-safe"
    ]
  },
  {
    "text": "scrub",
    "segs": "s.c.r.u.b",
    "unit": "EC45",
    "tags": [
      "review",
      "sort:c",
      "dictation-safe"
    ]
  },
  {
    "text": "scrap",
    "segs": "s.c.r.a.p",
    "unit": "EC45",
    "tags": [
      "review",
      "sort:c",
      "dictation-safe"
    ]
  },
  {
    "text": "clap",
    "segs": "c.l.a.p",
    "unit": "EC45",
    "tags": [
      "review",
      "dictation-safe",
      "sort:c"
    ]
  },
  {
    "text": "kick",
    "segs": "k.i.ck",
    "unit": "EC45",
    "tags": [
      "review",
      "dictation-safe"
    ]
  },
  {
    "text": "cut",
    "segs": "c.u.t",
    "unit": "EC45",
    "tags": [
      "review",
      "dictation-safe",
      "sort:c"
    ]
  },
  {
    "text": "snack",
    "segs": "s.n.a.ck",
    "unit": "EC45",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ck"
    ]
  },
  {
    "text": "catch",
    "segs": "c.a.tch",
    "unit": "EC45",
    "tags": [
      "review",
      "dictation-safe",
      "sort:c"
    ]
  },
  {
    "text": "quack",
    "segs": "q.u=w.a.ck",
    "unit": "EC45",
    "tags": [
      "review",
      "dictation-safe"
    ]
  },
  {
    "text": "pick",
    "segs": "p.i.ck",
    "unit": "EC45",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ck"
    ]
  },
  {
    "text": "can",
    "segs": "c.a.n",
    "unit": "EC45",
    "tags": [
      "review",
      "dictation-safe",
      "sort:c"
    ]
  },
  {
    "text": "stuck",
    "segs": "s.t.u.ck",
    "unit": "EC45",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ck"
    ]
  },
  {
    "text": "thick",
    "segs": "th.i.ck",
    "unit": "EC45",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ck"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC43"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC43"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC43"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC43"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC43"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC43"
  },
  {
    "text": "The bear sat on the chair.",
    "maxUnit": "EC43"
  },
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC43"
  }
] as const;

export const chains = [
  [
    "school",
    "stool",
    "tool",
    "cool",
    "coal"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "coffee",
    "syllables": "co|ffee",
    "schwa": [
      1
    ]
  },
  {
    "text": "shampoo",
    "syllables": "sham|poo"
  },
  {
    "text": "together",
    "syllables": "to|geth|er",
    "schwa": [
      0,
      2
    ]
  },
  {
    "text": "olive",
    "syllables": "o|live",
    "schwa": [
      0
    ]
  },
  {
    "text": "routine",
    "syllables": "rou|tine"
  },
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "seven",
    "syllables": "se|ven",
    "schwa": [
      1
    ]
  },
  {
    "text": "dogleg",
    "syllables": "dog|leg"
  },
  {
    "text": "admit",
    "syllables": "ad|mit"
  },
  {
    "text": "upset",
    "syllables": "up|set"
  }
] as const;
