// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "wrist",
    "segs": "wr=r.i.s.t",
    "unit": "EC46",
    "tags": [
      "new",
      "sort:wr",
      "dictation-safe"
    ]
  },
  {
    "text": "wrong",
    "segs": "wr=r.o.ng",
    "unit": "EC46",
    "tags": [
      "new",
      "dictation-safe",
      "sort:wr"
    ]
  },
  {
    "text": "wrap",
    "segs": "wr=r.a.p",
    "unit": "EC46",
    "tags": [
      "new",
      "dictation-safe",
      "sort:wr"
    ]
  },
  {
    "text": "tree",
    "segs": "t.r.ee",
    "unit": "EC46",
    "pic": "a tree",
    "tags": [
      "review",
      "picture",
      "sort:r"
    ]
  },
  {
    "text": "rain",
    "segs": "r.ai.n",
    "unit": "EC46",
    "pic": "heavy raindrops falling from one grey cloud",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:r"
    ]
  },
  {
    "text": "rock",
    "segs": "r.o.ck",
    "unit": "EC46",
    "pic": "a rock",
    "tags": [
      "review",
      "picture",
      "sort:r"
    ]
  },
  {
    "text": "run",
    "segs": "r.u.n",
    "unit": "EC46",
    "pic": "a child running",
    "tags": [
      "review",
      "picture",
      "sort:r"
    ]
  },
  {
    "text": "frog",
    "segs": "f.r.o.g",
    "unit": "EC46",
    "pic": "a green frog sitting and facing the viewer, big round eyes with shiny black pupils, a wide smile",
    "tags": [
      "review",
      "picture",
      "sort:r"
    ]
  },
  {
    "text": "road",
    "segs": "r.oa.d",
    "unit": "EC46",
    "pic": "a road",
    "tags": [
      "review",
      "picture",
      "sort:r"
    ]
  },
  {
    "text": "train",
    "segs": "t.r.ai.n",
    "unit": "EC46",
    "pic": "a steam train",
    "tags": [
      "review",
      "picture",
      "sort:r"
    ]
  },
  {
    "text": "dress",
    "segs": "d.r.e.ss",
    "unit": "EC46",
    "pic": "one simple bright red child-sized dress on a plain hanger, clear fitted bodice and wide flared skirt, shown full length with no person",
    "tags": [
      "review",
      "picture",
      "sort:r"
    ]
  },
  {
    "text": "ring",
    "segs": "r.i.ng",
    "unit": "EC46",
    "pic": "a ring",
    "tags": [
      "review",
      "picture",
      "sort:r"
    ]
  },
  {
    "text": "drum",
    "segs": "d.r.u.m",
    "unit": "EC46",
    "pic": "a drum",
    "tags": [
      "review",
      "picture",
      "sort:r"
    ]
  },
  {
    "text": "rug",
    "segs": "r.u.g",
    "unit": "EC46",
    "pic": "a round colourful rug",
    "tags": [
      "review",
      "picture",
      "sort:r"
    ]
  },
  {
    "text": "tray",
    "segs": "t.r.ay",
    "unit": "EC46",
    "pic": "a tray",
    "tags": [
      "review",
      "picture",
      "sort:r"
    ]
  },
  {
    "text": "crab",
    "segs": "c.r.a.b",
    "unit": "EC46",
    "pic": "a crab",
    "tags": [
      "review",
      "picture",
      "sort:r"
    ]
  },
  {
    "text": "rat",
    "segs": "r.a.t",
    "unit": "EC46",
    "pic": "one large brown rat side-on, with a long pointed snout, visible front teeth, very small ears, coarse fur and a long thick bare pink tail curling behind it, no mouse",
    "tags": [
      "review",
      "picture",
      "sort:r"
    ]
  },
  {
    "text": "crisp",
    "segs": "c.r.i.s.p",
    "unit": "EC46",
    "pic": "one very thin golden potato crisp with a wavy curled edge and a few darker toasted patches, shown tilted so its thinness is obvious, no whole potato",
    "tags": [
      "review",
      "picture",
      "sort:r"
    ]
  },
  {
    "text": "crow",
    "segs": "c.r.ow",
    "unit": "EC46",
    "pic": "one black crow standing alone",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:r"
    ]
  },
  {
    "text": "pram",
    "segs": "p.r.a.m",
    "unit": "EC46",
    "pic": "a pram",
    "tags": [
      "review",
      "picture",
      "sort:r"
    ]
  },
  {
    "text": "strap",
    "segs": "s.t.r.a.p",
    "unit": "EC46",
    "tags": [
      "review",
      "sort:r",
      "dictation-safe"
    ]
  },
  {
    "text": "crust",
    "segs": "c.r.u.s.t",
    "unit": "EC46",
    "tags": [
      "review",
      "sort:r",
      "dictation-safe"
    ]
  },
  {
    "text": "frost",
    "segs": "f.r.o.s.t",
    "unit": "EC46",
    "tags": [
      "review",
      "sort:r",
      "dictation-safe"
    ]
  },
  {
    "text": "scrub",
    "segs": "s.c.r.u.b",
    "unit": "EC46",
    "tags": [
      "review",
      "sort:r",
      "dictation-safe"
    ]
  },
  {
    "text": "strip",
    "segs": "s.t.r.i.p",
    "unit": "EC46",
    "tags": [
      "review",
      "sort:r",
      "dictation-safe"
    ]
  },
  {
    "text": "rod",
    "segs": "r.o.d",
    "unit": "EC46",
    "pic": "a fishing rod",
    "tags": [
      "review",
      "picture",
      "sort:r"
    ]
  },
  {
    "text": "scrap",
    "segs": "s.c.r.a.p",
    "unit": "EC46",
    "tags": [
      "review",
      "sort:r",
      "dictation-safe"
    ]
  },
  {
    "text": "red",
    "segs": "r.e.d",
    "unit": "EC46",
    "tags": [
      "review",
      "dictation-safe",
      "sort:r"
    ]
  },
  {
    "text": "green",
    "segs": "g.r.ee.n",
    "unit": "EC46",
    "tags": [
      "review",
      "dictation-safe",
      "sort:r"
    ]
  },
  {
    "text": "grow",
    "segs": "g.r.ow",
    "unit": "EC46",
    "tags": [
      "review",
      "dictation-safe",
      "sort:r"
    ]
  },
  {
    "text": "strong",
    "segs": "s.t.r.o.ng",
    "unit": "EC46",
    "tags": [
      "review",
      "dictation-safe",
      "sort:r"
    ]
  },
  {
    "text": "grin",
    "segs": "g.r.i.n",
    "unit": "EC46",
    "tags": [
      "review",
      "dictation-safe",
      "sort:r"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC44"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC44"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC44"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC44"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC44"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC44"
  },
  {
    "text": "The bear sat on the chair.",
    "maxUnit": "EC44"
  },
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC44"
  }
] as const;

export const chains = [
  [
    "wrist",
    "fist",
    "fit",
    "bit",
    "bat"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "grateful",
    "syllables": "grate|ful",
    "schwa": [
      1
    ]
  },
  {
    "text": "coffee",
    "syllables": "co|ffee",
    "schwa": [
      1
    ]
  },
  {
    "text": "shampoo",
    "syllables": "sham|poo"
  },
  {
    "text": "together",
    "syllables": "to|geth|er",
    "schwa": [
      0,
      2
    ]
  },
  {
    "text": "olive",
    "syllables": "o|live",
    "schwa": [
      0
    ]
  },
  {
    "text": "routine",
    "syllables": "rou|tine"
  },
  {
    "text": "lemon",
    "syllables": "le|mon",
    "schwa": [
      1
    ]
  },
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "object",
    "syllables": "ob|ject"
  },
  {
    "text": "uplift",
    "syllables": "up|lift"
  }
] as const;
