// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "mitt",
    "segs": "m.i.tt=t",
    "unit": "EC47",
    "tags": [
      "new",
      "dictation-safe",
      "sort:tt"
    ]
  },
  {
    "text": "tree",
    "segs": "t.r.ee",
    "unit": "EC47",
    "pic": "a tree",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "coat",
    "segs": "c.oa.t",
    "unit": "EC47",
    "pic": "a coat",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "feet",
    "segs": "f.ee.t",
    "unit": "EC47",
    "pic": "a pair of bare cartoon feet side by side with wiggly toes",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "boat",
    "segs": "b.oa.t",
    "unit": "EC47",
    "pic": "a boat",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "cat",
    "segs": "c.a.t",
    "unit": "EC47",
    "pic": "a cat",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "train",
    "segs": "t.r.ai.n",
    "unit": "EC47",
    "pic": "a steam train",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "ant",
    "segs": "a.n.t",
    "unit": "EC47",
    "pic": "an ant",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "goat",
    "segs": "g.oa.t",
    "unit": "EC47",
    "pic": "a goat",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "hat",
    "segs": "h.a.t",
    "unit": "EC47",
    "pic": "a red woolly bobble hat with a big white bobble on top",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "light",
    "segs": "l.igh.t",
    "unit": "EC47",
    "pic": "a glowing lamp light bulb shining",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "sit",
    "segs": "s.i.t",
    "unit": "EC47",
    "pic": "one smiling little girl sitting down: curly brown hair, a friendly face with two eyes and a big smile, a yellow T-shirt and blue shorts, sitting on a small red chair that is mostly hidden under her, both feet on the floor, facing the viewer, the whole girl visible from head to toe",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "stand",
    "segs": "s.t.a.n.d",
    "unit": "EC47",
    "tags": [
      "review",
      "sort:t",
      "dictation-safe"
    ]
  },
  {
    "text": "tray",
    "segs": "t.r.ay",
    "unit": "EC47",
    "pic": "a tray",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "belt",
    "segs": "b.e.l.t",
    "unit": "EC47",
    "pic": "a belt",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "rat",
    "segs": "r.a.t",
    "unit": "EC47",
    "pic": "one large brown rat side-on, with a long pointed snout, visible front teeth, very small ears, coarse fur and a long thick bare pink tail curling behind it, no mouse",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "tub",
    "segs": "t.u.b",
    "unit": "EC47",
    "tags": [
      "review",
      "sort:t",
      "dictation-safe"
    ]
  },
  {
    "text": "pot",
    "segs": "p.o.t",
    "unit": "EC47",
    "pic": "a clay cooking pot",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "toast",
    "segs": "t.oa.s.t",
    "unit": "EC47",
    "pic": "toast",
    "tags": [
      "review",
      "picture"
    ]
  },
  {
    "text": "jet",
    "segs": "j.e.t",
    "unit": "EC47",
    "tags": [
      "review",
      "sort:t",
      "dictation-safe"
    ]
  },
  {
    "text": "tail",
    "segs": "t.ai.l",
    "unit": "EC47",
    "pic": "a fox tail",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "mat",
    "segs": "m.a.t",
    "unit": "EC47",
    "pic": "a rectangular striped mat with a short fringe at both ends, lying flat, seen from slightly above",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "top",
    "segs": "t.o.p",
    "unit": "EC47",
    "pic": "a spinning top toy",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "cot",
    "segs": "c.o.t",
    "unit": "EC47",
    "pic": "a baby's cot",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "tap",
    "segs": "t.a.p",
    "unit": "EC47",
    "pic": "a kitchen water tap",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "chest",
    "segs": "ch.e.s.t",
    "unit": "EC47",
    "pic": "a plain wooden storage chest with a curved lid and simple iron bands, closed, no treasure or coins or lock",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "tea",
    "segs": "t.ea",
    "unit": "EC47",
    "pic": "one cup of tea in a plain white cup",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:t"
    ]
  },
  {
    "text": "tin",
    "segs": "t.i.n",
    "unit": "EC47",
    "pic": "a tin can",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "strap",
    "segs": "s.t.r.a.p",
    "unit": "EC47",
    "tags": [
      "review",
      "sort:t",
      "dictation-safe"
    ]
  },
  {
    "text": "dot",
    "segs": "d.o.t",
    "unit": "EC47",
    "tags": [
      "review",
      "sort:t",
      "dictation-safe"
    ]
  },
  {
    "text": "quilt",
    "segs": "q.u=w.i.l.t",
    "unit": "EC47",
    "tags": [
      "review",
      "sort:t",
      "dictation-safe"
    ]
  },
  {
    "text": "tent",
    "segs": "t.e.n.t",
    "unit": "EC47",
    "pic": "a tent",
    "tags": [
      "review",
      "picture"
    ]
  },
  {
    "text": "vest",
    "segs": "v.e.s.t",
    "unit": "EC47",
    "pic": "a vest",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "crust",
    "segs": "c.r.u.s.t",
    "unit": "EC47",
    "tags": [
      "review",
      "sort:t",
      "dictation-safe"
    ]
  },
  {
    "text": "paint",
    "segs": "p.ai.n.t",
    "unit": "EC47",
    "pic": "a paint pot",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "stamp",
    "segs": "s.t.a.m.p",
    "unit": "EC47",
    "pic": "one postage stamp with a scalloped edge and a simple flower picture, no letters or numbers",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:t"
    ]
  },
  {
    "text": "twist",
    "segs": "t.w.i.s.t",
    "unit": "EC47",
    "tags": [
      "review",
      "dictation-safe"
    ]
  },
  {
    "text": "twig",
    "segs": "t.w.i.g",
    "unit": "EC47",
    "tags": [
      "review",
      "sort:t",
      "dictation-safe"
    ]
  },
  {
    "text": "bat",
    "segs": "b.a.t",
    "unit": "EC47",
    "pic": "a cute bat flying",
    "tags": [
      "review",
      "picture",
      "sort:t"
    ]
  },
  {
    "text": "frost",
    "segs": "f.r.o.s.t",
    "unit": "EC47",
    "tags": [
      "review",
      "sort:t",
      "dictation-safe"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The bear sat on the chair.",
    "maxUnit": "EC45"
  },
  {
    "text": "The child had a big kite.",
    "maxUnit": "EC45"
  },
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC45"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC45"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC45"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC45"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC45"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC45"
  }
] as const;

export const chains = [
  [
    "mitt",
    "mill",
    "hill",
    "hills",
    "his"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "grateful",
    "syllables": "grate|ful",
    "schwa": [
      1
    ]
  },
  {
    "text": "coffee",
    "syllables": "co|ffee",
    "schwa": [
      1
    ]
  },
  {
    "text": "shampoo",
    "syllables": "sham|poo"
  },
  {
    "text": "together",
    "syllables": "to|geth|er",
    "schwa": [
      0,
      2
    ]
  },
  {
    "text": "olive",
    "syllables": "o|live",
    "schwa": [
      0
    ]
  },
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "seven",
    "syllables": "se|ven",
    "schwa": [
      1
    ]
  },
  {
    "text": "jackpot",
    "syllables": "jack|pot"
  },
  {
    "text": "padlock",
    "syllables": "pad|lock"
  },
  {
    "text": "backpack",
    "syllables": "back|pack"
  }
] as const;
