// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "breeze",
    "segs": "b.r.ee.ze=z",
    "unit": "EC48",
    "tags": [
      "review",
      "sort:ze",
      "dictation-safe"
    ]
  },
  {
    "text": "zip",
    "segs": "z.i.p",
    "unit": "EC48",
    "pic": "a zip",
    "tags": [
      "review",
      "picture",
      "sort:z"
    ]
  },
  {
    "text": "zoo",
    "segs": "z.oo",
    "unit": "EC48",
    "tags": [
      "review",
      "sort:z",
      "dictation-safe"
    ]
  },
  {
    "text": "quiz",
    "segs": "q.u=w.i.z",
    "unit": "EC48",
    "tags": [
      "review",
      "dictation-safe",
      "sort:z"
    ]
  },
  {
    "text": "buzz",
    "segs": "b.u.zz",
    "unit": "EC48",
    "tags": [
      "review",
      "dictation-safe",
      "sort:zz"
    ]
  },
  {
    "text": "fizz",
    "segs": "f.i.zz",
    "unit": "EC48",
    "tags": [
      "review",
      "dictation-safe",
      "sort:zz"
    ]
  },
  {
    "text": "drizzle",
    "segs": "d.r.i.zz.le=l",
    "unit": "EC48",
    "tags": [
      "review",
      "dictation-safe",
      "sort:zz"
    ]
  },
  {
    "text": "please",
    "segs": "p.l.ea.se=z",
    "unit": "EC48",
    "tags": [
      "review",
      "dictation-safe",
      "sort:se"
    ]
  },
  {
    "text": "choose",
    "segs": "ch.oo.se=z",
    "unit": "EC48",
    "tags": [
      "review",
      "dictation-safe",
      "sort:se"
    ]
  },
  {
    "text": "blouse",
    "segs": "b.l.ou=ou.se=z",
    "unit": "EC48",
    "tags": [
      "review",
      "dictation-safe",
      "sort:se"
    ]
  },
  {
    "text": "legs",
    "segs": "l.e.g.s=z",
    "unit": "EC48",
    "tags": [
      "review",
      "dictation-safe",
      "sort:s"
    ]
  },
  {
    "text": "his",
    "segs": "h.i.s=z",
    "unit": "EC48",
    "tags": [
      "review",
      "dictation-safe",
      "sort:s"
    ]
  },
  {
    "text": "was",
    "segs": "w.a=o.s=z",
    "unit": "EC48",
    "tags": [
      "review",
      "dictation-safe",
      "sort:s"
    ]
  },
  {
    "text": "hens",
    "segs": "h.e.n.s=z",
    "unit": "EC48",
    "tags": [
      "review",
      "dictation-safe",
      "sort:s"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC46"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC46"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC46"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC46"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC46"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC46"
  },
  {
    "text": "The bear sat on the chair.",
    "maxUnit": "EC46"
  },
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC46"
  }
] as const;

export const chains = [
  [
    "zip",
    "chip",
    "chick",
    "chin",
    "in"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "daughter",
    "syllables": "daugh|ter",
    "schwa": [
      1
    ]
  },
  {
    "text": "grateful",
    "syllables": "grate|ful",
    "schwa": [
      1
    ]
  },
  {
    "text": "coffee",
    "syllables": "co|ffee",
    "schwa": [
      1
    ]
  },
  {
    "text": "shampoo",
    "syllables": "sham|poo"
  },
  {
    "text": "together",
    "syllables": "to|geth|er",
    "schwa": [
      0,
      2
    ]
  },
  {
    "text": "olive",
    "syllables": "o|live",
    "schwa": [
      0
    ]
  },
  {
    "text": "lemon",
    "syllables": "le|mon",
    "schwa": [
      1
    ]
  },
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "backdrop",
    "syllables": "back|drop"
  },
  {
    "text": "chopstick",
    "syllables": "chop|stick"
  }
] as const;
