// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "here",
    "segs": "h.ere=eer",
    "unit": "EC49",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ere"
    ]
  },
  {
    "text": "deer",
    "segs": "d.eer=eer",
    "unit": "EC49",
    "pic": "one brown deer standing alone, full body",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:eer"
    ]
  },
  {
    "text": "cheer",
    "segs": "ch.eer=eer",
    "unit": "EC49",
    "tags": [
      "new",
      "dictation-safe",
      "sort:eer"
    ]
  },
  {
    "text": "ear",
    "segs": "ear=eer",
    "unit": "EC49",
    "pic": "one human ear seen close up, alone",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ear"
    ]
  },
  {
    "text": "beard",
    "segs": "b.ear=eer.d",
    "unit": "EC49",
    "pic": "one smiling man with a long full beard, portrait view",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ear"
    ]
  },
  {
    "text": "tear",
    "segs": "t.ear=eer",
    "unit": "EC49",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ear"
    ]
  },
  {
    "text": "near",
    "segs": "n.ear=eer",
    "unit": "EC49",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ear"
    ]
  },
  {
    "text": "fear",
    "segs": "f.ear=eer",
    "unit": "EC49",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ear"
    ]
  },
  {
    "text": "rear",
    "segs": "r.ear=eer",
    "unit": "EC49",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ear"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "A little bird sat on the fence.",
    "maxUnit": "EC47"
  },
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC47"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC47"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC47"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC47"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC47"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC47"
  },
  {
    "text": "The bear sat on the chair.",
    "maxUnit": "EC47"
  }
] as const;

export const chains = [
  [
    "here",
    "hair",
    "air",
    "ear",
    "fear"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "anchor",
    "syllables": "anch|or",
    "schwa": [
      1
    ]
  },
  {
    "text": "daughter",
    "syllables": "daugh|ter",
    "schwa": [
      1
    ]
  },
  {
    "text": "grateful",
    "syllables": "grate|ful",
    "schwa": [
      1
    ]
  },
  {
    "text": "coffee",
    "syllables": "co|ffee",
    "schwa": [
      1
    ]
  },
  {
    "text": "shampoo",
    "syllables": "sham|poo"
  },
  {
    "text": "together",
    "syllables": "to|geth|er",
    "schwa": [
      0,
      2
    ]
  },
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "seven",
    "syllables": "se|ven",
    "schwa": [
      1
    ]
  },
  {
    "text": "backrest",
    "syllables": "back|rest"
  },
  {
    "text": "sandpit",
    "syllables": "sand|pit"
  }
] as const;
