// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "go",
    "segs": "g.o=oe",
    "unit": "EC5",
    "tags": [
      "review",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "no",
    "segs": "n.o=oe",
    "unit": "EC5",
    "tags": [
      "review",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "so",
    "segs": "s.o=oe",
    "unit": "EC5",
    "tags": [
      "review",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "old",
    "segs": "o=oe.l.d",
    "unit": "EC5",
    "tags": [
      "review",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "post",
    "segs": "p.o=oe.s.t",
    "unit": "EC5",
    "tags": [
      "review",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "most",
    "segs": "m.o=oe.s.t",
    "unit": "EC5",
    "tags": [
      "review",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "both",
    "segs": "b.o=oe.th",
    "unit": "EC5",
    "tags": [
      "review",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "fro",
    "segs": "f.r.o=oe",
    "unit": "EC5",
    "tags": [
      "review",
      "dictation-safe",
      "sort:o"
    ]
  },
  {
    "text": "dog",
    "segs": "d.o.g",
    "unit": "EC5",
    "pic": "a friendly brown-and-white puppy sitting and facing the viewer, floppy ears, big shiny eyes, a little pink tongue, a wagging tail",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  },
  {
    "text": "doll",
    "segs": "d.o.ll",
    "unit": "EC5",
    "pic": "a doll",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  },
  {
    "text": "rock",
    "segs": "r.o.ck",
    "unit": "EC5",
    "pic": "a rock",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  },
  {
    "text": "box",
    "segs": "b.o.x",
    "unit": "EC5",
    "pic": "a simple open cardboard box with four folded flaps, hollow inside and clearly made of brown cardboard",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  },
  {
    "text": "frog",
    "segs": "f.r.o.g",
    "unit": "EC5",
    "pic": "a green frog sitting and facing the viewer, big round eyes with shiny black pupils, a wide smile",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  },
  {
    "text": "shop",
    "segs": "sh.o.p",
    "unit": "EC5",
    "pic": "a shop",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  },
  {
    "text": "clock",
    "segs": "c.l.o.ck",
    "unit": "EC5",
    "pic": "a clock",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  },
  {
    "text": "lock",
    "segs": "l.o.ck",
    "unit": "EC5",
    "pic": "a padlock",
    "tags": [
      "review",
      "picture",
      "sort:o"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The tart is on a plate.",
    "maxUnit": "EC3"
  },
  {
    "text": "The jar is on the cart.",
    "maxUnit": "EC3"
  },
  {
    "text": "The star is over the barn.",
    "maxUnit": "EC3"
  },
  {
    "text": "The car is by the farm.",
    "maxUnit": "EC3"
  },
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC3"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC3"
  }
] as const;

export const chains = [] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "dogleg",
    "syllables": "dog|leg"
  },
  {
    "text": "admit",
    "syllables": "ad|mit"
  },
  {
    "text": "upset",
    "syllables": "up|set"
  },
  {
    "text": "comic",
    "syllables": "co|mic"
  },
  {
    "text": "cabin",
    "syllables": "ca|bin"
  },
  {
    "text": "sunset",
    "syllables": "sun|set"
  },
  {
    "text": "zigzag",
    "syllables": "zig|zag"
  },
  {
    "text": "sunlit",
    "syllables": "sun|lit"
  },
  {
    "text": "wigwam",
    "syllables": "wig|wam"
  },
  {
    "text": "cobweb",
    "syllables": "cob|web"
  }
] as const;
