// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "her",
    "segs": "h.er=er",
    "unit": "EC6",
    "tags": [
      "new",
      "dictation-safe",
      "sort:er"
    ]
  },
  {
    "text": "kerb",
    "segs": "k.er=er.b",
    "unit": "EC6",
    "tags": [
      "new",
      "dictation-safe",
      "sort:er"
    ]
  },
  {
    "text": "herd",
    "segs": "h.er=er.d",
    "unit": "EC6",
    "tags": [
      "new",
      "dictation-safe",
      "sort:er"
    ]
  },
  {
    "text": "worm",
    "segs": "w.or=er.m",
    "unit": "EC6",
    "pic": "one pink earthworm curved on plain white",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:or"
    ]
  },
  {
    "text": "world",
    "segs": "w.or=er.l.d",
    "unit": "EC6",
    "tags": [
      "new",
      "dictation-safe",
      "sort:or"
    ]
  },
  {
    "text": "worst",
    "segs": "w.or=er.s.t",
    "unit": "EC6",
    "tags": [
      "new",
      "dictation-safe",
      "sort:or"
    ]
  },
  {
    "text": "work",
    "segs": "w.or=er.k",
    "unit": "EC6",
    "tags": [
      "new",
      "dictation-safe",
      "sort:or"
    ]
  },
  {
    "text": "word",
    "segs": "w.or=er.d",
    "unit": "EC6",
    "tags": [
      "new",
      "dictation-safe",
      "sort:or"
    ]
  },
  {
    "text": "nurse",
    "segs": "n.ur=er.se=s",
    "unit": "EC6",
    "pic": "one friendly nurse in plain blue scrubs with a stethoscope, no badges or writing",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ur"
    ]
  },
  {
    "text": "fur",
    "segs": "f.ur=er",
    "unit": "EC6",
    "pic": "one patch of soft brown animal fur",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ur"
    ]
  },
  {
    "text": "church",
    "segs": "ch.ur=er.ch",
    "unit": "EC6",
    "pic": "one small stone church with a steeple",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ur"
    ]
  },
  {
    "text": "purse",
    "segs": "p.ur=er.se=s",
    "unit": "EC6",
    "pic": "one small zipped purse for coins",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ur"
    ]
  },
  {
    "text": "hurt",
    "segs": "h.ur=er.t",
    "unit": "EC6",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ur"
    ]
  },
  {
    "text": "turn",
    "segs": "t.ur=er.n",
    "unit": "EC6",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ur"
    ]
  },
  {
    "text": "burn",
    "segs": "b.ur=er.n",
    "unit": "EC6",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ur"
    ]
  },
  {
    "text": "curl",
    "segs": "c.ur=er.l",
    "unit": "EC6",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ur"
    ]
  },
  {
    "text": "girl",
    "segs": "g.ir=er.l",
    "unit": "EC6",
    "pic": "one smiling young girl standing alone",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ir"
    ]
  },
  {
    "text": "bird",
    "segs": "b.ir=er.d",
    "unit": "EC6",
    "pic": "one small colourful bird standing alone",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ir"
    ]
  },
  {
    "text": "shirt",
    "segs": "sh.ir=er.t",
    "unit": "EC6",
    "pic": "one plain blue shirt with sleeves",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ir"
    ]
  },
  {
    "text": "skirt",
    "segs": "s.k.ir=er.t",
    "unit": "EC6",
    "pic": "one plain red skirt",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ir"
    ]
  },
  {
    "text": "dirt",
    "segs": "d.ir=er.t",
    "unit": "EC6",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ir"
    ]
  },
  {
    "text": "stir",
    "segs": "s.t.ir=er",
    "unit": "EC6",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ir"
    ]
  },
  {
    "text": "first",
    "segs": "f.ir=er.s.t",
    "unit": "EC6",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ir"
    ]
  },
  {
    "text": "third",
    "segs": "th.ir=er.d",
    "unit": "EC6",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ir"
    ]
  },
  {
    "text": "fir",
    "segs": "f.ir=er",
    "unit": "EC6",
    "tags": [
      "new",
      "reading-only",
      "sort:ir"
    ]
  },
  {
    "text": "surf",
    "segs": "s.ur=er.f",
    "unit": "EC6",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ur"
    ]
  },
  {
    "text": "twirl",
    "segs": "t.w.ir=er.l",
    "unit": "EC6",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ir"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The star is over the barn.",
    "maxUnit": "EC4"
  },
  {
    "text": "The boy found a toy car.",
    "maxUnit": "EC4"
  },
  {
    "text": "The coin fell in the soil.",
    "maxUnit": "EC4"
  },
  {
    "text": "The boy had a new toy.",
    "maxUnit": "EC4"
  },
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC4"
  },
  {
    "text": "The cube is in the tube.",
    "maxUnit": "EC4"
  },
  {
    "text": "The tall horse ate an apple.",
    "maxUnit": "EC4"
  },
  {
    "text": "The fork is on the table.",
    "maxUnit": "EC4"
  }
] as const;

export const chains = [
  [
    "her",
    "he",
    "hen",
    "den",
    "dent"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "himself",
    "syllables": "him|self"
  },
  {
    "text": "contest",
    "syllables": "con|test"
  },
  {
    "text": "backhand",
    "syllables": "back|hand"
  },
  {
    "text": "eggshell",
    "syllables": "egg|shell"
  },
  {
    "text": "acting",
    "syllables": "ac|ting"
  },
  {
    "text": "bedrock",
    "syllables": "bed|rock"
  },
  {
    "text": "jackpot",
    "syllables": "jack|pot"
  },
  {
    "text": "padlock",
    "syllables": "pad|lock"
  },
  {
    "text": "backpack",
    "syllables": "back|pack"
  },
  {
    "text": "catfish",
    "syllables": "cat|fish"
  }
] as const;
