// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "said",
    "segs": "s.ai=e.d",
    "unit": "EC7",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ai"
    ]
  },
  {
    "text": "head",
    "segs": "h.ea=e.d",
    "unit": "EC7",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "bread",
    "segs": "b.r.ea=e.d",
    "unit": "EC7",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "deaf",
    "segs": "d.ea=e.f",
    "unit": "EC7",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "sweat",
    "segs": "s.w.ea=e.t",
    "unit": "EC7",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "health",
    "segs": "h.ea=e.l.th",
    "unit": "EC7",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "meant",
    "segs": "m.ea=e.n.t",
    "unit": "EC7",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "thread",
    "segs": "th.r.ea=e.d",
    "unit": "EC7",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "dread",
    "segs": "d.r.ea=e.d",
    "unit": "EC7",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ea"
    ]
  },
  {
    "text": "bed",
    "segs": "b.e.d",
    "unit": "EC7",
    "pic": "a bed",
    "tags": [
      "review",
      "picture",
      "sort:e"
    ]
  },
  {
    "text": "leg",
    "segs": "l.e.g",
    "unit": "EC7",
    "pic": "one isolated bare human leg from the upper thigh to all five toes, bent slightly at the clearly visible knee, natural skin colour, no sock, shoe, trousers or rest of body",
    "tags": [
      "review",
      "picture",
      "sort:e"
    ]
  },
  {
    "text": "dress",
    "segs": "d.r.e.ss",
    "unit": "EC7",
    "pic": "one simple bright red child-sized dress on a plain hanger, clear fitted bodice and wide flared skirt, shown full length with no person",
    "tags": [
      "review",
      "picture",
      "sort:e"
    ]
  },
  {
    "text": "bell",
    "segs": "b.e.ll",
    "unit": "EC7",
    "pic": "a bell",
    "tags": [
      "review",
      "picture",
      "sort:e"
    ]
  },
  {
    "text": "desk",
    "segs": "d.e.s.k",
    "unit": "EC7",
    "pic": "one wooden writing desk with a wide flat top, a single drawer and an empty chair pushed under it, no writing",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:e"
    ]
  },
  {
    "text": "yell",
    "segs": "y.e.ll",
    "unit": "EC7",
    "pic": "one child calling out loudly with hands cupped round the mouth",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:e"
    ]
  },
  {
    "text": "belt",
    "segs": "b.e.l.t",
    "unit": "EC7",
    "pic": "a belt",
    "tags": [
      "review",
      "picture",
      "sort:e"
    ]
  },
  {
    "text": "mess",
    "segs": "m.e.ss",
    "unit": "EC7",
    "pic": "one messy pile of coloured toy blocks scattered on the floor",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:e"
    ]
  },
  {
    "text": "shell",
    "segs": "sh.e.ll",
    "unit": "EC7",
    "pic": "a sea shell",
    "tags": [
      "review",
      "picture",
      "sort:e"
    ]
  },
  {
    "text": "shed",
    "segs": "sh.e.d",
    "unit": "EC7",
    "pic": "a garden shed",
    "tags": [
      "review",
      "picture",
      "sort:e"
    ]
  },
  {
    "text": "hen",
    "segs": "h.e.n",
    "unit": "EC7",
    "pic": "one adult brown hen standing alone, with a red comb and short beak",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:e"
    ]
  },
  {
    "text": "bench",
    "segs": "b.e.n.ch",
    "unit": "EC7",
    "pic": "a park bench",
    "tags": [
      "review",
      "picture",
      "sort:e"
    ]
  },
  {
    "text": "jet",
    "segs": "j.e.t",
    "unit": "EC7",
    "pic": "one grey jet aircraft with swept wings and two engines, flying alone",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:e"
    ]
  },
  {
    "text": "pen",
    "segs": "p.e.n",
    "unit": "EC7",
    "pic": "a pen",
    "tags": [
      "review",
      "picture",
      "sort:e"
    ]
  },
  {
    "text": "elf",
    "segs": "e.l.f",
    "unit": "EC7",
    "pic": "an elf",
    "tags": [
      "review",
      "picture",
      "sort:e"
    ]
  },
  {
    "text": "chest",
    "segs": "ch.e.s.t",
    "unit": "EC7",
    "pic": "a plain wooden storage chest with a curved lid and simple iron bands, closed, no treasure or coins or lock",
    "tags": [
      "review",
      "picture",
      "sort:e"
    ]
  },
  {
    "text": "tent",
    "segs": "t.e.n.t",
    "unit": "EC7",
    "pic": "a tent",
    "tags": [
      "review",
      "picture",
      "sort:e"
    ]
  },
  {
    "text": "vest",
    "segs": "v.e.s.t",
    "unit": "EC7",
    "pic": "a vest",
    "tags": [
      "review",
      "picture",
      "sort:e"
    ]
  },
  {
    "text": "well",
    "segs": "w.e.ll",
    "unit": "EC7",
    "pic": "a stone well",
    "tags": [
      "review",
      "picture",
      "sort:e"
    ]
  },
  {
    "text": "nest",
    "segs": "n.e.s.t",
    "unit": "EC7",
    "pic": "a bird nest",
    "tags": [
      "review",
      "picture",
      "sort:e"
    ]
  },
  {
    "text": "den",
    "segs": "d.e.n",
    "unit": "EC7",
    "pic": "a small cosy den made of blankets draped over chairs",
    "tags": [
      "review",
      "picture",
      "sort:e"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The stew is in a bowl.",
    "maxUnit": "EC5"
  },
  {
    "text": "The cube is in the tube.",
    "maxUnit": "EC5"
  },
  {
    "text": "The tall horse ate an apple.",
    "maxUnit": "EC5"
  },
  {
    "text": "The horse stood by the gate.",
    "maxUnit": "EC5"
  },
  {
    "text": "The clown had a brown hat.",
    "maxUnit": "EC5"
  },
  {
    "text": "A mouse ran out of the house.",
    "maxUnit": "EC5"
  },
  {
    "text": "The cow is by the house.",
    "maxUnit": "EC5"
  },
  {
    "text": "The crow sat on a pole.",
    "maxUnit": "EC5"
  }
] as const;

export const chains = [
  [
    "said",
    "sad",
    "sand",
    "and",
    "an"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "discuss",
    "syllables": "dis|cuss"
  },
  {
    "text": "sunset",
    "syllables": "sun|set"
  },
  {
    "text": "zigzag",
    "syllables": "zig|zag"
  },
  {
    "text": "sunlit",
    "syllables": "sun|lit"
  },
  {
    "text": "wigwam",
    "syllables": "wig|wam"
  },
  {
    "text": "cobweb",
    "syllables": "cob|web"
  },
  {
    "text": "nutmeg",
    "syllables": "nut|meg"
  },
  {
    "text": "bedbug",
    "syllables": "bed|bug"
  },
  {
    "text": "hotdog",
    "syllables": "hot|dog"
  },
  {
    "text": "kidnap",
    "syllables": "kid|nap"
  }
] as const;
