// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "cow",
    "segs": "c.ow=ou",
    "unit": "EC8",
    "pic": "one black and white cow standing alone",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ow"
    ]
  },
  {
    "text": "clown",
    "segs": "c.l.ow=ou.n",
    "unit": "EC8",
    "pic": "one friendly circus clown with a red nose",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ow"
    ]
  },
  {
    "text": "owl",
    "segs": "ow=ou.l",
    "unit": "EC8",
    "pic": "one brown owl perched alone",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ow"
    ]
  },
  {
    "text": "town",
    "segs": "t.ow=ou.n",
    "unit": "EC8",
    "pic": "a small cluster of colourful houses in a town",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ow"
    ]
  },
  {
    "text": "howl",
    "segs": "h.ow=ou.l",
    "unit": "EC8",
    "pic": "one wolf with its head raised, howling",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ow"
    ]
  },
  {
    "text": "now",
    "segs": "n.ow=ou",
    "unit": "EC8",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "down",
    "segs": "d.ow=ou.n",
    "unit": "EC8",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "how",
    "segs": "h.ow=ou",
    "unit": "EC8",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "house",
    "segs": "h.ou=ou.se=s",
    "unit": "EC8",
    "pic": "one small red-roofed house",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ou"
    ]
  },
  {
    "text": "mouse",
    "segs": "m.ou=ou.se=s",
    "unit": "EC8",
    "pic": "one small grey mouse with a long tail",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ou"
    ]
  },
  {
    "text": "mouth",
    "segs": "m.ou=ou.th",
    "unit": "EC8",
    "pic": "one smiling mouth shown close up",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ou"
    ]
  },
  {
    "text": "cloud",
    "segs": "c.l.ou=ou.d",
    "unit": "EC8",
    "pic": "one fluffy white cloud",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ou"
    ]
  },
  {
    "text": "pouch",
    "segs": "p.ou=ou.ch",
    "unit": "EC8",
    "pic": "one small leather pouch with a drawstring",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:ou"
    ]
  },
  {
    "text": "out",
    "segs": "ou=ou.t",
    "unit": "EC8",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ou"
    ]
  },
  {
    "text": "loud",
    "segs": "l.ou=ou.d",
    "unit": "EC8",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ou"
    ]
  },
  {
    "text": "shout",
    "segs": "sh.ou=ou.t",
    "unit": "EC8",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ou"
    ]
  },
  {
    "text": "brown",
    "segs": "b.r.ow=ou.n",
    "unit": "EC8",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "ground",
    "segs": "g.r.ou=ou.n.d",
    "unit": "EC8",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ou"
    ]
  },
  {
    "text": "sound",
    "segs": "s.ou=ou.n.d",
    "unit": "EC8",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ou"
    ]
  },
  {
    "text": "round",
    "segs": "r.ou=ou.n.d",
    "unit": "EC8",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ou"
    ]
  },
  {
    "text": "pound",
    "segs": "p.ou=ou.n.d",
    "unit": "EC8",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ou"
    ]
  },
  {
    "text": "growl",
    "segs": "g.r.ow=ou.l",
    "unit": "EC8",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "count",
    "segs": "c.ou=ou.n.t",
    "unit": "EC8",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ou"
    ]
  },
  {
    "text": "found",
    "segs": "f.ou=ou.n.d",
    "unit": "EC8",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ou"
    ]
  },
  {
    "text": "frown",
    "segs": "f.r.ow=ou.n",
    "unit": "EC8",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "crowd",
    "segs": "c.r.ow=ou.d",
    "unit": "EC8",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "proud",
    "segs": "p.r.ou=ou.d",
    "unit": "EC8",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ou"
    ]
  },
  {
    "text": "spout",
    "segs": "s.p.ou=ou.t",
    "unit": "EC8",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ou"
    ]
  },
  {
    "text": "bound",
    "segs": "b.ou=ou.n.d",
    "unit": "EC8",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ou"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The star is over the barn.",
    "maxUnit": "EC6"
  },
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC6"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC6"
  },
  {
    "text": "The bear sat on the chair.",
    "maxUnit": "EC6"
  },
  {
    "text": "The tall horse ate an apple.",
    "maxUnit": "EC6"
  },
  {
    "text": "The fork is on the table.",
    "maxUnit": "EC6"
  },
  {
    "text": "The horse stood by the gate.",
    "maxUnit": "EC6"
  },
  {
    "text": "A little bird sat on the fence.",
    "maxUnit": "EC6"
  }
] as const;

export const chains = [
  [
    "cow",
    "how",
    "howl",
    "owl",
    "bowl"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "complex",
    "syllables": "com|plex"
  },
  {
    "text": "triplet",
    "syllables": "tri|plet"
  },
  {
    "text": "flagship",
    "syllables": "flag|ship"
  },
  {
    "text": "pinprick",
    "syllables": "pin|prick"
  },
  {
    "text": "splendid",
    "syllables": "splen|did"
  },
  {
    "text": "grandstand",
    "syllables": "grand|stand"
  },
  {
    "text": "benefit",
    "syllables": "be|ne|fit"
  },
  {
    "text": "habitat",
    "syllables": "ha|bi|tat"
  },
  {
    "text": "fantastic",
    "syllables": "fan|tas|tic"
  },
  {
    "text": "compliment",
    "syllables": "com|pli|ment"
  }
] as const;
