// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "crown",
    "segs": "c.r.ow=ou.n",
    "unit": "EC9",
    "pic": "one golden royal crown",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:ow"
    ]
  },
  {
    "text": "how",
    "segs": "h.ow=ou",
    "unit": "EC9",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "wow",
    "segs": "w.ow=ou",
    "unit": "EC9",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "brow",
    "segs": "b.r.ow=ou",
    "unit": "EC9",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "frown",
    "segs": "f.r.ow=ou.n",
    "unit": "EC9",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "crowd",
    "segs": "c.r.ow=ou.d",
    "unit": "EC9",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "snow",
    "segs": "s.n.ow",
    "unit": "EC9",
    "pic": "snow",
    "tags": [
      "review",
      "picture",
      "sort:ow"
    ]
  },
  {
    "text": "crow",
    "segs": "c.r.ow",
    "unit": "EC9",
    "pic": "one black crow standing alone",
    "tags": [
      "review",
      "picture",
      "new-prompt",
      "sort:ow"
    ]
  },
  {
    "text": "blow",
    "segs": "b.l.ow",
    "unit": "EC9",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "grow",
    "segs": "g.r.ow",
    "unit": "EC9",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "slow",
    "segs": "s.l.ow",
    "unit": "EC9",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "throw",
    "segs": "th.r.ow",
    "unit": "EC9",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "glow",
    "segs": "g.l.ow",
    "unit": "EC9",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "mow",
    "segs": "m.ow",
    "unit": "EC9",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ow"
    ]
  },
  {
    "text": "flow",
    "segs": "f.l.ow",
    "unit": "EC9",
    "tags": [
      "review",
      "dictation-safe",
      "sort:ow"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The girl has long hair.",
    "maxUnit": "EC7"
  },
  {
    "text": "A pear is on the stair.",
    "maxUnit": "EC7"
  },
  {
    "text": "The bear sat on the chair.",
    "maxUnit": "EC7"
  },
  {
    "text": "The star is over the barn.",
    "maxUnit": "EC7"
  },
  {
    "text": "The tall horse ate an apple.",
    "maxUnit": "EC7"
  },
  {
    "text": "The fork is on the table.",
    "maxUnit": "EC7"
  }
] as const;

export const chains = [] as const;

export const nonsense = [] as const;

export const poly = [
  {
    "text": "sunset",
    "syllables": "sun|set"
  },
  {
    "text": "zigzag",
    "syllables": "zig|zag"
  },
  {
    "text": "sunlit",
    "syllables": "sun|lit"
  },
  {
    "text": "wigwam",
    "syllables": "wig|wam"
  },
  {
    "text": "cobweb",
    "syllables": "cob|web"
  },
  {
    "text": "nutmeg",
    "syllables": "nut|meg"
  },
  {
    "text": "bedbug",
    "syllables": "bed|bug"
  },
  {
    "text": "hotdog",
    "syllables": "hot|dog"
  },
  {
    "text": "kidnap",
    "syllables": "kid|nap"
  },
  {
    "text": "pigpen",
    "syllables": "pig|pen"
  }
] as const;
