// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "sit",
    "segs": "s.i.t",
    "unit": "IC1",
    "pic": "one child seen clearly from the side, sitting upright on a low stool, bottom on the seat, knees bent and both bare feet on the floor, hands resting on knees, with the whole seated pose visible",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "mat",
    "segs": "m.a.t",
    "unit": "IC1",
    "pic": "a small woven floor mat",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "am",
    "segs": "a.m",
    "unit": "IC1",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "sat",
    "segs": "s.a.t",
    "unit": "IC1",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "it",
    "segs": "i.t",
    "unit": "IC1",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "at",
    "segs": "a.t",
    "unit": "IC1",
    "tags": [
      "new",
      "dictation-safe"
    ]
  }
] as const;

export const sentences = [] as const;

export const chains = [
  [
    "sit",
    "sat",
    "mat",
    "sat",
    "mat"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [] as const;
