// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "stand",
    "segs": "s.t.a.n.d",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "crisp",
    "segs": "c.r.i.s.p",
    "unit": "IC10",
    "pic": "one very thin golden potato crisp with a wavy curled edge and a few darker toasted patches, shown tilted so its thinness is obvious, no whole potato",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "strap",
    "segs": "s.t.r.a.p",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "crust",
    "segs": "c.r.u.s.t",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "stamp",
    "segs": "s.t.a.m.p",
    "unit": "IC10",
    "pic": "one postage stamp with a scalloped edge and a simple flower picture, no letters or numbers",
    "tags": [
      "new",
      "picture",
      "new-prompt"
    ]
  },
  {
    "text": "twist",
    "segs": "t.w.i.s.t",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "frost",
    "segs": "f.r.o.s.t",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "scrub",
    "segs": "s.c.r.u.b",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "stump",
    "segs": "s.t.u.m.p",
    "unit": "IC10",
    "pic": "a tree stump",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "strip",
    "segs": "s.t.r.i.p",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "split",
    "segs": "s.p.l.i.t",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "scrap",
    "segs": "s.c.r.a.p",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "tents",
    "segs": "t.e.n.t.s",
    "unit": "IC10",
    "pic": "two small camping tents on grass, no people or writing",
    "tags": [
      "new",
      "picture",
      "new-prompt"
    ]
  },
  {
    "text": "clump",
    "segs": "c.l.u.m.p",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "slept",
    "segs": "s.l.e.p.t",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "splat",
    "segs": "s.p.l.a.t",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "swept",
    "segs": "s.w.e.p.t",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "plump",
    "segs": "p.l.u.m.p",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "spend",
    "segs": "s.p.e.n.d",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "crept",
    "segs": "c.r.e.p.t",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "claps",
    "segs": "c.l.a.p.s",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "steps",
    "segs": "s.t.e.p.s",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "lamps",
    "segs": "l.a.m.p.s",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "mints",
    "segs": "m.i.n.t.s",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "gifts",
    "segs": "g.i.f.t.s",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "stomp",
    "segs": "s.t.o.m.p",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "skips",
    "segs": "s.k.i.p.s",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "drops",
    "segs": "d.r.o.p.s",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "lumps",
    "segs": "l.u.m.p.s",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "stops",
    "segs": "s.t.o.p.s",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "grand",
    "segs": "g.r.a.n.d",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "snaps",
    "segs": "s.n.a.p.s",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "belts",
    "segs": "b.e.l.t.s",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "fists",
    "segs": "f.i.s.t.s",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "lifts",
    "segs": "l.i.f.t.s",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "grunt",
    "segs": "g.r.u.n.t",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "pumps",
    "segs": "p.u.m.p.s",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "trips",
    "segs": "t.r.i.p.s",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "rests",
    "segs": "r.e.s.t.s",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "flaps",
    "segs": "f.l.a.p.s",
    "unit": "IC10",
    "tags": [
      "new",
      "dictation-safe"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The pup hid in the tent.",
    "maxUnit": "IC8",
    "special": [
      "the"
    ]
  },
  {
    "text": "The pup had a rest.",
    "maxUnit": "IC8",
    "special": [
      "the",
      "a"
    ]
  },
  {
    "text": "A lamp is on the desk.",
    "maxUnit": "IC8",
    "special": [
      "a",
      "the"
    ]
  },
  {
    "text": "The ant is on a log.",
    "maxUnit": "IC8",
    "special": [
      "the",
      "a"
    ]
  },
  {
    "text": "The fox ran up the hill.",
    "maxUnit": "IC8",
    "special": [
      "the"
    ]
  },
  {
    "text": "A fox ran off.",
    "maxUnit": "IC8",
    "special": [
      "a"
    ]
  },
  {
    "text": "The doll sat on a rug.",
    "maxUnit": "IC8",
    "special": [
      "the",
      "a"
    ]
  },
  {
    "text": "A bell fell in the well.",
    "maxUnit": "IC8",
    "special": [
      "a",
      "the"
    ]
  }
] as const;

export const chains = [
  [
    "stand",
    "sand",
    "and",
    "an",
    "am",
    "at",
    "bat",
    "bag"
  ],
  [
    "strap",
    "trap",
    "tap",
    "cap",
    "cab",
    "can",
    "an",
    "am"
  ],
  [
    "stamp",
    "stomp",
    "stop",
    "top",
    "hop",
    "hip",
    "dip",
    "did"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [] as const;
