// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "wink",
    "segs": "w.i.n=ng.k",
    "unit": "IC11",
    "pic": "one child winking one eye with a friendly smile, face shown close up",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:n"
    ]
  },
  {
    "text": "sink",
    "segs": "s.i.n=ng.k",
    "unit": "IC11",
    "pic": "one plain white kitchen sink with a tap and drain, empty and clean",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:n"
    ]
  },
  {
    "text": "fish",
    "segs": "f.i.sh",
    "unit": "IC11",
    "pic": "a fish",
    "tags": [
      "new",
      "picture",
      "sort:sh"
    ]
  },
  {
    "text": "shop",
    "segs": "sh.o.p",
    "unit": "IC11",
    "pic": "a shop",
    "tags": [
      "new",
      "picture",
      "sort:sh"
    ]
  },
  {
    "text": "ship",
    "segs": "sh.i.p",
    "unit": "IC11",
    "tags": [
      "new",
      "sort:sh",
      "dictation-safe"
    ]
  },
  {
    "text": "shell",
    "segs": "sh.e.ll",
    "unit": "IC11",
    "pic": "a sea shell",
    "tags": [
      "new",
      "picture",
      "sort:sh"
    ]
  },
  {
    "text": "shed",
    "segs": "sh.e.d",
    "unit": "IC11",
    "pic": "a garden shed",
    "tags": [
      "new",
      "picture",
      "sort:sh"
    ]
  },
  {
    "text": "dish",
    "segs": "d.i.sh",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:sh"
    ]
  },
  {
    "text": "shut",
    "segs": "sh.u.t",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:sh"
    ]
  },
  {
    "text": "cash",
    "segs": "c.a.sh",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:sh"
    ]
  },
  {
    "text": "chick",
    "segs": "ch.i.ck",
    "unit": "IC11",
    "pic": "a chick",
    "tags": [
      "new",
      "picture",
      "sort:ch",
      "sort:ck"
    ]
  },
  {
    "text": "bench",
    "segs": "b.e.n.ch",
    "unit": "IC11",
    "pic": "a park bench",
    "tags": [
      "new",
      "picture",
      "sort:ch"
    ]
  },
  {
    "text": "chest",
    "segs": "ch.e.s.t",
    "unit": "IC11",
    "pic": "a plain wooden storage chest with a curved lid and simple iron bands, closed, no treasure or coins or lock",
    "tags": [
      "new",
      "picture",
      "sort:ch"
    ]
  },
  {
    "text": "chunk",
    "segs": "ch.u.n=ng.k",
    "unit": "IC11",
    "tags": [
      "new",
      "sort:ch",
      "sort:n",
      "dictation-safe"
    ]
  },
  {
    "text": "lunch",
    "segs": "l.u.n.ch",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ch"
    ]
  },
  {
    "text": "chin",
    "segs": "ch.i.n",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ch"
    ]
  },
  {
    "text": "chip",
    "segs": "ch.i.p",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ch"
    ]
  },
  {
    "text": "chop",
    "segs": "ch.o.p",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ch"
    ]
  },
  {
    "text": "that",
    "segs": "th=dh.a.t",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:th"
    ]
  },
  {
    "text": "this",
    "segs": "th=dh.i.s",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:th"
    ]
  },
  {
    "text": "them",
    "segs": "th=dh.e.m",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:th"
    ]
  },
  {
    "text": "thing",
    "segs": "th.i.ng",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:th",
      "sort:ng"
    ]
  },
  {
    "text": "with",
    "segs": "w.i.th=dh",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:th"
    ]
  },
  {
    "text": "thin",
    "segs": "th.i.n",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:th"
    ]
  },
  {
    "text": "thick",
    "segs": "th.i.ck",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:th",
      "sort:ck"
    ]
  },
  {
    "text": "cloth",
    "segs": "c.l.o.th",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:th"
    ]
  },
  {
    "text": "duck",
    "segs": "d.u.ck",
    "unit": "IC11",
    "pic": "a duck",
    "tags": [
      "new",
      "picture",
      "sort:ck"
    ]
  },
  {
    "text": "rock",
    "segs": "r.o.ck",
    "unit": "IC11",
    "pic": "a rock",
    "tags": [
      "new",
      "picture",
      "sort:ck"
    ]
  },
  {
    "text": "lock",
    "segs": "l.o.ck",
    "unit": "IC11",
    "pic": "a padlock",
    "tags": [
      "new",
      "picture",
      "sort:ck"
    ]
  },
  {
    "text": "sock",
    "segs": "s.o.ck",
    "unit": "IC11",
    "pic": "a sock",
    "tags": [
      "new",
      "picture",
      "sort:ck"
    ]
  },
  {
    "text": "black",
    "segs": "b.l.a.ck",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ck"
    ]
  },
  {
    "text": "back",
    "segs": "b.a.ck",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ck"
    ]
  },
  {
    "text": "ring",
    "segs": "r.i.ng",
    "unit": "IC11",
    "pic": "a ring",
    "tags": [
      "new",
      "picture",
      "sort:ng"
    ]
  },
  {
    "text": "king",
    "segs": "k.i.ng",
    "unit": "IC11",
    "pic": "a friendly grown-up king wearing a golden crown and a long red royal robe, with his face, full body and hands visible, waving",
    "tags": [
      "new",
      "picture",
      "sort:ng"
    ]
  },
  {
    "text": "swing",
    "segs": "s.w.i.ng",
    "unit": "IC11",
    "pic": "a swing",
    "tags": [
      "new",
      "picture",
      "sort:ng"
    ]
  },
  {
    "text": "wing",
    "segs": "w.i.ng",
    "unit": "IC11",
    "pic": "a wing",
    "tags": [
      "new",
      "picture",
      "sort:ng"
    ]
  },
  {
    "text": "sing",
    "segs": "s.i.ng",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ng"
    ]
  },
  {
    "text": "song",
    "segs": "s.o.ng",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ng"
    ]
  },
  {
    "text": "bang",
    "segs": "b.a.ng",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ng"
    ]
  },
  {
    "text": "pink",
    "segs": "p.i.n=ng.k",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:n"
    ]
  },
  {
    "text": "drink",
    "segs": "d.r.i.n=ng.k",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:n"
    ]
  },
  {
    "text": "thank",
    "segs": "th.a.n=ng.k",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:th",
      "sort:n"
    ]
  },
  {
    "text": "think",
    "segs": "th.i.n=ng.k",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:th",
      "sort:n"
    ]
  },
  {
    "text": "bank",
    "segs": "b.a.n=ng.k",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:n"
    ]
  },
  {
    "text": "whisk",
    "segs": "wh.i.s.k",
    "unit": "IC11",
    "pic": "a whisk",
    "tags": [
      "new",
      "picture",
      "sort:wh"
    ]
  },
  {
    "text": "when",
    "segs": "wh.e.n",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:wh"
    ]
  },
  {
    "text": "which",
    "segs": "wh.i.ch",
    "unit": "IC11",
    "tags": [
      "new",
      "reading-only",
      "sort:ch",
      "sort:wh"
    ]
  },
  {
    "text": "whip",
    "segs": "wh.i.p",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:wh"
    ]
  },
  {
    "text": "whack",
    "segs": "wh.a.ck",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ck",
      "sort:wh"
    ]
  },
  {
    "text": "quilt",
    "segs": "q.u=w.i.l.t",
    "unit": "IC11",
    "tags": [
      "new",
      "sort:q",
      "sort:u",
      "dictation-safe"
    ]
  },
  {
    "text": "squid",
    "segs": "s.q.u=w.i.d",
    "unit": "IC11",
    "pic": "one squid swimming alone, with a long pointed mantle and ten trailing arms",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:q",
      "sort:u"
    ]
  },
  {
    "text": "quit",
    "segs": "q.u=w.i.t",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:q",
      "sort:u"
    ]
  },
  {
    "text": "quiz",
    "segs": "q.u=w.i.z",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:q",
      "sort:u"
    ]
  },
  {
    "text": "quack",
    "segs": "q.u=w.a.ck",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:u"
    ]
  },
  {
    "text": "quick",
    "segs": "q.u=w.i.ck",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:u"
    ]
  },
  {
    "text": "give",
    "segs": "g.i.ve",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ve"
    ]
  },
  {
    "text": "have",
    "segs": "h.a.ve",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ve"
    ]
  },
  {
    "text": "live",
    "segs": "l.i.ve",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ve"
    ]
  },
  {
    "text": "hutch",
    "segs": "h.u.tch",
    "unit": "IC11",
    "pic": "a rabbit hutch",
    "tags": [
      "new",
      "picture",
      "sort:tch"
    ]
  },
  {
    "text": "match",
    "segs": "m.a.tch",
    "unit": "IC11",
    "pic": "a match stick",
    "tags": [
      "new",
      "picture",
      "sort:tch"
    ]
  },
  {
    "text": "watch",
    "segs": "w.a.tch",
    "unit": "IC11",
    "pic": "one simple wristwatch with a round face and no numbers",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:tch"
    ]
  },
  {
    "text": "hatch",
    "segs": "h.a.tch",
    "unit": "IC11",
    "tags": [
      "new",
      "sort:tch",
      "dictation-safe"
    ]
  },
  {
    "text": "pitch",
    "segs": "p.i.tch",
    "unit": "IC11",
    "pic": "one grassy sports pitch with white boundary lines and no words",
    "tags": [
      "new",
      "picture",
      "new-prompt",
      "sort:tch"
    ]
  },
  {
    "text": "catch",
    "segs": "c.a.tch",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:tch"
    ]
  },
  {
    "text": "itch",
    "segs": "i.tch",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:tch"
    ]
  },
  {
    "text": "fetch",
    "segs": "f.e.tch",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:tch"
    ]
  },
  {
    "text": "clock",
    "segs": "c.l.o.ck",
    "unit": "IC11",
    "pic": "a clock",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "kick",
    "segs": "k.i.ck",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "long",
    "segs": "l.o.ng",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ng"
    ]
  },
  {
    "text": "neck",
    "segs": "n.e.ck",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ck"
    ]
  },
  {
    "text": "snack",
    "segs": "s.n.a.ck",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ck"
    ]
  },
  {
    "text": "hang",
    "segs": "h.a.ng",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ng"
    ]
  },
  {
    "text": "pick",
    "segs": "p.i.ck",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ck"
    ]
  },
  {
    "text": "strong",
    "segs": "s.t.r.o.ng",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ng"
    ]
  },
  {
    "text": "stuck",
    "segs": "s.t.u.ck",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ck"
    ]
  },
  {
    "text": "chat",
    "segs": "ch.a.t",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ch"
    ]
  },
  {
    "text": "much",
    "segs": "m.u.ch",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ch"
    ]
  },
  {
    "text": "then",
    "segs": "th=dh.e.n",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:th"
    ]
  },
  {
    "text": "check",
    "segs": "ch.e.ck",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ch",
      "sort:ck"
    ]
  },
  {
    "text": "wish",
    "segs": "w.i.sh",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:sh"
    ]
  },
  {
    "text": "munch",
    "segs": "m.u.n.ch",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ch"
    ]
  },
  {
    "text": "thump",
    "segs": "th.u.m.p",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:th"
    ]
  },
  {
    "text": "chimp",
    "segs": "ch.i.m.p",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ch"
    ]
  },
  {
    "text": "thud",
    "segs": "th.u.d",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:th"
    ]
  },
  {
    "text": "patch",
    "segs": "p.a.tch",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:tch"
    ]
  },
  {
    "text": "rush",
    "segs": "r.u.sh",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:sh"
    ]
  },
  {
    "text": "shock",
    "segs": "sh.o.ck",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:sh",
      "sort:ck"
    ]
  },
  {
    "text": "rich",
    "segs": "r.i.ch",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:ch"
    ]
  },
  {
    "text": "ditch",
    "segs": "d.i.tch",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:tch"
    ]
  },
  {
    "text": "sketch",
    "segs": "s.k.e.tch",
    "unit": "IC11",
    "tags": [
      "new",
      "dictation-safe",
      "sort:tch"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The drum is on the rug.",
    "maxUnit": "IC9",
    "special": [
      "the"
    ]
  },
  {
    "text": "A plum is in the pot.",
    "maxUnit": "IC9",
    "special": [
      "a",
      "the"
    ]
  },
  {
    "text": "A crab hid in the sand.",
    "maxUnit": "IC9",
    "special": [
      "a",
      "the"
    ]
  },
  {
    "text": "The frog swam in the pond.",
    "maxUnit": "IC9",
    "special": [
      "the"
    ]
  },
  {
    "text": "The wind bent the flag.",
    "maxUnit": "IC9",
    "special": [
      "the"
    ]
  },
  {
    "text": "A frog can hop.",
    "maxUnit": "IC9",
    "special": [
      "a"
    ]
  },
  {
    "text": "The pup hid in the tent.",
    "maxUnit": "IC9",
    "special": [
      "the"
    ]
  },
  {
    "text": "The pup had a rest.",
    "maxUnit": "IC9",
    "special": [
      "the",
      "a"
    ]
  }
] as const;

export const chains = [
  [
    "fish",
    "dish",
    "ditch",
    "itch",
    "pitch",
    "patch"
  ],
  [
    "shop",
    "chop",
    "chip",
    "chick",
    "chin",
    "in"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [] as const;
