// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "man",
    "segs": "m.a.n",
    "unit": "IC2",
    "pic": "a friendly grown-up man in a green jumper waving",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "mop",
    "segs": "m.o.p",
    "unit": "IC2",
    "pic": "a floor mop",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "pan",
    "segs": "p.a.n",
    "unit": "IC2",
    "pic": "a frying pan",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "pot",
    "segs": "p.o.t",
    "unit": "IC2",
    "pic": "a clay cooking pot",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "top",
    "segs": "t.o.p",
    "unit": "IC2",
    "pic": "a spinning top toy",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "tap",
    "segs": "t.a.p",
    "unit": "IC2",
    "pic": "a kitchen water tap",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "tin",
    "segs": "t.i.n",
    "unit": "IC2",
    "pic": "a tin can",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "nap",
    "segs": "n.a.p",
    "unit": "IC2",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "pin",
    "segs": "p.i.n",
    "unit": "IC2",
    "pic": "a big red drawing pin (a push pin) standing on its point, seen from the side",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "map",
    "segs": "m.a.p",
    "unit": "IC2",
    "pic": "a treasure map",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "not",
    "segs": "n.o.t",
    "unit": "IC2",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "pat",
    "segs": "p.a.t",
    "unit": "IC2",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "pop",
    "segs": "p.o.p",
    "unit": "IC2",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "in",
    "segs": "i.n",
    "unit": "IC2",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "an",
    "segs": "a.n",
    "unit": "IC2",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "on",
    "segs": "o.n",
    "unit": "IC2",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "sip",
    "segs": "s.i.p",
    "unit": "IC2",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "tip",
    "segs": "t.i.p",
    "unit": "IC2",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "pip",
    "segs": "p.i.p",
    "unit": "IC2",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "nip",
    "segs": "n.i.p",
    "unit": "IC2",
    "tags": [
      "new",
      "dictation-safe"
    ]
  }
] as const;

export const sentences = [] as const;

export const chains = [
  [
    "man",
    "map",
    "mop",
    "pop",
    "pip",
    "nip"
  ],
  [
    "mop",
    "map",
    "man",
    "pan",
    "pat",
    "pot"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [] as const;
