// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "cat",
    "segs": "c.a.t",
    "unit": "IC3",
    "pic": "a cat",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "pig",
    "segs": "p.i.g",
    "unit": "IC3",
    "pic": "a pink pig",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "hat",
    "segs": "h.a.t",
    "unit": "IC3",
    "pic": "a blue sun hat with a wide brim",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "bag",
    "segs": "b.a.g",
    "unit": "IC3",
    "pic": "a school bag",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "bib",
    "segs": "b.i.b",
    "unit": "IC3",
    "pic": "a baby bib",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "bin",
    "segs": "b.i.n",
    "unit": "IC3",
    "pic": "a rubbish bin",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "cap",
    "segs": "c.a.p",
    "unit": "IC3",
    "pic": "a baseball cap",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "cot",
    "segs": "c.o.t",
    "unit": "IC3",
    "pic": "a baby's cot",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "bat",
    "segs": "b.a.t",
    "unit": "IC3",
    "pic": "a cute bat flying",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "ham",
    "segs": "h.a.m",
    "unit": "IC3",
    "pic": "one slice of pink cooked ham on a plain white plate",
    "tags": [
      "new",
      "picture",
      "new-prompt"
    ]
  },
  {
    "text": "big",
    "segs": "b.i.g",
    "unit": "IC3",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "got",
    "segs": "g.o.t",
    "unit": "IC3",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "hot",
    "segs": "h.o.t",
    "unit": "IC3",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "can",
    "segs": "c.a.n",
    "unit": "IC3",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "him",
    "segs": "h.i.m",
    "unit": "IC3",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "hop",
    "segs": "h.o.p",
    "unit": "IC3",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "cab",
    "segs": "c.a.b",
    "unit": "IC3",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "gas",
    "segs": "g.a.s",
    "unit": "IC3",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "tag",
    "segs": "t.a.g",
    "unit": "IC3",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "bit",
    "segs": "b.i.t",
    "unit": "IC3",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "hip",
    "segs": "h.i.p",
    "unit": "IC3",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "gap",
    "segs": "g.a.p",
    "unit": "IC3",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "hog",
    "segs": "h.o.g",
    "unit": "IC3",
    "tags": [
      "new",
      "dictation-safe"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "Tim sat.",
    "maxUnit": "IC1"
  },
  {
    "text": "Sam sat.",
    "maxUnit": "IC1"
  }
] as const;

export const chains = [
  [
    "cat",
    "bat",
    "bag",
    "big",
    "bib",
    "bin"
  ],
  [
    "pig",
    "big",
    "bag",
    "bat",
    "bit",
    "bib"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [] as const;
