// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "dog",
    "segs": "d.o.g",
    "unit": "IC4",
    "pic": "a dog",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "bed",
    "segs": "b.e.d",
    "unit": "IC4",
    "pic": "a bed",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "hen",
    "segs": "h.e.n",
    "unit": "IC4",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "pen",
    "segs": "p.e.n",
    "unit": "IC4",
    "pic": "a pen",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "van",
    "segs": "v.a.n",
    "unit": "IC4",
    "pic": "a tall boxy delivery van with a large windowless cargo box behind the cab, two front seats only, sliding side door and rear doors, in bright blue",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "dot",
    "segs": "d.o.t",
    "unit": "IC4",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "fan",
    "segs": "f.a.n",
    "unit": "IC4",
    "pic": "an electric fan",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "den",
    "segs": "d.e.n",
    "unit": "IC4",
    "pic": "a small cosy den made of blankets draped over chairs",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "peg",
    "segs": "p.e.g",
    "unit": "IC4",
    "pic": "a clothes peg",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "net",
    "segs": "n.e.t",
    "unit": "IC4",
    "pic": "a fishing net",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "fog",
    "segs": "f.o.g",
    "unit": "IC4",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "vet",
    "segs": "v.e.t",
    "unit": "IC4",
    "pic": "a friendly woman vet in teal scrubs examining a small puppy on a low table, wearing a stethoscope around her neck, full person and puppy both clearly visible",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "fin",
    "segs": "f.i.n",
    "unit": "IC4",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "dad",
    "segs": "d.a.d",
    "unit": "IC4",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "get",
    "segs": "g.e.t",
    "unit": "IC4",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "pet",
    "segs": "p.e.t",
    "unit": "IC4",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "ten",
    "segs": "t.e.n",
    "unit": "IC4",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "fed",
    "segs": "f.e.d",
    "unit": "IC4",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "men",
    "segs": "m.e.n",
    "unit": "IC4",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "did",
    "segs": "d.i.d",
    "unit": "IC4",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "dip",
    "segs": "d.i.p",
    "unit": "IC4",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "fit",
    "segs": "f.i.t",
    "unit": "IC4",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "set",
    "segs": "s.e.t",
    "unit": "IC4",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "beg",
    "segs": "b.e.g",
    "unit": "IC4",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "sad",
    "segs": "s.a.d",
    "unit": "IC4",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "nod",
    "segs": "n.o.d",
    "unit": "IC4",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "dig",
    "segs": "d.i.g",
    "unit": "IC4",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "veg",
    "segs": "v.e.g",
    "unit": "IC4",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "mad",
    "segs": "m.a.d",
    "unit": "IC4",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "dab",
    "segs": "d.a.b",
    "unit": "IC4",
    "tags": [
      "new",
      "dictation-safe"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "A pan is on a mat.",
    "maxUnit": "IC2",
    "special": [
      "a"
    ]
  },
  {
    "text": "A pin is in a tin.",
    "maxUnit": "IC2",
    "special": [
      "a"
    ]
  },
  {
    "text": "A map is on a mat.",
    "maxUnit": "IC2",
    "special": [
      "a"
    ]
  },
  {
    "text": "A man sat.",
    "maxUnit": "IC2",
    "special": [
      "a"
    ]
  },
  {
    "text": "Pip sat on a mat.",
    "maxUnit": "IC2",
    "special": [
      "a"
    ]
  },
  {
    "text": "A man sat on a mat.",
    "maxUnit": "IC2",
    "special": [
      "a"
    ]
  },
  {
    "text": "Sam sat on a mat.",
    "maxUnit": "IC2",
    "special": [
      "a"
    ]
  },
  {
    "text": "Tim sat.",
    "maxUnit": "IC2"
  }
] as const;

export const chains = [
  [
    "dog",
    "dig",
    "did",
    "dad",
    "dab",
    "cab"
  ],
  [
    "bed",
    "beg",
    "peg",
    "pen",
    "den",
    "hen"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [] as const;
