// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "run",
    "segs": "r.u.n",
    "unit": "IC5",
    "pic": "a child running",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "hug",
    "segs": "h.u.g",
    "unit": "IC5",
    "pic": "two children facing each other in one clear hug, both full bodies visible",
    "tags": [
      "new",
      "picture",
      "new-prompt"
    ]
  },
  {
    "text": "leg",
    "segs": "l.e.g",
    "unit": "IC5",
    "pic": "one isolated bare human leg from the upper thigh to all five toes, bent slightly at the clearly visible knee, natural skin colour, no sock, shoe, trousers or rest of body",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "bug",
    "segs": "b.u.g",
    "unit": "IC5",
    "pic": "one small green six-legged garden bug, shown alone with its body and legs clearly visible",
    "tags": [
      "new",
      "picture",
      "new-prompt"
    ]
  },
  {
    "text": "sun",
    "segs": "s.u.n",
    "unit": "IC5",
    "pic": "the sun",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "bus",
    "segs": "b.u.s",
    "unit": "IC5",
    "pic": "a red double-decker bus",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "rug",
    "segs": "r.u.g",
    "unit": "IC5",
    "pic": "a round colourful rug",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "cup",
    "segs": "c.u.p",
    "unit": "IC5",
    "pic": "a small shallow porcelain teacup with a delicate curved handle, wide open rim, sitting on a matching saucer, empty inside",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "bun",
    "segs": "b.u.n",
    "unit": "IC5",
    "pic": "a single soft round iced bun with a little swirl of white icing on top, no plate or bread slices",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "mug",
    "segs": "m.u.g",
    "unit": "IC5",
    "pic": "a mug",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "rat",
    "segs": "r.a.t",
    "unit": "IC5",
    "pic": "one large brown rat side-on, with a long pointed snout, visible front teeth, very small ears, coarse fur and a long thick bare pink tail curling behind it, no mouse",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "tub",
    "segs": "t.u.b",
    "unit": "IC5",
    "pic": "one freestanding bath tub with four little feet and no taps",
    "tags": [
      "new",
      "picture",
      "new-prompt"
    ]
  },
  {
    "text": "pup",
    "segs": "p.u.p",
    "unit": "IC5",
    "pic": "one very young puppy standing alone with oversized paws and floppy ears",
    "tags": [
      "new",
      "picture",
      "new-prompt"
    ]
  },
  {
    "text": "log",
    "segs": "l.o.g",
    "unit": "IC5",
    "pic": "a log",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "lid",
    "segs": "l.i.d",
    "unit": "IC5",
    "pic": "a pot lid",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "cub",
    "segs": "c.u.b",
    "unit": "IC5",
    "pic": "one young bear cub standing alone, small round ears and short snout, no adult bear",
    "tags": [
      "new",
      "picture",
      "new-prompt"
    ]
  },
  {
    "text": "hut",
    "segs": "h.u.t",
    "unit": "IC5",
    "pic": "a tiny rustic round thatched hut with a simple wooden door and no windows, made of straw and timber, clearly a one-room shelter",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "nut",
    "segs": "n.u.t",
    "unit": "IC5",
    "pic": "a shelled walnut cracked open to show the wrinkled nut kernel inside, no acorn cap",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "rod",
    "segs": "r.o.d",
    "unit": "IC5",
    "pic": "a fishing rod",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "lad",
    "segs": "l.a.d",
    "unit": "IC5",
    "pic": "one smiling young boy standing alone in ordinary clothes",
    "tags": [
      "new",
      "picture",
      "new-prompt"
    ]
  },
  {
    "text": "ram",
    "segs": "r.a.m",
    "unit": "IC5",
    "pic": "one adult ram standing alone with large curled horns",
    "tags": [
      "new",
      "picture",
      "new-prompt"
    ]
  },
  {
    "text": "mum",
    "segs": "m.u.m",
    "unit": "IC5",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "red",
    "segs": "r.e.d",
    "unit": "IC5",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "up",
    "segs": "u.p",
    "unit": "IC5",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "us",
    "segs": "u.s",
    "unit": "IC5",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "cut",
    "segs": "c.u.t",
    "unit": "IC5",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "fun",
    "segs": "f.u.n",
    "unit": "IC5",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "kid",
    "segs": "k.i.d",
    "unit": "IC5",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "lap",
    "segs": "l.a.p",
    "unit": "IC5",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "lip",
    "segs": "l.i.p",
    "unit": "IC5",
    "tags": [
      "new",
      "dictation-safe"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The cat is in a cot.",
    "maxUnit": "IC3",
    "special": [
      "the",
      "a"
    ]
  },
  {
    "text": "A big pig sat.",
    "maxUnit": "IC3",
    "special": [
      "a"
    ]
  },
  {
    "text": "The cat sat on a mat.",
    "maxUnit": "IC3",
    "special": [
      "the",
      "a"
    ]
  },
  {
    "text": "A pan is on a mat.",
    "maxUnit": "IC3",
    "special": [
      "a"
    ]
  },
  {
    "text": "A pin is in a tin.",
    "maxUnit": "IC3",
    "special": [
      "a"
    ]
  },
  {
    "text": "A map is on a mat.",
    "maxUnit": "IC3",
    "special": [
      "a"
    ]
  },
  {
    "text": "A man sat.",
    "maxUnit": "IC3",
    "special": [
      "a"
    ]
  },
  {
    "text": "Pip sat on a mat.",
    "maxUnit": "IC3",
    "special": [
      "a"
    ]
  }
] as const;

export const chains = [
  [
    "run",
    "bun",
    "bug",
    "hug",
    "hut",
    "cut"
  ],
  [
    "hug",
    "bug",
    "bun",
    "fun",
    "run",
    "rug"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [] as const;
