// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "wag",
    "segs": "w.a.g",
    "unit": "IC6",
    "pic": "one happy dog's tail wagging from side to side, full dog shown",
    "tags": [
      "new",
      "picture",
      "new-prompt"
    ]
  },
  {
    "text": "jam",
    "segs": "j.a.m",
    "unit": "IC6",
    "pic": "a jar of jam",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "jet",
    "segs": "j.e.t",
    "unit": "IC6",
    "pic": "one grey jet aircraft with swept wings and two engines, flying alone",
    "tags": [
      "new",
      "picture",
      "new-prompt"
    ]
  },
  {
    "text": "win",
    "segs": "w.i.n",
    "unit": "IC6",
    "pic": "one child crossing a finish line first with both arms raised, no writing",
    "tags": [
      "new",
      "picture",
      "new-prompt"
    ]
  },
  {
    "text": "jug",
    "segs": "j.u.g",
    "unit": "IC6",
    "pic": "a jug",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "jog",
    "segs": "j.o.g",
    "unit": "IC6",
    "pic": "one child jogging along a clear path in trainers, seen from the side",
    "tags": [
      "new",
      "picture",
      "new-prompt"
    ]
  },
  {
    "text": "wig",
    "segs": "w.i.g",
    "unit": "IC6",
    "pic": "a bright purple curly wig resting on a simple plain wooden wig stand, with the wig cap edge visible below the curls",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "zip",
    "segs": "z.i.p",
    "unit": "IC6",
    "pic": "a zip",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "web",
    "segs": "w.e.b",
    "unit": "IC6",
    "pic": "a spider web",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "wet",
    "segs": "w.e.t",
    "unit": "IC6",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "wad",
    "segs": "w.a.d",
    "unit": "IC6",
    "tags": [
      "new",
      "dictation-safe"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The vet met a dog.",
    "maxUnit": "IC4",
    "special": [
      "the",
      "a"
    ]
  },
  {
    "text": "Dad sat on the bed.",
    "maxUnit": "IC4",
    "special": [
      "the"
    ]
  },
  {
    "text": "The dog had a nap.",
    "maxUnit": "IC4",
    "special": [
      "the",
      "a"
    ]
  },
  {
    "text": "A cat had a nap.",
    "maxUnit": "IC4",
    "special": [
      "a"
    ]
  },
  {
    "text": "A hen sat on a bed.",
    "maxUnit": "IC4",
    "special": [
      "a"
    ]
  },
  {
    "text": "The dog is in a den.",
    "maxUnit": "IC4",
    "special": [
      "the",
      "a"
    ]
  },
  {
    "text": "A dog sat on a mat.",
    "maxUnit": "IC4",
    "special": [
      "a"
    ]
  },
  {
    "text": "The cat is in a cot.",
    "maxUnit": "IC4",
    "special": [
      "the",
      "a"
    ]
  }
] as const;

export const chains = [
  [
    "wag",
    "wad",
    "dad",
    "dab",
    "cab",
    "can"
  ],
  [
    "jam",
    "ham",
    "hat",
    "bat",
    "bag",
    "wag"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [] as const;
