// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "doll",
    "segs": "d.o.ll",
    "unit": "IC7",
    "pic": "a doll",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "box",
    "segs": "b.o.x",
    "unit": "IC7",
    "pic": "a simple open cardboard box with four folded flaps, hollow inside and clearly made of brown cardboard",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "kiss",
    "segs": "k.i.ss",
    "unit": "IC7",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "bell",
    "segs": "b.e.ll",
    "unit": "IC7",
    "pic": "a bell",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "hill",
    "segs": "h.i.ll",
    "unit": "IC7",
    "pic": "one smooth green grassy hill rising above a flat plain, no food or buildings",
    "tags": [
      "new",
      "picture",
      "new-prompt"
    ]
  },
  {
    "text": "yell",
    "segs": "y.e.ll",
    "unit": "IC7",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "mess",
    "segs": "m.e.ss",
    "unit": "IC7",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "puff",
    "segs": "p.u.ff",
    "unit": "IC7",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "fox",
    "segs": "f.o.x",
    "unit": "IC7",
    "pic": "a fox",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "fix",
    "segs": "f.i.x",
    "unit": "IC7",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "well",
    "segs": "w.e.ll",
    "unit": "IC7",
    "pic": "a stone well",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "mill",
    "segs": "m.i.ll",
    "unit": "IC7",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "yes",
    "segs": "y.e.s",
    "unit": "IC7",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "off",
    "segs": "o.ff",
    "unit": "IC7",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "six",
    "segs": "s.i.x",
    "unit": "IC7",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "tell",
    "segs": "t.e.ll",
    "unit": "IC7",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "yum",
    "segs": "y.u.m",
    "unit": "IC7",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "buzz",
    "segs": "b.u.zz",
    "unit": "IC7",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "fuss",
    "segs": "f.u.ss",
    "unit": "IC7",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "hiss",
    "segs": "h.i.ss",
    "unit": "IC7",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "mix",
    "segs": "m.i.x",
    "unit": "IC7",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "miss",
    "segs": "m.i.ss",
    "unit": "IC7",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "yet",
    "segs": "y.e.t",
    "unit": "IC7",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "fizz",
    "segs": "f.i.zz",
    "unit": "IC7",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "yap",
    "segs": "y.a.p",
    "unit": "IC7",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "wax",
    "segs": "w.a.x",
    "unit": "IC7",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "less",
    "segs": "l.e.ss",
    "unit": "IC7",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "huff",
    "segs": "h.u.ff",
    "unit": "IC7",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "fell",
    "segs": "f.e.ll",
    "unit": "IC7",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "boss",
    "segs": "b.o.ss",
    "unit": "IC7",
    "tags": [
      "new",
      "dictation-safe"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "Mum met the vet.",
    "maxUnit": "IC5",
    "special": [
      "the"
    ]
  },
  {
    "text": "The dog ran in the sun.",
    "maxUnit": "IC5",
    "special": [
      "the"
    ]
  },
  {
    "text": "A kid had a bun.",
    "maxUnit": "IC5",
    "special": [
      "a"
    ]
  },
  {
    "text": "A lid is on the pot.",
    "maxUnit": "IC5",
    "special": [
      "a",
      "the"
    ]
  },
  {
    "text": "The pup ran in the sun.",
    "maxUnit": "IC5",
    "special": [
      "the"
    ]
  },
  {
    "text": "The pup sat on a rug.",
    "maxUnit": "IC5",
    "special": [
      "the",
      "a"
    ]
  },
  {
    "text": "A bug sat on a log.",
    "maxUnit": "IC5",
    "special": [
      "a"
    ]
  },
  {
    "text": "Mum had a hug.",
    "maxUnit": "IC5",
    "special": [
      "a"
    ]
  }
] as const;

export const chains = [
  [
    "doll",
    "dog",
    "dot",
    "cot",
    "cat",
    "bat"
  ],
  [
    "box",
    "fox",
    "fix",
    "fizz",
    "fin",
    "bin"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [] as const;
