// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "hand",
    "segs": "h.a.n.d",
    "unit": "IC8",
    "pic": "one open cartoon hand waving hello, palm facing the viewer, five fingers spread",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "jump",
    "segs": "j.u.m.p",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "milk",
    "segs": "m.i.l.k",
    "unit": "IC8",
    "pic": "a glass of milk",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "ant",
    "segs": "a.n.t",
    "unit": "IC8",
    "pic": "an ant",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "desk",
    "segs": "d.e.s.k",
    "unit": "IC8",
    "pic": "one wooden writing desk with a wide flat top, a single drawer and an empty chair pushed under it, no writing",
    "tags": [
      "new",
      "picture",
      "new-prompt"
    ]
  },
  {
    "text": "lamp",
    "segs": "l.a.m.p",
    "unit": "IC8",
    "pic": "a lamp",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "belt",
    "segs": "b.e.l.t",
    "unit": "IC8",
    "pic": "a belt",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "sand",
    "segs": "s.a.n.d",
    "unit": "IC8",
    "pic": "a small golden sandcastle with a little flag on top, sitting on a heap of sand",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "elf",
    "segs": "e.l.f",
    "unit": "IC8",
    "pic": "an elf",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "tent",
    "segs": "t.e.n.t",
    "unit": "IC8",
    "pic": "a tent",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "vest",
    "segs": "v.e.s.t",
    "unit": "IC8",
    "pic": "a vest",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "nest",
    "segs": "n.e.s.t",
    "unit": "IC8",
    "pic": "a bird nest",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "pond",
    "segs": "p.o.n.d",
    "unit": "IC8",
    "pic": "a pond",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "mint",
    "segs": "m.i.n.t",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "dent",
    "segs": "d.e.n.t",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "and",
    "segs": "a.n.d",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "help",
    "segs": "h.e.l.p",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "end",
    "segs": "e.n.d",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "gift",
    "segs": "g.i.f.t",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "best",
    "segs": "b.e.s.t",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "dust",
    "segs": "d.u.s.t",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "went",
    "segs": "w.e.n.t",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "rest",
    "segs": "r.e.s.t",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "hunt",
    "segs": "h.u.n.t",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "soft",
    "segs": "s.o.f.t",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "bump",
    "segs": "b.u.m.p",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "fist",
    "segs": "f.i.s.t",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "left",
    "segs": "l.e.f.t",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "lift",
    "segs": "l.i.f.t",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "next",
    "segs": "n.e.x.t",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "lost",
    "segs": "l.o.s.t",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "lump",
    "segs": "l.u.m.p",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "must",
    "segs": "m.u.s.t",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "bulb",
    "segs": "b.u.l.b",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "bend",
    "segs": "b.e.n.d",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "send",
    "segs": "s.e.n.d",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "camp",
    "segs": "c.a.m.p",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "melt",
    "segs": "m.e.l.t",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "damp",
    "segs": "d.a.m.p",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "just",
    "segs": "j.u.s.t",
    "unit": "IC8",
    "tags": [
      "new",
      "dictation-safe"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The dog can wag.",
    "maxUnit": "IC6",
    "special": [
      "the"
    ]
  },
  {
    "text": "A wig is on a peg.",
    "maxUnit": "IC6",
    "special": [
      "a"
    ]
  },
  {
    "text": "The jug is on the mat.",
    "maxUnit": "IC6",
    "special": [
      "the"
    ]
  },
  {
    "text": "Mum met the vet.",
    "maxUnit": "IC6",
    "special": [
      "the"
    ]
  },
  {
    "text": "The dog ran in the sun.",
    "maxUnit": "IC6",
    "special": [
      "the"
    ]
  },
  {
    "text": "A kid had a bun.",
    "maxUnit": "IC6",
    "special": [
      "a"
    ]
  },
  {
    "text": "A lid is on the pot.",
    "maxUnit": "IC6",
    "special": [
      "a",
      "the"
    ]
  },
  {
    "text": "The pup ran in the sun.",
    "maxUnit": "IC6",
    "special": [
      "the"
    ]
  }
] as const;

export const chains = [
  [
    "vimp",
    "limp",
    "lamp",
    "lap",
    "cap",
    "cat",
    "bat",
    "bag"
  ],
  [
    "jump",
    "bump",
    "lump",
    "lamp",
    "lap",
    "cap",
    "camp",
    "damp"
  ],
  [
    "ant",
    "an",
    "and",
    "end",
    "bend",
    "send",
    "sand",
    "hand"
  ]
] as const;

export const nonsense = [
  "vimp"
] as const;

export const poly = [] as const;
