// Generated by scripts/content/build-unit.ts. Official Sounds~Write September 2024 policy.
export const words = [
  {
    "text": "frog",
    "segs": "f.r.o.g",
    "unit": "IC9",
    "pic": "a frog",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "dress",
    "segs": "d.r.e.ss",
    "unit": "IC9",
    "pic": "one simple bright red child-sized dress on a plain hanger, clear fitted bodice and wide flared skirt, shown full length with no person",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "drum",
    "segs": "d.r.u.m",
    "unit": "IC9",
    "pic": "a drum",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "swim",
    "segs": "s.w.i.m",
    "unit": "IC9",
    "pic": "a child actively swimming across a little patch of bright blue water, side view with face above the water and one arm reaching forward in a swimming stroke, small splashes around them",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "flag",
    "segs": "f.l.a.g",
    "unit": "IC9",
    "pic": "a flag",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "crab",
    "segs": "c.r.a.b",
    "unit": "IC9",
    "pic": "a crab",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "plum",
    "segs": "p.l.u.m",
    "unit": "IC9",
    "pic": "a plum",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "plug",
    "segs": "p.l.u.g",
    "unit": "IC9",
    "pic": "a plug",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "pram",
    "segs": "p.r.a.m",
    "unit": "IC9",
    "pic": "a pram",
    "tags": [
      "new",
      "picture"
    ]
  },
  {
    "text": "twig",
    "segs": "t.w.i.g",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "flap",
    "segs": "f.l.a.p",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "slam",
    "segs": "s.l.a.m",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "plod",
    "segs": "p.l.o.d",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "stop",
    "segs": "s.t.o.p",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "clap",
    "segs": "c.l.a.p",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "smell",
    "segs": "s.m.e.ll",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "step",
    "segs": "s.t.e.p",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "sniff",
    "segs": "s.n.i.ff",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "spot",
    "segs": "s.p.o.t",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "grin",
    "segs": "g.r.i.n",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "snap",
    "segs": "s.n.a.p",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "skip",
    "segs": "s.k.i.p",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "from",
    "segs": "f.r.o.m",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "stuff",
    "segs": "s.t.u.ff",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "flat",
    "segs": "f.l.a.t",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "spin",
    "segs": "s.p.i.n",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "glad",
    "segs": "g.l.a.d",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "twin",
    "segs": "t.w.i.n",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "snip",
    "segs": "s.n.i.p",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "flop",
    "segs": "f.l.o.p",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "drip",
    "segs": "d.r.i.p",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "flip",
    "segs": "f.l.i.p",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "slip",
    "segs": "s.l.i.p",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "swam",
    "segs": "s.w.a.m",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "trot",
    "segs": "t.r.o.t",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "trip",
    "segs": "t.r.i.p",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "trap",
    "segs": "t.r.a.p",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "grip",
    "segs": "g.r.i.p",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "clip",
    "segs": "c.l.i.p",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  },
  {
    "text": "slim",
    "segs": "s.l.i.m",
    "unit": "IC9",
    "tags": [
      "new",
      "dictation-safe"
    ]
  }
] as const;

export const sentences = [
  {
    "text": "The fox ran up the hill.",
    "maxUnit": "IC7",
    "special": [
      "the"
    ]
  },
  {
    "text": "A fox ran off.",
    "maxUnit": "IC7",
    "special": [
      "a"
    ]
  },
  {
    "text": "The doll sat on a rug.",
    "maxUnit": "IC7",
    "special": [
      "the",
      "a"
    ]
  },
  {
    "text": "A bell fell in the well.",
    "maxUnit": "IC7",
    "special": [
      "a",
      "the"
    ]
  },
  {
    "text": "A fox sat on a hill.",
    "maxUnit": "IC7",
    "special": [
      "a"
    ]
  },
  {
    "text": "The dog can wag.",
    "maxUnit": "IC7",
    "special": [
      "the"
    ]
  },
  {
    "text": "A wig is on a peg.",
    "maxUnit": "IC7",
    "special": [
      "a"
    ]
  },
  {
    "text": "The jug is on the mat.",
    "maxUnit": "IC7",
    "special": [
      "the"
    ]
  }
] as const;

export const chains = [
  [
    "frog",
    "fog",
    "dog",
    "doll",
    "dot",
    "cot",
    "cat",
    "at"
  ],
  [
    "swim",
    "slim",
    "slip",
    "lip",
    "clip",
    "clap",
    "flap",
    "flag"
  ],
  [
    "flag",
    "flap",
    "lap",
    "clap",
    "clip",
    "flip",
    "slip",
    "skip"
  ]
] as const;

export const nonsense = [] as const;

export const poly = [] as const;
