// Generated by scripts/content/build-poly.ts. PW stages are local staging.
export const words = [] as const;

export const sentences = [] as const;

export const chains = [] as const;

export const poly = [
  {
    "text": "sunset",
    "syllables": "sun|set"
  },
  {
    "text": "upset",
    "syllables": "up|set"
  },
  {
    "text": "comic",
    "syllables": "co|mic"
  },
  {
    "text": "zigzag",
    "syllables": "zig|zag"
  },
  {
    "text": "sunlit",
    "syllables": "sun|lit"
  },
  {
    "text": "wigwam",
    "syllables": "wig|wam"
  },
  {
    "text": "cobweb",
    "syllables": "cob|web"
  },
  {
    "text": "nutmeg",
    "syllables": "nut|meg"
  },
  {
    "text": "bedbug",
    "syllables": "bed|bug"
  },
  {
    "text": "hotdog",
    "syllables": "hot|dog"
  },
  {
    "text": "kidnap",
    "syllables": "kid|nap"
  },
  {
    "text": "pigpen",
    "syllables": "pig|pen"
  },
  {
    "text": "dogleg",
    "syllables": "dog|leg"
  },
  {
    "text": "admit",
    "syllables": "ad|mit"
  },
  {
    "text": "cabin",
    "syllables": "ca|bin"
  }
] as const;
