// Generated by scripts/content/build-poly.ts. PW stages are local staging.
export const words = [] as const;

export const sentences = [] as const;

export const chains = [] as const;

export const poly = [
  {
    "text": "insect",
    "syllables": "in|sect"
  },
  {
    "text": "dentist",
    "syllables": "den|tist"
  },
  {
    "text": "desktop",
    "syllables": "desk|top"
  },
  {
    "text": "project",
    "syllables": "pro|ject"
  },
  {
    "text": "invent",
    "syllables": "in|vent"
  },
  {
    "text": "object",
    "syllables": "ob|ject"
  },
  {
    "text": "himself",
    "syllables": "him|self"
  },
  {
    "text": "eggshell",
    "syllables": "egg|shell"
  },
  {
    "text": "jackpot",
    "syllables": "jack|pot"
  },
  {
    "text": "chopstick",
    "syllables": "chop|stick"
  },
  {
    "text": "dishcloth",
    "syllables": "dish|cloth"
  },
  {
    "text": "acting",
    "syllables": "ac|ting"
  },
  {
    "text": "padlock",
    "syllables": "pad|lock"
  },
  {
    "text": "backpack",
    "syllables": "back|pack"
  },
  {
    "text": "lipstick",
    "syllables": "lip|stick"
  },
  {
    "text": "wingspan",
    "syllables": "wing|span"
  },
  {
    "text": "sandpit",
    "syllables": "sand|pit"
  },
  {
    "text": "plastic",
    "syllables": "plas|tic"
  },
  {
    "text": "finish",
    "syllables": "fi|nish"
  },
  {
    "text": "sunset",
    "syllables": "sun|set"
  },
  {
    "text": "upset",
    "syllables": "up|set"
  },
  {
    "text": "comic",
    "syllables": "co|mic"
  },
  {
    "text": "zigzag",
    "syllables": "zig|zag"
  },
  {
    "text": "sunlit",
    "syllables": "sun|lit"
  },
  {
    "text": "wigwam",
    "syllables": "wig|wam"
  },
  {
    "text": "cobweb",
    "syllables": "cob|web"
  },
  {
    "text": "nutmeg",
    "syllables": "nut|meg"
  },
  {
    "text": "bedbug",
    "syllables": "bed|bug"
  },
  {
    "text": "hotdog",
    "syllables": "hot|dog"
  },
  {
    "text": "kidnap",
    "syllables": "kid|nap"
  }
] as const;
