// Generated by scripts/content/build-poly.ts. PW stages are local staging.
export const words = [] as const;

export const sentences = [] as const;

export const chains = [] as const;

export const poly = [
  {
    "text": "inspect",
    "syllables": "in|spect"
  },
  {
    "text": "abstract",
    "syllables": "ab|stract"
  },
  {
    "text": "splendid",
    "syllables": "splen|did"
  },
  {
    "text": "fantastic",
    "syllables": "fan|tas|tic"
  },
  {
    "text": "benefit",
    "syllables": "be|ne|fit"
  },
  {
    "text": "habitat",
    "syllables": "ha|bi|tat"
  },
  {
    "text": "compliment",
    "syllables": "com|pli|ment"
  },
  {
    "text": "triplet",
    "syllables": "tri|plet"
  },
  {
    "text": "sunlit",
    "syllables": "sun|lit"
  },
  {
    "text": "address",
    "syllables": "a|ddress",
    "schwa": [
      0
    ]
  },
  {
    "text": "carrot",
    "syllables": "ca|rrot",
    "schwa": [
      1
    ]
  },
  {
    "text": "hundred",
    "syllables": "hun|dred",
    "schwa": [
      1
    ]
  },
  {
    "text": "kitchen",
    "syllables": "ki|tchen",
    "schwa": [
      1
    ]
  },
  {
    "text": "lemon",
    "syllables": "le|mon",
    "schwa": [
      1
    ]
  },
  {
    "text": "lesson",
    "syllables": "le|sson",
    "schwa": [
      1
    ]
  },
  {
    "text": "salad",
    "syllables": "sa|lad",
    "schwa": [
      1
    ]
  },
  {
    "text": "seven",
    "syllables": "se|ven",
    "schwa": [
      1
    ]
  },
  {
    "text": "collect",
    "syllables": "co|llect",
    "schwa": [
      0
    ]
  },
  {
    "text": "equipment",
    "syllables": "e|quip|ment",
    "schwa": [
      0
    ]
  },
  {
    "text": "contradict",
    "syllables": "con|tra|dict"
  },
  {
    "text": "insect",
    "syllables": "in|sect"
  },
  {
    "text": "dentist",
    "syllables": "den|tist"
  },
  {
    "text": "desktop",
    "syllables": "desk|top"
  },
  {
    "text": "project",
    "syllables": "pro|ject"
  },
  {
    "text": "invent",
    "syllables": "in|vent"
  },
  {
    "text": "object",
    "syllables": "ob|ject"
  },
  {
    "text": "himself",
    "syllables": "him|self"
  },
  {
    "text": "eggshell",
    "syllables": "egg|shell"
  },
  {
    "text": "jackpot",
    "syllables": "jack|pot"
  },
  {
    "text": "chopstick",
    "syllables": "chop|stick"
  }
] as const;
