// Generated by scripts/content/build-poly.ts. PW stages are local staging.
export const words = [] as const;

export const sentences = [] as const;

export const chains = [] as const;

export const poly = [
  {
    "text": "daybreak",
    "syllables": "day|break"
  },
  {
    "text": "painting",
    "syllables": "pain|ting"
  },
  {
    "text": "sunday",
    "syllables": "sun|day"
  },
  {
    "text": "reading",
    "syllables": "rea|ding"
  },
  {
    "text": "indeed",
    "syllables": "in|deed"
  },
  {
    "text": "landscape",
    "syllables": "land|scape"
  },
  {
    "text": "handshake",
    "syllables": "hand|shake"
  },
  {
    "text": "meaning",
    "syllables": "mea|ning"
  },
  {
    "text": "window",
    "syllables": "win|dow"
  },
  {
    "text": "yellow",
    "syllables": "ye|llow"
  },
  {
    "text": "fishbowl",
    "syllables": "fish|bowl"
  },
  {
    "text": "snowflake",
    "syllables": "snow|flake"
  },
  {
    "text": "password",
    "syllables": "pass|word"
  },
  {
    "text": "sunburn",
    "syllables": "sun|burn"
  },
  {
    "text": "dirty",
    "syllables": "dir|ty"
  },
  {
    "text": "author",
    "syllables": "au|thor",
    "schwa": [
      1
    ]
  },
  {
    "text": "water",
    "syllables": "wa|ter",
    "schwa": [
      1
    ]
  },
  {
    "text": "haircut",
    "syllables": "hair|cut"
  },
  {
    "text": "somewhere",
    "syllables": "some|where"
  },
  {
    "text": "staircase",
    "syllables": "stair|case"
  },
  {
    "text": "airline",
    "syllables": "air|line"
  },
  {
    "text": "toilet",
    "syllables": "toi|let",
    "schwa": [
      1
    ]
  },
  {
    "text": "partner",
    "syllables": "part|ner",
    "schwa": [
      1
    ]
  },
  {
    "text": "oyster",
    "syllables": "oys|ter",
    "schwa": [
      1
    ]
  },
  {
    "text": "target",
    "syllables": "tar|get",
    "schwa": [
      1
    ]
  },
  {
    "text": "bottle",
    "syllables": "bot|tle",
    "schwa": [
      1
    ]
  },
  {
    "text": "rotten",
    "syllables": "rot|ten",
    "schwa": [
      1
    ]
  },
  {
    "text": "payment",
    "syllables": "pay|ment",
    "schwa": [
      1
    ]
  },
  {
    "text": "holiday",
    "syllables": "hol|i|day",
    "schwa": [
      1
    ]
  },
  {
    "text": "chimney",
    "syllables": "chim|ney",
    "schwa": [
      1
    ]
  }
] as const;
