// Generated by scripts/content/build-poly.ts. PW stages are local staging.
export const words = [] as const;

export const sentences = [] as const;

export const chains = [] as const;

export const poly = [
  {
    "text": "farmer",
    "syllables": "far|mer",
    "schwa": [
      1
    ]
  },
  {
    "text": "baker",
    "syllables": "ba|ker",
    "schwa": [
      1
    ]
  },
  {
    "text": "faster",
    "syllables": "fas|ter",
    "schwa": [
      1
    ]
  },
  {
    "text": "after",
    "syllables": "af|ter",
    "schwa": [
      1
    ]
  },
  {
    "text": "children",
    "syllables": "chil|dren"
  },
  {
    "text": "about",
    "syllables": "a|bout",
    "schwa": [
      0
    ]
  },
  {
    "text": "multiply",
    "syllables": "mul|ti|ply"
  },
  {
    "text": "picture",
    "syllables": "pic|ture",
    "schwa": [
      1
    ]
  },
  {
    "text": "location",
    "syllables": "lo|ca|tion"
  },
  {
    "text": "enormous",
    "syllables": "e|nor|mous",
    "schwa": [
      0,
      2
    ]
  },
  {
    "text": "musician",
    "syllables": "mu|si|cian",
    "schwa": [
      0,
      2
    ]
  },
  {
    "text": "author",
    "syllables": "au|thor",
    "schwa": [
      1
    ]
  },
  {
    "text": "water",
    "syllables": "wa|ter",
    "schwa": [
      1
    ]
  },
  {
    "text": "haircut",
    "syllables": "hair|cut"
  },
  {
    "text": "somewhere",
    "syllables": "some|where"
  },
  {
    "text": "staircase",
    "syllables": "stair|case"
  },
  {
    "text": "airline",
    "syllables": "air|line"
  },
  {
    "text": "toilet",
    "syllables": "toi|let",
    "schwa": [
      1
    ]
  },
  {
    "text": "partner",
    "syllables": "part|ner",
    "schwa": [
      1
    ]
  },
  {
    "text": "oyster",
    "syllables": "oys|ter",
    "schwa": [
      1
    ]
  },
  {
    "text": "target",
    "syllables": "tar|get",
    "schwa": [
      1
    ]
  },
  {
    "text": "bottle",
    "syllables": "bot|tle",
    "schwa": [
      1
    ]
  },
  {
    "text": "rotten",
    "syllables": "rot|ten",
    "schwa": [
      1
    ]
  },
  {
    "text": "payment",
    "syllables": "pay|ment",
    "schwa": [
      1
    ]
  },
  {
    "text": "holiday",
    "syllables": "hol|i|day",
    "schwa": [
      1
    ]
  },
  {
    "text": "chimney",
    "syllables": "chim|ney",
    "schwa": [
      1
    ]
  },
  {
    "text": "litre",
    "syllables": "li|tre",
    "schwa": [
      1
    ]
  },
  {
    "text": "solar",
    "syllables": "so|lar",
    "schwa": [
      1
    ]
  },
  {
    "text": "favour",
    "syllables": "fa|vour",
    "schwa": [
      1
    ]
  },
  {
    "text": "collar",
    "syllables": "co|llar",
    "schwa": [
      1
    ]
  }
] as const;
