// Generated by scripts/content/build-poly.ts. PW stages are local staging.
export const words = [] as const;

export const sentences = [] as const;

export const chains = [] as const;

export const poly = [
  {
    "text": "author",
    "syllables": "au|thor",
    "schwa": [
      1
    ]
  },
  {
    "text": "water",
    "syllables": "wa|ter",
    "schwa": [
      1
    ]
  },
  {
    "text": "haircut",
    "syllables": "hair|cut"
  },
  {
    "text": "somewhere",
    "syllables": "some|where"
  },
  {
    "text": "staircase",
    "syllables": "stair|case"
  },
  {
    "text": "airline",
    "syllables": "air|line"
  },
  {
    "text": "toilet",
    "syllables": "toi|let",
    "schwa": [
      1
    ]
  },
  {
    "text": "partner",
    "syllables": "part|ner",
    "schwa": [
      1
    ]
  },
  {
    "text": "oyster",
    "syllables": "oys|ter",
    "schwa": [
      1
    ]
  },
  {
    "text": "target",
    "syllables": "tar|get",
    "schwa": [
      1
    ]
  },
  {
    "text": "bottle",
    "syllables": "bot|tle",
    "schwa": [
      1
    ]
  },
  {
    "text": "rotten",
    "syllables": "rot|ten",
    "schwa": [
      1
    ]
  },
  {
    "text": "payment",
    "syllables": "pay|ment",
    "schwa": [
      1
    ]
  },
  {
    "text": "holiday",
    "syllables": "hol|i|day",
    "schwa": [
      1
    ]
  },
  {
    "text": "chimney",
    "syllables": "chim|ney",
    "schwa": [
      1
    ]
  },
  {
    "text": "litre",
    "syllables": "li|tre",
    "schwa": [
      1
    ]
  },
  {
    "text": "solar",
    "syllables": "so|lar",
    "schwa": [
      1
    ]
  },
  {
    "text": "favour",
    "syllables": "fa|vour",
    "schwa": [
      1
    ]
  },
  {
    "text": "collar",
    "syllables": "co|llar",
    "schwa": [
      1
    ]
  },
  {
    "text": "savvy",
    "syllables": "sa|vvy",
    "schwa": [
      1
    ]
  },
  {
    "text": "skivvy",
    "syllables": "ski|vvy",
    "schwa": [
      1
    ]
  },
  {
    "text": "evening",
    "syllables": "e|ve|ning",
    "schwa": [
      0
    ]
  },
  {
    "text": "season",
    "syllables": "sea|son",
    "schwa": [
      1
    ]
  },
  {
    "text": "piano",
    "syllables": "pi|a|no",
    "schwa": [
      1
    ]
  },
  {
    "text": "notebook",
    "syllables": "note|book"
  },
  {
    "text": "kneecap",
    "syllables": "knee|cap"
  },
  {
    "text": "routine",
    "syllables": "rou|tine"
  },
  {
    "text": "olive",
    "syllables": "o|live",
    "schwa": [
      0
    ]
  },
  {
    "text": "shampoo",
    "syllables": "sham|poo"
  },
  {
    "text": "together",
    "syllables": "to|geth|er",
    "schwa": [
      0,
      2
    ]
  }
] as const;
