// Generated by scripts/content/build-poly.ts. PW stages are local staging.
export const words = [] as const;

export const sentences = [] as const;

export const chains = [] as const;

export const poly = [
  {
    "text": "fantastic",
    "syllables": "fan|tas|tic"
  },
  {
    "text": "demonstrate",
    "syllables": "de|mon|strate"
  },
  {
    "text": "multiplication",
    "syllables": "mul|ti|pli|ca|tion",
    "schwa": [
      4
    ]
  },
  {
    "text": "absolutely",
    "syllables": "ab|so|lute|ly",
    "schwa": [
      0,
      2,
      3
    ]
  },
  {
    "text": "biography",
    "syllables": "bi|o|gra|phy",
    "schwa": [
      1,
      3
    ]
  },
  {
    "text": "automatic",
    "syllables": "au|to|mat|ic",
    "schwa": [
      0,
      2
    ]
  },
  {
    "text": "holiday",
    "syllables": "hol|i|day",
    "schwa": [
      1
    ]
  },
  {
    "text": "evening",
    "syllables": "e|ve|ning",
    "schwa": [
      0
    ]
  },
  {
    "text": "piano",
    "syllables": "pi|a|no",
    "schwa": [
      1
    ]
  },
  {
    "text": "together",
    "syllables": "to|geth|er",
    "schwa": [
      0,
      2
    ]
  },
  {
    "text": "tomato",
    "syllables": "to|ma|to",
    "schwa": [
      0
    ]
  },
  {
    "text": "potato",
    "syllables": "po|ta|to",
    "schwa": [
      0
    ]
  },
  {
    "text": "uniform",
    "syllables": "u|ni|form",
    "schwa": [
      0
    ]
  },
  {
    "text": "animal",
    "syllables": "an|i|mal",
    "schwa": [
      0,
      2
    ]
  },
  {
    "text": "elephant",
    "syllables": "el|e|phant",
    "schwa": [
      0,
      2
    ]
  },
  {
    "text": "butterfly",
    "syllables": "but|ter|fly"
  },
  {
    "text": "hospital",
    "syllables": "hos|pi|tal",
    "schwa": [
      0,
      2
    ]
  },
  {
    "text": "important",
    "syllables": "im|por|tant",
    "schwa": [
      0,
      2
    ]
  },
  {
    "text": "yesterday",
    "syllables": "yes|ter|day",
    "schwa": [
      1
    ]
  },
  {
    "text": "tomorrow",
    "syllables": "to|mor|row",
    "schwa": [
      0,
      2
    ]
  },
  {
    "text": "decorate",
    "syllables": "de|co|rate",
    "schwa": [
      1,
      2
    ]
  },
  {
    "text": "hesitate",
    "syllables": "hes|i|tate",
    "schwa": [
      1
    ]
  },
  {
    "text": "container",
    "syllables": "con|tain|er",
    "schwa": [
      1
    ]
  },
  {
    "text": "heavily",
    "syllables": "heav|i|ly",
    "schwa": [
      1,
      2
    ]
  },
  {
    "text": "happily",
    "syllables": "hap|pi|ly",
    "schwa": [
      1,
      2
    ]
  },
  {
    "text": "radio",
    "syllables": "ra|di|o",
    "schwa": [
      1
    ]
  },
  {
    "text": "sympathy",
    "syllables": "sym|pa|thy",
    "schwa": [
      1,
      2
    ]
  },
  {
    "text": "episode",
    "syllables": "ep|i|sode",
    "schwa": [
      0,
      2
    ]
  },
  {
    "text": "typical",
    "syllables": "ty|pi|cal",
    "schwa": [
      0,
      2
    ]
  },
  {
    "text": "magazine",
    "syllables": "mag|a|zine",
    "schwa": [
      1,
      2
    ]
  }
] as const;
