// Generated by scripts/content/build-poly.ts. PW stages are local staging.
export const words = [] as const;

export const sentences = [] as const;

export const chains = [] as const;

export const poly = [
  {
    "text": "chlorophyll",
    "syllables": "chlo|ro|phyll",
    "schwa": [
      1
    ]
  },
  {
    "text": "multiplication",
    "syllables": "mul|ti|pli|ca|tion",
    "schwa": [
      4
    ]
  },
  {
    "text": "autobiographical",
    "syllables": "au|to|bi|o|gra|phi|cal",
    "schwa": [
      3,
      6
    ]
  },
  {
    "text": "disastrous",
    "syllables": "di|sas|trous",
    "schwa": [
      2
    ]
  },
  {
    "text": "photograph",
    "syllables": "pho|to|graph",
    "schwa": [
      1,
      2
    ]
  },
  {
    "text": "biography",
    "syllables": "bi|o|gra|phy",
    "schwa": [
      1,
      3
    ]
  },
  {
    "text": "volcanic",
    "syllables": "vol|can|ic",
    "schwa": [
      0
    ]
  },
  {
    "text": "chemistry",
    "syllables": "chem|is|try",
    "schwa": [
      1,
      2
    ]
  },
  {
    "text": "mechanic",
    "syllables": "me|chan|ic",
    "schwa": [
      1
    ]
  },
  {
    "text": "character",
    "syllables": "cha|rac|ter",
    "schwa": [
      1,
      2
    ]
  },
  {
    "text": "alphabet",
    "syllables": "al|pha|bet",
    "schwa": [
      0,
      2
    ]
  },
  {
    "text": "astronaut",
    "syllables": "as|tro|naut",
    "schwa": [
      2
    ]
  },
  {
    "text": "digital",
    "syllables": "di|gi|tal",
    "schwa": [
      0,
      2
    ]
  },
  {
    "text": "register",
    "syllables": "re|gis|ter",
    "schwa": [
      1,
      2
    ]
  },
  {
    "text": "automatic",
    "syllables": "au|to|mat|ic",
    "schwa": [
      0,
      2
    ]
  },
  {
    "text": "improvement",
    "syllables": "im|prove|ment",
    "schwa": [
      0
    ]
  },
  {
    "text": "sympathy",
    "syllables": "sym|pa|thy",
    "schwa": [
      1,
      2
    ]
  },
  {
    "text": "episode",
    "syllables": "ep|i|sode",
    "schwa": [
      0,
      2
    ]
  },
  {
    "text": "disinfect",
    "syllables": "dis|in|fect",
    "schwa": [
      0
    ]
  },
  {
    "text": "dangerous",
    "syllables": "dan|ger|ous",
    "schwa": [
      1,
      2
    ]
  },
  {
    "text": "absolutely",
    "syllables": "ab|so|lute|ly",
    "schwa": [
      0,
      2,
      3
    ]
  },
  {
    "text": "holiday",
    "syllables": "hol|i|day",
    "schwa": [
      1
    ]
  },
  {
    "text": "evening",
    "syllables": "e|ve|ning",
    "schwa": [
      0
    ]
  },
  {
    "text": "piano",
    "syllables": "pi|a|no",
    "schwa": [
      1
    ]
  },
  {
    "text": "together",
    "syllables": "to|geth|er",
    "schwa": [
      0,
      2
    ]
  },
  {
    "text": "tomato",
    "syllables": "to|ma|to",
    "schwa": [
      0
    ]
  },
  {
    "text": "potato",
    "syllables": "po|ta|to",
    "schwa": [
      0
    ]
  },
  {
    "text": "uniform",
    "syllables": "u|ni|form",
    "schwa": [
      0
    ]
  },
  {
    "text": "animal",
    "syllables": "an|i|mal",
    "schwa": [
      0,
      2
    ]
  },
  {
    "text": "elephant",
    "syllables": "el|e|phant",
    "schwa": [
      0,
      2
    ]
  }
] as const;
