  // --- Teacher voice (docs/TEACHER_SCRIPT.md, 27 Sep).
  // Owned by the teacher-voice lines lane (docs/FIX_PLAN_PERF_SCRIPT_SOUNDS.md §13, TV-F2.1); edit only this block. The
  // 339 ids of TS §7.1, generated from the script by playtest/voice/make-block.py; each generated family (TS's <w>,
  // <n>, <p>, <pair>, <game>, <reader>) is one whole recording per member. A lead-in ends on "..." and is recorded
  // suspended, so a pure sound or a word can follow it. Sub-headings name the screen for jev-lint-lines.
  // --- Early learning (teacher voice, TS §2.3): The readiness interaction
  s("tv_ready_first", "Look, your ninja is ready. Are you ready too? Tap the green arrow."),
  s("tv_ready_paw", "Do you want to have a go now? Tap the green arrow. Or tap my paw to see it again."),
  s("tv_show_again", "Of course. Watch my paw again."),
  s("tv_ready_now", "Are you ready to have a go now?"),
  s("tv_ready_go", "Do you want to have a go now?"),
  s("tv_ready_together", "Let's do the next one together. Are you ready?"),
  s("tv_ready_yours", "Now you do one. Are you ready?"),
  s("tv_ready_to_watch", "I'll show you first. Are you ready to watch? Tap the green arrow."),
  s("tv_turn_again", "Now it's your turn again."),
  s("tv_offer_show", "Or I can show you again. Just tap my paw."),
  s("tv_ready_help", "When you're ready, tap the green arrow. To see it again, tap my paw."),
  // --- Title (teacher voice, TS §3.1): The film
  s("tv_film_arrow", "When you're ready to see what happens next, tap the green arrow."),
  // --- First minutes (teacher voice, TS §3.2): Choose your ninja
  s("tv_choose_q", "First, choose your ninja. Will it be Kai, or Suki?"),
  s("tv_choose_hello", "Hello! I'm Sensei Maple, and I'm going to be your teacher."),
  s("tv_choose_why", "Baron Muddle took the sounds away. We'll win them back by playing games together."),
  s("tv_choose_ninja", "Your ninja will play every game with you."),
  // --- First minutes (teacher voice, TS §3.3): The opt-in: "Do you go to big school yet?"
  s("tv_opt_why", "First, let's find the right games for you."),
  s("tv_opt_notyet", "If you don't go yet, tap the teddy."),
  s("tv_opt_yes", "If you do, tap the school."),
  s("tv_opt_echo_notyet", "Not yet. That's fine."),
  s("tv_opt_echo_school", "You go to big school."),
  s("tv_opt_again", "If you don't go yet, tap the teddy. If you do, tap the school."),
  s("tv_opt_ask", "Ask a grown-up to help you choose."),
  s("tv_opt_ok_notyet", "Then we'll start with some listening games, just for you."),
  s("tv_opt_grownups", "Grown-ups, you can change this later in the settings."),
  s("tv_opt_to_dojo", "Now come with me to the dojo. Tap the green arrow."),
  // --- Ninja Training (teacher voice, TS §3.4): The dojo welcome: three ninja tricks (Training.tsx)
  s("tv_train_tricks", "I'll teach you three ninja tricks. Each one wins a star."),
  s("tv_train_help", "Here's trick two. If you're ever stuck, tap me, down here in the corner."),
  s("tv_train_speaker", "Here's trick three, the speaker. First, listen to my little ninja rhyme."),
  s("tv_train_hello", "Welcome to my dojo. A dojo is a school for ninjas."),
  s("tv_train_gong", "Trick one is the gong. Tap it, and your ninja will kick it."),
  s("tv_train_gong_ok", "Bong! That's your first star."),
  s("tv_train_try_help", "Can you tap me now?"),
  s("tv_rhyme", "Tip, tap, tiptoe, quiet as a mouse."),
  s("tv_train_hear_again", "Tap the speaker, and I'll say it again."),
  s("tv_train_speaker_ok", "That's it! The speaker always says it again."),
  s("tv_train_done", "Three tricks, three stars. Now you're ready for your first game."),
  s("tv_first_game", "It's a listening game, called Ninja Ears. Tap the green arrow when you're ready."),
  // --- First minutes (teacher voice, TS §3.5): W1, Ninja Ears: the first lesson
  s("tv_pocket_ready_two", "Now you find the other two. Are you ready?"),
  s("tv_pocket_ready_three", "Now you find the other three. Are you ready?"),
  s("tv_ts_meet", "Here are my friends, the rabbit and the tortoise."),
  s("tv_ts_fast", "The rabbit says words fast..."),
  s("tv_ts_slow", "The tortoise says them slowly..."),
  s("tv_ears_on", "Look, your ninja has its ninja ears on. That means listening really carefully."),
  s("tv_petal_first", "That sound has its very own petal. Tap the petal, and say the sound with me."),
  s("tv_pocket_frame", "In Pocket Hunt, we find pictures that start with this sound."),
  s("tv_so_pocket", "So into the pocket it goes!"),
  s("tv_ears_frame", "I'll say a word. Then you find its picture."),
  s("tv_ears_demo", "I'll go first. My word is sun... There it is!"),
  s("tv_your_word_sock", "Your word is sock. Can you find the sock?"),
  s("tv_find_again_sock", "Can you find the sock?"),
  s("tv_idle_look_sock", "Have a look at each picture. Where's the sock?"),
  s("tv_show_offer", "Not sure? Tap my paw, and I'll show you again."),
  s("tv_idle_point", "Here it is. Tap it when you're ready."),
  s("tv_fix_together", "Let's do it together. It's this one. Now you tap it."),
  s("tv_same_word", "Fast or slow, it's the same word. When I say it slowly, I can hear its sounds."),
  s("tv_ts_wrong_rabbit", "That's my rabbit. It says words fast. Now tap the tortoise to say it slowly."),
  s("tv_ts_wrong_tortoise", "That's my tortoise. It says words slowly. Now tap the rabbit to say it fast."),
  s("tv_notice_frame", "Now let's listen for the very first sound."),
  s("tv_tap_hear_sun", "Tap the sun, and listen to how it starts."),
  s("tv_now_tap_hear_sock", "Now tap the sock, and listen to how it starts."),
  s("tv_pocket_ido", "I'll find one first."),
  s("tv_fix_start", "Listen for the start..."),
  s("tv_petal_hint", "Tap the petal if you want to hear the sound again."),
  s("tv_w1_end", "That's the end of Ninja Ears. Now watch what happens to your pictures."),
  // --- Sticker Book (teacher voice, TS §3.6): Reward 1: the Sticker Book
  s("tv_rw_book", "This is your Sticker Book! Tap it to open it."),
  s("tv_rw_every", "Every picture you play with becomes a sticker."),
  s("tv_rw_tap", "Tap a sticker, and it will say its word."),
  s("tv_rw_fast_slow", "Fast, then slow, like the rabbit and the tortoise!"),
  s("tv_rw_next", "Next, we're going to read some pictures, the ninja way. Tap the green arrow when you're ready."),
  // --- First minutes (teacher voice, TS §3.7): W2, Ninja Reading: the second lesson
  s("tv_rail_ready", "Now you read them. Do you want to have a go?"),
  s("tv_squish_ready", "Two little words make one big word. Now you make one. Are you ready?"),
  s("tv_next_game", "When you're ready for the next game, tap the green arrow."),
  s("tv_rail_frame", "Let's play Ninja Reading. Ninjas always start on this side, and go this way."),
  s("tv_which_frame", "Here are two rows of pictures. I'll read one, and you tap it."),
  s("tv_rail_ido", "I'll read them first. Then you read them."),
  s("tv_rail_turn", "Tap each picture, starting on this side."),
  s("tv_silly", "What a silly animal!"),
  s("tv_rail_start", "Ninjas start on this side. Tap this one first."),
  s("tv_which_demo", "I'll go first. Fish... dog."),
  s("tv_which_so", "Fish came first. So I tap this row."),
  s("tv_which_q_cat_dog", "Here I go. Cat... dog. Which row did I read?"),
  s("tv_which_fix_cat_dog", "Let's listen again. Cat... dog. Which row has the cat first?"),
  s("tv_squish_frame", "Here's a new game, called Word Squish."),
  s("tv_squish_slow", "I tap the tortoise, and say them slowly. Sun... flower."),
  s("tv_squish_fast", "Then I tap the rabbit, and squish them. Sunflower!"),
  s("tv_praise_squish", "You squished them into one big word!"),
  s("tv_pocket_more_s", "One more Pocket Hunt. Find the pictures that start with..."),
  s("tv_pocket_more_m", "One more Pocket Hunt. Find the pictures that start with..."),
  s("tv_rw_link_book", "Let's put your new pictures in your Sticker Book."),
  // --- World Flower (teacher voice, TS §3.8): Reward 2, the World Flower's first glimpse, and the first map
  s("tv_rw2_flower", "This is the World Flower. Your sounds make it shine."),
  // --- Map (teacher voice, TS §3.8): Reward 2, the World Flower's first glimpse, and the first map
  s("tv_map_intro", "This is the map of Bamboo Village. Every stone is a game."),
  // --- World Flower (teacher voice, TS §3.8): Reward 2, the World Flower's first glimpse, and the first map
  s("tv_rw2_tap_petal", "Tap your petal, and hear its sound."),
  // --- Map (teacher voice, TS §3.8): Reward 2, the World Flower's first glimpse, and the first map
  s("tv_map_flower", "And your World Flower lives here."),
  s("tv_map_hint", "The glowing stone is your next game. Tap it when you're ready."),
  // --- First minutes (teacher voice, TS §3.9): W3, Ninja Ears again: Slow Words, and sounds in the middle
  s("tv_ts_again", "Here come the rabbit and the tortoise again."),
  s("tv_ts_slow_one", "The tortoise says it slowly..."),
  s("tv_praise_slowly", "You said it slowly, just like the tortoise."),
  s("tv_slow_frame", "Let's play Slow Words. I say a word slowly. You find its picture."),
  s("tv_slow_demo", "Here's my slow word..."),
  s("tv_i_hear_mug", "I can hear mug!"),
  s("tv_i_hear_sun", "I can hear sun!"),
  s("tv_slow_yours", "Here's your slow word..."),
  s("tv_slow_again", "Let's listen again..."),
  s("tv_pocket_middle", "It's Pocket Hunt again. This time, the sound is hiding in the middle of the words."),
  s("tv_here_sound", "Here's the sound..."),
  s("tv_new_petal_say", "It's a new sound. Tap its petal, and say it with me."),
  s("tv_hear_middle", "I can hear it in the middle."),
  s("tv_fix_middle", "Listen for the middle..."),
  s("tv_w3_done", "You heard sounds at the start of words, and in the middle. Super listening!"),
  // --- First minutes (teacher voice, TS §3.10): W4, Ninja Reading again: three in a row
  s("tv_rail_again", "It's Ninja Reading again. This time, there are three pictures."),
  s("tv_rail_yours", "Now you read them."),
  s("tv_which_again", "Here are two rows again. I'll read one, and you tap it."),
  s("tv_which_q_fish_dog_cat", "Here I go. Fish... dog... cat. Which row did I read?"),
  s("tv_which_fix_fish_dog_cat", "Let's listen again. Fish... dog... cat. Which row has the fish first?"),
  s("tv_squish_again", "It's Word Squish again. Two little words make one big word."),
  s("tv_w4_done", "You read three pictures in a row, the ninja way."),
  s("tv_practise_again", "That game was a bit tricky. Let's play it once more."),
  // --- First minutes (teacher voice, TS §3.11): W5, Guess My Word (sounds, full)
  s("tv_guess_frame", "I'll say the sounds, and you listen for the word."),
  s("tv_my_sounds", "My sounds are..."),
  s("tv_guess_so_sun", "I can hear sun. So I tap the sun."),
  s("tv_guess_q", "Listen for the word..."),
  s("tv_guess_together", "Let's say it together."),
  s("tv_guess_again", "Let's listen again..."),
  s("tv_w5_done", "You listened to the sounds, and you heard the words."),
  // --- First minutes (teacher voice, TS §3.12): W6, Sound Dots (dots, full)
  s("tv_dots_ready", "Now you tap the dots, and say the sounds with me. Are you ready?"),
  s("tv_dots_frame", "Every dot is one sound in the word."),
  s("tv_dots_ido", "I start here, and go this way."),
  s("tv_dots_word_ido", "Then I say the word..."),
  s("tv_now_say_word", "Now say the whole word..."),
  // --- Early learning (teacher voice, TS §3.13): w1-2, First Sounds, and the first letters
  s("tv_watch_write", "Now watch my ninja write it."),
  s("tv_how_we_write", "This is how we write..."),
  s("tv_first_frame", "In First Sounds, I say a sound, and you find the picture that starts with it."),
  s("tv_first_sound", "Our first sound is..."),
  s("tv_petal_say", "Tap the petal, and say it with me."),
  s("tv_ido_pair_map_hat", "I'll go first. Here's a map and a hat."),
  s("tv_ido_pair_bed_sock", "I'll go first. Here's a bed and a sock."),
  s("tv_ido_pair_cat_ant", "I'll go first. Here's a cat and an ant."),
  s("tv_ido_pair_jam_tent", "I'll go first. Here's some jam and a tent."),
  s("tv_ido_pair_nut_hat", "I'll go first. Here's a nut and a hat."),
  s("tv_ido_pair_bus_pig", "I'll go first. Here's a bus and a pig."),
  s("tv_ido_pair_pan_pin", "I'll go first. Here's a pan and a pin."),
  s("tv_ido_pair_map_mop", "I'll go first. Here's a map and a mop."),
  s("tv_let_me_listen", "Hmm, let me listen."),
  s("tv_so_i_tap", "So I'll tap it."),
  s("tv_tap_it_say", "Now you tap it, and say the sound."),
  s("tv_by_yourself", "Now you do one all by yourself."),
  s("tv_praise_start", "You listened right to the very start."),
  s("tv_next_sound_known", "Our next sound is one you know..."),
  s("tv_together", "Let's do this one together."),
  s("tv_and_how_we_write", "And this is how we write..."),
  s("tv_mix_up", "Now it could be either sound. Listen carefully to my sound."),
  s("tv_ne_frame", "Next, a game called Ninja Eyes. I say a sound, and you find how we write it."),
  s("tv_which_write", "Which of these is the way we write..."),
  s("tv_find_write", "Find how we write..."),
  s("tv_now_find", "Now find how we write..."),
  s("tv_thats_write", "That's how we write..."),
  s("tv_first_done", "You listened for the first sound in every word, and you found how we write it."),
  // --- Rewards (teacher voice, TS §3.14): The reward, and the World Flower's first visit (after w1-2)
  s("tv_to_reward", "Let's see what you won back from Baron Muddle."),
  s("tv_won_two", "You won back two sounds..."),
  s("tv_won_three", "You won back three sounds..."),
  s("tv_won_four", "You won back four sounds..."),
  // --- World Flower (teacher voice, TS §3.14): The reward, and the World Flower's first visit (after w1-2)
  s("tv_to_flower_first", "Now let's go and see where your sounds live. Tap the green arrow."),
  s("tv_flower_petal", "Every petal is one sound. This is the petal for..."),
  s("tv_flower_tap", "Tap it, and hear its sound."),
  s("tv_another_sound", "And here's another new sound..."),
  s("tv_flower_bye", "Your World Flower is waiting for more sounds. Let's go and find them!"),
  // --- Early learning (teacher voice, TS §3.15): w1-3, First Sounds again (/a/, /t/)
  s("tv_next_sound", "Our next sound is..."),
  s("tv_first_again_new", "It's First Sounds again, with two new sounds."),
  s("tv_first_recap", "It's First Sounds again. I say a sound, and you find the picture that starts with it."),
  s("tv_ne_again", "Now let's play Ninja Eyes."),
  // --- Early learning (teacher voice, TS §3.16): w1-4, Word Building, then Kai and Suki
  s("tv_build_lines", "Each line is for one sound."),
  s("tv_word_card", "This card is my word. Tap it, and hear the word."),
  s("tv_readers_meet", "Look, it's Kai and Suki. They're learning to read, like you."),
  s("tv_your_word", "Your word is..."),
  s("tv_build_frame", "This game is called Word Building. I say a word, and we build it with its sounds."),
  s("tv_i_say_slowly", "I say it slowly..."),
  s("tv_first_is", "The first sound is..."),
  s("tv_you_find_last", "Can you find the last one?"),
  s("tv_lets_say_read", "Now let's say the sounds... and read the word."),
  s("tv_build_ready", "Now let's build one together. Are you ready?"),
  s("tv_our_word", "Here's our word..."),
  s("tv_last_first", "Now the last sound. Listen right to the end..."),
  s("tv_by_yourself_build", "Now you build one all by yourself."),
  s("tv_praise_built", "You built that whole word by yourself!"),
  s("tv_rc_how", "They'll both read this word. Only one of them reads it right."),
  s("tv_you_read_first", "First, you read it. Tap each sound, and say it with me."),
  s("tv_now_readers", "Now listen to Kai and Suki read it."),
  s("tv_rc_q", "Who read it right? Tap Kai, or tap Suki."),
  s("tv_yes_kai", "Yes! Kai read it right."),
  s("tv_yes_suki", "Yes! Suki read it right."),
  s("tv_lets_check", "Let's check. Say the sounds with me..."),
  s("tv_right_kai", "Kai read it right."),
  s("tv_right_suki", "Suki read it right."),
  s("tv_build_done", "You built words with their sounds, and you read them."),
  // --- Early learning (teacher voice, TS §3.17): w1-5, Word Building with three sounds
  s("tv_build_again_3", "It's Word Building again. This word has three sounds, so there are three lines."),
  s("tv_next_middle", "Now the next sound. It's in the middle..."),
  s("tv_readers_back", "Kai and Suki are back. You read it first, then they read it."),
  // --- Battle (teacher voice, TS §3.18): w1-6, the first Monster Battle (battle, full)
  s("tv_battle_ready", "That's how we spell a word. Now you spell one. Are you ready to zap it?"),
  s("tv_bar_down", "Zap! Look, its bar went down."),
  s("tv_battle_oh_no", "Oh no! One of Baron Muddle's monsters is in the way!"),
  s("tv_battle_frame", "We zap it with words, just like Word Building."),
  s("tv_battle_card", "I'll zap the first one. Tap my word card, and hear the word."),
  s("tv_next_word", "Here's your next word..."),
  s("tv_battle_why", "Every monster you beat helps us win back the sounds."),
  // --- Early learning (teacher voice, TS §3.19): w1-7, Sound Hunt: a sound in the middle (soundhunt, full)
  s("tv_next_build", "Next, we're going to build some words with this sound..."),
  s("tv_hunt_frame", "In Sound Hunt, the sound is hiding in the middle of the word."),
  s("tv_swap_both", "Listen to them both..."),
  s("tv_hunt_q", "Which one has this sound in the middle..."),
  s("tv_praise_middle", "You heard it, right in the middle."),
  s("tv_not_in_middle", "That one has a different sound in the middle."),
  s("tv_hunt_done", "You heard a sound right in the middle of words. That's tricky, and you did it!"),
  // --- Swap (teacher voice, TS §3.20): w1-8, Sound Swap (swap, full)
  s("tv_swap_ready", "Now you swap one. Do you want to have a go?"),
  s("tv_swap_oh_dear", "Oh dear. Baron Muddle has been muddling up words."),
  s("tv_swap_read_first", "First, let's read this word. Tap each sound, and say it with me."),
  s("tv_swap_frame", "In Sound Swap, we change just one sound, to make a new word."),
  s("tv_swap_change_to", "I'll change it to..."),
  s("tv_swap_kick", "The first sound changes. Can you tap it, and kick it out?"),
  s("tv_swap_in", "And in goes..."),
  s("tv_swap_now_change", "Now let's change it to..."),
  s("tv_swap_pick", "Now tap the new one."),
  s("tv_praise_swap", "You changed just one sound."),
  s("tv_swap_done", "You fixed all of Baron's muddled words!"),
  // --- Run (teacher voice, TS §3.21): w1-9, Ninja Run (run, full)
  s("tv_run_ready", "Are you ready? Tap the green arrow, and off we go!"),
  s("tv_run_lanterns", "Here come the lanterns. I'll say the sounds of a word."),
  s("tv_run_frame", "This game is called Ninja Run. Your ninja runs all by itself."),
  s("tv_run_jump", "Tap anywhere to make your ninja jump. Can you try it now?"),
  s("tv_run_jump_ok", "Good jumping!"),
  s("tv_run_lanterns_how", "When the lanterns come, I'll say some sounds, and you catch the word."),
  s("tv_run_which", "Tap the lantern with my word."),
  s("tv_run_fix", "That's a different word. Listen again..."),
  // --- Early learning (teacher voice, TS §3.22): w1-10 to w1-13: the second meetings
  s("tv_next_build_plain", "Next, we're going to build some words."),
  s("tv_hunt_again", "It's Sound Hunt again, with a new sound."),
  // --- Swap (teacher voice, TS §3.22): w1-10 to w1-13: the second meetings
  s("tv_swap_again", "It's Sound Swap again. We change one sound to make a new word."),
  s("tv_show_offer_short", "If you'd like to see me do one first, tap my paw."),
  // --- Battle (teacher voice, TS §3.22): w1-10 to w1-13: the second meetings
  s("tv_battle_again", "Another monster! Let's zap it with words."),
  // --- Story (teacher voice, TS §3.23): w1-14, Story Time (story, full)
  s("tv_story_tick", "When you've read it all, tap the green tick."),
  s("tv_story_frame", "Story time! I'll read some pages to you, and you'll read some pages to me."),
  s("tv_story_title", "This story is called..."),
  s("tv_story_begin", "Tap the green arrow, and let's begin."),
  s("tv_story_yours", "This page is yours. Say the sounds, and read each word."),
  s("tv_story_help", "If you get stuck, tap a word, and I'll help."),
  s("tv_story_together", "Let's read it together."),
  s("tv_story_choice", "Now you choose what happens. Read the two words, and tap one."),
  s("tv_story_q", "Now a question about the story."),
  s("tv_story_tick_idle", "When you've read it, tap the green tick."),
  // --- Battle (teacher voice, TS §3.24): w1-15, the first boss (boss, full)
  s("tv_boss_ready", "Are you ready to beat the boss? Tap the green arrow."),
  s("tv_boss_calm", "Don't worry, ninja. You know what to do."),
  s("tv_boss_frame", "A boss takes lots of words to beat."),
  // --- Map (teacher voice, TS §3.25): The land is done: the World Flower, then Blossom Hills
  s("tv_map_next_sounds", "Next is a new game, called Guess My Word. Tap the glowing stone to play."),
  s("tv_map_next_dots", "Next is a new game, called Sound Dots. Tap the glowing stone to play."),
  s("tv_map_next_firstsound", "Next is a new game, called First Sounds. Tap the glowing stone to play."),
  s("tv_map_next_build", "Next is a new game, called Word Building. Tap the glowing stone to play."),
  s("tv_map_next_battle", "Next is a Monster Battle. Baron Muddle's monsters are guarding the sounds. Tap the glowing stone, if you're brave."),
  s("tv_map_next_soundhunt", "Next is a new game, called Sound Hunt. Tap the glowing stone to play."),
  s("tv_map_next_swap", "Next is a new game, called Sound Swap. Baron Muddle has mixed up some words! Tap the glowing stone to fix them."),
  s("tv_map_next_run", "Next is a new game, called Ninja Run. Tap the glowing stone to play."),
  s("tv_map_next_story", "Next is Story Time. Tap the glowing stone to open the book."),
  s("tv_map_next_boss", "Next is the boss of Bamboo Village. Tap the glowing stone, if you're ready."),
  s("tv_map_next_learn", "Next is the dojo. You'll learn some new sounds there. Tap the glowing stone to go."),
  s("tv_map_next_sort", "Next is a new game, called Sorting. Tap the glowing stone to play."),
  // --- World Flower (teacher voice, TS §3.25): The land is done: the World Flower, then Blossom Hills
  s("tv_flower_recap", "Here's a sound you learnt..."),
  // --- Dojo (teacher voice, TS §3.26): w2-1, the first Dojo lesson: New Sounds (Jonas's "Listen!" and the ear)
  s("tv_learn_ready", "Are you ready for the first one? Tap the green arrow."),
  s("tv_learn_frame_two", "Today in the dojo, I'm going to teach you two new sounds."),
  s("tv_learn_frame_three", "Today in the dojo, I'm going to teach you three new sounds."),
  s("tv_learn_frame_four", "Today in the dojo, I'm going to teach you four new sounds."),
  s("tv_learn_how", "I'll say each sound, and show you how we write it. Then you say it with me."),
  s("tv_learn_first", "Here's the first new sound. Get your ninja ears ready."),
  s("tv_here_it_comes", "Here it comes..."),
  s("tv_tap_letter_say", "Now you tap it, and say the sound."),
  s("tv_once_more", "Tap it once more, and say it again."),
  s("tv_said_well", "Good, you said that sound really well."),
  s("tv_learn_next", "Here's the next new sound..."),
  s("tv_petal_say_short", "Tap its petal, and say it."),
  s("tv_tap_it_say_short", "Now you tap it, and say it."),
  s("tv_learn_another", "Here's another new sound..."),
  s("tv_learn_last", "Here's the last new sound..."),
  s("tv_learn_all_two", "Two new sounds! You said every one."),
  s("tv_learn_all_three", "Three new sounds! You said every one."),
  s("tv_learn_all_four", "Four new sounds! You said every one."),
  s("tv_dojo_idle_say", "Tap the letter, and say the sound with me..."),
  s("tv_dojo_help_sound", "Here's the sound again..."),
  s("tv_x_two_sounds", "This spelling is two sounds together."),
  s("tv_ne_new_sounds", "Now let's play Ninja Eyes, with your new sounds."),
  s("tv_build_dojo", "Now let's build some words with your new sounds."),
  s("tv_learn_done", "You learnt four new sounds today, and you built words with them."),
  // --- Early learning (teacher voice, TS §4.1): The registry (the content of src/content/games.ts)
  s("tv_now_your_turn", "Now it's your turn."),
  // --- First minutes (teacher voice, TS §4.1): The registry (the content of src/content/games.ts)
  s("tv_pocket_recap", "It's Pocket Hunt again. We find pictures that start with this sound."),
  s("tv_pocket_middle_more_o", "One more Pocket Hunt. Find the pictures with this sound in the middle..."),
  s("tv_slow_recap", "It's Slow Words again. I say a word slowly, and you find its picture."),
  s("tv_slow_short", "Let's play Slow Words again."),
  s("tv_guess_recap", "It's Guess My Word again. I'll say the sounds, and you listen for the word."),
  s("tv_guess_short", "Let's play Guess My Word again."),
  s("tv_dots_recap", "It's Sound Dots again. Every dot is one sound in the word."),
  s("tv_dots_short", "It's Sound Dots again. Tap the dots, and say the sounds with me."),
  // --- Early learning (teacher voice, TS §4.1): The registry (the content of src/content/games.ts)
  s("tv_first_again_known", "It's First Sounds again. Let's see which sounds you know."),
  s("tv_ne_recap", "It's Ninja Eyes again. I say a sound, and you find how we write it."),
  s("tv_hunt_recap", "It's Sound Hunt again. The sound is hiding in the middle of the word."),
  s("tv_build_recap", "It's Word Building again. I say a word, and we build it with its sounds."),
  s("tv_build_again_short", "Let's build some more words."),
  // --- Battle (teacher voice, TS §4.1): The registry (the content of src/content/games.ts)
  s("tv_battle_recap", "Another of Baron's monsters! You know how to zap it. Find the sounds in each word."),
  s("tv_battle_go", "Are you ready to zap it? Tap the green arrow."),
  s("tv_boss_again", "Oh no, another boss! Don't worry. You know just what to do."),
  // --- Run (teacher voice, TS §4.1): The registry (the content of src/content/games.ts)
  s("tv_run_again", "It's Ninja Run again! Are you ready? Tap the green arrow, and off we go!"),
  // --- Story (teacher voice, TS §4.1): The registry (the content of src/content/games.ts)
  s("tv_story_recap", "Story time! I'll read some pages, and you'll read some too."),
  s("tv_story_short", "Story time!"),
  // --- Dojo (teacher voice, TS §4.1): The registry (the content of src/content/games.ts)
  s("tv_learn_recap_two", "Back to the dojo, for two new sounds. You know how this goes."),
  s("tv_learn_recap_three", "Back to the dojo, for three new sounds. You know how this goes."),
  s("tv_learn_recap_four", "Back to the dojo, for four new sounds. You know how this goes."),
  s("tv_learn_short_two", "Back to the dojo. Today there are two new sounds."),
  s("tv_learn_short_three", "Back to the dojo. Today there are three new sounds."),
  s("tv_learn_short_four", "Back to the dojo. Today there are four new sounds."),
  s("tv_learn_first_short", "Here's the first new sound..."),
  // --- Battle (teacher voice, TS §4.2): Gem battles (trial, full: the first Gem Trial; a child of 5 or more)
  s("tv_trial_ready", "The bar starts when you're ready. Tap the green arrow."),
  s("tv_trial_heart", "The bar filled up, so you lost a heart. That's fine. Keep going."),
  s("tv_trial_short", "It's a gem battle! Spell each word before the bar is full. Tap the green arrow when you're ready."),
  s("tv_trial_frame", "This is a gem battle. Win it, and the gem is yours."),
  s("tv_trial_bar", "Spell each word before this purple bar is full."),
  // --- Sort (teacher voice, TS §4.3): Sorting (sort, full: w6-br1, a Year One child of 5 or more)
  s("tv_sort_recap", "It's Sorting again. Every word goes in the chest with the same spelling."),
  s("tv_sort_frame", "This game is called Sorting. Every word goes in the chest with the same spelling."),
  s("tv_sort_open", "This sound can be spelt in three ways. Tap each chest to open it."),
  s("tv_spelt_like_this_kit", "In kit, it's spelt like this."),
  s("tv_spelt_like_this_cat", "In cat, it's spelt like this."),
  s("tv_spelt_like_this_yak", "In yak, it's spelt like this."),
  s("tv_spelt_like_this_duck", "In duck, it's spelt like this."),
  s("tv_spelt_like_this_chick", "In chick, it's spelt like this."),
  s("tv_spelt_like_this_match", "In match, it's spelt like this."),
  s("tv_spelt_like_this_rain", "In rain, it's spelt like this."),
  s("tv_spelt_like_this_tray", "In tray, it's spelt like this."),
  s("tv_spelt_like_this_bee", "In bee, it's spelt like this."),
  s("tv_spelt_like_this_leaf", "In leaf, it's spelt like this."),
  s("tv_spelt_like_this_boat", "In boat, it's spelt like this."),
  s("tv_spelt_like_this_snow", "In snow, it's spelt like this."),
  s("tv_spelt_like_this_light", "In light, it's spelt like this."),
  s("tv_spelt_like_this_pie", "In pie, it's spelt like this."),
  s("tv_sort_ido", "I'll sort the first one. My word is..."),
  s("tv_sort_see", "I can see this spelling at the end."),
  s("tv_sort_so", "So it goes in this chest."),
  s("tv_sort_fix", "Let's look again. Which chest has the same spelling?"),
  s("tv_sort_done", "Same sound, different spellings. You sorted them all."),
  // --- Battle (teacher voice, TS §4.4): Sensei's Challenge (review, full: the first time the map's button is tapped)
  s("tv_review_short", "It's Sensei's Challenge! Are you ready? Tap the green arrow."),
  s("tv_review_frame", "This is Sensei's Challenge. It has words from all the games you've played."),
  s("tv_review_how", "Find the sounds in each word to zap it. Let's see how many you can do!"),
  s("tv_review_done", "You zapped so many words! That was a real challenge."),
  // --- Run (teacher voice, TS §4.5): Ninja Run's reading groups (run, reading: the first time)
  s("tv_run_read_first", "Now it's your turn to read. Read the word at the top, and catch its picture."),
  // --- Dojo (teacher voice, TS §4.6): A school path's first Dojo (Reception after the autumn, Years One and Two)
  s("tv_dj_room", "This is the dojo, a school for ninjas. Here, you learn new sounds."),
  s("tv_learn_frame_ways", "Today in the dojo, I'm going to teach you new ways to write a sound you know."),
  s("tv_and_another_way", "And here's another way to spell it..."),
  // --- Early learning (teacher voice, TS §4.7): The Year One and Two word hunt (tapall, words, the first time)
  s("tv_word_hunt_frame", "It's a word hunt. Every word with our sound in it goes in a pocket."),
  s("tv_find_words_in", "Find every word with this sound in it..."),
  s("tv_hear_in_rain", "I can hear it in rain."),
  // --- Placement (teacher voice, TS §4.9): Show Sensei (the placement quiz, started by a grown-up)
  s("tv_place_frame", "Let's play a quick game, so I can see what you know already."),
  s("tv_place_ok", "Some might be tricky. That's fine. Just have a go."),
  s("tv_place_sound_round", "I say a sound, and you find how we write it."),
  s("tv_place_findall_round", "Find every picture with this sound in it..."),
  s("tv_place_done", "Thank you, ninja. Now I know just where to start."),
  // --- Dojo (teacher voice, TS §4.10): The practice dojo (the World Flower's Practise gate)
  s("tv_practise_gem", "Let's practise this gem. I say a word, and you build it."),
  // --- Early learning (teacher voice, TS §5.2): Show me again (the paw)
  s("tv_offer_show_miss", "Shall I show you again? Tap my paw."),
  // --- Praise (teacher voice, TS §5.3): Praise
  s("tv_praise_found", "You found it!"),
  s("tv_praise_order", "You read them the ninja way."),
  s("tv_praise_row", "You remembered which came first."),
  s("tv_praise_heard_word", "You heard the word in the sounds."),
  s("tv_praise_write", "You know how we write that sound."),
  s("tv_praise_judge", "You checked their reading, like a real teacher!"),
  s("tv_praise_sorted", "That's the right chest."),
  s("tv_praise_read", "Lovely reading!"),
  s("tv_praise_kept_going", "That was a tricky one, and you kept going."),
  s("tv_praise_helped", "Now you've got it."),
  s("tv_yay_lovely", "Lovely!"),
  s("tv_yay_thats_it", "That's it!"),
  s("tv_streak_10", "Ten in a row! Look how your ninja is glowing!"),
  // --- Correction (teacher voice, TS §5.4): Gentle correction
  s("tv_listen_here", "Let's listen again. What can you hear here?"),
  // --- Correction (teacher voice, TS §5.5): When the child is quiet (a turn's idle ladder), and Help
  s("tv_listen_sound_again", "Listen to my sound again..."),
  s("tv_which_starts_it", "Which picture starts with it?"),
  s("tv_which_way_write_it", "Which one is the way we write it?"),
  s("tv_both_again", "Listen to them both again..."),
  s("tv_which_changes", "Which sound changes?"),
  s("tv_take_time", "Take your time, ninja."),
  s("tv_look_glow", "Look for the glow."),
  // --- Rewards (teacher voice, TS §5.6): Wrapping up, and moving on
  s("tv_dojo_review_done", "You built lots of words. Your ninja is getting stronger."),
  // --- Rewards (teacher voice, TS §5.7): The moment before a reward, and the reward
  s("tv_to_flower", "Let's take your new sounds to the World Flower. Tap the green arrow."),
  s("tv_won_one", "You won back a sound..."),
  s("tv_rest", "You've practised so much today! Ninjas need rest too. You can stop here, and your ninja will wait for you."),
  s("tv_jump_offer", "Wow, you got everything right! Grown-ups, if this is too easy, you can jump ahead."),
  // --- Map (teacher voice, TS §5.8): The map, and coming back
  s("tv_welcome_back", "Welcome back, ninja! I'm so happy to see you."),
