/** Short, concrete picture-card prompts for Extended Code words. */
export const EC_PICTURE_PROMPTS: Record<string, string> = {
  rain: "heavy raindrops falling from one grey cloud",
  sail: "one white sailing boat sail on a small mast",
  train: "one red passenger train with carriages on a short piece of track",
  snail: "one garden snail with a large spiral shell",
  cake: "one round birthday cake with icing and candles",
  gate: "one wooden garden gate with a latch",
  flame: "one orange flame rising from a candle",
  whale: "one large blue whale swimming alone",
  steak: "one cooked beef steak on a plain plate",
  bee: "one yellow and black bee flying alone",
  tree: "one leafy green tree with a brown trunk",
  beach: "one sandy beach beside blue sea",
  queen: "one friendly queen wearing a crown and royal dress",
  tea: "one cup of tea in a plain white cup",
  teeth: "a smiling mouth showing clean white teeth",
  meal: "one plate of food with vegetables and potatoes",
  sheep: "one fluffy white sheep standing alone",
  leaf: "one bright green leaf",
  bean: "one green bean pod with two beans visible",
  seed: "one large brown seed with a tiny shoot",
  wheel: "one single bicycle wheel with spokes",
  boat: "one small sailing boat with a white sail",
  goat: "one brown goat with short horns standing alone",
  soap: "one plain pink bar of soap",
  toad: "one brown toad sitting alone",
  road: "one short stretch of road with white edges",
  oak: "one broad oak tree with a thick trunk",
  coal: "one lump of black coal",
  gold: "one small plain gold nugget",
  hole: "one round hole in a wooden plank",
  mole: "one small brown mole animal with a pointed nose and digging paws",
  cone: "one brown pine cone",
  bowl: "one empty blue ceramic bowl",
  crow: "one black crow standing alone",
  bone: "one clean white dog bone",
  pole: "one plain upright wooden pole",
  snow: "snowflakes falling onto a white snowy mound",
  toe: "one bare foot with its toes clearly visible",
  girl: "one smiling young girl standing alone",
  bird: "one small colourful bird standing alone",
  worm: "one pink earthworm curved on plain white",
  shirt: "one plain blue shirt with sleeves",
  skirt: "one plain red skirt",
  church: "one small stone church with a steeple",
  fern: "one green fern frond",
  fur: "one patch of soft brown animal fur",
  nurse: "one friendly nurse in plain blue scrubs with a stethoscope, no badges or writing",
  purse: "one small zipped purse for coins",
  cow: "one black and white cow standing alone",
  house: "one small red-roofed house",
  mouse: "one small grey mouse with a long tail",
  mouth: "one smiling mouth shown close up",
  cloud: "one fluffy white cloud",
  howl: "one wolf with its head raised, howling",
  clown: "one friendly circus clown with a red nose",
  owl: "one brown owl perched alone",
  town: "a small cluster of colourful houses in a town",
  pouch: "one small leather pouch with a drawstring",
  crown: "one golden royal crown",
  moon: "one bright full moon",
  spoon: "one silver spoon",
  glue: "one plain bottle of glue with its cap open, no writing",
  broom: "one wooden broom with straw bristles",
  hoop: "one colourful hula hoop",
  flute: "one silver flute",
  pool: "one small blue swimming pool, empty of people",
  tool: "one hammer as a simple hand tool",
  zoo: "one zoo entrance with an animal statue and no writing",
  roof: "one red tiled house roof",
  boot: "one green rubber boot",
  foot: "one bare foot, side view",
  cook: "one smiling cook in a white hat stirring a pot",
  hook: "one simple curved metal hook",
  bush: "one small leafy green bush",
  bull: "one large bull with short horns standing alone",
  child: "one smiling child standing alone",
  bike: "one blue bicycle, side view",
  lime: "one green lime fruit cut in half",
  pie: "one whole fruit pie with golden pastry crust",
  light: "one lit bedside lamp",
  kite: "one bright diamond-shaped kite with a tail",
  sky: "blue sky with one small white cloud",
  five: "five identical red apples in one row",
  line: "one straight blue line on a plain white card",
  wood: "one small stack of cut firewood logs",
  soup: "one bowl of vegetable soup with a spoon",
  group: "one small group of smiling children standing together",
  mess: "one messy pile of toy blocks scattered on the floor",
  cell: "one simple prison cell with a barred door, empty",
  fence: "one short wooden garden fence",
  face: "one smiling child's face, front view",
  ice: "one clear ice cube",
  horse: "one brown horse standing alone",
  pencil: "one sharpened yellow pencil without writing",
  apple: "one red apple with a green leaf",
  camel: "one camel standing alone, full body",
  table: "one simple wooden table",
  towel: "one folded blue bath towel",
  fork: "one silver dinner fork",
  chalk: "one short white stick of chalk",
  claw: "one crab claw, detached and clearly shaped",
  cork: "one bottle cork alone",
  hawk: "one hawk perched alone, full body",
  paw: "one animal paw with soft pads shown close up",
  jaw: "one animal jawbone with teeth, shown gently",
  lawn: "one small square of green lawn grass",
  corn: "one corn cob with yellow kernels and green husk",
  horn: "one curved animal horn",
  ball: "one red rubber ball",
  wall: "one short brick wall",
  saw: "one hand saw with a wooden handle",
  straw: "one drinking straw bent at the top",
  wart: "one small wart on a finger, shown gently",
  dwarf: "one friendly storybook dwarf standing alone",
  hair: "one child's head with long flowing hair",
  bear: "one brown bear standing alone",
  chair: "one simple wooden chair",
  pear: "one ripe green pear",
  hare: "one brown hare with long ears standing alone",
  stair: "one staircase with several clear steps",
  square: "one blue square on a white card",
  cube: "one solid blue toy cube",
  tube: "one plain metal tube, hollow at both ends",
  stew: "one bowl of chunky vegetable stew",
  duke: "one friendly duke in a royal coat, standing alone",
  boy: "one smiling young boy standing alone",
  toy: "one small colourful toy robot",
  coin: "one plain gold coin with no writing or numbers",
  oil: "one small clear bottle filled with golden cooking oil, no label",
  soil: "one little pile of dark garden soil",
  boil: "one pot of water bubbling on a hob",
  car: "one small red car",
  farm: "one farm barn with a field and a tractor",
  star: "one bright yellow five-pointed star",
  cart: "one small wooden hand cart with two wheels",
  jar: "one clear glass jar with a lid",
  card: "one blank greeting card folded open",
  tart: "one small fruit tart with pastry",
  palm: "one palm tree with coconuts",
  raft: "one small wooden raft floating on water",
  almond: "one brown almond nut",
  arm: "one person's bent arm shown from shoulder to hand",
  barn: "one red farm barn with a pitched roof",
  park: "one small park with a bench and a tree",
  shark: "one grey shark swimming alone, full body",
  charm: "one small silver charm hanging from a bracelet",
  watch: "one simple wristwatch with a round face and no numbers",
  wasp: "one yellow and black wasp with a narrow waist",
  eight: "eight identical red apples arranged in two neat rows, no numerals",
  sleigh: "one traditional wooden sleigh with curved runners, empty and alone",
  veil: "one sheer white bridal veil hanging alone",
  chain: "one short silver metal chain lying alone",
  brain: "one simple pink model of a human brain, alone",
  clay: "one lump of soft brown modelling clay, alone",
  grey: "one grey crayon lying alone without writing",
  daddy: "one smiling father standing alone in everyday clothes",
  muddy: "one pair of muddy wellington boots, alone",
  ladder: "one wooden ladder standing alone",
  paddle: "one canoe paddle with a broad blade, alone",
  code: "one simple locked padlock with a row of coloured dials, no numbers",
  key: "one plain silver door key, alone",
  chief: "one friendly fire chief in a helmet, standing alone",
  shield: "one round toy shield with a simple colour pattern, no writing",
  beach: "one sandy beach with a single beach bucket",
  taxi: "one black London taxi standing alone, no writing",
  field: "one open green field with a single tree at its edge",
  ski: "one pair of skis crossed together, alone",
  biscuit: "one round plain biscuit on a plate",
  jacket: "one child's blue jacket hanging alone on a hook",
  kitchen: "one small kitchen with a sink and cooker, no people",
  gym: "one school gymnasium with a climbing frame, empty",
  yellow: "one bright yellow crayon lying alone, no writing",
  yam: "one brown yam root with a rough skin, alone",
  myth: "one illustrated dragon from a myth, standing alone",
  cloak: "one dark blue cloak hanging alone from a hook",
  dough: "one round ball of uncooked bread dough, alone",
  mould: "one patch of fuzzy green mould on a slice of bread",
  soul: "one small glowing spirit in a gentle storybook style, alone",
  pillow: "one plain white pillow lying alone",
  gnome: "one small garden gnome with a red pointed hat, alone",
  knee: "one bent human knee seen close up, no other body part prominent",
  knife: "one blunt table knife with a rounded tip, alone",
  knot: "one thick rope tied in a single knot, alone",
  collar: "one blue pet collar with a buckle, alone",
  earth: "one globe of planet Earth, with no labels",
  pearl: "one white pearl sitting alone in an open oyster shell",
  dollar: "one plain coin with a dollar symbol, no other writing",
  groove: "one vinyl record with its circular grooves visible, no label",
  sleeve: "one blue shirt sleeve hanging from a shirt on a hanger",
  olive: "one green olive with a small leaf, alone",
  river: "one winding blue river passing through green fields",
  goose: "one white goose standing alone, full body",
  fruit: "one apple, one pear and one banana grouped together",
  juice: "one glass of orange juice, alone",
  screw: "one silver metal screw lying alone",
  shampoo: "one plain bottle of shampoo with bubbles, no writing",
  badge: "one round metal badge with a simple star, no text",
  fridge: "one white refrigerator standing alone, closed",
  giant: "one friendly storybook giant standing alone",
  hedge: "one short neatly clipped garden hedge",
  bridge: "one stone bridge over a narrow stream",
  guest: "one person arriving at a door with a small suitcase",
  guard: "one friendly castle guard standing alone in a helmet",
  guide: "one person pointing the way on a woodland path",
  graph: "one simple bar graph made of coloured blocks, no numbers or words",
  phone: "one plain mobile phone with a blank screen, alone",
  photo: "one photograph showing a smiling dog, no frame or writing",
  cough: "one child coughing gently into their elbow, full face visible",
  ghee: "one small clear bowl of golden melted butter, alone",
  comb: "one simple blue hair comb, alone",
  thumb: "one hand showing its thumb upright, close up",
  lamb: "one young white lamb standing alone, full body",
  autumn: "one orange autumn leaf lying alone",
  roar: "one lion with open mouth roaring, alone",
  shore: "one sandy sea shore with a small wave",
  boar: "one brown wild boar standing alone, full body",
  board: "one plain wooden board lying alone",
  whole: "one whole uncut apple, alone",
  school: "one small primary school building with playground, no writing",
  echo: "one child calling into a mountain valley, sound waves shown without words",
  anchor: "one black ship anchor lying alone",
  wreck: "one old broken shipwreck resting on sand",
  wrist: "one person's wrist shown close up with a colourful bracelet",
  wreath: "one circular wreath of green leaves hanging alone",
  rhyme: "two matching picture cards of a cat and hat, no writing",
  debt: "one empty purse beside a small stack of coins, no writing",
  kitten: "one small fluffy kitten sitting alone, full body",
  twenty: "twenty identical red beads in two neat rows, no numerals",
  breeze: "one small windsock fluttering in a gentle breeze",
  scissors: "one pair of child-safe scissors lying alone",
  deer: "one brown deer standing alone, full body",
  ear: "one human ear seen close up, alone",
  beard: "one smiling man with a long full beard, portrait view",
  spear: "one blunt toy spear with a wooden shaft, alone",
};
