// The template catalogue proposed by docs/SPEECH_TEMPLATES.md §2 and §6: every row of
// docs/speech-templates/inventory.md → a template. Wording follows Sounds~Write and TEACHER_SCRIPT; where the TS
// line bent the English around a slot, the slot goes back where English puts it. `lane` is the FIX_PLAN §2 owner
// of the call sites. `domain` names the content set that enumerates the members (design §3.1).
import type { Say, TemplateDef, Values } from "./template";

const L = (line: string): Say => ({ line });
const J = (join: "breath" | "sentence"): Say => ({ join });
const W = (v: Values, k = "word"): Say => ({ word: String(v[k]) });
const SLOW = (v: Values, k = "word"): Say => ({ stretch: String(v[k]) });
const S = (v: Values, k = "sound"): Say => ({ sound: String(v[k]), show: "petal" });
/** Fallbacks: a complete recorded sentence, then the clip standing alone. Never a word joined inside a sentence. */
const FB_WORD = (line: string) => (v: Values) => [L(line), J("sentence"), W(v)];
const FB_SLOW = (line: string) => (v: Values) => [L(line), J("breath"), SLOW(v)];
const FB_SOUND = (line: string) => (v: Values) => [L(line), J("breath"), S(v)];

type T = Omit<TemplateDef, "purpose"> & { purpose?: TemplateDef["purpose"] };
const t = (d: T): TemplateDef => ({ purpose: "instruction", who: "sensei", ...d });

export const CATALOGUE: TemplateDef[] = [
  // ============================================================ tier "whole": a word, picture, name or number inside
  // ---- building and dictation (C1 Early, D1 Dojo, D2 Battle, A Placement)
  t({ id: "w_position_q", text: "What's the {pos} sound in {word}? {word~slow}", slots: { pos: "pos", word: "word" }, tier: "whole", purpose: "question", domain: "build-items", hide: true,
    replaces: ["first_sound_q + stretch (the item's first ask)", "tv_last_first", "tv_next_middle", "audit_last_place"], inventory: [1], lane: "C1 Early, D1 Dojo, D2 Battle",
    fallback: (v) => [L(v.pos === "last" ? "last_sound_q" : v.pos === "next" ? "next_sound_q" : "first_sound_q"), J("sentence"), SLOW(v)] }),
  t({ id: "w_next_q", text: "What's the {pos} sound? {word~slow}", slots: { pos: "pos", word: "word" }, tier: "sequence", purpose: "question", domain: "fixed-next-last",
    src: { 0: "<pos>_sound_q" }, replaces: ["next_sound_q / last_sound_q + stretch (later asks: the word is already named)", "which_sound + word (idle)"], inventory: [1, 49], lane: "C1 Early, D1 Dojo, D2 Battle" }),
  t({ id: "w_your_word", text: "Your word is {word}.", slots: { word: "word" }, tier: "whole", domain: "words", hide: true,
    replaces: ["tv_your_word + [w]", "battle_spell + [w]", "dojo_build_word + [w]", "place_spell + [w]", "Build the word… + [w]"], inventory: [2], lane: "D2 Battle, D1 Dojo, C1 Early, A Placement",
    fallback: FB_WORD("tv_listen_word") }),
  t({ id: "w_your_next_word", text: "Your next word is {word}.", slots: { word: "word" }, tier: "whole", domain: "words", hide: true,
    replaces: ["tv_next_word + [w]"], inventory: [2], lane: "D2 Battle, D1 Dojo, C1 Early", fallback: FB_WORD("tv_listen_word") }),
  t({ id: "w_bare_word", text: "{word~bare}", slots: { word: "word" }, tier: "sequence", domain: "words", replaces: ["the dictation fade from the third word (TS §3.18): kept"], inventory: [2], lane: "D2 Battle, D1 Dojo, C1 Early" }),
  t({ id: "w_listen_again", text: "Let's listen to {word} again. {word~slow}", slots: { word: "word" }, tier: "whole", purpose: "correction", domain: "words", hide: true,
    replaces: ["listen_again + [w]", "tv_listen_here", "audit_listen_slowly", "narrative.ts LISTEN_AGAIN leads + [w, slowly]"], inventory: [3], lane: "F2 Voice (feedback.ts, narrate.tsx), D2 Battle",
    fallback: FB_SLOW("tv_fs_stuck_slow") }),
  t({ id: "w_say_slowly", text: "Say {word} slowly.", slots: { word: "word" }, tier: "whole", domain: "words", hide: true,
    replaces: ["Jonas's example: 'Say this word slowly: mat' → 'Say mat slowly.'", "tv_fs_say_slow (the child's turn)"], inventory: [14], lane: "C1 Early, D1 Dojo, D2 Battle",
    fallback: FB_SLOW("tv_fs_say_slow") }),
  t({ id: "w_i_say_slowly", text: "I'll say {word} slowly. {word~slow}", slots: { word: "word" }, tier: "whole", purpose: "demo", domain: "demo-words",
    replaces: ["tv_i_say_slowly + [w, slowly]", "build_ido_1 + [w] + build_ido_2 + stretch"], inventory: [14], lane: "C1 Early", fallback: FB_SLOW("tv_fs_say_slow") }),
  t({ id: "ws_first_is", text: "The {pos} sound in {word} is {sound}.", slots: { pos: "pos", word: "word", sound: "sound" }, tier: "sound", purpose: "demo", domain: "demo-positions",
    replaces: ["tv_first_is + /s/", "runDemo's [w, slowly] + /s/ per slot"], inventory: [24], lane: "C1 Early", fallback: (v) => [L("tv_first_is"), J("breath"), S(v)] }),
  t({ id: "n_reader_says", text: "{name} says {word}.", slots: { name: "name", word: "word" }, tier: "whole", purpose: "demo", domain: "read-words", hide: true,
    replaces: ["kai_says / suki_says + 100 ms + [w]"], inventory: [18], lane: "C1 Early", fallback: (v) => [L(`tv_${v.name}_reads`), J("sentence"), W(v)] }),
  t({ id: "n_reader_right", text: "Yes! {name} read it right. {word~sounds}. {word~bare}.", slots: { name: "name", word: "word" }, tier: "sequence", purpose: "praise", domain: "read-words",
    src: { 0: "tv_yes_<name>" }, replaces: ["tv_yes_<reader> · sounds · [w] (kept, as a sequence)"], inventory: [18], lane: "C1 Early" }),
  t({ id: "ws_if_it_was", text: "If it was {word}, this would be {sound}. Is it? No, it's {sound2}.", slots: { word: "word", sound: "sound", sound2: "sound" }, tier: "sound", purpose: "correction", domain: "read-wrong",
    src: { 1: "is_it_no" }, replaces: ["if_it_was + [w] + this_would_be + /x/ + is_it_no + /y/ (five joins)"], inventory: [38], lane: "C1 Early" }),
  t({ id: "w_sort_where", text: "Where does {word} go?", slots: { word: "word" }, tier: "whole", purpose: "question", domain: "sort-words", hide: true,
    replaces: ["the falling word said bare", "listen + [w] (wrongChest)"], inventory: [31], lane: "D4 Sort", fallback: FB_WORD("tv_listen_word") }),
  t({ id: "w_sort_ido", text: "I'll sort the first one. My word is {word}.", slots: { word: "word" }, tier: "whole", purpose: "demo", domain: "sort-demos",
    replaces: ["tv_sort_ido + [w]"], inventory: [2], lane: "D4 Sort" }),
  t({ id: "w_spelt_like", text: "In {word}, it's spelt like this.", slots: { word: "word" }, tier: "whole", purpose: "explanation", domain: "chest-examples",
    src: { 0: "tv_spelt_like_this_<word>" }, replaces: ["tv_spelt_like_this_<w> (adopted)"], inventory: [44], lane: "D4 Sort" }),
  // ---- Sound Swap (D3)
  t({ id: "w_swap_start", text: "Our first word is {word}.", slots: { word: "word" }, tier: "whole", domain: "swap-starts",
    replaces: ["this_is + [w] (Swap's start)", "tv_our_word + [w]"], inventory: [25], lane: "D3 Swap", fallback: FB_WORD("tv_listen_word") }),
  t({ id: "ww_i_change", text: "I'll change {word} to {word2}.", slots: { word: "word", word2: "word" }, tier: "whole", purpose: "demo", domain: "swap-demo-steps",
    replaces: ["tv_swap_change_to + [w]"], inventory: [4], lane: "D3 Swap" }),
  t({ id: "ww_change", text: "{word} to {word2}. What do we need to change?", slots: { word: "word", word2: "word" }, tier: "whole", purpose: "question", domain: "swap-steps", hide: true,
    replaces: ["swap_make + [w] + stretches + st_what_change (four joins)", "tv_swap_now_change + [w]", "st_what_change"], inventory: [4], lane: "D3 Swap",
    fallback: (v) => [L("st_what_change"), J("sentence"), W(v, "word2")] }),
  t({ id: "ww_both", text: "Listen to them both. {word~slow}. {word2~slow}.", slots: { word: "word", word2: "word" }, tier: "sequence", domain: "swap-steps",
    replaces: ["tv_swap_both (re-recorded as a whole sentence, no trailing '…')"], inventory: [4], lane: "D3 Swap" }),
  // ---- pictures (C2 Warm-ups, C1 Early)
  t({ id: "w_name_pic", text: "This is {picture~a}.", slots: { picture: "picture" }, tier: "whole", purpose: "explanation", domain: "pictures",
    src: { 0: "fm_name_<picture>" }, replaces: ["fm_name_<w> (adopted)", "this_is_a / this_is_an + [w] (the fallback: deleted)"], inventory: [6], lane: "C2 Warm-ups, C1 Early" }),
  t({ id: "w_find_pic", text: "Your word is {picture}. Can you find the {picture}?", slots: { picture: "picture" }, tier: "whole", purpose: "question", domain: "find-pictures",
    src: { 0: "tv_your_word_<picture>" }, replaces: ["tv_your_word_<w> (adopted)", "listen_tap + [w]", "place_tap + [w]"], inventory: [40], lane: "C2 Warm-ups, C1 Early, A Placement" }),
  t({ id: "w_find_again", text: "Can you find the {picture}?", slots: { picture: "picture" }, tier: "whole", purpose: "question", domain: "find-pictures",
    src: { 0: "tv_find_again_<picture>" }, replaces: ["tv_find_again_<w> (adopted)", "st_find_q2 / st_find_q3 + [w]"], inventory: [40], lane: "C2 Warm-ups" }),
  t({ id: "w_idle_look", text: "Where's the {picture}?", slots: { picture: "picture" }, tier: "whole", purpose: "hint", domain: "find-pictures",
    src: { 0: "tv_idle_look_<picture>" }, replaces: ["tv_idle_look_<w> (adopted)"], inventory: [40], lane: "C2 Warm-ups" }),
  t({ id: "w_diff_start", text: "{picture} starts with a different sound.", slots: { picture: "picture" }, tier: "whole", purpose: "correction", domain: "pictures",
    src: { 0: "fm_diff_<picture>" }, replaces: ["fm_diff_<w> (adopted)"], inventory: [42], lane: "F2 Voice (feedback.ts), C2 Warm-ups" }),
  t({ id: "w_i_hear", text: "I can hear {picture}.", slots: { picture: "picture" }, tier: "whole", purpose: "demo", domain: "demo-pictures",
    src: { 0: "tv_i_hear_<picture>" }, replaces: ["i_can_hear + [w]", "tv_i_hear_<w> (adopted)"], inventory: [41], lane: "C1 Early, C2 Warm-ups" }),
  t({ id: "w_tap_hear", text: "Tap the {picture}, and listen to how it starts.", slots: { picture: "picture" }, tier: "whole", domain: "demo-pictures",
    src: { 0: "tv_tap_hear_<picture>" }, replaces: ["tv_tap_hear_<w> (adopted)"], inventory: [45], lane: "C2 Warm-ups" }),
  t({ id: "w_tap_tortoise", text: "Now tap the tortoise, and say {picture} slowly with me.", slots: { picture: "picture" }, tier: "whole", domain: "fastslow-pictures",
    replaces: ["fm_tap_tortoise ↻ ('say it slowly')"], inventory: [14], lane: "C2 Warm-ups" }),
  t({ id: "w_tap_rabbit", text: "Now tap the rabbit, and say {picture} fast.", slots: { picture: "picture" }, tier: "whole", domain: "fastslow-pictures",
    replaces: ["fm_tap_rabbit ↻ ('say it fast')"], inventory: [14], lane: "C2 Warm-ups" }),
  t({ id: "w_ts_slow", text: "The tortoise says {picture} slowly. {picture~slow}", slots: { picture: "picture" }, tier: "whole", purpose: "demo", domain: "fastslow-pictures",
    replaces: ["tv_ts_slow / tv_ts_slow_one + [w, slowly]"], inventory: [14], lane: "C2 Warm-ups" }),
  t({ id: "w_ts_fast", text: "The rabbit says {picture} fast. {picture~bare}.", slots: { picture: "picture" }, tier: "whole", purpose: "demo", domain: "fastslow-pictures",
    replaces: ["tv_ts_fast + [w]"], inventory: [14], lane: "C2 Warm-ups" }),
  t({ id: "w_slow_word", text: "Here's my slow word. {picture~slow}", slots: { picture: "picture" }, tier: "sequence", purpose: "demo", domain: "slowpick-pictures",
    replaces: ["tv_slow_demo / tv_slow_yours (re-recorded as whole sentences)"], inventory: [30], lane: "C2 Warm-ups" }),
  t({ id: "ww_notice", text: "{picture} and {picture2} both start with {sound}.", slots: { picture: "picture", picture2: "picture", sound: "sound" }, tier: "sound", purpose: "explanation", domain: "notice-pairs",
    replaces: ["fm_notice_sun_sock + /s/"], inventory: [47], lane: "C2 Warm-ups" }),
  t({ id: "ww_ido_pair", text: "I'll go first. Here's {picture~a} and {picture2~a}.", slots: { picture: "picture", picture2: "picture" }, tier: "whole", purpose: "demo", domain: "demo-pairs",
    src: { 0: "tv_ido_pair_<picture>_<picture2>" }, replaces: ["tv_ido_pair_<pair>, tv_which_q_<pair>, fm_read/pair/triple_* (adopted)"], inventory: [46], lane: "C2 Warm-ups" }),
  // ---- names, numbers, stories, special words
  t({ id: "w_story_title", text: "This story is called {title}.", slots: { title: "title" }, tier: "whole", domain: "stories",
    replaces: ["story_start/tv_story_title + the title clip"], inventory: [51], lane: "D6 Story" }),
  t({ id: "w_special", text: "This is '{word}'. Just say '{word}' here.", slots: { word: "word" }, tier: "whole", purpose: "explanation", domain: "specials",
    src: { 0: "audit_special_<word>" }, replaces: ["audit_special_<w> (adopted)"], inventory: [53], lane: "D6 Story" }),
  t({ id: "w_example_hear", text: "You can hear it in {examples}.", slots: { sound: "key", examples: "list" }, tier: "whole", purpose: "explanation", domain: "sounds",
    src: { 0: "tp_<sound>_hear" }, replaces: ["tp_<p>_hear (adopted)", "t_you_can_hear_it_in + word clips + t_and (the fallback: deleted)"], inventory: [20], lane: "F2 Voice (teach.ts)" }),
  t({ id: "w_example_see", text: "We see this spelling in {examples}.", slots: { spelling: "spelling", examples: "list" }, tier: "whole", purpose: "explanation", domain: "spellings",
    src: { 0: "tg_<spelling>_see" }, replaces: ["tg_<g>_<p>_see (adopted)", "t_we_see_it_in + word clips (the fallback: deleted)"], inventory: [20], lane: "F2 Voice (teach.ts)" }),

  // ============================================================ tier "sound": the QA'd pure sound at a phrase end
  // ---- Jonas's example and the choral "say it with me" (D1 Dojo, C2 Warm-ups, B2 Flower via teach.ts)
  t({ id: "s_say_the_sound", text: "Say the sound {sound}.", slots: { sound: "sound" }, tier: "sound", domain: "sounds",
    replaces: ["Jonas's example: 'Say this sound: a' → 'Say the sound… /a/'", "t_say + /s/"], inventory: [13], lane: "F2 Voice (teach.ts), D1 Dojo", fallback: FB_SOUND("t_this_is_sound") }),
  t({ id: "s_say_with_me", text: "Tap the petal, and say the sound {sound} with me.", slots: { sound: "sound" }, tier: "sound", domain: "sounds",
    replaces: ["tv_petal_say", "tv_petal_first", "tv_new_petal_say", "tv_petal_say_short", "tv_rw2_tap_petal", "tv_flower_tap", "t_everyone_say"], inventory: [13], lane: "D1 Dojo, C2 Warm-ups, B2 Flower, F2 Voice (teach.ts)" }),
  t({ id: "s_tap_letter_say", text: "Tap the letter, and say the sound {sound} with me.", slots: { sound: "sound" }, tier: "sound", domain: "sounds",
    replaces: ["tv_dojo_idle_say"], inventory: [13], lane: "D1 Dojo" }),
  t({ id: "s_once_more", text: "Once more. Tap it, and say the sound {sound}.", slots: { sound: "sound" }, tier: "sound", domain: "sounds", replaces: ["tv_once_more"], inventory: [13], lane: "D1 Dojo" }),
  t({ id: "s_say_here", text: "This is the sound {sound}. Say it here.", slots: { sound: "sound" }, tier: "sound", purpose: "correction", domain: "sounds",
    src: { 0: "t_this_is_sound", 1: "t_say_it_here" }, replaces: ["teach.ts sayHere (exported, never called): the official correction"], inventory: [54], lane: "F2 Voice (teach.ts, narrate.tsx)" }),
  // ---- naming a sound (the ~12 suspended lead-ins of TS §3.9, 3.13, 3.26, 5.9)
  t({ id: "s_here_sound", text: "Here's the sound {sound}.", slots: { sound: "sound" }, tier: "sound", domain: "sounds", src: { 0: "tv_here_sound" }, replaces: ["tv_here_sound + /s/", "listen + /s/ (the bare 'Listen…')"], inventory: [10], lane: "D1 Dojo, F2 Voice (teach.ts)" }),
  t({ id: "s_first_sound", text: "Our first sound is {sound}.", slots: { sound: "sound" }, tier: "sound", domain: "sounds", src: { 0: "tv_first_sound" }, inventory: [10], lane: "D1 Dojo" }),
  t({ id: "s_next_sound", text: "Our next sound is {sound}.", slots: { sound: "sound" }, tier: "sound", domain: "sounds", src: { 0: "tv_next_sound" }, inventory: [10], lane: "D1 Dojo" }),
  t({ id: "s_learn_first", text: "Here's the first new sound, {sound}.", slots: { sound: "sound" }, tier: "sound", domain: "sounds", src: { 0: "tv_learn_first_short" }, inventory: [10], lane: "D1 Dojo" }),
  t({ id: "s_learn_next", text: "Here's the next new sound, {sound}.", slots: { sound: "sound" }, tier: "sound", domain: "sounds", src: { 0: "tv_learn_next" }, inventory: [10], lane: "D1 Dojo" }),
  t({ id: "s_learn_another", text: "Here's another new sound, {sound}.", slots: { sound: "sound" }, tier: "sound", domain: "sounds", src: { 0: "tv_learn_another" }, inventory: [10], lane: "D1 Dojo" }),
  t({ id: "s_learn_last", text: "Here's the last new sound, {sound}.", slots: { sound: "sound" }, tier: "sound", domain: "sounds", src: { 0: "tv_learn_last" }, inventory: [10], lane: "D1 Dojo" }),
  t({ id: "s_flower_recap", text: "Here's a sound you know, {sound}.", slots: { sound: "sound" }, tier: "sound", domain: "sounds", replaces: ["tv_flower_recap"], inventory: [10], lane: "B2 Flower, F2 Voice (teach.ts)" }),
  t({ id: "s_sound_again", text: "Here's the sound again, {sound}.", slots: { sound: "sound" }, tier: "sound", purpose: "hint", domain: "sounds", src: { 0: "tv_dojo_help_sound" }, replaces: ["tv_dojo_help_sound", "tv_listen_sound_again"], inventory: [10], lane: "D1 Dojo" }),
  t({ id: "s_petal_for", text: "This is the petal for the sound {sound}.", slots: { sound: "sound" }, tier: "sound", purpose: "explanation", domain: "sounds",
    replaces: ["audit_petal_means", "flower_i2", "tv_flower_petal ('…the petal for…')"], inventory: [35], lane: "B3 Shows, B4 Stickers" }),
  // ---- questions and prompts that end on a sound
  t({ id: "s_which_starts", text: "Which one starts with {sound}?", slots: { sound: "sound" }, tier: "sound", purpose: "question", domain: "sounds", src: { 0: "first_q" }, replaces: ["first_q + 300 ms + /s/"], inventory: [5], lane: "C1 Early" }),
  t({ id: "s_which_picture_starts", text: "Which picture starts with {sound}?", slots: { sound: "sound" }, tier: "sound", purpose: "question", domain: "sounds", src: { 0: "st_first_q2" }, inventory: [5], lane: "C1 Early" }),
  t({ id: "s_find_starts", text: "Find the one that starts with {sound}.", slots: { sound: "sound" }, tier: "sound", domain: "sounds", src: { 0: "st_first_q3" }, inventory: [5], lane: "C1 Early" }),
  t({ id: "s_which_write", text: "Which of these is the way we write {sound}?", slots: { sound: "sound" }, tier: "sound", purpose: "question", domain: "sounds", src: { 0: "tv_which_write" },
    replaces: ["find_q ('Find this sound…')", "dojo_find", "place_sound"], inventory: [7], lane: "C1 Early, D1 Dojo, A Placement" }),
  t({ id: "s_find_write", text: "Find how we write {sound}.", slots: { sound: "sound" }, tier: "sound", domain: "sounds", src: { 0: "tv_find_write" }, inventory: [7], lane: "D1 Dojo" }),
  t({ id: "s_now_find_write", text: "Now find how we write {sound}.", slots: { sound: "sound" }, tier: "sound", domain: "sounds", src: { 0: "tv_now_find" }, inventory: [7], lane: "D1 Dojo" }),
  t({ id: "s_how_write", text: "This is how we write {sound}.", slots: { sound: "sound" }, tier: "sound", purpose: "explanation", domain: "sounds", src: { 0: "tv_how_we_write" },
    replaces: ["how_we_spell + /s/", "audit_spell_it", "audit_hear_see"], inventory: [9], lane: "C1 Early, C2 Warm-ups, D1 Dojo" }),
  t({ id: "s_and_how_write", text: "And this is how we write {sound}.", slots: { sound: "sound" }, tier: "sound", purpose: "explanation", domain: "sounds", src: { 0: "tv_and_how_we_write" }, inventory: [9], lane: "C1 Early, D1 Dojo" }),
  t({ id: "s_which_middle", text: "Which one has {sound} in the middle? {word~slow}. {word2~slow}.", slots: { sound: "sound", word: "picture", word2: "picture" }, tier: "sound", purpose: "question", domain: "hunt-pairs",
    replaces: ["hunt_q + /i/ + stretches", "tv_hunt_q ('…this sound in the middle…')"], inventory: [19], lane: "C1 Early" }),
  t({ id: "ws_middle_is", text: "The middle sound in {picture} is {sound}.", slots: { picture: "picture", sound: "sound" }, tier: "sound", purpose: "explanation", domain: "three-sound-pictures",
    replaces: ["mid_<w> ('Pin has this sound in the middle…')", "[w] + has_in_middle + /i/ (the fallback: deleted)"], inventory: [21], lane: "C1 Early" }),
  t({ id: "ws_not_in", text: "{picture} doesn't have the sound {sound}.", slots: { picture: "picture", sound: "sound" }, tier: "sound", purpose: "correction", domain: "three-sound-pictures",
    replaces: ["fm_not_in_<w> + tv_fix_middle + /a/", "tv_not_in_middle"], inventory: [43], lane: "F2 Voice (feedback.ts)" }),
  t({ id: "ws_starts_with", text: "{picture} starts with {sound}.", slots: { picture: "picture", sound: "sound" }, tier: "sound", purpose: "explanation", domain: "pictures",
    src: { 0: "fs_<picture>" }, replaces: ["fs_<w> (adopted)", "[w] + starts_with + /s/ (the fallback: deleted)"], inventory: [12], lane: "C1 Early, F2 Voice (feedback.ts)" }),
  t({ id: "s_find_start", text: "Find every picture that starts with {sound}.", slots: { sound: "sound" }, tier: "sound", domain: "sounds", replaces: ["fm_tap_all_start", "fm_quick_tap_all", "tv_pocket_more_<p>"], inventory: [23], lane: "C2 Warm-ups, A Placement" }),
  t({ id: "s_find_middle", text: "Find the pictures with {sound} in the middle.", slots: { sound: "sound" }, tier: "sound", domain: "sounds", replaces: ["tv_pocket_middle_more_<p>", "fm_tap_all_in"], inventory: [23], lane: "C2 Warm-ups" }),
  t({ id: "s_find_word_with", text: "Find every word with {sound} in it.", slots: { sound: "sound" }, tier: "sound", domain: "sounds", replaces: ["tv_find_words_in", "tv_place_findall_round", "fm_tap_all_words_in", "place_findall"], inventory: [23], lane: "C2 Warm-ups, A Placement" }),
  t({ id: "s_pocket_frame", text: "In Pocket Hunt, we find pictures that start with {sound}.", slots: { sound: "sound" }, tier: "sound", purpose: "explanation", domain: "sounds", replaces: ["tv_pocket_frame ('…with this sound.')"], inventory: [58], lane: "C2 Warm-ups" }),
  t({ id: "s_pocket_recap", text: "It's Pocket Hunt again. We find pictures that start with {sound}.", slots: { sound: "sound" }, tier: "sound", purpose: "explanation", domain: "sounds", replaces: ["tv_pocket_recap"], inventory: [58], lane: "C2 Warm-ups" }),
  t({ id: "s_they_all_start", text: "They all start with {sound}.", slots: { sound: "sound" }, tier: "sound", purpose: "explanation", domain: "sounds", src: { 0: "fm_all_start" }, inventory: [28], lane: "C2 Warm-ups, B4 Stickers" }),
  t({ id: "s_they_all_have", text: "They all have the sound {sound}.", slots: { sound: "sound" }, tier: "sound", purpose: "explanation", domain: "sounds", src: { 0: "t_they_all_have" }, inventory: [28], lane: "C2 Warm-ups" }),
  t({ id: "s_look_this", text: "Look! This one starts with {sound}.", slots: { sound: "sound" }, tier: "sound", domain: "sounds", src: { 0: "fm_look_this" }, inventory: [28], lane: "C2 Warm-ups" }),
  t({ id: "s_found_both", text: "You found them both! They both start with {sound}.", slots: { sound: "sound" }, tier: "sound", purpose: "praise", domain: "sounds", src: { 0: "fm_found_both" }, inventory: [28], lane: "C2 Warm-ups" }),
  t({ id: "s_build_with", text: "Next, let's build some words with {sound}.", slots: { sound: "sound" }, tier: "sound", purpose: "transition", domain: "sounds", replaces: ["tv_next_build ('…with this sound…')"], inventory: [37], lane: "D1 Dojo" }),
  t({ id: "s_help_look", text: "Let me show you. It's the sound {sound}.", slots: { sound: "sound" }, tier: "sound", purpose: "hint", domain: "sounds", replaces: ["help_look + /s/", "dojo_find + /s/ + help_listen"], inventory: [48], lane: "D1 Dojo, D2 Battle, D3 Swap" }),
  t({ id: "s_listening_for", text: "We're listening for the sound {sound}.", slots: { sound: "sound" }, tier: "sound", purpose: "correction", domain: "sounds", replaces: ["tv_fix_start + /s/", "tv_fix_middle + /a/"], inventory: [42, 43], lane: "F2 Voice (feedback.ts)" }),
  // ---- spelling facts (F2 teach.ts, narrate.tsx; D4 Sort)
  t({ id: "s_letters", text: "It's {count} letters, but it's one sound. {sound}.", slots: { count: "count", sound: "sound" }, tier: "sound", purpose: "explanation", domain: "letter-counts",
    src: { 0: "t_<count>_letters" }, replaces: ["t_two_letters / t_three_letters / t_four_letters + 250 ms + /s/ (kept: Dec4)"], inventory: [15], lane: "F2 Voice (narrate.tsx, feedback.ts), D4 Sort" }),
  t({ id: "ss_x_two", text: "This spelling is two sounds together. {sounds}.", slots: { sounds: "sounds" }, tier: "sound", purpose: "explanation", domain: "fixed-x",
    replaces: ["tv_x_two_sounds + /k/ /s/", "t_one_spelling_two_sounds"], inventory: [15], lane: "F2 Voice (narrate.tsx)" }),
  t({ id: "ws_way_we_spell", text: "This is the way we spell {sound} in {word}.", slots: { sound: "sound", word: "word", spelling: "spelling" }, tier: "sound", purpose: "explanation", domain: "spellings",
    src: { 0: "t_way_we_spell", 1: "tg_<spelling>_in" }, replaces: ["tv_here_sound · tg_<g>_<p>_way ('…spell it in rain.')", "t_way_we_spell + /s/ + t_in + [w] (the fallback)"], inventory: [11], lane: "F2 Voice (teach.ts)" }),
  t({ id: "s_another_way", text: "This is another way to spell the sound {sound}.", slots: { sound: "sound" }, tier: "sound", purpose: "explanation", domain: "second-spellings", src: { 0: "t_another_way" }, inventory: [27], lane: "F2 Voice (teach.ts), D1 Dojo" }),
  t({ id: "s_and_another_way", text: "And here's another way to spell the sound {sound}.", slots: { sound: "sound" }, tier: "sound", purpose: "explanation", domain: "second-spellings", replaces: ["tv_and_another_way ('…to spell it…')", "wf_found_gem", "same_sound_new"], inventory: [27], lane: "F2 Voice (teach.ts), B3 Shows" }),
  t({ id: "n_ways", text: "Now you know {n} ways to spell {sound}.", slots: { n: "n", sound: "sound" }, tier: "sound", purpose: "explanation", domain: "ways-counts", src: { 0: "t_ways_<n>" }, replaces: ["t_ways_<n> + /s/ (adopted)"], inventory: [34], lane: "F2 Voice (teach.ts)" }),
  t({ id: "s_diff_spellings", text: "They're different spellings, but it's the same sound, {sound}.", slots: { sound: "sound" }, tier: "sound", purpose: "explanation", domain: "multi-spelling-sounds",
    replaces: ["t_diff_spellings_of + /s/ + t_same_sound"], inventory: [33], lane: "F2 Voice (teach.ts)" }),
  t({ id: "s_ways_list", text: "Let's remember the ways to spell {sound}, like in {examples}.", slots: { sound: "sound", examples: "list" }, tier: "sound", purpose: "explanation", domain: "multi-spelling-sounds",
    src: { 0: "t_lets_remember" }, replaces: ["t_lets_remember + /s/ + spliced list"], inventory: [33], lane: "F2 Voice (teach.ts)" }),
  t({ id: "ss_can_be", text: "This can be {sound}, but in this word, it's {sound2}. Say it here.", slots: { sound: "sound", sound2: "sound" }, tier: "sound", purpose: "correction", domain: "sound-pairs",
    src: { 0: "t_this_can_be", 1: "t_but_in_this_word", 2: "t_say_it_here" }, replaces: ["teach.ts canBe (kept, joins designed)"], inventory: [29], lane: "F2 Voice (teach.ts, narrate.tsx)" }),
  t({ id: "ss_does_it_have", text: "Does this word have the sound {sound}, or the sound {sound2}?", slots: { sound: "sound", sound2: "sound" }, tier: "sound", purpose: "question", domain: "sound-pairs",
    replaces: ["teach.ts whichSound (exported, never called): the Lesson 10 question", "t_does_it_have + /o/ + t_or + /oe/"], inventory: [55], lane: "F2 Voice (teach.ts)" }),
  t({ id: "ss_same_spelling", text: "The same spelling can sometimes be {sound}, like in {word}, and sometimes {sound2}, like in {word2}.", slots: { sound: "sound", word: "word", sound2: "sound", word2: "word" }, tier: "sound", purpose: "explanation", domain: "sound-pairs",
    src: { 0: "t_same_spelling_sometimes" }, replaces: ["t_same_spelling_sometimes + /s/ + st_<pair>_sometimes + /s/ + tg_*_in", "t_and_sometimes"], inventory: [32], lane: "F2 Voice (teach.ts)" }),
  // ---- corrections (F2 feedback.ts; D1 Dojo)
  t({ id: "ss_thats_we_need", text: "That's how we write {sound}. We need {sound2}.", slots: { sound: "sound", sound2: "sound" }, tier: "sound", purpose: "correction", domain: "sounds",
    src: { 0: "tv_thats_write", 1: "we_need" }, replaces: ["thats + /s/ · we_need + /m/", "that_says"], inventory: [17], lane: "F2 Voice (feedback.ts), D1 Dojo" }),
  t({ id: "s_its_this_one", text: "It's this one. Say the sound {sound}, as you put it on the line.", slots: { sound: "sound" }, tier: "sound", purpose: "correction", domain: "sounds",
    replaces: ["its_this_one ↻ ('Say the sound as you put it…')"], inventory: [17], lane: "F2 Voice (feedback.ts)" }),
  t({ id: "s_same_sound_spelling", text: "Yes, that's a spelling of that sound too! But in this word, we spell it like this. {sound}.", slots: { sound: "sound" }, tier: "sound", purpose: "correction", domain: "sounds",
    src: { 0: "same_sound_spelling" }, replaces: ["same_sound_spelling + 100 ms + /s/ (re-recorded as a whole sentence)"], lane: "F2 Voice (feedback.ts)" }),
  // ---- Sound Swap (D3)
  t({ id: "s_stays_same", text: "The sound {sound} stays the same.", slots: { sound: "sound" }, tier: "sound", purpose: "explanation", domain: "sounds", replaces: ["thats + /t/ · stays_same"], inventory: [26], lane: "D3 Swap" }),
  t({ id: "ss_swap_sounds", text: "Take out the sound {sound}, and put in the sound {sound2}.", slots: { sound: "sound", sound2: "sound" }, tier: "sound", purpose: "demo", domain: "swap-demo-steps",
    replaces: ["tv_swap_kick", "tv_swap_in + /s/"], inventory: [36], lane: "D3 Swap" }),
  // ---- placement (A)
  t({ id: "ws_gap", text: "In {word}, which one spells the sound {sound}?", slots: { word: "word", sound: "sound" }, tier: "sound", purpose: "question", domain: "placement-gaps",
    replaces: ["place_gap + /ae/ + place_gap_in + [w] (a sound mid-sentence, two joins)"], inventory: [39], lane: "A Placement" }),

  // ---- introducing a sound or a spelling (F2 teach.ts: introPetal, introGem, foundScript)
  t({ id: "s_petal_is", text: "This petal is the sound {sound}.", slots: { sound: "sound" }, tier: "sound", purpose: "explanation", domain: "sounds", src: { 0: "t_petal_is" }, inventory: [10], lane: "F2 Voice (teach.ts)" }),
  t({ id: "s_can_you_hear", text: "Listen. Can you hear the sound {sound} in these words?", slots: { sound: "sound" }, tier: "sound", purpose: "question", domain: "sounds",
    src: { 1: "t_in_these_words" }, replaces: ["t_listen_can_you_hear ('Listen. Can you hear...')"], inventory: [10], lane: "F2 Voice (teach.ts)" }),
  t({ id: "s_now_you_say", text: "Now you say the sound {sound}.", slots: { sound: "sound" }, tier: "sound", domain: "sounds", replaces: ["t_now_you_say_it + /s/ ('Now you say it!')"], inventory: [13], lane: "F2 Voice (teach.ts)" }),
  t({ id: "s_everyone_say", text: "Everyone say that sound. {sound}.", slots: { sound: "sound" }, tier: "sound", domain: "sounds",
    src: { 0: "t_everyone_say" }, replaces: ["t_everyone_say ('Say that sound with me!') re-recorded as S~W's 'Everyone say that sound.'"], inventory: [13], lane: "F2 Voice (teach.ts)" }),
  t({ id: "ws_spelling_of", text: "This is a spelling of the sound {sound}, like in {examples}.", slots: { spelling: "spelling", sound: "sound", examples: "list" }, tier: "sound", purpose: "explanation", domain: "spellings",
    src: { 0: "wf_spelling_of", 1: "tg_<spelling>_like" }, replaces: ["t_spelling_of", "t_like_in + spliced list (the fallback: deleted)"], inventory: [20, 27], lane: "F2 Voice (teach.ts)" }),
  t({ id: "ws_another_way_like", text: "This is another way to spell the sound {sound}, like in {examples}.", slots: { spelling: "spelling", sound: "sound", examples: "list" }, tier: "sound", purpose: "explanation", domain: "second-spellings",
    src: { 0: "t_another_way", 1: "tg_<spelling>_like" }, inventory: [27], lane: "F2 Voice (teach.ts)" }),
  t({ id: "s_next_known", text: "Our next sound is one you know, {sound}.", slots: { sound: "sound" }, tier: "sound", domain: "sounds", src: { 0: "tv_next_sound_known" }, inventory: [10], lane: "D1 Dojo" }),
  t({ id: "s_another_sound", text: "And here's another new sound, {sound}.", slots: { sound: "sound" }, tier: "sound", domain: "sounds", src: { 0: "tv_another_sound" }, inventory: [10], lane: "D1 Dojo" }),
  t({ id: "s_here_it_comes", text: "Here it comes, {sound}.", slots: { sound: "sound" }, tier: "sound", domain: "sounds", src: { 0: "tv_here_it_comes" }, inventory: [10], lane: "F3 Petals (NavDemo), D1 Dojo" }),
  t({ id: "s_rw2_all_start", text: "Sun, sock, sausage and sunflower. They all start with {sound}.", slots: { sound: "sound" }, tier: "sound", purpose: "explanation", domain: "fixed", src: { 0: "fm_rw2_s" }, inventory: [28], lane: "B1 Shell, B4 Stickers" }),
  // ---- the slow way and the fast way (TEACHER_SCRIPT §9): a demonstration after a suspended lead-in
  t({ id: "fs_say_sounds_slow", text: "Let's say the sounds, the slow way {word~slow}.", slots: { word: "word" }, tier: "sound", purpose: "demo", domain: "words", src: { 0: "tv_fs_say_sounds_slow" }, inventory: [14], lane: "C1 Early, D1 Dojo, D2 Battle, D3 Swap" }),
  t({ id: "fs_say_slow", text: "Let's say it the slow way {word~slow}.", slots: { word: "word" }, tier: "sound", purpose: "demo", domain: "words", src: { 0: "tv_fs_say_slow" }, inventory: [14], lane: "C1 Early, D1 Dojo, D2 Battle" }),
  t({ id: "fs_now_fast", text: "And now the fast way {word~fast}.", slots: { word: "word" }, tier: "sound", purpose: "demo", domain: "words", src: { 0: "tv_fs_now_fast" }, inventory: [14], lane: "C1 Early, D1 Dojo, D2 Battle" }),
  t({ id: "fs_slow_tortoise", text: "First the slow way, like the tortoise {word~slow}.", slots: { word: "word" }, tier: "sound", purpose: "demo", domain: "words", src: { 0: "tv_fs_slow_tortoise" }, inventory: [14], lane: "C1 Early, D1 Dojo, D2 Battle" }),
  t({ id: "fs_fast_rabbit", text: "Now the fast way, like the rabbit {word~fast}.", slots: { word: "word" }, tier: "sound", purpose: "demo", domain: "words", src: { 0: "tv_fs_fast_rabbit" }, inventory: [14], lane: "C1 Early, D1 Dojo, D2 Battle" }),
  t({ id: "fs_stuck_slow", text: "Let's say it the slow way first {word~slow}.", slots: { word: "word" }, tier: "sound", purpose: "hint", domain: "words", src: { 0: "tv_fs_stuck_slow" }, inventory: [3], lane: "C1 Early, D1 Dojo, D2 Battle" }),
  t({ id: "fs_stuck_again", text: "Here's the slow way again, one sound at a time {word~slow}.", slots: { word: "word" }, tier: "sound", purpose: "hint", domain: "words", src: { 0: "tv_fs_stuck_again" }, inventory: [3], lane: "C2 Warm-ups" }),
  t({ id: "fs_or_slowly", text: "Or I can say it slowly {picture~slow}.", slots: { picture: "picture" }, tier: "sound", purpose: "demo", domain: "fastslow-pictures", src: { 0: "fm_slow" }, inventory: [14], lane: "C2 Warm-ups" }),
  t({ id: "fs_dots_ido", text: "Then I say the word {word~fast}.", slots: { word: "word" }, tier: "sound", purpose: "demo", domain: "words", src: { 0: "tv_dots_word_ido" }, inventory: [16], lane: "C2 Warm-ups" }),
  t({ id: "w_slow_again", text: "Let's listen again {word~slow}.", slots: { word: "word" }, tier: "sound", purpose: "correction", domain: "words", src: { 0: "tv_slow_again" },
    replaces: ["tv_guess_again (the same words: one recording)"], inventory: [3, 30], lane: "F2 Voice (feedback.ts, narrative.ts)" }),
  t({ id: "s_lets_check", text: "Let's check. Say the sounds with me {word~sounds}.", slots: { word: "word" }, tier: "sound", domain: "words", src: { 0: "tv_lets_check" }, inventory: [8], lane: "C1 Early, D1 Dojo" }),
  t({ id: "ww_both_again", text: "Listen to them both again. {word~slow}. {word2~slow}.", slots: { word: "word", word2: "word" }, tier: "sequence", domain: "fixed", replaces: ["tv_both_again (re-recorded as a whole sentence)"], inventory: [4, 19], lane: "D3 Swap, C1 Early" }),

  // ============================================================ tier "sequence": a whole sentence, then the clips alone
  t({ id: "s_say_read", text: "Now let's say the sounds, and read the word. {word~sounds}. {word~bare}.", slots: { word: "word" }, tier: "sequence", domain: "words",
    replaces: ["tv_lets_say_read ('…say the sounds… and read the word.' re-recorded whole)", "say_sounds_read · sounds · [w] (kept as a sequence)"], inventory: [8], lane: "C1 Early, D1 Dojo, D2 Battle, D3 Swap" }),
  t({ id: "s_listen_for_word", text: "Listen for the word. {word~sounds}.", slots: { word: "word" }, tier: "sequence", purpose: "question", domain: "words",
    src: { 0: "tv_guess_q" }, replaces: ["tv_guess_q (S~W exact; re-recorded as a sentence)", "Run cue + sounds"], inventory: [16], lane: "C2 Warm-ups, D5 Run, F2 Voice (feedback.ts)" }),
  t({ id: "s_my_sounds", text: "My sounds are {word~sounds}.", slots: { word: "word" }, tier: "sound", purpose: "question", domain: "words", src: { 0: "tv_my_sounds" }, inventory: [16], lane: "C2 Warm-ups" }),
  t({ id: "n_won_one", text: "You won back a sound! {sound}.", slots: { sound: "sound" }, tier: "sequence", purpose: "praise", domain: "sounds",
    src: { 0: "tv_won_one" }, replaces: ["tv_won_one ('You won back a sound…') re-recorded as a whole sentence"], inventory: [22], lane: "B1 Shell" }),
  t({ id: "n_won_back", text: "You won back {n} sounds! {sounds}.", slots: { n: "n", sounds: "sounds" }, tier: "sequence", purpose: "praise", domain: "won-counts",
    src: { 0: "tv_won_<n>" }, replaces: ["tv_won_<n> ('…two sounds…') re-recorded as whole sentences"], inventory: [22], lane: "B1 Shell" }),
  t({ id: "w_catch", text: "Here's your word. {word~bare}.", slots: { word: "word" }, tier: "sequence", domain: "fixed", replaces: ["run_catch ('Catch the word…') + [w]"], inventory: [50], lane: "D5 Run" }),
  t({ id: "w_run_wrong", text: "That's a different word. {word~bare}. Listen again. {word2~sounds}.", slots: { word: "word", word2: "word" }, tier: "sequence", purpose: "correction", domain: "fixed",
    replaces: ["that_says + sounds + [w] + listen + sounds", "tv_run_fix"], inventory: [56], lane: "D5 Run" }),
];

export const BY_ID = new Map(CATALOGUE.map((d) => [d.id, d]));
