// Turn a blind picture audit (pic-audit.ts → <runDir>/pics-all.json) into src/content/pic-names.ts: what a 4-year-old
// actually calls each picture, and whether that name keeps the sounds a picture-only game relies on.
// Usage: bun scripts/treadmill/pics-to-content.ts <runDir>
import { readFileSync, writeFileSync } from "node:fs";
type Row = { word: string; names: { name: string; probability: number }[]; intendedRank: number | null; sharesFirstSound: boolean; sharesVowel: boolean };
const all: Row[] = JSON.parse(readFileSync(`${process.argv[2]}/pics-all.json`, "utf8"));
// "treasure map", "spinning top", "doggy" still say the word
const saysWord = (r: Row) => r.intendedRank === 1 || new RegExp(`\\b${r.word}`).test(r.names[0]?.name ?? "");
const odd = all.filter((r) => !saysWord(r)).sort((a, b) => a.word.localeCompare(b.word));
writeFileSync(
  "src/content/pic-names.ts",
  `// GENERATED by scripts/treadmill/pics-to-content.ts from a blind picture audit (${process.argv[2]}). Don't edit by hand:
// improve the picture (scripts/art-manifest.ts), rerun pic-audit.ts, then this.
// Pictures a 4-year-old names as something else: [what they say, same first sound?, same vowel?].
// Pictures not listed are named as intended.
export const PIC_NAMES: Record<string, [said: string, first: boolean, vowel: boolean]> = {
${odd.map((r) => `  ${JSON.stringify(r.word)}: [${JSON.stringify(r.names[0]?.name ?? "?")}, ${r.sharesFirstSound}, ${r.sharesVowel}],`).join("\n")}
};
/** Safe for a picture-only game that tests this part of the word. */
export const picSaysFirst = (w: string) => !PIC_NAMES[w] || PIC_NAMES[w][1];
export const picSaysVowel = (w: string) => !PIC_NAMES[w] || (PIC_NAMES[w][1] && PIC_NAMES[w][2]);
`,
);
console.log(`${odd.length} named differently of ${all.length}; ${odd.filter((r) => !r.sharesFirstSound).length} lose the first sound → src/content/pic-names.ts`);

// Hand-picked picture lists in the scenes (listening pairs, middle-sound pairs) don't go through the filters: check them here.
const odds = new Map(odd.map((r) => [r.word, r.names[0]?.name]));
const src = readFileSync("src/scenes/Early.tsx", "utf8");
const fixed = new Set([...src.matchAll(/mk\("\w+", "(\w+)", "(\w+)"/g), ...src.matchAll(/\["(\w+)", "(\w+)"\]/g)].flatMap((m) => [m[1], m[2]]));
const clash = [...fixed].filter((w) => odds.has(w));
if (clash.length) console.log(`⚠ hand-picked pictures in Early.tsx that children name differently: ${clash.map((w) => `${w} ("${odds.get(w)}")`).join(", ")}`);
