// Every spoken line (besides pure sounds and single words). Generated to /a/l/<id>.mp3.
// Speakers: "sensei" (warm British teacher narrator) and "baron" (the villain: sinister, never gory).

export type Speaker = "sensei" | "baron";
export interface Line { id: string; text: string; who?: Speaker }

const s = (id: string, text: string): Line => ({ id, text, who: "sensei" });
const b = (id: string, text: string): Line => ({ id, text, who: "baron" });

import { TEACH_LINES } from "./teach-lines.gen";

export const LINES: Line[] = [
  // --- Title & intro
  s("tap_start", "Tap to start!"),
  s("turn_phone", "Oops! Turn your phone sideways, like this!"),
  // the opening film, one line per shot (src/scenes/IntroFilm.tsx, docs/INTRO_STORYBOARD.md)
  s("film_1", "Long ago, on the Island of Sounds, there grew a magic World Flower."),
  s("film_2", "Every petal was a sound. With sounds, we could talk, and read, and sing!"),
  b("film_3", "Words, words, WORDS! How I HATE them!"),
  b("film_4", "I am Baron Muddle! Every sound on this island is MINE! Mwa-ha-ha-ha!"),
  s("film_5", "Oh no! The petals blew away, all over the island!"),
  s("film_6", "The World Flower has gone dark. Now nobody can read!"),
  s("film_7", "We need a hero. We need... a Super Ninja!"),
  s("film_8", "Win back every petal, one sound at a time!"),
  s("intro_8", "I am Sensei Maple. I will train you. Now, choose your ninja!"),
  s("chose", "Great choice!"),
  s("welcome_back", "Welcome back, Super Ninja! Ready for more training?"),

  // --- Map
  s("map_hint", "Tap the glowing stone to start your next adventure."),
  s("map_locked", "Not yet! Play the big gold stone first."),
  s("map_tree", "This is the World Flower!"),
  s("tree_tap", "Tap a petal, and listen!"),
  s("world_1", "Welcome to Bamboo Village!"),
  s("world_2", "Welcome to Blossom Hills!"),
  s("world_3", "Welcome to the Misty Mountains! Brrr!"),
  s("world_4", "Welcome to Dragon River!"),
  s("world_5", "Welcome to Shadow Castle. Don't worry, I'm right beside you."),
  s("world_6", "Welcome to the Sky Temple! Baron Muddle is hiding up here somewhere!"),

  // --- Praise
  s("yay_1", "Brilliant!"), s("yay_2", "Super!"), s("yay_3", "Fantastic!"), s("yay_4", "Well done."),
  s("yay_5", "Amazing!"), s("yay_6", "Ninja power!"), s("yay_7", "You did it!"), s("yay_8", "Wow, great listening!"),
  s("yay_9", "Smashing!"), s("yay_10", "Ace!"),
  s("well_read", "Well read!"), s("well_spelt", "Well spelt!"),
  s("streak_3", "Ninja power!"),
  s("streak_6", "Wow! Super ninja streak!"),
  s("streak_10", "Amazing! You're a ninja master!"),
  s("streak_lost", "Keep going, ninja."),

  // --- Correction language (always specific, composed with sound/word clips)
  s("thats", "That's..."),
  s("we_need", "We need..."),
  s("that_says", "That's..."),
  s("listen", "Listen..."),
  s("listen_again", "Listen again."),
  s("nearly", "Nearly! Let's try that one again."),
  s("not_quite", "Ooh, not quite. Have another go."),
  s("say_sounds", "Say the sounds..."),
  s("read_word", "Now read the word."),
  s("its", "It's..."),
  s("this_is", "This is..."),
  s("which_sound", "Which sound comes next?"),
  s("two_letters_one_sound", "Two letters, one sound!"),
  s("same_sound_diff", "Same sound, different spellings!"),
  s("same_sound_new", "Ooh! You already know this sound. Here's another way to spell it! Same sound, different spelling."),
  s("same_sound_spelling", "Yes, that's a spelling of that sound too! But in this word, we spell it like this..."),
  s("stays_same", "That sound stays the same."),

  // --- Dojo (learning new sounds + word building)
  s("dojo_hello", "This is the dojo. A dojo is where ninjas practise! Let's practise some sounds."),
  s("dojo_tap_say", "Tap it, and say it with me!"),
  s("dojo_find", "Can you find..."),
  s("dojo_build", "Now let's make words! First, listen to the word. Then tap its sounds, one at a time."),
  s("dojo_build_word", "Build the word..."),
  s("dojo_done", "Well done! You practised so hard!"),
  s("dojo_longer", "Longer words today! Some sounds sit very close together. Listen for every one."),
  s("challenge_start", "Practice time with Sensei! Let's try the sounds you found tricky. You can do it!"),

  // --- Battle
  s("battle_start", "Uh oh! One of Baron Muddle's monsters is in the way! Spell the words to zap it!"),
  s("battle_spell", "Spell..."),
  s("battle_boss", "A big boss monster! Listen carefully, and spell your best!"),
  s("battle_charge", "Watch out, it's charging up!"),
  s("timer_intro_1", "This is a gem battle! See this purple bar? It fills up slowly."),
  s("timer_intro_2", "Spell each word before the bar is full, or the monster jumps!"),
  s("timer_intro_3", "Don't worry. If you run out of hearts, I'll help you. Ready? Let's go!"),
  s("battle_win", "Hooray! The monster ran away!"),
  s("battle_boss_win", "You beat the boss! What a ninja!"),
  s("battle_oops", "Oof! You ran out of hearts. Don't worry, I'll help. Let's try again!"),
  s("battle_hint", "Here's a clue. Listen to the sounds."),

  // --- Run
  s("run_start", "Ninja Run! Tap to jump, and catch the right word!"),
  s("run_catch", "Catch the word..."),
  s("run_blend", "Listen to the sounds. What word do they make?"),
  s("run_end", "Bong! You made it to the gong!"),
  s("run_read", "Read the word, and catch the matching picture."),

  // --- Swap
  s("swap_start", "Baron Muddle has mixed up these words! Can you fix them? Change one sound at a time."),
  s("swap_make", "Change it to make..."),
  s("swap_which", "Which sound needs to change?"),
  s("swap_pick", "Now pick the new sound."),
  s("swap_done", "You fixed them all!"),

  // --- Sort (same sound, different spellings)
  s("sort_done", "Sorted! What a clever ninja."),

  // --- Story
  s("story_start", "Story time! I'll read, and you read too."),
  s("story_your_turn", "Your turn to read."),
  s("story_question", "Let's think about the story..."),
  s("story_end", "The end! What a story!"),
  s("story_tap_help", "Tap any word and I'll help you read it."),

  // --- Rewards & session
  s("petal_got", "You won back a sound!"),
  s("petals_got", "You won back some sounds!"),
  s("world_done", "You found every sound in this land! Let's go to the next one!"),
  s("break_time", "Great ninja training today! Now, go and read a book with a grown-up."),
  s("finale", "You did it, Super Ninja! Every petal is back on the World Flower. The whole island can read and spell again!"),

  // --- World Flower & gems
  s("flower_intro", "This is the World Flower! Every petal is a sound. The gems inside are all the different ways to spell it."),
  s("flower_i1", "This is the World Flower. Baron Muddle blew all its petals away."),
  s("flower_i2", "Every petal is one sound. Listen! This is the petal for the sound..."),
  s("flower_i4", "When you play and get it right, a gem fills up with ninja power."),
  s("flower_i5", "When a gem is full, it glows. Then you can win it in a gem battle!"),
  s("flower_i6", "Win all the gems in a petal, and the petal flies back onto the World Flower!"),
  s("flower_tap", "Tap a petal to see its gems."),
  s("gem_ready", "A gem is glowing! It's ready for a gem battle."),
  s("gem_charging", "This gem is filling up. Keep playing to fill it!"),
  s("gem_hidden", "This gem is still a secret. You'll find it later!"),
  s("gem_future", "This gem is far, far away. We'll find it one day!"),
  s("petal_secret", "This sound is still a secret. You'll find it on your adventure!"),
  s("trial_start", "Gem battle! Spell the words to win the gem!"),
  s("trial_win", "You won the gem! It's going into its petal!"),
  s("trial_fail", "So close! Keep playing, and try again soon."),
  s("petal_complete", "All the gems are in! The petal flies back onto the World Flower!"),
  s("flower_complete", "The World Flower is glowing again! You are a true Super Ninja!"),

  // --- Sticker Book
  s("book_missing", "This sticker is still out on your adventure. Keep playing to find it!"),
  s("help_players", "Tap your picture to play. New ninja? Tap the big plus!"),
  s("help_name", "Ask a grown-up to help you type your name, then tap the green tick."),
  s("help_book", "Tap a sticker to hear its word. Tap the arrows to turn the pages."),

  // --- Early learning (docs/PEDAGOGY.md): watch me, together, your turn
  s("ido", "Watch me first!"),
  s("wedo", "Let's do it together!"),
  s("youdo", "Now it's your turn!"),
  s("this_is_a", "This is a..."),
  s("this_is_an", "This is an..."),
  s("i_can_hear", "I can hear..."),
  s("listen_intro", "Let's play a listening game! Listen carefully, then tap the right picture."),
  s("listen_tap", "Tap the..."),
  s("listen_slow", "Now I'll say it slowly. Tap the..."),
  s("listen_sounds", "Now I'll say it in sounds. Can you hear the word? Tap the..."),
  s("first_intro", "Every word starts with a sound. Let's listen for the very first sound!"),
  s("first_q", "Which one starts with..."),
  s("starts_with", "starts with..."),
  s("how_we_spell", "This is how we spell..."),
  s("hunt_intro", "Now let's listen for a sound in the middle of a word!"),
  s("hunt_q", "Which one has this sound in it?"),
  s("has_in_middle", "has this sound in the middle..."),
  s("find_q", "Find this sound..."),
  s("like_in", "like in..."),
  s("build_ido_1", "I say the word..."),
  s("build_ido_2", "I say it slowly..."),
  s("build_ido_3", "Now I find each sound, one at a time."),
  s("first_sound_q", "What's the first sound?"),
  s("next_sound_q", "What's the next sound?"),
  s("last_sound_q", "What's the last sound?"),
  s("listen_here", "Listen again... What do you hear here?"),
  s("its_this_one", "It's this one. Say the sound as you put it on the line."),
  s("say_sounds_read", "Say the sounds, and read the word."),

  // ---- Teacher language for sounds and spellings (src/content/teach.ts). Wording follows the official Sounds~Write
  // scripts (assets-src/sw-sources/research/sections/teacher-language.md): spellings "spell" sounds, never "say" or "make"
  // them; no letter names, no "magic e", no rules. Each clip is a short phrase that joins with a pure sound or a word clip.
  // sounds (petals)
  s("t_this_is_sound", "This is the sound..."),
  s("t_petal_is", "This petal is the sound..."),
  s("t_listen_can_you_hear", "Listen. Can you hear..."),
  s("t_in_these_words", "...in these words?"),
  s("t_you_can_hear_it_in", "You can hear it in..."),
  s("t_and", "...and..."),
  s("t_they_all_have", "They all have the sound..."),
  s("t_now_you_say_it", "Now you say it!"),
  s("t_everyone_say", "Say that sound with me!"),
  // spellings (gems)
  s("t_way_we_spell", "This is the way we spell..."),
  s("t_in", "...in..."),
  s("t_like_in", "...like in..."),
  s("t_spelling_of", "This is a spelling of the sound..."),
  s("t_another_way", "This is another way to spell the sound..."),
  s("t_we_see_it_in", "We see this spelling in..."),
  s("t_two_letters", "It's two letters, but it's one sound."),
  s("t_three_letters", "It's three letters, but it's just one sound."),
  s("t_four_letters", "It's four letters, but it's just one sound."),
  s("t_one_spelling_two_sounds", "This spelling is two sounds together!"),
  s("t_often_end_short", "We often spell it like this at the end of short words."),
  s("t_ways_2", "Now you know two ways to spell..."),
  s("t_ways_3", "Now you know three ways to spell..."),
  s("t_ways_4", "Now you know four ways to spell..."),
  s("t_ways_5", "Now you know five ways to spell..."),
  s("t_ways_6", "Now you know six ways to spell..."),
  s("t_ways_7", "Now you know seven ways to spell..."),
  s("t_ways_8", "Now you know eight ways to spell..."),
  s("t_ways_9", "Now you know nine ways to spell..."),
  s("t_ways_10", "Now you know ten ways to spell..."),
  s("t_diff_spellings_of", "Different spellings of..."),
  s("t_same_sound", "...but it's the same sound!"),
  // one spelling, different sounds (Extended Code)
  s("t_this_can_be", "This can be..."),
  s("t_but_in_this_word", "...but in this word, it's..."),
  s("t_same_spelling_sometimes", "The same spelling can sometimes be..."),
  s("t_and_sometimes", "...and sometimes..."),
  // reading and checking
  s("t_say", "Say..."),
  s("t_here", "...here."),
  s("t_say_it_here", "Say it here!"),
  s("t_listen_for_word", "Say the sounds, and listen for the word."),
  s("t_if_you_say_sounds", "If you say the sounds, you can hear the word."),
  s("t_in_this_word_this_is", "In this word, this is..."),
  s("t_does_it_have", "Does this word have..."),
  s("t_or", "...or..."),
  // coming back to the World Flower
  s("t_visit", "Let's visit the World Flower!"),
  s("t_look_growing", "Look how your World Flower is growing!"),
  s("t_remember_this", "Do you remember this one?"),
  s("t_lets_remember", "Let's remember the ways to spell..."),
  s("t_new_gem_here", "Your new gem goes right here!"),
  s("t_practise_invite", "Shall we practise this in the dojo?"),
  s("t_words_you_found", "Here are the words you found with this sound. Tap one to hear it!"),
  s("two_sounds", "This word has two sounds!"),
  s("three_sounds", "This word has three sounds!"),
  s("read_intro", "Who read it right? Listen to Kai and Suki!"),
  s("read_tap_sounds", "Tap each sound, and say it."),
  s("read_who", "Who read it right?"),
  s("kai_says", "Kai says..."),
  s("suki_says", "Suki says..."),
  s("if_it_was", "If it was..."),
  s("this_would_be", "this would be..."),
  s("is_it_no", "Is it? No! It's..."),
  s("again_practise", "Let's practise that one again!"),
  s("i_am_ninja", "I am a ninja!"),
  s("dojo_nap", "Wow, you've practised so much! Ninjas need rest too. Shall we have a little break?"),
  s("what_changed", "What changed? Listen here."),

  // --- Jump ahead
  s("jump_offer", "Wow! You got everything right. Is this too easy? You can jump ahead!"),
  s("jump_pick", "How far shall we jump? Ask a grown-up to help you choose."),
  s("jump_done", "Whoosh! Off we go!"),

  // --- Placement ("Show Sensei")
  s("place_ask", "Do you know some sounds already? Tap the little seed if you're just starting. Tap the star to show me what you know!"),
  s("place_intro", "Let's see what you know! Just have a go."),
  s("place_tap", "Which one is..."),
  s("place_sound", "Which is the spelling of this sound?"),
  s("place_spell", "Can you spell..."),
  s("place_gap", "Which spelling of"),
  s("place_gap_in", "is in the word..."),
  s("place_findall", "Tap every picture that has this sound."),
  s("place_done", "Wow! Now I know just where to start your adventure. Let's go!"),
  s("place_new", "Hooray! We'll start right at the beginning."),

  // --- Help button (Sensei in the corner): what to do on each screen, then bigger clues
  s("help_start", "Tap the big green button to start!"),
  s("help_choose", "Tap the ninja you want to be!"),
  s("help_map", "Tap the big, gold, bouncing stone to play!"),
  s("help_next", "Tap the green arrow to carry on!"),
  s("help_tiles", "Tap the sound tiles, one sound at a time."),
  s("help_look", "Let me show you..."),
  s("help_run", "Tap anywhere to jump. Tap a lantern to catch it."),
  s("help_swap_pos", "First, tap the sound that changes."),
  s("help_swap_new", "Now tap the new sound."),
  s("help_sort", "Tap the chest with the same spelling as the word."),
  s("help_read", "Read each word, then tap the green tick."),
  s("help_story", "Tap the green arrow to turn the page."),
  s("help_question", "Tap the right picture!"),
  s("help_flower", "Tap a petal to see its gems. A bouncing gem is ready for a gem battle!"),
  s("help_listen", "Listen carefully. Tap the speaker to hear it again."),

  // --- Ninja Training (tutorial)
  s("tut_1", "Ninja training! First, tap the big gong!"),
  s("tut_good", "Great tapping!"),
  s("tut_help", "Whenever you're stuck, tap me! I'm always here in the corner, and I'll tell you what to do. Try it now. Tap me!"),
  s("tut_help_ok", "That's it! And if you're still stuck, tap me again, and again, and I'll give you bigger clues."),
  s("tut_tile", "Now find this sound..."),
  s("tut_speaker", "Tap the speaker to hear the sound again."),
  s("tut_test", "Last one. All by yourself! Find this sound..."),
  s("tut_stuck", "Not sure? Tap me for a clue!"),
  s("tut_done", "You're ready, ninja! Let's go!"),

  // --- Grown-ups
  s("grownups", "This part is for grown-ups. Hold the button to open."),

  // --- First minutes (docs/FIRST_MINUTES.md): the school-year opt-in, the dojo welcome, and warm-up games for 3-to-4-year-olds who can't read (big picture cards; Sensei shows one first, then the child tries), then the Sticker Book rewards
  // Every line that contains a word is one whole recording; only pure sounds, stretched words and held first sounds are
  // spliced, after a lead-in ending on "..." (§12).
  // opt-in (§4)
  s("fm_opt_q1", "Do you go to big school yet?"),
  s("fm_opt_notyet", "Not yet? Tap the teddy!"),
  s("fm_opt_yes", "Yes? Tap the school!"),
  s("fm_opt_q1_again", "Teddy, or school? Tap one!"),
  s("fm_opt_echo_notyet", "Not yet!"),
  s("fm_opt_echo_school", "Big school!"),
  s("fm_opt_q2", "Which class are you in? Tap your class."),
  s("fm_opt_rec", "Reception!"),
  s("fm_opt_y1", "Year One!"),
  s("fm_opt_y2", "Year Two!"),
  s("fm_opt_unsure", "Not sure? Tap the cloud."),
  s("fm_opt_q2_again", "Tap your class, or the cloud."),
  s("fm_opt_ok_notyet", "Then I've set up some listening games, just for you!"),
  s("fm_opt_ok_unsure", "That's fine! I've set up some listening games for you, and we'll see how you get on."),
  s("fm_opt_ok_rec", "I've set up the game for Reception, with sounds just like at school!"),
  s("fm_opt_ok_y1", "I've set up the game for Year One, with new ways to spell the sounds you know!"),
  s("fm_opt_ok_y2", "I've set up the game for Year Two, with even more ways to spell the sounds you know!"),
  s("fm_opt_grownups", "Your grown-ups can change this later, in the grown-ups' settings."),
  s("fm_opt_default_home", "Let's start at the very beginning, with listening games!"),
  s("fm_opt_default_rec", "Let's start with the Reception games!"),
  s("fm_newyear_q", "It's a new school year! Which class are you in now?"),
  s("fm_newyear_up", "Hooray! You've moved up!"),
  // dojo welcome, help and the time governor
  s("fm_help_short", "Stuck? Tap me, down here in the corner. Try it now!"),
  s("fm_help_ok", "That's it! I'm always here to help."),
  s("fm_its_this", "It's this one!"),
  s("fm_last_one", "Here's the last one."),
  // Lesson 1: Ninja Ears (§5)
  s("fm_l1_hello", "Ninja ears on! Let's listen to some words."),
  s("fm_name_sun", "This is the sun."),
  s("fm_name_sock", "This is a sock."),
  s("fm_name_cat", "This is a cat."),
  s("fm_tap_sock", "Tap the sock!"),
  s("fm_fast_sun", "I can say a word fast. Sun!"),
  s("fm_slow", "Or I can say it slowly..."),
  s("fm_same_word", "Fast or slow, it's the same word. Sun!"),
  s("fm_hear_sounds", "When I say a word slowly, I can hear the sounds that make up the word. Words are made of sounds!"),
  s("fm_tap_tortoise", "Now you tap the tortoise, and say it slowly with me."),
  s("fm_tap_rabbit", "Now tap the rabbit, and say it fast."),
  s("fm_slow_listen", "Listen to my slow word..."),
  s("fm_which_pic", "Which picture is it?"),
  s("fm_slow_another", "Here's another slow word..."),
  s("fm_first_listen", "Listen to the very first sound."),
  s("fm_notice_sun_sock", "Sun and sock start with the same sound..."),
  s("fm_name_sausage", "This is a sausage."),
  s("fm_name_moon", "This is the moon."),
  s("fm_tap_all_start", "Tap all the pictures that start with..."),
  s("fm_diff_moon", "Moon starts with a different sound."),
  s("fm_diff_cat", "Cat starts with a different sound."),
  s("fm_found_both", "You found them both! They both start with..."),
  s("fm_look_this", "Look! This one starts with..."),
  s("fm_l1_done", "You can hear the sounds in words. Brilliant listening!"),
  // Reward 1: the Sticker Book (§6)
  s("fm_rw_look", "Look! Your pictures are turning into stickers!"),
  s("fm_rw_book", "This is your Sticker Book!"),
  s("fm_rw1_list", "Sun, sock, cat, sausage and moon!"),
  s("fm_rw_every", "Every picture you play with becomes a sticker!"),
  s("fm_rw_tap", "Tap a sticker!"),
  s("fm_rw_next", "Ready for the next game? Tap the big arrow!"),
  s("fm_rw_more", "More stickers for your Sticker Book!"),
  // Lesson 2: Ninjas Read This Way (§7)
  s("fm_l2_way", "Ninjas read this way!"),
  s("fm_name_fish", "This is a fish."),
  s("fm_name_dog", "This is a dog."),
  s("fm_read_fish_dog", "Fish... dog. Fish dog!"),
  s("fm_l2_turn", "Your turn! Tap them the ninja way."),
  s("fm_pair_fish_dog", "Fish dog!"),
  s("fm_l2_start", "Start here, on this side!"),
  s("fm_l2_swap", "Whoops! Now they're the other way round. Dog... fish. Dog fish!"),
  s("fm_which_cat_dog", "Listen. Cat... dog. Which one did I read?"),
  s("fm_pair_cat_dog", "Cat dog!"),
  s("fm_l2_big_word", "Two little words can make one big word!"),
  s("fm_name_flower", "This is a flower."),
  s("fm_sunflower", "Say them slowly: sun... flower. Say them fast: sunflower!"),
  s("fm_name_star", "This is a star."),
  s("fm_starfish_q", "Star... fish. Tap the rabbit, and say them fast."),
  s("fm_starfish", "Starfish!"),
  s("fm_quick_tap_all", "Quick! Tap all the pictures that start with..."),
  s("fm_diff_fish", "Fish starts with a different sound."),
  s("fm_diff_dog", "Dog starts with a different sound."),
  s("fm_l2_done", "You read the pictures, just like a real reader!"),
  // Reward 2: shiny sticker, first petal, map (§8)
  s("fm_rw2_list", "Fish, dog, flower, sunflower, star and starfish!"),
  s("fm_rw_shiny", "Ooh, a shiny sticker! Fish dog!"),
  s("fm_rw2_s", "Sun, sock, sausage and sunflower. They all start with..."),
  s("fm_rw2_petal", "You found your very first sound! Look, its petal is shining through the mist."),
  s("fm_rw2_map", "Your Sticker Book lives here, on the map!"),
  // other starting points and adjusting (§9, §10)
  s("fm_tap_all_in", "Tap all the pictures with this sound in them..."),
  s("fm_not_in_sun", "Sun doesn't have that sound in it."),
  s("fm_not_in_dog", "Dog doesn't have that sound in it."),
  s("fm_found_all", "You found them all!"),
  s("fm_tap_all_words_in", "Tap all the words with this sound in them..."),
  s("fm_warm_up", "Let's do some warm-up training first!"),
  s("fm_super_listener", "You're a super listener! Now let's find out how we write the sounds."),
  // "Let me show you!" then "Now you try!" (the Amendment): every warm-up game type opens with Sensei and the ninja
  // doing one item, then the child's turn. The _2 lines are alternates for variety.
  s("fm_show_me", "Let me show you!"),
  s("fm_you_try", "Now you try!"),
  s("fm_show_me_2", "Watch me first!"),
  s("fm_you_try_2", "Your turn!"),
  s("fm_tap_sun", "Tap the sun!"),
  // the dojo welcome also shows the Hear it again button (docs/ARCHITECTURE.md §15.3)
  s("fm_speaker", "And when you tap the speaker, I'll say it again!"),
  // pace across the warm-ups (§10)
  s("fm_practise_again", "Let's practise that again!"),
  // W3 (ears): fast and slow on mug, "/a/ in it", first sound /m/
  s("fm_name_mug", "This is a mug."),
  s("fm_name_bag", "This is a bag."),
  s("fm_name_jam", "This is some jam."),
  s("fm_name_van", "This is a van."),
  s("fm_name_map", "This is a map."),
  s("fm_diff_sun", "Sun starts with a different sound."),
  s("fm_all_start", "They all start with..."),
  // W4 (picread): three in a row, and a picture word the child makes
  s("fm_read_cat_dog_fish", "Cat... dog... fish. Cat-dog-fish!"),
  s("fm_triple_cat_dog_fish", "Cat dog fish!"),
  s("fm_l4_swap", "Now they're the other way round. Fish... dog... cat. Fish dog cat!"),
  s("fm_which_three", "Listen. Fish... dog... cat. Which one did I read?"),
  s("fm_triple_fish_dog_cat", "Fish dog cat!"),
  s("fm_sunflower_q", "Sun... flower. Tap the rabbit to say them fast!"),
  s("fm_sunflower_fast", "Sunflower!"),
  // W5 (ears): Sensei says the sounds, the child listens for the word
  s("fm_sounds_intro", "I'll say the sounds. You listen for the word!"),
  s("fm_name_mop", "This is a mop."),
  s("fm_name_cap", "This is a cap."),
  s("fm_name_bug", "This is a bug."),
  s("fm_name_fan", "This is a fan."),
  s("fm_name_man", "This is a man."),
  s("fm_name_jug", "This is a jug."),
  s("fm_name_bun", "This is a bun."),
  s("fm_name_bus", "This is a bus."),
  s("fm_l5_done", "You heard the words in the sounds. Super listening!"),
  // W6 (picread): sound dots under pictures, tapped this way like the sound buttons in the dojo
  s("fm_dots_intro", "Every dot is a sound. Ninjas tap them this way!"),
  s("fm_dots_turn", "Your turn! Tap the dots this way, and say the sounds with me."),
  s("fm_dots_say", "Say the sounds... and say the word!"),
  s("fm_l6_done", "Now you're ready to find out how we write the sounds!"),

  // --- World Flower 2.0 (src/scenes/Tree.tsx, src/scenes/Intros.tsx; the scripts are in src/content/teach.ts)
  // trips to the World Flower (engine/gems.ts FlowerVisit), the petal detail's Practise gate, and the first-visit intro
  s("wf_i3", "Inside each petal are shiny gems. Each gem is a way to spell the sound."),
  s("wf_found_sound", "You found a new sound! Look, here is its petal, shining through the mist."),
  s("wf_found_gem", "You found a new gem! It's a spelling of the sound..."),
  s("wf_petals_you_know", "Every shining petal is a sound that you know!"),
  s("wf_world_new", "New sounds are hiding in this land. Let's go and find them!"),
  s("wf_practised", "Look! Your gem filled up with ninja power."),
  s("wf_help_petal", "Tap a gem to hear how it spells the sound. Tap the gate to practise it in the dojo!"),
  s("wf_new_gem_here", "Look! Your new gem goes here, in its petal."),
  s("wf_spelling_of", "This is a spelling of the sound..."),

  // ---- Narrative audit (docs/NARRATIVE_AUDIT.md, playtest/narrative/audit.json): explanations in the level scenes.
  // When each one plays is src/content/narrative.ts (spacing) and src/scenes/narrate.tsx (the per-save ledger). The
  // sub-headings below name the scene, so the line linter knows what is on screen.
  // --- Dojo (narrative audit): a new spelling, adjacent consonants (F12), and Help that never segments the word (F27)
  s("audit_spell_it", "And this is how we spell it."),
  s("audit_hear_see", "We hear the sound. Now look: this is how we spell it."),
  s("audit_dojo_back", "Back to the dojo! Let's learn some new sounds."),
  s("audit_neighbours", "These sounds sit next to each other. Listen for each one as we say the word slowly."),
  s("audit_neighbours_plain", "These sounds sit next to each other. Listen for every one!"),
  s("audit_spelling_help", "Listen to the word slowly. What sound do you hear here?"),
  s("audit_spelling_help_plain", "Listen to the word again. What sound do you hear here?"),
  // --- Correction (narrative audit): whole-sentence alternatives to listen_here, rotated; a stretched word follows
  s("audit_listen_slowly", "Let's listen to the word again, slowly."),
  s("audit_listen_next", "Let's listen again. What sound comes next?"),
  // --- Praise (narrative audit): the first time the child's right answers fill a gem, in any level (F04)
  s("audit_gem_first", "Look, a gem! Each gem holds a way to spell a sound. When you get words right, it fills up."),
  // --- Battle (narrative audit): Baron Muddle's motive (F18), the first Gem Trial and its bar (F16)
  s("audit_baron_first", "Baron Muddle hid the sounds. Let's win them back from his monsters."),
  s("audit_trial_first", "Your gem is ready. Spell the words to win it."),
  s("audit_timer_short", "Watch the purple bar. Spell the word before it fills."),
  s("audit_timer_hearts", "If it fills, you lose a heart. I will help you try again."),
  s("audit_neighbours_short", "In these words, some sounds sit close together. Listen carefully for every one!"),
  // --- Run (narrative audit): a rotating cue before a word's sounds (with run_blend and t_listen_for_word)
  s("audit_sounds_again", "Listen to the sounds, and catch the word they make!"),
  // --- Sort (narrative audit): the chests' spellings, shown one by one with their sound (F13)
  s("audit_sort_first", "Sorting time! These words have the same sound, but it's spelt in different ways."),
  s("audit_sort_again", "Sorting time! Same sound, different spellings."),
  s("audit_sort_pair", "This sound can be spelt in two ways."),
  s("audit_sort_three", "This sound can be spelt in three ways."),
  // --- Swap (narrative audit): the place of the sound that changes (first, middle, last)
  s("audit_swap_first", "Yes, the first sound changes! Now pick the new sound."),
  s("audit_swap_middle", "Yes, the middle sound changes! Now pick the new sound."),
  s("audit_swap_last", "Yes, the last sound changes! Now pick the new sound."),
  // --- Story (narrative audit): choosing by reading (F14), and common words with untaught spellings (F15), in the
  // official parent wording "This is 'the', just say 'the' here"
  s("audit_story_choice", "Read the two words. Tap the one you choose."),
  s("audit_story_choose_again", "Read the words, and tap one!"),
  s("audit_special_the", "This is 'the'. Just say 'the' here."),
  s("audit_special_is", "This is 'is'. Just say 'is' here."),
  s("audit_special_his", "This is 'his'. Just say 'his' here."),
  s("audit_special_to", "This is 'to'. Just say 'to' here."),
  s("audit_special_i", "This is 'I'. Just say 'I' here."),
  s("audit_special_so", "This is 'so'. Just say 'so' here."),
  s("audit_special_he", "This is 'he'. Just say 'he' here."),
  s("audit_special_you", "This is 'you'. Just say 'you' here."),
  s("audit_special_go", "This is 'go'. Just say 'go' here."),

  // ---- Integration (26 Sep 2026): the narrative audit's explanations in the early games, the rewards and the
  // Bridging Unit (docs/NARRATIVE_AUDIT.md F02, F04, F08-F10, F17, F25). Sub-headings name the scene for the linter.
  // --- Dojo (integration): the first word-building dojo (w1-4): what a dojo is, left to right, and the last sound
  s("audit_dojo_first", "This is our dojo. Here we listen to sounds, make words, and read them."),
  s("audit_left_right", "We start here, and go this way."),
  s("audit_last_place", "The last sound is at the end of the word. Listen to the end."),
  // --- Early learning (integration): the middle sound (Sound Hunt), and a reminder before the sounds-to-words game
  s("audit_middle_place", "The middle sound comes after the first sound, and before the last sound."),
  s("audit_made_of_sounds", "Remember? Words are made of sounds!"),
  // --- Early learning (integration): each picture in the first-sound and sound-hunt games named in one whole sentence
  // (Round 13: no "This is a..." + [word] splices), like the warm-ups' fm_name_ lines
  s("fm_name_ant", "This is an ant."), s("fm_name_apple", "This is an apple."), s("fm_name_bed", "This is a bed."), s("fm_name_bin", "This is a bin."),
  s("fm_name_cot", "This is a cot."), s("fm_name_cup", "This is a cup."), s("fm_name_fox", "This is a fox."), s("fm_name_hat", "This is a hat."),
  s("fm_name_leg", "This is a leg."), s("fm_name_lid", "This is a lid."), s("fm_name_log", "This is a log."), s("fm_name_mat", "This is a mat."),
  s("fm_name_milk", "This is some milk."), s("fm_name_nest", "This is a nest."), s("fm_name_net", "This is a net."), s("fm_name_nut", "This is a nut."),
  s("fm_name_pan", "This is a pan."), s("fm_name_peg", "This is a peg."), s("fm_name_pen", "This is a pen."), s("fm_name_pig", "This is a pig."),
  s("fm_name_pin", "This is a pin."), s("fm_name_pond", "This is a pond."), s("fm_name_pot", "This is a pot."), s("fm_name_sand", "This is some sand."),
  s("fm_name_sit", "Look, she can sit."), s("fm_name_tap", "This is a tap."), s("fm_name_tent", "This is a tent."), s("fm_name_tin", "This is a tin."),
  s("fm_name_top", "This is a top."), s("fm_name_web", "This is a web."), s("fm_name_zip", "This is a zip."),
  // --- Early learning (integration): the answer's word and its lead-in in one recording, so only the pure sound is
  // joined ("Mop starts with..." [/m/], "Pin has this sound in the middle..." [/i/]; docs/FIRST_MINUTES.md §12 rule 1)
  s("fs_ant", "Ant starts with..."), s("fs_apple", "Apple starts with..."), s("fs_man", "Man starts with..."), s("fs_map", "Map starts with..."),
  s("fs_mat", "Mat starts with..."), s("fs_milk", "Milk starts with..."), s("fs_mop", "Mop starts with..."), s("fs_mug", "Mug starts with..."),
  s("fs_nest", "Nest starts with..."), s("fs_net", "Net starts with..."), s("fs_nut", "Nut starts with..."), s("fs_pan", "Pan starts with..."),
  s("fs_peg", "Peg starts with..."), s("fs_pen", "Pen starts with..."), s("fs_pig", "Pig starts with..."), s("fs_pin", "Pin starts with..."),
  s("fs_pond", "Pond starts with..."), s("fs_pot", "Pot starts with..."), s("fs_sand", "Sand starts with..."), s("fs_sit", "Sit starts with..."),
  s("fs_sock", "Sock starts with..."), s("fs_sun", "Sun starts with..."), s("fs_tap", "Tap starts with..."), s("fs_tent", "Tent starts with..."),
  s("fs_tin", "Tin starts with..."), s("fs_top", "Top starts with..."),
  s("mid_pin", "Pin has this sound in the middle..."), s("mid_tin", "Tin has this sound in the middle..."), s("mid_zip", "Zip has this sound in the middle..."),
  s("mid_lid", "Lid has this sound in the middle..."), s("mid_pig", "Pig has this sound in the middle..."), s("mid_milk", "Milk has this sound in the middle..."),
  s("mid_bin", "Bin has this sound in the middle..."), s("mid_mop", "Mop has this sound in the middle..."), s("mid_top", "Top has this sound in the middle..."),
  s("mid_pot", "Pot has this sound in the middle..."), s("mid_cot", "Cot has this sound in the middle..."), s("mid_log", "Log has this sound in the middle..."),
  s("mid_dog", "Dog has this sound in the middle..."), s("mid_fox", "Fox has this sound in the middle..."),
  // --- First minutes (integration): warm-up W4's picture words, rain + bow and snow + man (the child says them fast)
  s("fm_name_rain", "This is rain."), s("fm_name_bow", "This is a bow."), s("fm_name_snow", "This is snow."),
  s("fm_rainbow_q", "Rain... bow. Tap the rabbit, and say them fast."), s("fm_rainbow", "Rainbow!"),
  s("fm_snowman_q", "Snow... man. Tap the rabbit, and say them fast."), s("fm_snowman", "Snowman!"),
  // --- Rewards (integration): what the first petal means (F03), and gem energy only when a gem visibly fills (F04)
  s("audit_petal_means", "This petal is for the sound..."),
  s("audit_gem_more", "Look, this gem has filled a little more."),
  // --- Praise (integration): the first time a streak powers the ninja up (F17)
  s("audit_streak_first", "Three right answers in a row! Your ninja is getting stronger."),
  // --- Sort (integration): the Bridging Unit's first sort, after all the one-sound spellings (F25)
  s("audit_bridging_first", "You know this sound! Now let's look at the different ways we spell it."),

  // --- First minutes (review pass, 26 Sep): Lesson 1's "words are made of sounds" in about 4 s (the 7.2 s
  // fm_hear_sounds stays as the fallback). Owned by the first-minutes review fixes; edit only this block.
  s("fm_hear_sounds_short", "Slowly, I hear its sounds. Words are made of sounds!"),

  // --- Re-audit r2 fixes (26 Sep): whole sentences for a merged picture said again once it is clean (the dog-fish), and
  // the battle reward naming more than one gem. Owned by the re-audit r2 fix pass; edit only this block.
  s("r2_dog_fish", "Dog fish!"),
  s("r2_gems_more", "Look, these gems have filled a little more."),

  // --- Navigation (docs/NAVIGATION.md §3.2): the idle nudge at a held Next arrow, 16 s after a step has finished (and
  // Help's second press on a held step). One whole recording, never spliced. Owned by src/ui/nav.tsx; edit only this block.
  s("nav_ready", "Tap the green arrow when you're ready."),

  // --- Baron Muddle
  b("baron_taunt_1", "Mwa-ha-ha... I hid THAT sound very well, little ninja."),
  b("baron_taunt_2", "Muddle... muddle... muddle. Your sounds belong to ME now!"),
  b("baron_taunt_3", "Silence! No more words! Not ever!"),
  b("baron_grr", "Grrrr... You dare to fight ME?"),
  b("baron_lose", "Nooo! My muddle! This is not over, ninja... I will be back!"),
  b("baron_w1", "So... a little ninja wants to stop me? My sumo panda will squash you!"),
  b("baron_w2", "My big red monster is hungry, ninja. Hungry... for SOUNDS!"),
  b("baron_w3", "In my mountains, every word freezes solid. Mwa-ha-ha!"),
  b("baron_w4", "My river dragon gobbles up sounds. Slurp! Mwa-ha-ha!"),
  b("baron_w5", "Welcome to my castle, little ninja! In here, some sounds are spelt with two letters. How muddling! Mwa-ha-ha!"),
  b("baron_w6", "So. You came all this way. Same sound, different spellings? That was my best muddle of all! Grrr!"),
  b("baron_final", "Oh... Well... I suppose words ARE rather nice. Especially... stories. Sorry for all the muddle."),

  // ---- Script style (docs/SCRIPT_STYLE.md, 26 Sep). Owned by the script fixes; edit only this block. SCRIPT_FIXES
  // Part B, where docs/TEACHER_SCRIPT.md keeps the line (not recorded: st_speaker_ok, st_like_this_in and
  // st_and_like_this_in, TS §7.3; fm_fast_mug, TS §3.5 B). TS's calm punctuation for st_hear_two/three and st_last_one.
  // --- Dojo (script style): SCRIPT_FIXES Part B
  s("st_two_letters_too", "This one's two letters too, but it's just one sound."),
  s("st_know_this_sound", "Ooh, you already know this sound!"),
  s("st_last_one", "Here's the last one."),
  s("st_find_q2", "Where's..."),
  s("st_find_q3", "Now find..."),
  s("st_th_moth_sometimes", "...in moth, and sometimes..."),
  // --- Swap (script style): SCRIPT_FIXES Part B
  s("st_what_change", "What do we need to change?"),
  s("st_first_changes", "Yes, the first sound changes!"),
  s("st_middle_changes", "Yes, the middle sound changes!"),
  s("st_last_changes", "Yes, the last sound changes!"),
  // --- Early learning (script style): SCRIPT_FIXES Part B
  s("st_hear_two", "I can hear two sounds."),
  s("st_hear_three", "I can hear three sounds."),
  s("st_first_q2", "Which picture starts with..."),
  s("st_first_q3", "Find the one that starts with..."),
  // --- World Flower (script style): SCRIPT_FIXES Part B
  s("st_found_new_sounds", "You found some new sounds! Look, here are their petals, shining through the mist."),
  s("st_another_new_sound", "And here's another new sound!"),

  // --- Teacher voice (docs/TEACHER_SCRIPT.md, 27 Sep).
  // Owned by the teacher-voice lines lane (docs/FIX_PLAN_PERF_SCRIPT_SOUNDS.md §13, TV-F2.1); edit only this block. The
  // 339 ids of TS §7.1, generated from the script by playtest/voice/make-block.py; each generated family (TS's <w>,
  // <n>, <p>, <pair>, <game>, <reader>) is one whole recording per member. A lead-in ends on "..." and is recorded
  // suspended, so a pure sound or a word can follow it. Sub-headings name the screen for jev-lint-lines.
  // --- Early learning (teacher voice, TS §2.3): The readiness interaction
  s("tv_ready_first", "Look, your ninja is ready. Are you ready too? Tap the green arrow."),
  s("tv_ready_paw", "Do you want to have a go now? Tap the green arrow. Or tap my paw to see it again."),
  s("tv_show_again", "Of course. Watch my paw again."),
  s("tv_ready_now", "Are you ready to have a go now?"),
  s("tv_ready_go", "Do you want to have a go now?"),
  s("tv_ready_together", "Let's do the next one together. Are you ready?"),
  s("tv_ready_yours", "Now you do one. Are you ready?"),
  s("tv_ready_to_watch", "I'll show you first. Are you ready to watch? Tap the green arrow."),
  s("tv_turn_again", "Now it's your turn again."),
  s("tv_offer_show", "Or I can show you again. Just tap my paw."),
  s("tv_ready_help", "When you're ready, tap the green arrow. To see it again, tap my paw."),
  // --- Title (teacher voice, TS §3.1): The film
  s("tv_film_arrow", "When you're ready to see what happens next, tap the green arrow."),
  // --- First minutes (teacher voice, TS §3.2): Choose your ninja
  s("tv_choose_q", "First, choose your ninja. Will it be Kai, or Suki?"),
  s("tv_choose_hello", "Hello! I'm Sensei Maple, and I'm going to be your teacher."),
  s("tv_choose_why", "Baron Muddle took the sounds away. We'll win them back by playing games together."),
  s("tv_choose_ninja", "Your ninja will play every game with you."),
  // --- First minutes (teacher voice, TS §3.3): The opt-in: "Do you go to big school yet?"
  s("tv_opt_why", "First, let's find the right games for you."),
  s("tv_opt_notyet", "If you don't go yet, tap the teddy."),
  s("tv_opt_yes", "If you do, tap the school."),
  s("tv_opt_echo_notyet", "Not yet. That's fine."),
  s("tv_opt_echo_school", "You go to big school."),
  s("tv_opt_again", "If you don't go yet, tap the teddy. If you do, tap the school."),
  s("tv_opt_ask", "Ask a grown-up to help you choose."),
  s("tv_opt_ok_notyet", "Then we'll start with some listening games, just for you."),
  s("tv_opt_grownups", "Grown-ups, you can change this later in the settings."),
  s("tv_opt_to_dojo", "Now come with me to the dojo. Tap the green arrow."),
  // --- Ninja Training (teacher voice, TS §3.4): The dojo welcome: three ninja tricks (Training.tsx)
  s("tv_train_tricks", "I'll teach you three ninja tricks. Each one wins a star."),
  s("tv_train_help", "Here's trick two. If you're ever stuck, tap me, down here in the corner."),
  s("tv_train_speaker", "Here's trick three, the speaker. First, listen to my little ninja rhyme."),
  s("tv_train_hello", "Welcome to my dojo. A dojo is a school for ninjas."),
  s("tv_train_gong", "Trick one is the gong. Tap it, and your ninja will kick it."),
  s("tv_train_gong_ok", "Bong! That's your first star."),
  s("tv_train_try_help", "Can you tap me now?"),
  s("tv_rhyme", "Tip, tap, tiptoe, quiet as a mouse."),
  s("tv_train_hear_again", "Tap the speaker, and I'll say it again."),
  s("tv_train_speaker_ok", "That's it! The speaker always says it again."),
  s("tv_train_done", "Three tricks, three stars. Now you're ready for your first game."),
  s("tv_first_game", "It's a listening game, called Ninja Ears. Tap the green arrow when you're ready."),
  // --- First minutes (teacher voice, TS §3.5): W1, Ninja Ears: the first lesson
  s("tv_pocket_ready_two", "Now you find the other two. Are you ready?"),
  s("tv_pocket_ready_three", "Now you find the other three. Are you ready?"),
  s("tv_ts_meet", "Here are my friends, the rabbit and the tortoise."),
  s("tv_ts_fast", "The rabbit says words fast..."),
  s("tv_ts_slow", "The tortoise says them slowly..."),
  s("tv_ears_on", "Look, your ninja has its ninja ears on. That means listening really carefully."),
  s("tv_petal_first", "That sound has its very own petal. Tap the petal, and say the sound with me."),
  s("tv_pocket_frame", "In Pocket Hunt, we find pictures that start with this sound."),
  s("tv_so_pocket", "So into the pocket it goes!"),
  s("tv_ears_frame", "I'll say a word. Then you find its picture."),
  s("tv_ears_demo", "I'll go first. My word is sun... There it is!"),
  s("tv_your_word_sock", "Your word is sock. Can you find the sock?"),
  s("tv_find_again_sock", "Can you find the sock?"),
  s("tv_idle_look_sock", "Have a look at each picture. Where's the sock?"),
  s("tv_show_offer", "Not sure? Tap my paw, and I'll show you again."),
  s("tv_idle_point", "Here it is. Tap it when you're ready."),
  s("tv_fix_together", "Let's do it together. It's this one. Now you tap it."),
  s("tv_same_word", "Fast or slow, it's the same word. When I say it slowly, I can hear its sounds."),
  s("tv_ts_wrong_rabbit", "That's my rabbit. It says words fast. Now tap the tortoise to say it slowly."),
  s("tv_ts_wrong_tortoise", "That's my tortoise. It says words slowly. Now tap the rabbit to say it fast."),
  s("tv_notice_frame", "Now let's listen for the very first sound."),
  s("tv_tap_hear_sun", "Tap the sun, and listen to how it starts."),
  s("tv_now_tap_hear_sock", "Now tap the sock, and listen to how it starts."),
  s("tv_pocket_ido", "I'll find one first."),
  s("tv_fix_start", "Listen for the start..."),
  s("tv_petal_hint", "Tap the petal if you want to hear the sound again."),
  s("tv_w1_end", "That's the end of Ninja Ears. Now watch what happens to your pictures."),
  // --- Sticker Book (teacher voice, TS §3.6): Reward 1: the Sticker Book
  s("tv_rw_book", "This is your Sticker Book! Tap it to open it."),
  s("tv_rw_every", "Every picture you play with becomes a sticker."),
  s("tv_rw_tap", "Tap a sticker, and it will say its word."),
  s("tv_rw_fast_slow", "Fast, then slow, like the rabbit and the tortoise!"),
  s("tv_rw_next", "Next, we're going to read some pictures, the ninja way. Tap the green arrow when you're ready."),
  // --- First minutes (teacher voice, TS §3.7): W2, Ninja Reading: the second lesson
  s("tv_rail_ready", "Now you read them. Do you want to have a go?"),
  s("tv_squish_ready", "Two little words make one big word. Now you make one. Are you ready?"),
  s("tv_next_game", "When you're ready for the next game, tap the green arrow."),
  s("tv_rail_frame", "Let's play Ninja Reading. Ninjas always start on this side, and go this way."),
  s("tv_which_frame", "Here are two rows of pictures. I'll read one, and you tap it."),
  s("tv_rail_ido", "I'll read them first. Then you read them."),
  s("tv_rail_turn", "Tap each picture, starting on this side."),
  s("tv_silly", "What a silly animal!"),
  s("tv_rail_start", "Ninjas start on this side. Tap this one first."),
  s("tv_which_demo", "I'll go first. Fish... dog."),
  s("tv_which_so", "Fish came first. So I tap this row."),
  s("tv_which_q_cat_dog", "Here I go. Cat... dog. Which row did I read?"),
  s("tv_which_fix_cat_dog", "Let's listen again. Cat... dog. Which row has the cat first?"),
  s("tv_squish_frame", "Here's a new game, called Word Squish."),
  s("tv_squish_slow", "I tap the tortoise, and say them slowly. Sun... flower."),
  s("tv_squish_fast", "Then I tap the rabbit, and squish them. Sunflower!"),
  s("tv_praise_squish", "You squished them into one big word!"),
  s("tv_pocket_more_s", "One more Pocket Hunt. Find the pictures that start with..."),
  s("tv_pocket_more_m", "One more Pocket Hunt. Find the pictures that start with..."),
  s("tv_rw_link_book", "Let's put your new pictures in your Sticker Book."),
  // --- World Flower (teacher voice, TS §3.8): Reward 2, the World Flower's first glimpse, and the first map
  s("tv_rw2_flower", "This is the World Flower. Your sounds make it shine."),
  // --- Map (teacher voice, TS §3.8): Reward 2, the World Flower's first glimpse, and the first map
  s("tv_map_intro", "This is the map of Bamboo Village. Every stone is a game."),
  // --- World Flower (teacher voice, TS §3.8): Reward 2, the World Flower's first glimpse, and the first map
  s("tv_rw2_tap_petal", "Tap your petal, and hear its sound."),
  // --- Map (teacher voice, TS §3.8): Reward 2, the World Flower's first glimpse, and the first map
  s("tv_map_flower", "And your World Flower lives here."),
  s("tv_map_hint", "The glowing stone is your next game. Tap it when you're ready."),
  // --- First minutes (teacher voice, TS §3.9): W3, Ninja Ears again: Slow Words, and sounds in the middle
  s("tv_ts_again", "Here come the rabbit and the tortoise again."),
  s("tv_ts_slow_one", "The tortoise says it slowly..."),
  s("tv_praise_slowly", "You said it slowly, just like the tortoise."),
  s("tv_slow_frame", "Let's play Slow Words. I say a word slowly. You find its picture."),
  s("tv_slow_demo", "Here's my slow word..."),
  s("tv_i_hear_mug", "I can hear mug!"),
  s("tv_i_hear_sun", "I can hear sun!"),
  s("tv_slow_yours", "Here's your slow word..."),
  s("tv_slow_again", "Let's listen again..."),
  s("tv_pocket_middle", "It's Pocket Hunt again. This time, the sound is hiding in the middle of the words."),
  s("tv_here_sound", "Here's the sound..."),
  s("tv_new_petal_say", "It's a new sound. Tap its petal, and say it with me."),
  s("tv_hear_middle", "I can hear it in the middle."),
  s("tv_fix_middle", "Listen for the middle..."),
  s("tv_w3_done", "You heard sounds at the start of words, and in the middle. Super listening!"),
  // --- First minutes (teacher voice, TS §3.10): W4, Ninja Reading again: three in a row
  s("tv_rail_again", "It's Ninja Reading again. This time, there are three pictures."),
  s("tv_rail_yours", "Now you read them."),
  s("tv_which_again", "Here are two rows again. I'll read one, and you tap it."),
  s("tv_which_q_fish_dog_cat", "Here I go. Fish... dog... cat. Which row did I read?"),
  s("tv_which_fix_fish_dog_cat", "Let's listen again. Fish... dog... cat. Which row has the fish first?"),
  s("tv_squish_again", "It's Word Squish again. Two little words make one big word."),
  s("tv_w4_done", "You read three pictures in a row, the ninja way."),
  s("tv_practise_again", "That game was a bit tricky. Let's play it once more."),
  // --- First minutes (teacher voice, TS §3.11): W5, Guess My Word (sounds, full)
  s("tv_guess_frame", "I'll say the sounds, and you listen for the word."),
  s("tv_my_sounds", "My sounds are..."),
  s("tv_guess_so_sun", "I can hear sun. So I tap the sun."),
  s("tv_guess_q", "Listen for the word..."),
  s("tv_guess_together", "Let's say it together."),
  s("tv_guess_again", "Let's listen again..."),
  s("tv_w5_done", "You listened to the sounds, and you heard the words."),
  // --- First minutes (teacher voice, TS §3.12): W6, Sound Dots (dots, full)
  s("tv_dots_ready", "Now you tap the dots, and say the sounds with me. Are you ready?"),
  s("tv_dots_frame", "Every dot is one sound in the word."),
  s("tv_dots_ido", "I start here, and go this way."),
  s("tv_dots_word_ido", "Then I say the word..."),
  s("tv_now_say_word", "Now say the whole word..."),
  // --- Early learning (teacher voice, TS §3.13): w1-2, First Sounds, and the first letters
  s("tv_watch_write", "Now watch my ninja write it."),
  s("tv_how_we_write", "This is how we write..."),
  s("tv_first_frame", "In First Sounds, I say a sound, and you find the picture that starts with it."),
  s("tv_first_sound", "Our first sound is..."),
  s("tv_petal_say", "Tap the petal, and say it with me."),
  s("tv_ido_pair_map_hat", "I'll go first. Here's a map and a hat."),
  s("tv_ido_pair_bed_sock", "I'll go first. Here's a bed and a sock."),
  s("tv_ido_pair_cat_ant", "I'll go first. Here's a cat and an ant."),
  s("tv_ido_pair_jam_tent", "I'll go first. Here's some jam and a tent."),
  s("tv_ido_pair_nut_hat", "I'll go first. Here's a nut and a hat."),
  s("tv_ido_pair_bus_pig", "I'll go first. Here's a bus and a pig."),
  s("tv_ido_pair_pan_pin", "I'll go first. Here's a pan and a pin."),
  s("tv_ido_pair_map_mop", "I'll go first. Here's a map and a mop."),
  s("tv_let_me_listen", "Hmm, let me listen."),
  s("tv_so_i_tap", "So I'll tap it."),
  s("tv_tap_it_say", "Now you tap it, and say the sound."),
  s("tv_by_yourself", "Now you do one all by yourself."),
  s("tv_praise_start", "You listened right to the very start."),
  s("tv_next_sound_known", "Our next sound is one you know..."),
  s("tv_together", "Let's do this one together."),
  s("tv_and_how_we_write", "And this is how we write..."),
  s("tv_mix_up", "Now it could be either sound. Listen carefully to my sound."),
  s("tv_ne_frame", "Next, a game called Ninja Eyes. I say a sound, and you find how we write it."),
  s("tv_which_write", "Which of these is the way we write..."),
  s("tv_find_write", "Find how we write..."),
  s("tv_now_find", "Now find how we write..."),
  s("tv_thats_write", "That's how we write..."),
  s("tv_first_done", "You listened for the first sound in every word, and you found how we write it."),
  // --- Rewards (teacher voice, TS §3.14): The reward, and the World Flower's first visit (after w1-2)
  s("tv_to_reward", "Let's see what you won back from Baron Muddle."),
  s("tv_won_two", "You won back two sounds..."),
  s("tv_won_three", "You won back three sounds..."),
  s("tv_won_four", "You won back four sounds..."),
  // --- World Flower (teacher voice, TS §3.14): The reward, and the World Flower's first visit (after w1-2)
  s("tv_to_flower_first", "Now let's go and see where your sounds live. Tap the green arrow."),
  s("tv_flower_petal", "Every petal is one sound. This is the petal for..."),
  s("tv_flower_tap", "Tap it, and hear its sound."),
  s("tv_another_sound", "And here's another new sound..."),
  s("tv_flower_bye", "Your World Flower is waiting for more sounds. Let's go and find them!"),
  // --- Early learning (teacher voice, TS §3.15): w1-3, First Sounds again (/a/, /t/)
  s("tv_next_sound", "Our next sound is..."),
  s("tv_first_again_new", "It's First Sounds again, with two new sounds."),
  s("tv_first_recap", "It's First Sounds again. I say a sound, and you find the picture that starts with it."),
  s("tv_ne_again", "Now let's play Ninja Eyes."),
  // --- Early learning (teacher voice, TS §3.16): w1-4, Word Building, then Kai and Suki
  s("tv_build_lines", "Each line is for one sound."),
  s("tv_word_card", "This card is my word. Tap it, and hear the word."),
  s("tv_readers_meet", "Look, it's Kai and Suki. They're learning to read, like you."),
  s("tv_your_word", "Your word is..."),
  s("tv_build_frame", "This game is called Word Building. I say a word, and we build it with its sounds."),
  s("tv_i_say_slowly", "I say it slowly..."),
  s("tv_first_is", "The first sound is..."),
  s("tv_you_find_last", "Can you find the last one?"),
  s("tv_lets_say_read", "Now let's say the sounds... and read the word."),
  s("tv_build_ready", "Now let's build one together. Are you ready?"),
  s("tv_our_word", "Here's our word..."),
  s("tv_last_first", "Now the last sound. Listen right to the end..."),
  s("tv_by_yourself_build", "Now you build one all by yourself."),
  s("tv_praise_built", "You built that whole word by yourself!"),
  s("tv_rc_how", "They'll both read this word. Only one of them reads it right."),
  s("tv_you_read_first", "First, you read it. Tap each sound, and say it with me."),
  s("tv_now_readers", "Now listen to Kai and Suki read it."),
  s("tv_rc_q", "Who read it right? Tap Kai, or tap Suki."),
  s("tv_yes_kai", "Yes! Kai read it right."),
  s("tv_yes_suki", "Yes! Suki read it right."),
  s("tv_lets_check", "Let's check. Say the sounds with me..."),
  s("tv_right_kai", "Kai read it right."),
  s("tv_right_suki", "Suki read it right."),
  s("tv_build_done", "You built words with their sounds, and you read them."),
  // --- Early learning (teacher voice, TS §3.17): w1-5, Word Building with three sounds
  s("tv_build_again_3", "It's Word Building again. This word has three sounds, so there are three lines."),
  s("tv_next_middle", "Now the next sound. It's in the middle..."),
  s("tv_readers_back", "Kai and Suki are back. You read it first, then they read it."),
  // --- Battle (teacher voice, TS §3.18): w1-6, the first Monster Battle (battle, full)
  s("tv_battle_ready", "That's how we spell a word. Now you spell one. Are you ready to zap it?"),
  s("tv_bar_down", "Zap! Look, its bar went down."),
  s("tv_battle_oh_no", "Oh no! One of Baron Muddle's monsters is in the way!"),
  s("tv_battle_frame", "We zap it with words, just like Word Building."),
  s("tv_battle_card", "I'll zap the first one. Tap my word card, and hear the word."),
  s("tv_next_word", "Here's your next word..."),
  s("tv_battle_why", "Every monster you beat helps us win back the sounds."),
  // --- Early learning (teacher voice, TS §3.19): w1-7, Sound Hunt: a sound in the middle (soundhunt, full)
  s("tv_next_build", "Next, we're going to build some words with this sound..."),
  s("tv_hunt_frame", "In Sound Hunt, the sound is hiding in the middle of the word."),
  s("tv_swap_both", "Listen to them both..."),
  s("tv_hunt_q", "Which one has this sound in the middle..."),
  s("tv_praise_middle", "You heard it, right in the middle."),
  s("tv_not_in_middle", "That one has a different sound in the middle."),
  s("tv_hunt_done", "You heard a sound right in the middle of words. That's tricky, and you did it!"),
  // --- Swap (teacher voice, TS §3.20): w1-8, Sound Swap (swap, full)
  s("tv_swap_ready", "Now you swap one. Do you want to have a go?"),
  s("tv_swap_oh_dear", "Oh dear. Baron Muddle has been muddling up words."),
  s("tv_swap_read_first", "First, let's read this word. Tap each sound, and say it with me."),
  s("tv_swap_frame", "In Sound Swap, we change just one sound, to make a new word."),
  s("tv_swap_change_to", "I'll change it to..."),
  s("tv_swap_kick", "The first sound changes. Can you tap it, and kick it out?"),
  s("tv_swap_in", "And in goes..."),
  s("tv_swap_now_change", "Now let's change it to..."),
  s("tv_swap_pick", "Now tap the new one."),
  s("tv_praise_swap", "You changed just one sound."),
  s("tv_swap_done", "You fixed all of Baron's muddled words!"),
  // --- Run (teacher voice, TS §3.21): w1-9, Ninja Run (run, full)
  s("tv_run_ready", "Are you ready? Tap the green arrow, and off we go!"),
  s("tv_run_lanterns", "Here come the lanterns. I'll say the sounds of a word."),
  s("tv_run_frame", "This game is called Ninja Run. Your ninja runs all by itself."),
  s("tv_run_jump", "Tap anywhere to make your ninja jump. Can you try it now?"),
  s("tv_run_jump_ok", "Good jumping!"),
  s("tv_run_lanterns_how", "When the lanterns come, I'll say some sounds, and you catch the word."),
  s("tv_run_which", "Tap the lantern with my word."),
  s("tv_run_fix", "That's a different word. Listen again..."),
  // --- Early learning (teacher voice, TS §3.22): w1-10 to w1-13: the second meetings
  s("tv_next_build_plain", "Next, we're going to build some words."),
  s("tv_hunt_again", "It's Sound Hunt again, with a new sound."),
  // --- Swap (teacher voice, TS §3.22): w1-10 to w1-13: the second meetings
  s("tv_swap_again", "It's Sound Swap again. We change one sound to make a new word."),
  s("tv_show_offer_short", "If you'd like to see me do one first, tap my paw."),
  // --- Battle (teacher voice, TS §3.22): w1-10 to w1-13: the second meetings
  s("tv_battle_again", "Another monster! Let's zap it with words."),
  // --- Story (teacher voice, TS §3.23): w1-14, Story Time (story, full)
  s("tv_story_tick", "When you've read it all, tap the green tick."),
  s("tv_story_frame", "Story time! I'll read some pages to you, and you'll read some pages to me."),
  s("tv_story_title", "This story is called..."),
  s("tv_story_begin", "Tap the green arrow, and let's begin."),
  s("tv_story_yours", "This page is yours. Say the sounds, and read each word."),
  s("tv_story_help", "If you get stuck, tap a word, and I'll help."),
  s("tv_story_together", "Let's read it together."),
  s("tv_story_choice", "Now you choose what happens. Read the two words, and tap one."),
  s("tv_story_q", "Now a question about the story."),
  s("tv_story_tick_idle", "When you've read it, tap the green tick."),
  // --- Battle (teacher voice, TS §3.24): w1-15, the first boss (boss, full)
  s("tv_boss_ready", "Are you ready to beat the boss? Tap the green arrow."),
  s("tv_boss_calm", "Don't worry, ninja. You know what to do."),
  s("tv_boss_frame", "A boss takes lots of words to beat."),
  // --- Map (teacher voice, TS §3.25): The land is done: the World Flower, then Blossom Hills
  s("tv_map_next_sounds", "Next is a new game, called Guess My Word. Tap the glowing stone to play."),
  s("tv_map_next_dots", "Next is a new game, called Sound Dots. Tap the glowing stone to play."),
  s("tv_map_next_firstsound", "Next is a new game, called First Sounds. Tap the glowing stone to play."),
  s("tv_map_next_build", "Next is a new game, called Word Building. Tap the glowing stone to play."),
  s("tv_map_next_battle", "Next is a Monster Battle. Baron Muddle's monsters are guarding the sounds. Tap the glowing stone, if you're brave."),
  s("tv_map_next_soundhunt", "Next is a new game, called Sound Hunt. Tap the glowing stone to play."),
  s("tv_map_next_swap", "Next is a new game, called Sound Swap. Baron Muddle has mixed up some words! Tap the glowing stone to fix them."),
  s("tv_map_next_run", "Next is a new game, called Ninja Run. Tap the glowing stone to play."),
  s("tv_map_next_story", "Next is Story Time. Tap the glowing stone to open the book."),
  s("tv_map_next_boss", "Next is the boss of Bamboo Village. Tap the glowing stone, if you're ready."),
  s("tv_map_next_learn", "Next is the dojo. You'll learn some new sounds there. Tap the glowing stone to go."),
  s("tv_map_next_sort", "Next is a new game, called Sorting. Tap the glowing stone to play."),
  // --- World Flower (teacher voice, TS §3.25): The land is done: the World Flower, then Blossom Hills
  s("tv_flower_recap", "Here's a sound you learnt..."),
  // --- Dojo (teacher voice, TS §3.26): w2-1, the first Dojo lesson: New Sounds (Jonas's "Listen!" and the ear)
  s("tv_learn_ready", "Are you ready for the first one? Tap the green arrow."),
  s("tv_learn_frame_two", "Today in the dojo, I'm going to teach you two new sounds."),
  s("tv_learn_frame_three", "Today in the dojo, I'm going to teach you three new sounds."),
  s("tv_learn_frame_four", "Today in the dojo, I'm going to teach you four new sounds."),
  s("tv_learn_how", "I'll say each sound, and show you how we write it. Then you say it with me."),
  s("tv_learn_first", "Here's the first new sound. Get your ninja ears ready."),
  s("tv_here_it_comes", "Here it comes..."),
  s("tv_tap_letter_say", "Now you tap it, and say the sound."),
  s("tv_once_more", "Tap it once more, and say it again."),
  s("tv_said_well", "Good, you said that sound really well."),
  s("tv_learn_next", "Here's the next new sound..."),
  s("tv_petal_say_short", "Tap its petal, and say it."),
  s("tv_tap_it_say_short", "Now you tap it, and say it."),
  s("tv_learn_another", "Here's another new sound..."),
  s("tv_learn_last", "Here's the last new sound..."),
  s("tv_learn_all_two", "Two new sounds! You said every one."),
  s("tv_learn_all_three", "Three new sounds! You said every one."),
  s("tv_learn_all_four", "Four new sounds! You said every one."),
  s("tv_dojo_idle_say", "Tap the letter, and say the sound with me..."),
  s("tv_dojo_help_sound", "Here's the sound again..."),
  s("tv_x_two_sounds", "This spelling is two sounds together."),
  s("tv_ne_new_sounds", "Now let's play Ninja Eyes, with your new sounds."),
  s("tv_build_dojo", "Now let's build some words with your new sounds."),
  s("tv_learn_done", "You learnt four new sounds today, and you built words with them."),
  // --- Early learning (teacher voice, TS §4.1): The registry (the content of src/content/games.ts)
  s("tv_now_your_turn", "Now it's your turn."),
  // --- First minutes (teacher voice, TS §4.1): The registry (the content of src/content/games.ts)
  s("tv_pocket_recap", "It's Pocket Hunt again. We find pictures that start with this sound."),
  s("tv_pocket_middle_more_o", "One more Pocket Hunt. Find the pictures with this sound in the middle..."),
  s("tv_slow_recap", "It's Slow Words again. I say a word slowly, and you find its picture."),
  s("tv_slow_short", "Let's play Slow Words again."),
  s("tv_guess_recap", "It's Guess My Word again. I'll say the sounds, and you listen for the word."),
  s("tv_guess_short", "Let's play Guess My Word again."),
  s("tv_dots_recap", "It's Sound Dots again. Every dot is one sound in the word."),
  s("tv_dots_short", "It's Sound Dots again. Tap the dots, and say the sounds with me."),
  // --- Early learning (teacher voice, TS §4.1): The registry (the content of src/content/games.ts)
  s("tv_first_again_known", "It's First Sounds again. Let's see which sounds you know."),
  s("tv_ne_recap", "It's Ninja Eyes again. I say a sound, and you find how we write it."),
  s("tv_hunt_recap", "It's Sound Hunt again. The sound is hiding in the middle of the word."),
  s("tv_build_recap", "It's Word Building again. I say a word, and we build it with its sounds."),
  s("tv_build_again_short", "Let's build some more words."),
  // --- Battle (teacher voice, TS §4.1): The registry (the content of src/content/games.ts)
  s("tv_battle_recap", "Another of Baron's monsters! You know how to zap it. Find the sounds in each word."),
  s("tv_battle_go", "Are you ready to zap it? Tap the green arrow."),
  s("tv_boss_again", "Oh no, another boss! Don't worry. You know just what to do."),
  // --- Run (teacher voice, TS §4.1): The registry (the content of src/content/games.ts)
  s("tv_run_again", "It's Ninja Run again! Are you ready? Tap the green arrow, and off we go!"),
  // --- Story (teacher voice, TS §4.1): The registry (the content of src/content/games.ts)
  s("tv_story_recap", "Story time! I'll read some pages, and you'll read some too."),
  s("tv_story_short", "Story time!"),
  // --- Dojo (teacher voice, TS §4.1): The registry (the content of src/content/games.ts)
  s("tv_learn_recap_two", "Back to the dojo, for two new sounds. You know how this goes."),
  s("tv_learn_recap_three", "Back to the dojo, for three new sounds. You know how this goes."),
  s("tv_learn_recap_four", "Back to the dojo, for four new sounds. You know how this goes."),
  s("tv_learn_short_two", "Back to the dojo. Today there are two new sounds."),
  s("tv_learn_short_three", "Back to the dojo. Today there are three new sounds."),
  s("tv_learn_short_four", "Back to the dojo. Today there are four new sounds."),
  s("tv_learn_first_short", "Here's the first new sound..."),
  // --- Battle (teacher voice, TS §4.2): Gem battles (trial, full: the first Gem Trial; a child of 5 or more)
  s("tv_trial_ready", "The bar starts when you're ready. Tap the green arrow."),
  s("tv_trial_heart", "The bar filled up, so you lost a heart. That's fine. Keep going."),
  s("tv_trial_short", "It's a gem battle! Spell each word before the bar is full. Tap the green arrow when you're ready."),
  s("tv_trial_frame", "This is a gem battle. Win it, and the gem is yours."),
  s("tv_trial_bar", "Spell each word before this purple bar is full."),
  // --- Sort (teacher voice, TS §4.3): Sorting (sort, full: w6-br1, a Year One child of 5 or more)
  s("tv_sort_recap", "It's Sorting again. Every word goes in the chest with the same spelling."),
  s("tv_sort_frame", "This game is called Sorting. Every word goes in the chest with the same spelling."),
  s("tv_sort_open", "This sound can be spelt in three ways. Tap each chest to open it."),
  s("tv_spelt_like_this_kit", "In kit, it's spelt like this."),
  s("tv_spelt_like_this_cat", "In cat, it's spelt like this."),
  s("tv_spelt_like_this_yak", "In yak, it's spelt like this."),
  s("tv_spelt_like_this_duck", "In duck, it's spelt like this."),
  s("tv_spelt_like_this_chick", "In chick, it's spelt like this."),
  s("tv_spelt_like_this_match", "In match, it's spelt like this."),
  s("tv_spelt_like_this_rain", "In rain, it's spelt like this."),
  s("tv_spelt_like_this_tray", "In tray, it's spelt like this."),
  s("tv_spelt_like_this_bee", "In bee, it's spelt like this."),
  s("tv_spelt_like_this_leaf", "In leaf, it's spelt like this."),
  s("tv_spelt_like_this_boat", "In boat, it's spelt like this."),
  s("tv_spelt_like_this_snow", "In snow, it's spelt like this."),
  s("tv_spelt_like_this_light", "In light, it's spelt like this."),
  s("tv_spelt_like_this_pie", "In pie, it's spelt like this."),
  s("tv_sort_ido", "I'll sort the first one. My word is..."),
  s("tv_sort_see", "I can see this spelling at the end."),
  s("tv_sort_so", "So it goes in this chest."),
  s("tv_sort_fix", "Let's look again. Which chest has the same spelling?"),
  s("tv_sort_done", "Same sound, different spellings. You sorted them all."),
  // --- Battle (teacher voice, TS §4.4): Sensei's Challenge (review, full: the first time the map's button is tapped)
  s("tv_review_short", "It's Sensei's Challenge! Are you ready? Tap the green arrow."),
  s("tv_review_frame", "This is Sensei's Challenge. It has words from all the games you've played."),
  s("tv_review_how", "Find the sounds in each word to zap it. Let's see how many you can do!"),
  s("tv_review_done", "You zapped so many words! That was a real challenge."),
  // --- Run (teacher voice, TS §4.5): Ninja Run's reading groups (run, reading: the first time)
  s("tv_run_read_first", "Now it's your turn to read. Read the word at the top, and catch its picture."),
  // --- Dojo (teacher voice, TS §4.6): A school path's first Dojo (Reception after the autumn, Years One and Two)
  s("tv_dj_room", "This is the dojo, a school for ninjas. Here, you learn new sounds."),
  s("tv_learn_frame_ways", "Today in the dojo, I'm going to teach you new ways to write a sound you know."),
  s("tv_and_another_way", "And here's another way to spell it..."),
  // --- Early learning (teacher voice, TS §4.7): The Year One and Two word hunt (tapall, words, the first time)
  s("tv_word_hunt_frame", "It's a word hunt. Every word with our sound in it goes in a pocket."),
  s("tv_find_words_in", "Find every word with this sound in it..."),
  s("tv_hear_in_rain", "I can hear it in rain."),
  // --- Placement (teacher voice, TS §4.9): Show Sensei (the placement quiz, started by a grown-up)
  s("tv_place_frame", "Let's play a quick game, so I can see what you know already."),
  s("tv_place_ok", "Some might be tricky. That's fine. Just have a go."),
  s("tv_place_sound_round", "I say a sound, and you find how we write it."),
  s("tv_place_findall_round", "Find every picture with this sound in it..."),
  s("tv_place_done", "Thank you, ninja. Now I know just where to start."),
  // --- Dojo (teacher voice, TS §4.10): The practice dojo (the World Flower's Practise gate)
  s("tv_practise_gem", "Let's practise this gem. I say a word, and you build it."),
  // --- Early learning (teacher voice, TS §5.2): Show me again (the paw)
  s("tv_offer_show_miss", "Shall I show you again? Tap my paw."),
  // --- Praise (teacher voice, TS §5.3): Praise
  s("tv_praise_found", "You found it!"),
  s("tv_praise_order", "You read them the ninja way."),
  s("tv_praise_row", "You remembered which came first."),
  s("tv_praise_heard_word", "You heard the word in the sounds."),
  s("tv_praise_write", "You know how we write that sound."),
  s("tv_praise_judge", "You checked their reading, like a real teacher!"),
  s("tv_praise_sorted", "That's the right chest."),
  s("tv_praise_read", "Lovely reading!"),
  s("tv_praise_kept_going", "That was a tricky one, and you kept going."),
  s("tv_praise_helped", "Now you've got it."),
  s("tv_yay_lovely", "Lovely!"),
  s("tv_yay_thats_it", "That's it!"),
  s("tv_streak_10", "Ten in a row! Look how your ninja is glowing!"),
  // --- Correction (teacher voice, TS §5.4): Gentle correction
  s("tv_listen_here", "Let's listen again. What can you hear here?"),
  // --- Correction (teacher voice, TS §5.5): When the child is quiet (a turn's idle ladder), and Help
  s("tv_listen_sound_again", "Listen to my sound again..."),
  s("tv_which_starts_it", "Which picture starts with it?"),
  s("tv_which_way_write_it", "Which one is the way we write it?"),
  s("tv_both_again", "Listen to them both again..."),
  s("tv_which_changes", "Which sound changes?"),
  s("tv_take_time", "Take your time, ninja."),
  s("tv_look_glow", "Look for the glow."),
  // --- Rewards (teacher voice, TS §5.6): Wrapping up, and moving on
  s("tv_dojo_review_done", "You built lots of words. Your ninja is getting stronger."),
  // --- Rewards (teacher voice, TS §5.7): The moment before a reward, and the reward
  s("tv_to_flower", "Let's take your new sounds to the World Flower. Tap the green arrow."),
  s("tv_won_one", "You won back a sound..."),
  s("tv_rest", "You've practised so much today! Ninjas need rest too. You can stop here, and your ninja will wait for you."),
  s("tv_jump_offer", "Wow, you got everything right! Grown-ups, if this is too easy, you can jump ahead."),
  // --- Map (teacher voice, TS §5.8): The map, and coming back
  s("tv_welcome_back", "Welcome back, ninja! I'm so happy to see you."),
];
// whole-sentence example clips for the teacher language (scripts/gen-teach-lines.ts → teach-lines.gen.ts)
LINES.push(...TEACH_LINES.map((l) => s(l.id, l.text)));

export const PRAISE = ["yay_1", "yay_2", "yay_3", "yay_4", "yay_5", "yay_6", "yay_7", "yay_8", "yay_9", "yay_10"];
export const BARON_TAUNTS = ["baron_taunt_1", "baron_taunt_2", "baron_taunt_3"];

// --- Teacher voice: retired lines (docs/TEACHER_SCRIPT.md §7.3, 27 Sep). Owned by the teacher-voice lines lane.
/** Lines the teacher's voice retires from the preschool and early paths. They stay in LINES (and keep their clips) until
 *  nothing calls them; the value says where they retire ("retired on these paths" everywhere TS covers). The tail
 *  clips `tg_<g>_<p>_in` retire too, replaced by `tg_<g>_<p>_way` (TS §3.14, T11). */
export const RETIRED_LINES: Readonly<Record<string, string>> = {
  intro_8: "retired on these paths",
  tut_1: "retired on these paths",
  fm_help_short: "retired on these paths",
  fm_speaker: "retired on these paths",
  fm_opt_notyet: "retired on these paths",
  fm_opt_yes: "retired on these paths",
  fm_opt_q1_again: "retired on these paths",
  fm_opt_echo_notyet: "retired on these paths",
  fm_opt_echo_school: "retired on these paths",
  fm_opt_ok_notyet: "retired on these paths",
  fm_opt_grownups: "retired on these paths",
  fm_show_me: "retired on these paths",
  fm_show_me_2: "retired on these paths",
  fm_you_try: "retired on these paths",
  fm_you_try_2: "retired on these paths",
  ido: "retired on these paths",
  wedo: "retired on these paths",
  youdo: "retired on these paths",
  fm_tap_sun: "retired on these paths",
  fm_tap_sock: "retired on these paths",
  fm_l1_hello: "retired on these paths",
  fm_same_word: "retired on these paths",
  fm_hear_sounds: "retired on these paths",
  fm_hear_sounds_short: "retired on these paths",
  fm_first_listen: "retired on these paths",
  t_everyone_say: "retired on these paths",
  fm_tap_all_start: "retired on these paths",
  fm_l1_done: "retired on these paths",
  fm_rw_book: "retired on these paths",
  fm_rw_every: "retired on these paths",
  fm_rw_tap: "retired on these paths",
  fm_rw_next: "retired on these paths",
  fm_l2_way: "retired on these paths",
  fm_l2_turn: "retired on these paths",
  fm_l2_start: "retired on these paths",
  fm_which_cat_dog: "retired on these paths",
  fm_which_three: "retired on these paths",
  fm_l2_big_word: "retired on these paths",
  fm_sunflower: "retired on these paths",
  fm_sunflower_q: "retired on these paths",
  fm_sunflower_fast: "retired on these paths",
  fm_quick_tap_all: "retired on these paths",
  fm_slow_listen: "retired on these paths",
  fm_slow_another: "retired on these paths",
  fm_tap_all_in: "retired on these paths",
  fm_tap_all_words_in: "retired on these paths",
  audit_made_of_sounds: "retired on these paths",
  fm_sounds_intro: "retired on these paths",
  fm_l5_done: "retired on these paths",
  fm_dots_intro: "retired on these paths",
  fm_dots_turn: "retired on these paths",
  fm_dots_say: "retired on these paths",
  fm_practise_again: "retired on these paths",
  audit_petal_means: "retired on these paths",
  map_hint: "retired on these paths",
  fm_its_this: "retired on these paths",
  first_intro: "retired on these paths",
  find_q: "retired on these paths",
  how_we_spell: "on this path",
  hunt_intro: "retired on these paths",
  hunt_q: "retired on these paths",
  audit_middle_place: "retired on these paths",
  audit_last_place: "retired on these paths",
  audit_dojo_first: "retired on these paths",
  two_sounds: "retired on these paths",
  three_sounds: "retired on these paths",
  build_ido_1: "retired on these paths",
  build_ido_2: "retired on these paths",
  build_ido_3: "retired on these paths",
  read_intro: "retired on these paths",
  listen_again: "retired on these paths",
  listen_here: "retired on these paths",
  dojo_hello: "retired on these paths",
  audit_dojo_back: "retired on these paths",
  listen: "as any opener",
  audit_spell_it: "retired on these paths",
  dojo_tap_say: "retired on these paths",
  dojo_find: "retired on these paths",
  tut_speaker: "retired on these paths",
  dojo_build: "retired on these paths",
  dojo_build_word: "retired on these paths",
  dojo_done: "retired on these paths",
  battle_start: "retired on these paths",
  battle_spell: "retired on these paths",
  battle_boss: "retired on these paths",
  audit_baron_first: "retired on these paths",
  timer_intro_1: "retired on these paths",
  timer_intro_2: "retired on these paths",
  timer_intro_3: "retired on these paths",
  audit_trial_first: "retired on these paths",
  audit_timer_short: "retired on these paths",
  audit_timer_hearts: "retired on these paths",
  trial_start: "retired on these paths",
  swap_start: "retired on these paths",
  this_is: "in Sound Swap",
  swap_make: "retired on these paths",
  swap_pick: "retired on these paths",
  what_changed: "retired on these paths",
  audit_swap_first: "retired on these paths",
  audit_swap_middle: "retired on these paths",
  audit_swap_last: "retired on these paths",
  swap_done: "retired on these paths",
  run_start: "retired on these paths",
  run_blend: "retired on these paths",
  audit_sounds_again: "retired on these paths",
  t_listen_for_word: "retired on these paths",
  story_start: "retired on these paths",
  story_question: "retired on these paths",
  audit_story_choice: "retired on these paths",
  audit_sort_first: "retired on these paths",
  audit_sort_three: "on the first sort",
  sort_done: "retired on these paths",
  flower_i2: "retired on these paths",
  flower_i4: "retired on these paths",
  flower_i6: "retired on these paths",
  t_remember_this: "retired on these paths",
  t_now_you_say_it: "retired on these paths",
  petal_got: "retired on these paths",
  petals_got: "retired on these paths",
  dojo_nap: "retired on these paths",
  jump_offer: "retired on these paths",
  welcome_back: "retired on these paths",
  streak_10: "retired on these paths",
  yay_7: "as a reward lead",
  audit_hear_see: "on this path",
};
