// GENERATED by scripts/treadmill/pics-to-content.ts from a blind picture audit (playtest/runs/pics-v2). Don't edit by hand:
// improve the picture (scripts/art-manifest.ts), rerun pic-audit.ts, then this.
// Pictures a 4-year-old names as something else: [what they say, same first sound?, same vowel?].
// Pictures not listed are named as intended.
export const PIC_NAMES: Record<string, [said: string, first: boolean, vowel: boolean]> = {
  "astronaut": ["spaceman", false, true],
  "beach": ["bucket", true, false],
  "bulb": ["lightbulb", false, false],
  "cab": ["taxi", false, true],
  "chimp": ["monkey", false, false],
  "cob": ["sweetcorn", false, false],
  "crow": ["bird", false, false],
  "cub": ["bear", false, false],
  "dot": ["ball", false, false],
  "fig": ["fruit", true, false],
  "fin": ["shark", false, false],
  "fog": ["tree", false, false],
  "gift": ["present", false, false],
  "hen": ["chicken", false, false],
  "hill": ["jelly", false, false],
  "hob": ["cooker", false, false],
  "hop": ["jumping", false, false],
  "hot": ["soup", false, false],
  "hug": ["cuddle", false, true],
  "insect": ["beetle", false, false],
  "jet": ["aeroplane", false, false],
  "nap": ["cat", false, true],
  "night": ["moon", false, false],
  "pup": ["doggy", false, false],
  "queen": ["king", true, false],
  "quilt": ["blanket", false, false],
  "sea": ["wave", false, false],
  "ship": ["boat", false, false],
  "squid": ["octopus", false, false],
  "stamp": ["flower", false, false],
  "tea": ["cup", false, false],
  "tub": ["bath", false, false],
  "tusk": ["horn", false, false],
  "twig": ["stick", false, true],
};
/** Safe for a picture-only game that tests this part of the word. */
export const picSaysFirst = (w: string) => !PIC_NAMES[w] || PIC_NAMES[w][1];
export const picSaysVowel = (w: string) => !PIC_NAMES[w] || (PIC_NAMES[w][1] && PIC_NAMES[w][2]);
