// GENERATED by scripts/gen-teach-lines.ts: example sentences for teach.ts, one clip each. Don't edit by hand.
export const TEACH_LINES: { id: string; text: string }[] = [
 {
  "id": "tp_ae_hear",
  "text": "You can hear it in rain, tray and tail."
 },
 {
  "id": "tp_ae_list",
  "text": "Rain, tray and tail."
 },
 {
  "id": "tg_ai_ae_way",
  "text": "This is the way we spell it in rain."
 },
 {
  "id": "tg_ai_ae_in",
  "text": "...in rain."
 },
 {
  "id": "tg_ai_ae_see",
  "text": "We see this spelling in tail and nail."
 },
 {
  "id": "tg_ai_ae_like",
  "text": "...like in rain, tail and nail."
 },
 {
  "id": "tg_ay_ae_way",
  "text": "This is the way we spell it in tray."
 },
 {
  "id": "tg_ay_ae_in",
  "text": "...in tray."
 },
 {
  "id": "tg_ay_ae_see",
  "text": "We see this spelling in day and say."
 },
 {
  "id": "tg_ay_ae_like",
  "text": "...like in tray, day and say."
 },
 {
  "id": "tp_ee_hear",
  "text": "You can hear it in bee, leaf and tree."
 },
 {
  "id": "tp_ee_list",
  "text": "Bee, leaf and tree."
 },
 {
  "id": "tg_ee_ee_way",
  "text": "This is the way we spell it in bee."
 },
 {
  "id": "tg_ee_ee_in",
  "text": "...in bee."
 },
 {
  "id": "tg_ee_ee_see",
  "text": "We see this spelling in tree and feet."
 },
 {
  "id": "tg_ee_ee_like",
  "text": "...like in bee, tree and feet."
 },
 {
  "id": "tg_ea_ee_way",
  "text": "This is the way we spell it in leaf."
 },
 {
  "id": "tg_ea_ee_in",
  "text": "...in leaf."
 },
 {
  "id": "tg_ea_ee_see",
  "text": "We see this spelling in sea and tea."
 },
 {
  "id": "tg_ea_ee_like",
  "text": "...like in leaf, sea and tea."
 },
 {
  "id": "tp_ie_hear",
  "text": "You can hear it in pie, light and tie."
 },
 {
  "id": "tp_ie_list",
  "text": "Pie, light and tie."
 },
 {
  "id": "tg_ie_ie_way",
  "text": "This is the way we spell it in pie."
 },
 {
  "id": "tg_ie_ie_in",
  "text": "...in pie."
 },
 {
  "id": "tg_ie_ie_see",
  "text": "We see this spelling in tie and lie."
 },
 {
  "id": "tg_ie_ie_like",
  "text": "...like in pie, tie and lie."
 },
 {
  "id": "tg_igh_ie_way",
  "text": "This is the way we spell it in light."
 },
 {
  "id": "tg_igh_ie_in",
  "text": "...in light."
 },
 {
  "id": "tg_igh_ie_see",
  "text": "We see this spelling in night and high."
 },
 {
  "id": "tg_igh_ie_like",
  "text": "...like in light, night and high."
 },
 {
  "id": "tp_oe_hear",
  "text": "You can hear it in boat, snow and goat."
 },
 {
  "id": "tp_oe_list",
  "text": "Boat, snow and goat."
 },
 {
  "id": "tg_oa_oe_way",
  "text": "This is the way we spell it in boat."
 },
 {
  "id": "tg_oa_oe_in",
  "text": "...in boat."
 },
 {
  "id": "tg_oa_oe_see",
  "text": "We see this spelling in goat and coat."
 },
 {
  "id": "tg_oa_oe_like",
  "text": "...like in boat, goat and coat."
 },
 {
  "id": "tg_ow_oe_way",
  "text": "This is the way we spell it in snow."
 },
 {
  "id": "tg_ow_oe_in",
  "text": "...in snow."
 },
 {
  "id": "tg_ow_oe_see",
  "text": "We see this spelling in crow and grow."
 },
 {
  "id": "tg_ow_oe_like",
  "text": "...like in snow, crow and grow."
 },
 {
  "id": "tp_s_hear",
  "text": "You can hear it in sit, dress and sun."
 },
 {
  "id": "tp_s_list",
  "text": "Sit, dress and sun."
 },
 {
  "id": "tg_s_s_way",
  "text": "This is the way we spell it in sit."
 },
 {
  "id": "tg_s_s_in",
  "text": "...in sit."
 },
 {
  "id": "tg_s_s_see",
  "text": "We see this spelling in sun and bus."
 },
 {
  "id": "tg_s_s_like",
  "text": "...like in sit, sun and bus."
 },
 {
  "id": "tg_ss_s_way",
  "text": "This is the way we spell it in dress."
 },
 {
  "id": "tg_ss_s_in",
  "text": "...in dress."
 },
 {
  "id": "tg_ss_s_see",
  "text": "We see this spelling in kiss and mess."
 },
 {
  "id": "tg_ss_s_like",
  "text": "...like in dress, kiss and mess."
 },
 {
  "id": "tp_l_hear",
  "text": "You can hear it in leg, doll and lid."
 },
 {
  "id": "tp_l_list",
  "text": "Leg, doll and lid."
 },
 {
  "id": "tg_l_l_way",
  "text": "This is the way we spell it in leg."
 },
 {
  "id": "tg_l_l_in",
  "text": "...in leg."
 },
 {
  "id": "tg_l_l_see",
  "text": "We see this spelling in lid and log."
 },
 {
  "id": "tg_l_l_like",
  "text": "...like in leg, lid and log."
 },
 {
  "id": "tg_ll_l_way",
  "text": "This is the way we spell it in doll."
 },
 {
  "id": "tg_ll_l_in",
  "text": "...in doll."
 },
 {
  "id": "tg_ll_l_see",
  "text": "We see this spelling in bell and well."
 },
 {
  "id": "tg_ll_l_like",
  "text": "...like in doll, bell and well."
 },
 {
  "id": "tp_f_hear",
  "text": "You can hear it in fan, off and fox."
 },
 {
  "id": "tp_f_list",
  "text": "Fan, off and fox."
 },
 {
  "id": "tg_f_f_way",
  "text": "This is the way we spell it in fan."
 },
 {
  "id": "tg_f_f_in",
  "text": "...in fan."
 },
 {
  "id": "tg_f_f_see",
  "text": "We see this spelling in fox and elf."
 },
 {
  "id": "tg_f_f_like",
  "text": "...like in fan, fox and elf."
 },
 {
  "id": "tg_ff_f_way",
  "text": "This is the way we spell it in off."
 },
 {
  "id": "tg_ff_f_in",
  "text": "...in off."
 },
 {
  "id": "tg_ff_f_see",
  "text": "We see this spelling in puff and huff."
 },
 {
  "id": "tg_ff_f_like",
  "text": "...like in off, puff and huff."
 },
 {
  "id": "tp_e_hear",
  "text": "You can hear it in den, bed and peg."
 },
 {
  "id": "tp_e_list",
  "text": "Den, bed and peg."
 },
 {
  "id": "tg_e_e_way",
  "text": "This is the way we spell it in den."
 },
 {
  "id": "tg_e_e_in",
  "text": "...in den."
 },
 {
  "id": "tg_e_e_see",
  "text": "We see this spelling in bed and peg."
 },
 {
  "id": "tg_e_e_like",
  "text": "...like in den, bed and peg."
 },
 {
  "id": "tp_u_hear",
  "text": "You can hear it in run, rug and cup."
 },
 {
  "id": "tp_u_list",
  "text": "Run, rug and cup."
 },
 {
  "id": "tg_u_u_way",
  "text": "This is the way we spell it in run."
 },
 {
  "id": "tg_u_u_in",
  "text": "...in run."
 },
 {
  "id": "tg_u_u_see",
  "text": "We see this spelling in rug and cup."
 },
 {
  "id": "tg_u_u_like",
  "text": "...like in run, rug and cup."
 },
 {
  "id": "tp_o_hear",
  "text": "You can hear it in pot, top and mop."
 },
 {
  "id": "tp_o_list",
  "text": "Pot, top and mop."
 },
 {
  "id": "tg_o_o_way",
  "text": "This is the way we spell it in pot."
 },
 {
  "id": "tg_o_o_in",
  "text": "...in pot."
 },
 {
  "id": "tg_o_o_see",
  "text": "We see this spelling in top and mop."
 },
 {
  "id": "tg_o_o_like",
  "text": "...like in pot, top and mop."
 },
 {
  "id": "tp_d_hear",
  "text": "You can hear it in dog, den and doll."
 },
 {
  "id": "tp_d_list",
  "text": "Dog, den and doll."
 },
 {
  "id": "tg_d_d_way",
  "text": "This is the way we spell it in dog."
 },
 {
  "id": "tg_d_d_in",
  "text": "...in dog."
 },
 {
  "id": "tg_d_d_see",
  "text": "We see this spelling in den and bed."
 },
 {
  "id": "tg_d_d_like",
  "text": "...like in dog, den and bed."
 },
 {
  "id": "tp_i_hear",
  "text": "You can hear it in sit, pin and tin."
 },
 {
  "id": "tp_i_list",
  "text": "Sit, pin and tin."
 },
 {
  "id": "tg_i_i_way",
  "text": "This is the way we spell it in sit."
 },
 {
  "id": "tg_i_i_in",
  "text": "...in sit."
 },
 {
  "id": "tg_i_i_see",
  "text": "We see this spelling in pin and tin."
 },
 {
  "id": "tg_i_i_like",
  "text": "...like in sit, pin and tin."
 },
 {
  "id": "tp_n_hear",
  "text": "You can hear it in net, nut and nest."
 },
 {
  "id": "tp_n_list",
  "text": "Net, nut and nest."
 },
 {
  "id": "tg_n_n_way",
  "text": "This is the way we spell it in man."
 },
 {
  "id": "tg_n_n_in",
  "text": "...in man."
 },
 {
  "id": "tg_n_n_see",
  "text": "We see this spelling in pan and pin."
 },
 {
  "id": "tg_n_n_like",
  "text": "...like in man, pan and pin."
 },
 {
  "id": "tp_v_hear",
  "text": "You can hear it in vet, have and van."
 },
 {
  "id": "tp_v_list",
  "text": "Vet, have and van."
 },
 {
  "id": "tg_v_v_way",
  "text": "This is the way we spell it in vet."
 },
 {
  "id": "tg_v_v_in",
  "text": "...in vet."
 },
 {
  "id": "tg_v_v_see",
  "text": "We see this spelling in van and vest."
 },
 {
  "id": "tg_v_v_like",
  "text": "...like in vet, van and vest."
 },
 {
  "id": "tg_ve_v_way",
  "text": "This is the way we spell it in have."
 },
 {
  "id": "tg_ve_v_in",
  "text": "...in have."
 },
 {
  "id": "tg_ve_v_see",
  "text": "We see this spelling in give."
 },
 {
  "id": "tg_ve_v_like",
  "text": "...like in have and give."
 },
 {
  "id": "tp_j_hear",
  "text": "You can hear it in jam, jug and jump."
 },
 {
  "id": "tp_j_list",
  "text": "Jam, jug and jump."
 },
 {
  "id": "tg_j_j_way",
  "text": "This is the way we spell it in jam."
 },
 {
  "id": "tg_j_j_in",
  "text": "...in jam."
 },
 {
  "id": "tg_j_j_see",
  "text": "We see this spelling in jug and jump."
 },
 {
  "id": "tg_j_j_like",
  "text": "...like in jam, jug and jump."
 },
 {
  "id": "tp_g_hear",
  "text": "You can hear it in goat, bag and pig."
 },
 {
  "id": "tp_g_list",
  "text": "Goat, bag and pig."
 },
 {
  "id": "tg_g_g_way",
  "text": "This is the way we spell it in bag."
 },
 {
  "id": "tg_g_g_in",
  "text": "...in bag."
 },
 {
  "id": "tg_g_g_see",
  "text": "We see this spelling in pig and dog."
 },
 {
  "id": "tg_g_g_like",
  "text": "...like in bag, pig and dog."
 },
 {
  "id": "tp_m_hear",
  "text": "You can hear it in mat, man and map."
 },
 {
  "id": "tp_m_list",
  "text": "Mat, man and map."
 },
 {
  "id": "tg_m_m_way",
  "text": "This is the way we spell it in mat."
 },
 {
  "id": "tg_m_m_in",
  "text": "...in mat."
 },
 {
  "id": "tg_m_m_see",
  "text": "We see this spelling in man and map."
 },
 {
  "id": "tg_m_m_like",
  "text": "...like in mat, man and map."
 },
 {
  "id": "tp_h_hear",
  "text": "You can hear it in hat, hut and hutch."
 },
 {
  "id": "tp_h_list",
  "text": "Hat, hut and hutch."
 },
 {
  "id": "tg_h_h_way",
  "text": "This is the way we spell it in hat."
 },
 {
  "id": "tg_h_h_in",
  "text": "...in hat."
 },
 {
  "id": "tg_h_h_see",
  "text": "We see this spelling in hut and hutch."
 },
 {
  "id": "tg_h_h_like",
  "text": "...like in hat, hut and hutch."
 },
 {
  "id": "tp_k_hear",
  "text": "You can hear it in cat, king and duck."
 },
 {
  "id": "tp_k_list",
  "text": "Cat, king and duck."
 },
 {
  "id": "tg_c_k_way",
  "text": "This is the way we spell it in cat."
 },
 {
  "id": "tg_c_k_in",
  "text": "...in cat."
 },
 {
  "id": "tg_c_k_see",
  "text": "We see this spelling in cap and cot."
 },
 {
  "id": "tg_c_k_like",
  "text": "...like in cat, cap and cot."
 },
 {
  "id": "tg_k_k_way",
  "text": "This is the way we spell it in yak."
 },
 {
  "id": "tg_k_k_in",
  "text": "...in yak."
 },
 {
  "id": "tg_k_k_see",
  "text": "We see this spelling in king and milk."
 },
 {
  "id": "tg_k_k_like",
  "text": "...like in yak, king and milk."
 },
 {
  "id": "tg_ck_k_way",
  "text": "This is the way we spell it in duck."
 },
 {
  "id": "tg_ck_k_in",
  "text": "...in duck."
 },
 {
  "id": "tg_ck_k_see",
  "text": "We see this spelling in sock and rock."
 },
 {
  "id": "tg_ck_k_like",
  "text": "...like in duck, sock and rock."
 },
 {
  "id": "tg_q_k_way",
  "text": "This is the way we spell it in queen."
 },
 {
  "id": "tg_q_k_in",
  "text": "...in queen."
 },
 {
  "id": "tg_q_k_see",
  "text": "We see this spelling in quiz and quit."
 },
 {
  "id": "tg_q_k_like",
  "text": "...like in queen, quiz and quit."
 },
 {
  "id": "tp_r_hear",
  "text": "You can hear it in rat, rod and run."
 },
 {
  "id": "tp_r_list",
  "text": "Rat, rod and run."
 },
 {
  "id": "tg_r_r_way",
  "text": "This is the way we spell it in rat."
 },
 {
  "id": "tg_r_r_in",
  "text": "...in rat."
 },
 {
  "id": "tg_r_r_see",
  "text": "We see this spelling in rod and run."
 },
 {
  "id": "tg_r_r_like",
  "text": "...like in rat, rod and run."
 },
 {
  "id": "tp_t_hear",
  "text": "You can hear it in tap, tin and top."
 },
 {
  "id": "tp_t_list",
  "text": "Tap, tin and top."
 },
 {
  "id": "tg_t_t_way",
  "text": "This is the way we spell it in tap."
 },
 {
  "id": "tg_t_t_in",
  "text": "...in tap."
 },
 {
  "id": "tg_t_t_see",
  "text": "We see this spelling in mat and sit."
 },
 {
  "id": "tg_t_t_like",
  "text": "...like in tap, mat and sit."
 },
 {
  "id": "tp_z_hear",
  "text": "You can hear it in zip, buzz and zap."
 },
 {
  "id": "tp_z_list",
  "text": "Zip, buzz and zap."
 },
 {
  "id": "tg_z_z_way",
  "text": "This is the way we spell it in zip."
 },
 {
  "id": "tg_z_z_in",
  "text": "...in zip."
 },
 {
  "id": "tg_z_z_see",
  "text": "We see this spelling in zap and quiz."
 },
 {
  "id": "tg_z_z_like",
  "text": "...like in zip, zap and quiz."
 },
 {
  "id": "tg_zz_z_way",
  "text": "This is the way we spell it in buzz."
 },
 {
  "id": "tg_zz_z_in",
  "text": "...in buzz."
 },
 {
  "id": "tg_zz_z_see",
  "text": "We see this spelling in fizz and jazz."
 },
 {
  "id": "tg_zz_z_like",
  "text": "...like in buzz, fizz and jazz."
 },
 {
  "id": "tp_a_hear",
  "text": "You can hear it in mat, man and pan."
 },
 {
  "id": "tp_a_list",
  "text": "Mat, man and pan."
 },
 {
  "id": "tg_a_a_way",
  "text": "This is the way we spell it in mat."
 },
 {
  "id": "tg_a_a_in",
  "text": "...in mat."
 },
 {
  "id": "tg_a_a_see",
  "text": "We see this spelling in man and pan."
 },
 {
  "id": "tg_a_a_like",
  "text": "...like in mat, man and pan."
 },
 {
  "id": "tp_p_hear",
  "text": "You can hear it in pan, pin and pot."
 },
 {
  "id": "tp_p_list",
  "text": "Pan, pin and pot."
 },
 {
  "id": "tg_p_p_way",
  "text": "This is the way we spell it in pan."
 },
 {
  "id": "tg_p_p_in",
  "text": "...in pan."
 },
 {
  "id": "tg_p_p_see",
  "text": "We see this spelling in tap and map."
 },
 {
  "id": "tg_p_p_like",
  "text": "...like in pan, tap and map."
 },
 {
  "id": "tp_b_hear",
  "text": "You can hear it in bat, bag and bin."
 },
 {
  "id": "tp_b_list",
  "text": "Bat, bag and bin."
 },
 {
  "id": "tg_b_b_way",
  "text": "This is the way we spell it in bat."
 },
 {
  "id": "tg_b_b_in",
  "text": "...in bat."
 },
 {
  "id": "tg_b_b_see",
  "text": "We see this spelling in bag and bin."
 },
 {
  "id": "tg_b_b_like",
  "text": "...like in bat, bag and bin."
 },
 {
  "id": "tp_w_hear",
  "text": "You can hear it in web, whisk and quick."
 },
 {
  "id": "tp_w_list",
  "text": "Web, whisk and quick."
 },
 {
  "id": "tg_w_w_way",
  "text": "This is the way we spell it in web."
 },
 {
  "id": "tg_w_w_in",
  "text": "...in web."
 },
 {
  "id": "tg_w_w_see",
  "text": "We see this spelling in wig and well."
 },
 {
  "id": "tg_w_w_like",
  "text": "...like in web, wig and well."
 },
 {
  "id": "tg_wh_w_way",
  "text": "This is the way we spell it in whisk."
 },
 {
  "id": "tg_wh_w_in",
  "text": "...in whisk."
 },
 {
  "id": "tg_wh_w_see",
  "text": "We see this spelling in when and which."
 },
 {
  "id": "tg_wh_w_like",
  "text": "...like in whisk, when and which."
 },
 {
  "id": "tg_u_w_way",
  "text": "This is the way we spell it in queen."
 },
 {
  "id": "tg_u_w_in",
  "text": "...in queen."
 },
 {
  "id": "tg_u_w_see",
  "text": "We see this spelling in quick and quiz."
 },
 {
  "id": "tg_u_w_like",
  "text": "...like in queen, quick and quiz."
 },
 {
  "id": "tp_y_hear",
  "text": "You can hear it in yak, yes and yum."
 },
 {
  "id": "tp_y_list",
  "text": "Yak, yes and yum."
 },
 {
  "id": "tg_y_y_way",
  "text": "This is the way we spell it in yak."
 },
 {
  "id": "tg_y_y_in",
  "text": "...in yak."
 },
 {
  "id": "tg_y_y_see",
  "text": "We see this spelling in yes and yum."
 },
 {
  "id": "tg_y_y_like",
  "text": "...like in yak, yes and yum."
 },
 {
  "id": "tp_sh_hear",
  "text": "You can hear it in shop, shed and shell."
 },
 {
  "id": "tp_sh_list",
  "text": "Shop, shed and shell."
 },
 {
  "id": "tg_sh_sh_way",
  "text": "This is the way we spell it in shop."
 },
 {
  "id": "tg_sh_sh_in",
  "text": "...in shop."
 },
 {
  "id": "tg_sh_sh_see",
  "text": "We see this spelling in shed and shell."
 },
 {
  "id": "tg_sh_sh_like",
  "text": "...like in shop, shed and shell."
 },
 {
  "id": "tp_ch_hear",
  "text": "You can hear it in chick, match and chest."
 },
 {
  "id": "tp_ch_list",
  "text": "Chick, match and chest."
 },
 {
  "id": "tg_ch_ch_way",
  "text": "This is the way we spell it in chick."
 },
 {
  "id": "tg_ch_ch_in",
  "text": "...in chick."
 },
 {
  "id": "tg_ch_ch_see",
  "text": "We see this spelling in chest and bench."
 },
 {
  "id": "tg_ch_ch_like",
  "text": "...like in chick, chest and bench."
 },
 {
  "id": "tg_tch_ch_way",
  "text": "This is the way we spell it in match."
 },
 {
  "id": "tg_tch_ch_in",
  "text": "...in match."
 },
 {
  "id": "tg_tch_ch_see",
  "text": "We see this spelling in witch and hutch."
 },
 {
  "id": "tg_tch_ch_like",
  "text": "...like in match, witch and hutch."
 },
 {
  "id": "tp_th_hear",
  "text": "You can hear it in moth, thin and thick."
 },
 {
  "id": "tp_th_list",
  "text": "Moth, thin and thick."
 },
 {
  "id": "tg_th_th_way",
  "text": "This is the way we spell it in moth."
 },
 {
  "id": "tg_th_th_in",
  "text": "...in moth."
 },
 {
  "id": "tg_th_th_see",
  "text": "We see this spelling in thin and thick."
 },
 {
  "id": "tg_th_th_like",
  "text": "...like in moth, thin and thick."
 },
 {
  "id": "tp_dh_hear",
  "text": "You can hear it in this, that and them."
 },
 {
  "id": "tp_dh_list",
  "text": "This, that and them."
 },
 {
  "id": "tg_th_dh_way",
  "text": "This is the way we spell it in this."
 },
 {
  "id": "tg_th_dh_in",
  "text": "...in this."
 },
 {
  "id": "tg_th_dh_see",
  "text": "We see this spelling in that and them."
 },
 {
  "id": "tg_th_dh_like",
  "text": "...like in this, that and them."
 },
 {
  "id": "tp_ng_hear",
  "text": "You can hear it in ring, king and wing."
 },
 {
  "id": "tp_ng_list",
  "text": "Ring, king and wing."
 },
 {
  "id": "tg_ng_ng_way",
  "text": "This is the way we spell it in ring."
 },
 {
  "id": "tg_ng_ng_in",
  "text": "...in ring."
 },
 {
  "id": "tg_ng_ng_see",
  "text": "We see this spelling in king and wing."
 },
 {
  "id": "tg_ng_ng_like",
  "text": "...like in ring, king and wing."
 }
];
/** The example words each clip says, so the screen shows the same words ("petal:ae", "gem:ai>ae"). */
export const TEACH_EXAMPLES: Record<string, string[]> = {
 "petal:ae": [
  "rain",
  "tray",
  "tail"
 ],
 "gem:ai>ae": [
  "rain",
  "tail",
  "nail"
 ],
 "gem:ay>ae": [
  "tray",
  "day",
  "say"
 ],
 "petal:ee": [
  "bee",
  "leaf",
  "tree"
 ],
 "gem:ee>ee": [
  "bee",
  "tree",
  "feet"
 ],
 "gem:ea>ee": [
  "leaf",
  "sea",
  "tea"
 ],
 "petal:ie": [
  "pie",
  "light",
  "tie"
 ],
 "gem:ie>ie": [
  "pie",
  "tie",
  "lie"
 ],
 "gem:igh>ie": [
  "light",
  "night",
  "high"
 ],
 "petal:oe": [
  "boat",
  "snow",
  "goat"
 ],
 "gem:oa>oe": [
  "boat",
  "goat",
  "coat"
 ],
 "gem:ow>oe": [
  "snow",
  "crow",
  "grow"
 ],
 "petal:s": [
  "sit",
  "dress",
  "sun"
 ],
 "gem:s>s": [
  "sit",
  "sun",
  "bus"
 ],
 "gem:ss>s": [
  "dress",
  "kiss",
  "mess"
 ],
 "petal:l": [
  "leg",
  "doll",
  "lid"
 ],
 "gem:l>l": [
  "leg",
  "lid",
  "log"
 ],
 "gem:ll>l": [
  "doll",
  "bell",
  "well"
 ],
 "petal:f": [
  "fan",
  "off",
  "fox"
 ],
 "gem:f>f": [
  "fan",
  "fox",
  "elf"
 ],
 "gem:ff>f": [
  "off",
  "puff",
  "huff"
 ],
 "petal:e": [
  "den",
  "bed",
  "peg"
 ],
 "gem:e>e": [
  "den",
  "bed",
  "peg"
 ],
 "petal:u": [
  "run",
  "rug",
  "cup"
 ],
 "gem:u>u": [
  "run",
  "rug",
  "cup"
 ],
 "petal:o": [
  "pot",
  "top",
  "mop"
 ],
 "gem:o>o": [
  "pot",
  "top",
  "mop"
 ],
 "petal:d": [
  "dog",
  "den",
  "doll"
 ],
 "gem:d>d": [
  "dog",
  "den",
  "bed"
 ],
 "petal:i": [
  "sit",
  "pin",
  "tin"
 ],
 "gem:i>i": [
  "sit",
  "pin",
  "tin"
 ],
 "petal:n": [
  "net",
  "nut",
  "nest"
 ],
 "gem:n>n": [
  "man",
  "pan",
  "pin"
 ],
 "petal:v": [
  "vet",
  "have",
  "van"
 ],
 "gem:v>v": [
  "vet",
  "van",
  "vest"
 ],
 "gem:ve>v": [
  "have",
  "give"
 ],
 "petal:j": [
  "jam",
  "jug",
  "jump"
 ],
 "gem:j>j": [
  "jam",
  "jug",
  "jump"
 ],
 "petal:g": [
  "goat",
  "bag",
  "pig"
 ],
 "gem:g>g": [
  "bag",
  "pig",
  "dog"
 ],
 "petal:m": [
  "mat",
  "man",
  "map"
 ],
 "gem:m>m": [
  "mat",
  "man",
  "map"
 ],
 "petal:h": [
  "hat",
  "hut",
  "hutch"
 ],
 "gem:h>h": [
  "hat",
  "hut",
  "hutch"
 ],
 "petal:k": [
  "cat",
  "king",
  "duck"
 ],
 "gem:c>k": [
  "cat",
  "cap",
  "cot"
 ],
 "gem:k>k": [
  "yak",
  "king",
  "milk"
 ],
 "gem:ck>k": [
  "duck",
  "sock",
  "rock"
 ],
 "gem:q>k": [
  "queen",
  "quiz",
  "quit"
 ],
 "petal:r": [
  "rat",
  "rod",
  "run"
 ],
 "gem:r>r": [
  "rat",
  "rod",
  "run"
 ],
 "petal:t": [
  "tap",
  "tin",
  "top"
 ],
 "gem:t>t": [
  "tap",
  "mat",
  "sit"
 ],
 "petal:z": [
  "zip",
  "buzz",
  "zap"
 ],
 "gem:z>z": [
  "zip",
  "zap",
  "quiz"
 ],
 "gem:zz>z": [
  "buzz",
  "fizz",
  "jazz"
 ],
 "petal:a": [
  "mat",
  "man",
  "pan"
 ],
 "gem:a>a": [
  "mat",
  "man",
  "pan"
 ],
 "petal:p": [
  "pan",
  "pin",
  "pot"
 ],
 "gem:p>p": [
  "pan",
  "tap",
  "map"
 ],
 "petal:b": [
  "bat",
  "bag",
  "bin"
 ],
 "gem:b>b": [
  "bat",
  "bag",
  "bin"
 ],
 "petal:w": [
  "web",
  "whisk",
  "quick"
 ],
 "gem:w>w": [
  "web",
  "wig",
  "well"
 ],
 "gem:wh>w": [
  "whisk",
  "when",
  "which"
 ],
 "gem:u>w": [
  "queen",
  "quick",
  "quiz"
 ],
 "petal:y": [
  "yak",
  "yes",
  "yum"
 ],
 "gem:y>y": [
  "yak",
  "yes",
  "yum"
 ],
 "petal:sh": [
  "shop",
  "shed",
  "shell"
 ],
 "gem:sh>sh": [
  "shop",
  "shed",
  "shell"
 ],
 "petal:ch": [
  "chick",
  "match",
  "chest"
 ],
 "gem:ch>ch": [
  "chick",
  "chest",
  "bench"
 ],
 "gem:tch>ch": [
  "match",
  "witch",
  "hutch"
 ],
 "petal:th": [
  "moth",
  "thin",
  "thick"
 ],
 "gem:th>th": [
  "moth",
  "thin",
  "thick"
 ],
 "petal:dh": [
  "this",
  "that",
  "them"
 ],
 "gem:th>dh": [
  "this",
  "that",
  "them"
 ],
 "petal:ng": [
  "ring",
  "king",
  "wing"
 ],
 "gem:ng>ng": [
  "ring",
  "king",
  "wing"
 ]
};
