// Whole-sentence example clips for the teacher language (src/content/teach.ts). Splicing single word clips with
// "…and…" sounded choppy, so each sound and each spelling gets its example words recorded as ONE natural sentence,
// e.g. "You can hear it in rain, tray and tail." Pure sounds are still spliced in, because TTS can't say them inside
// a sentence. Writes src/content/teach-lines.gen.ts (the lines and the example words the screen should show);
// then `bun scripts/gen-audio.ts lines` records and checks them like every other line.
// Usage: bun scripts/gen-teach-lines.ts   (re-run when words or gems change)
import { writeFileSync } from "node:fs";
import { PETALS } from "../src/content/flower";

const store: Record<string, string> = {};
(globalThis as any).localStorage = { getItem: (k: string) => store[k] ?? null, setItem: (k: string, v: string) => (store[k] = v) };
const { soundExamples, examplesFor } = await import("../src/content/teach");

const listText = (ws: string[]) => (ws.length > 1 ? `${ws.slice(0, -1).join(", ")} and ${ws[ws.length - 1]}` : ws[0] ?? "");
const cap = (s: string) => s[0].toUpperCase() + s.slice(1);
const safe = (k: string) => k.replace(">", "_").replace(/-/g, "");

const lines: { id: string; text: string }[] = [];
const examples: Record<string, string[]> = {};
for (const pt of PETALS) {
  if (!pt.gems.some((g) => g.inPlay)) continue; // sounds not in the game yet stay a secret
  const ex = soundExamples(pt.p, { n: 3 }).map((w) => w.text);
  if (ex.length) {
    examples[`petal:${pt.p}`] = ex;
    lines.push({ id: `tp_${pt.p}_hear`, text: `You can hear it in ${listText(ex)}.` });
    lines.push({ id: `tp_${pt.p}_list`, text: `${cap(listText(ex))}.` });
  }
  for (const gem of pt.gems.filter((g) => g.inPlay)) {
    const ws = examplesFor(gem.g, gem.p, { n: 3 }).map((w) => w.text);
    if (!ws.length) continue;
    const k = safe(gem.key);
    examples[`gem:${gem.key}`] = ws;
    lines.push({ id: `tg_${k}_in`, text: `...in ${ws[0]}.` });
    if (ws.length > 1) lines.push({ id: `tg_${k}_see`, text: `We see this spelling in ${listText(ws.slice(1))}.` });
    lines.push({ id: `tg_${k}_like`, text: `...like in ${listText(ws)}.` });
  }
}
writeFileSync(
  "src/content/teach-lines.gen.ts",
  `// GENERATED by scripts/gen-teach-lines.ts: example sentences for teach.ts, one clip each. Don't edit by hand.
export const TEACH_LINES: { id: string; text: string }[] = ${JSON.stringify(lines, null, 1)};
/** The example words each clip says, so the screen shows the same words ("petal:ae", "gem:ai>ae"). */
export const TEACH_EXAMPLES: Record<string, string[]> = ${JSON.stringify(examples, null, 1)};
`,
);
console.log(`${lines.length} example lines for ${Object.keys(examples).length} sounds and spellings → src/content/teach-lines.gen.ts`);
