# When each example word starts inside Sensei's teacher-language sentences (tg_*, tp_*: "...like in rain, tail and
# nail."), so the World Flower can spotlight each word's card as she names it (Round 13: "highlight the card being
# named"). Whisper (mlx, large-v3-turbo) gives word spans; a word whose span holds the start of a speech island (after
# a pause) starts where the island does, because Whisper's starts run early after pauses (docs/DECISIONS.md, WORD_TIMES).
# Writes src/content/teach-word-times.gen.ts.
#   uv run -q --with mlx-whisper --with numpy python scripts/gen-teach-word-times.py
import json, re, subprocess, sys
import numpy as np
import mlx_whisper

ROOT = "/Users/jonastemplestein/src/github.com/jonastemplestein/superninja"
src = open(f"{ROOT}/src/content/teach-lines.gen.ts").read()
lines = re.findall(r'"id": "([^"]+)",\s*"text": "([^"]+)"', src)
extra = sys.argv[1:]  # more line ids (from lines.ts) to time, e.g. fm_rw2_petal


def env(path):
    raw = subprocess.run(["ffmpeg", "-loglevel", "error", "-i", path, "-ac", "1", "-ar", "16000", "-f", "s16le", "-"], capture_output=True).stdout
    x = np.frombuffer(raw, dtype=np.int16).astype(np.float32) / 32768
    hop = 160  # 10 ms
    return np.array([np.sqrt(np.mean(x[i:i + 320] ** 2)) + 1e-6 for i in range(0, max(1, len(x) - 320), hop)])


def islands(e):
    """Starts (s) of speech islands: sound after at least 50 ms quieter than 27 dB below the clip's peak."""
    db = 20 * np.log10(e)
    quiet = db < db.max() - 27
    starts, run = [], 99
    for i, q in enumerate(quiet):
        if q:
            run += 1
        else:
            if run >= 5:
                starts.append(i / 100)
            run = 0
    return starts


def place(words, e):
    """After a pause, Whisper stretches a word's start back into the silence (its end stays right), so a word starts
    at the first speech island that begins inside its Whisper span, if one does; otherwise at Whisper's start."""
    isl = islands(e)
    out, prev = [], -1.0
    for w, a, b in words:
        cand = [t for t in isl if a - 0.05 <= t < b - 0.05 and t > prev + 0.05]
        t = max(cand[0] if cand else a, prev + 0.05)
        out.append([w, round(t, 2)])
        prev = t
    return out


out = {}
for id_, text in lines:
    path = f"{ROOT}/public/a/l/{id_}.mp3"
    try:
        r = mlx_whisper.transcribe(path, path_or_hf_repo="mlx-community/whisper-large-v3-turbo", word_timestamps=True, language="en")
    except Exception as ex:
        print("skip", id_, ex, file=sys.stderr)
        continue
    raw = []
    for seg in r.get("segments", []):
        for w in seg.get("words", []):
            clean = re.sub(r"[^a-z']", "", w["word"].lower())
            if clean:
                raw.append((clean, float(w["start"]), float(w["end"])))
    words = place(raw, env(path))
    out[id_] = words
    print(id_, words, file=sys.stderr)

with open(f"{ROOT}/src/content/teach-word-times.gen.ts", "w") as f:
    f.write("// GENERATED by scripts/gen-teach-word-times.py: when each word starts (s) inside the teacher-language\n")
    f.write("// sentences, for the World Flower's word spotlight. Don't edit by hand.\n")
    f.write("export const TEACH_WORD_TIMES: Record<string, [string, number][]> = {\n")
    for k, v in out.items():
        f.write(f"  {json.dumps(k)}: {json.dumps(v)},\n")
    f.write("};\n")
print(len(out), "lines", file=sys.stderr)
